kubernetes/cloud-provider-openstack

charts/manila-csi-plugin/Chart.yaml
charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml

This PR addresses a review comment here https://github.com/kubernetes/cloud-provider-openstack/pull/1579#discussion_r660297101 .
Deployment manifests and manila-csi helm chart have been modified so that they don't use `--v=LEVEL` log verbosity level flags by default.
```release-note
NONE
```

[manila-csi-plugin] Use low verbosity logging by default

---

Makefile

This PR enables installing import-boss using go install command
fixes #1588
```release-note
NONE
```

Fix `make import-boss` gate failure 

---

pkg/csi/manila/nodeserver.go

This change prevents the node server's `nodeStageCache` from being populated with invalid (nil) values, when an error occurred previously.
fixes #1587
n/a
```release-note
NONE
```

[manila-csi-plugin] Do not populate nodeStageCache when an error occurred previously

---

pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go
pkg/csi/cinder/fake.go

fixes #1545
```release-note
[cinder-csi-plugin] Add metadata for creating snapshot if `--extra-create-metadata` is enabled in external-snapshotter.
```

[cinder-csi-plugin]Avoid create tag from metadata req of snapshot

---

pkg/csi/manila/controllerserver.go
pkg/csi/manila/nodeserver.go
pkg/csi/manila/share.go
pkg/csi/manila/volumesource.go

This PR addresses review comment here https://github.com/kubernetes/cloud-provider-openstack/pull/1579#discussion_r659004435 .
It consolidates share/volume terms used in various log and error messages all over the codebase manila-csi. Where possible, it replaces the term "share" with CSI term "volume". Share names are used to identify volumes, since that is the CO-facing identifier.
Some log messages were also removed, as they weren't adding any more information than what was already available.
```release-note
NONE
```

[manila-csi-plugin] Consolidate log and error messages

---

manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml

This PR is to sync the RBAC rules as per latest sidecars
versions.
fixes #
```release-note
NONE
```

[cinder-csi-plugin] Sync RBAC as per latest sidecar versions

---

docs/manila-csi-plugin/using-manila-csi-plugin.md
pkg/csi/manila/options/shareoptions.go
pkg/csi/manila/shareadapters/cephfs.go

manila-csi already passes mount options to its partner Node Plugins. However, cephfs-csi consumes mount options for CephFS kernel and FUSE client via separate volume context parameters: `kernelMountOptions` and `fuseMountOptions`. In order for user to be able to control these, manila-csi needs to expose these params as well.
Please see https://github.com/ceph/ceph-csi/blob/devel/docs/deploy-cephfs.md#configuration for reference (section "Available volume parameters").
Exposing kernel opts are especially important for environments with SELinux enabled, where users may want to pass in SELinux context options.
```release-note
[manila-csi-plugin] Add cephfs-kernelMountOptions and cephfs-fuseMountOptions …
```

[manila-csi-plugin] Add options for passing mount opts to cephfs-csi

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml

imagePullPolicy is defined twice in some places , which overwirtes to specific value. This PR is to keep the value configurable.
fixes #1598
```release-note
NONE
```

[cinder-csi-plugin] Remove redundant imagePullPolicy

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/cinder-csi-plugin/values.yaml

Fix duplicate keys of tolerations in node plugin yaml
fixes #1608 
```release-note
NONE
```

[cinder-csi-plugin] Fix duplicate keys of tolerations

---

.github/workflows/pr.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/clusterrole.yaml

* [osccm-helm] add missing RBAC for serviceaccount token
* [osccm-helm] bump version
(cherry picked from commit dcef7202697f7caead1055dcef50c2e0c3388951)
New clientbuilder needs permission to create serviceaccount token
fixes #1514
```release-note
NONE
```

[occm] add missing RBAC for serviceaccount token (#1521)

---

pkg/openstack/instances.go
pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go
pkg/openstack/routes.go
pkg/util/errors/errors.go

This PR refactors/moves the provider code for better readability and also removes the unused code in the repo
/kind cleanup
fixes #
```release-note
NONE
```

Refactor the openstack provider code

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/cinder-csi-plugin/values.yaml

The chart assumes Kubelet uses /var/lib/kubelet, which isn't the case on k0s and microk8s (and presumably others). This allows it to be overridden in the values file to handle these cases.
```release-note
NONE
```

[cinder-csi-plugin] Allow overridng kubelet dir in chart values

---

charts/manila-csi-plugin/Chart.yaml
charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/manila-csi-plugin/values.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml

This PR updates sidecars for v1.22:
* csi-node-driver-registrar: v1.3.0 -> v2.2.0
* csi-provisioner: v2.0.2 -> v2.2.2
* csi-snapshotter: v2.1.3 -> v4.1.1
Also, removed `preStop` hook from node-driver-registrar container spec, as it's no longer needed: https://github.com/kubernetes-csi/node-driver-registrar/pull/61
In the light of current issues with CPO's CI infra, I've run the acceptance manually and everything seems to remain working just fine.
```release-note
[manila-csi-plugin] Updated sidecar versions: csi-node-driver-registrar v2.2.0, csi-provisioner v2.2.2, csi-snapshotter v4.1.1
```

[manila-csi-plugin] Bump sidecar versions for v1.22 release

---

pkg/csi/cinder/driver.go
pkg/csi/cinder/driver_test.go

This PR bumps cinder driver version to 1.3.3 for 1.22 release
fixes #
```release-note
NONE
```

[cinder-csi-plugin] Bump driver version for 1.22 release

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml

preStop hook is not required from node-driver-registrar v2.0.0 as the mechanism of removing the sock is changed . So removing the same.
ref: https://github.com/kubernetes-csi/node-driver-registrar/issues/21
fixes #1617 
```release-note
NONE
```

[cinder-csi-plugin] Remove preStop hook

---

docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md

TokenReview, SubjectAccessReview v1beta1 apiVersions are removed
in 1.22. This PR updates the docs for the same.
Ref: https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes
fixes #
```release-note
NONE
```

[docs] Update the apiVersions for TokenReview, SubjectAcessReview

---

docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md

(cherry picked from commit 8d484ee00032c51825a4f909d044db07235456db)
TokenReview, SubjectAccessReview v1beta1 apiVersions are removed
in 1.22. This PR updates the docs for the same.
fixes #
```release-note
NONE
```

[docs] Update the apiVersions (#1622)

---

pkg/csi/manila/controllerserver.go
pkg/csi/manila/options/shareoptions.go
pkg/csi/manila/validator/validator.go
pkg/csi/manila/validator/validator_test.go

Currently, `Volume.volume_context` is populated manually:
https://github.com/kubernetes/cloud-provider-openstack/blob/61bdbe5bf4b75453b67e77b543891e1a5bb3eea2/pkg/csi/manila/controllerserver.go#L167-L179
If we wanted to add more entries to the map, we'd need to do it explicitly which is tedious and error prone. https://github.com/kubernetes/cloud-provider-openstack/pull/1605 added two new parameters, and I forgot to add them into the map. As a result, they are missing in provisioned volumes, despite having them set in my storage class.
This PR makes it so that *all* recognized volume parameters(*) in `CreateVolumeRequest.parameters` map are automatically passed as `Volume.volume_context`. Doing so makes sure no similar bug should happen in the …

[manila-csi-plugin] pass CreateVolumeRequest.parameters as Volume.volume_context

---

pkg/csi/manila/controllerserver.go
pkg/csi/manila/options/shareoptions.go
pkg/csi/manila/validator/validator.go
pkg/csi/manila/validator/validator_test.go

(cherry picked from 88654df74232c3509eedd1208ddd7fb1d9499751)
* validator: added Validator.Fields exposing recognized field names
* options: added NodeVolumeContextFields() to expose nodeVolumeCtxValidator.Fields
* CreateVolume: pass all recognized CreateVolumeRequest.parameters fields as Volume.volume_context
fixes #
```release-note
NONE
```

[manila-csi-plugin] Pass CreateVolumeRequest.parameters in volume context

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml

Update docker image tag in the manifest files for release v1.22.0
fixes #
```release-note
NONE
```

[All] Update CPO docker image tag to v1.22.0

---

pkg/csi/cinder/nodeserver.go

Add 'nouuid' mount option to all XFS mounts to be able to mount a volume and its restored snapshot on the same node. Without the option, such a mount fails, because XFS detects that two different volumes with the same filesystem UUID are being mounted.
See https://github.com/container-storage-interface/spec/issues/482
```release-note
[cinder-csi-plugin] Added support to mount a volume with XFS filesystem and its restored snapshot on the same node.
```

cinder-csi: Disable uuid checks on XFS

---

.zuul.yaml
go.mod

CSI sanity tests have been added to prow , so removing the openlab test to avoid duplicate test.
https://github.com/kubernetes/test-infra/pull/23434
fixes #
```release-note
NONE
```

[cinder-csi-plugin] Remove openlab sanity test

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
charts/cinder-csi-plugin/templates/controllerplugin-rbac.yaml
charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
charts/cinder-csi-plugin/templates/snapshot-controller-rbac.yaml
charts/cinder-csi-plugin/values.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml

Adding support for running HA CSI controller.
fixes #702
Increase replicas to 3, all operations should work as expected (attach, detach, provision, deprovision, resize, snapshot).
I tested it on k8s 1.20, all operations are completing without errors. Also I can see successful leader election change events:
```
29m         Normal    LeaderElection      lease/csi-cinderplugin                               csi-cinder-controllerplugin-0 became leader
3m30s       Normal    LeaderElection      lease/csi-cinderplugin                               csi-cinder-controllerplugin-0 became leader
29m         Normal    LeaderElection      lease/external-attacher-leader-csi-cinderplugin …
```

[cinder-csi-plugin] add leader election

---

charts/cinder-csi-plugin/templates/snapshot-controller-rbac.yaml

fix typo with service account name for snapshot-controller. Different occurrences found here:
* https://github.com/kubernetes/cloud-provider-openstack/blob/fd836e90ef52ebf15dc5cb353395f75b814953c7/charts/cinder-csi-plugin/templates/snapshot-controller-statefulset.yaml#L27
* https://github.com/kubernetes/cloud-provider-openstack/blob/fd836e90ef52ebf15dc5cb353395f75b814953c7/charts/cinder-csi-plugin/templates/snapshot-controller-rbac.yaml#L15
* https://github.com/kubernetes/cloud-provider-openstack/blob/fd836e90ef52ebf15dc5cb353395f75b814953c7/charts/cinder-csi-plugin/templates/snapshot-controller-rbac.yaml#L54
* https://github.com/kubernetes/cloud-provider-openstack/blob/fd836e90ef52ebf15dc5cb353395f75b814953c7/charts/cinder-csi-plugin/templates/snaps …

[cinder-csi-plugin] make SA snapshot-controller-sa references match across templates 

---

tests/playbooks/roles/install-cpo-occm/tasks/main.yaml

this reference is useless in new CI
fixes #
```release-note
NONE
```

[OCCM][CI]: Remove openlab secret usage

---

.github/workflows/pr.yaml
docs/developers-guide.md

With the current chart version bump behavior, the charts version has
been bumped each time when there are changes in the current development
cycle but those versions are never released until the final official
release which could confuse the user.
The chart version should be bumped in the following situations:
* Official release following the new Kubernetes major/minor version, we should bump at least the minor version unless there are backward-incompatible chart changes.
* cloud-provider-openstack own patch version release for stable branches when there are related chart changes.
fixes #
```release-note
NONE
```

[Charts] Do not check chart version in dev cycle

---

tests/playbooks/roles/install-devstack/defaults/main.yaml
tests/playbooks/roles/install-devstack/tasks/main.yml
tests/playbooks/roles/install-devstack/templates/local.conf.j2
tests/playbooks/test-occm-e2e.yaml

This PR makes `local.conf` configurable via `enable_services` variable set in playbooks.
fixes #1650 
The contents of the config file are based on @lingxiankong's https://gist.github.com/lingxiankong/a109303f48e9a74fc8a7c01de4156d71/raw . I've only reshuffled the plugin sections and added `enable_plugin <PLUGIN NAME> https://opendev.org/openstack/<PLUGIN NAME>.git {{ branch }}` for each plugin.
```release-note
NONE
```

[CI] Make devstack local.conf configurable

---

pkg/csi/manila/controllerserver.go

This is a backport of https://github.com/kubernetes/cloud-provider-openstack/pull/1667 into the release-1.22 branch.
Cherry-picked from 4128209d8f6013137516cfe04a50ee45af6b9990.
Without this fix, `ControllerExpandVolume` breaks locks on the affected volume. Controller plugin would need a manual restart (pod deletion).
fixes #
```release-note
[manila-csi-plugin] Fixed locking in ControllerExpandVolume
```

[manila-csi-plugin] ControllerExpandVolume: fix bad key for deleting from pendingVolumes (release-1.22)

---

.zuul.yaml

This PR removes `cloud-provider-openstack-acceptance-test-csi-manila` Zuul CI job trigger. We don't use OpenLab CI infra anymore.
```release-note
NONE
```

[manila-csi-plugin] Remove cloud-provider-openstack-acceptance-test-csi-manila job trigger

---

tests/playbooks/roles/install-devstack/defaults/main.yaml
tests/playbooks/roles/install-devstack/tasks/main.yml

This PR updates the openstack version used for testing to stable/xena
fixes #
```release-note
NONE
```

Update devstack branch to stable/xena

---

.github/workflows/pr.yaml
charts/cinder-csi-plugin/values.yaml

fixes #
```release-note
NONE
```

[Helm Chart][CI] Fix ct lint parameter

---

charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/cinder-csi-plugin/templates/snapshot-controller-statefulset.yaml
charts/cinder-csi-plugin/values.yaml
charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/manila-csi-plugin/values.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/values.yaml

This PR adds `logVerbosityLevel` variable to all Helm charts in this repository. Operators can now choose how verbose they want their logs. Default levels are set to 2.
fixes #
```release-note
[Charts] Added logVerbosityLevel variable to cinder-csi-plugin, manila-csi-plugin and openstack-controller-manager Helm charts
```

[Charts] Add logVerbosityLevel variable to all Helm charts

---

tests/ci-occm-e2e.sh
tests/e2e/cloudprovider/test-lb-service.sh
tests/playbooks/roles/install-devstack/defaults/main.yaml
tests/playbooks/roles/install-devstack/tasks/main.yml
tests/playbooks/roles/install-devstack/templates/local.conf.j2

* Use pre-built amphora image to avoid the creation during the devstack run.
* Copy the image build log when necessary.
* Enable auto resource clean up option in the script, default true.
* Added the function to wait for the load balancer IP address accessible.
fixes #
```release-note
NONE
```

[occm][CI] Use pre-built amphora image in DevStack

---

pkg/openstack/loadbalancer.go

In the case of octavia, when creating `listener, pool, healthmonitor` name is not properly set in createOpts.
So, edit the name to be set.
fixes #
```release-note
NONE
```

[occm] Fix listener, pool, healthmonitor's empty name

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go

This PR makes it possible to use other alternatives than nip.io as temporary solution for PROXY protocol loadbalancers
fixes #1693
```release-note
[openstack-cloud-controller-manager] "nip.io hack" can now use different dns suffix by configuring `ingress-hostname-suffix` to config file
```

[occm] make PROXY loadbalancer ingress suffix configurable

---

pkg/client/client.go

Related #1684
```release-note
NONE
```

[general] return error early to avoid nil pointer usage

---

charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/values.yaml

Depending on which controllers of the OCCM are being used, not all
volume mounts specified in the Helm chart are necessary.
Furthermore, some systems use different paths for these components [1] or
they don't have them at all [2], which will result in failure to attach
the volume to the pod and subsequently run the pod.
This patch makes the volume mounts configurable for the Helm chart
user. By default, the same volumes as before (flexvolume-dir,
ca-certs, k8s-certs) are mounted into the pods.
This makes this change transparent to current users of the Helm
chart (no breaking change).
This patch also updates the deprecated --address parameter to use
--bind-address instead.
**Which issue this PR fixes(if applicable)**: N/A
**Special notes for …

[occm] Make volume mounts configurable in Helm Chart

---

charts/cinder-csi-plugin/values.yaml
charts/manila-csi-plugin/values.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml

for various purposed:
1) currency
2) potential new features introduced
3) potential update of CSI spec
fixes #
```release-note
NONE
```

[csi-plugins] Bump CSI sidecar containers versions

---

pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/openstack/openstack_volumes.go

What this PR does / why we need it:
This patch adds the microversion needed to be able to properly
filter volumes by name.
Which issue this PR fixes(if applicable):
fixes #1487

[cinder-csi-plugin] Add microversion to GetVolumeByName

---

pkg/ingress/controller/controller.go

[octavia-ingress-controller] Include CA certs into Barbican secret
It adds the CA certificates into the Barbican secret.
**Which issue this PR fixes(if applicable):**
fixes #1700
```release-note
NONE
```

[octavia-ingress-controller] Include CA certs into Barbican secret

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/values.yaml

This PR introduces the use of `initContainers` in the chart, we need `initContainers` because is some use cases, users may need to run a few more things before OCCM starts (such as waiting for a DNS to come online)
fixes: #1709
To test this PR you can uncomment the example that I have under `extraInitContainers` in the chart values:
```
```
Then if you do a `helm install`, OCCM should start in 10 seconds after the `busybox` container.
```release-note
[openstack-cloud-controller-manager] Added support for InitContainer in the OCCM chart
```

[occm] InitContainers Support

---

pkg/ingress/controller/controller.go

fixes #
```release-note
NONE
```

[OCCM] Update log of delete resource to provide more info

---

docs/octavia-ingress-controller/using-octavia-ingress-controller.md

doc update, according to 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/ingress/utils/utils.go#L37
and 
```
+--------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------------------+----------------------------------+-------------------------------------------------------------------+
| ID                                   | Name                                               | Description                                                                           | Project                          | Tags                                                              | …
```

doc: from k8s_ing to kube_ingress in doc

---

cluster/images/barbican-kms-plugin/Dockerfile
cluster/images/barbican-kms-plugin/Dockerfile.build
cluster/images/k8s-keystone-auth/Dockerfile
cluster/images/k8s-keystone-auth/Dockerfile.build
cluster/images/magnum-auto-healer/Dockerfile
cluster/images/magnum-auto-healer/Dockerfile.build
cluster/images/manila-csi-plugin/Dockerfile
cluster/images/manila-csi-plugin/Dockerfile.build
cluster/images/octavia-ingress-controller/Dockerfile
cluster/images/octavia-ingress-controller/Dockerfile.build
cluster/images/openstack-cloud-controller-manager/Dockerfile
cluster/images/openstack-cloud-controller-manager/Dockerfile.build

Alpine 3.11 is not supported anymore
fixes #
```release-note
Base images updated to alpine 3.15
```

update alpine base images to 3.15

---

pkg/autohealing/controller/controller.go

Support for configmaps lock for leaderelection is removed in K8s 1.24 with kubernetes/kubernetes#106852.
More details about the motivation to switch to leases - ref kubernetes/kubernetes#80289.
To preserve the backward compatibility, resource lock for migration purposes (configmapsleases) should be used when switching from the legacy resource locks (configmaps).
`magnum-auto-healer` is currently using configmaps. As the first step, this PR adapts configmapsleases.
Once this is merged, we can migrate to leases.
fixes #1732
```release-note
NONE
```

[magnum-auto-healer] Migrate resourcelock to configmapsleases for leader election

---

docs/octavia-ingress-controller/using-octavia-ingress-controller.md
pkg/ingress/controller/controller.go
pkg/ingress/controller/openstack/octavia.go

Add support for `ingress.kubernetes.io/whitelist-source-range` annotation.
fixes #1703 
```release-note
[octavia-ingress-controller] Add support for whitelist-source-range annotation.
```

[octavia-ingress-controller] support for whitelist-source-range annotation

---

pkg/csi/cinder/driver.go
pkg/csi/cinder/driver_test.go

cinder csi driver version bumped to 2.0.0 to match the chart version
and because of the breaking change introduced in deploying driver
from statefulset to Deployment.
fixes #
```release-note
NONE
```

[cinder-csi-plugin] Bump driver version to 2.0.0

---

docs/cinder-csi-plugin/using-cinder-csi-plugin.md

fixes #
```release-note
NONE
```

doc: add reference from ignore_volume_az to cross_az_attach in doc

---

charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
charts/cinder-csi-plugin/values.yaml

cinder-csi doesn't currently allow to set the cluster ID via its helm chart. It's hardcoded to `kubernetes`. This PR adds a Helm value `clusterID` so that it's configurable.
fixes #
```release-note
[cinder-csi-plugin] Add clusterID Helm chart value
```

[cinder-csi-plugin] Add clusterID Helm value

---

pkg/ingress/controller/controller.go

fixes #1724 
```release-note
NONE
```

[octavia-ingress-controller]: update label from master to excludeLB

---

pkg/csi/manila/csiclient/client.go
pkg/csi/manila/csiclient/interface.go
pkg/csi/manila/nodeserver.go
tests/sanity/manila/fakecsiclient.go

`NodeGetVolumeStats` is now forwarded to the partner plugin if it supports `GET_VOLUME_STATS` Node Service capability.
Tested with a CephFS share.
Logs:
```
I0107 15:22:15.382326       1 driver.go:314] [ID:10] GRPC call: /csi.v1.Node/NodeGetVolumeStats
I0107 15:22:15.382340       1 driver.go:315] [ID:10] GRPC request: {"volume_id":"94f7e992-9be2-462d-a679-59d7cf275a17","volume_path":"/var/lib/kubelet/pods/93883049-72db-404d-8f2e-7c64b5252475/volumes/kubernetes.io~csi/pvc-b479a5de-5274-488e-8951-de5cc8223390/mount"}
I0107 15:22:15.382852       1 builder.go:45] [ID:6] FWD GRPC call: /csi.v1.Node/NodeGetVolumeStats
I0107 15:22:15.382865       1 builder.go:46] [ID:6] FWD GRPC request: {"volume_id":"94f7e992-9be2-462d-a679-59d7cf275a17","volume_path":"/va …
```

[manila-csi-plugin] Add NodeGetVolumeStats

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/openstack/loadbalancer.go
pkg/util/openstack/loadbalancer.go

This PR adds support for `externalTrafficPolicy: local` which currently is listed as a limitation in the docs.
This change also handles the update case. So changing `externalTrafficPolicy` reconfigures the health monitor and members accordingly. 
fixes #763 
```release-note
[openstack-cloud-controller-manager] Support setting externalTrafficPolicy to Local so that traffic is only sent to the worker nodes which have the service pods.
```

[oocm] support for externalTrafficPolicy: Local

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/barbican-kms-plugin/using-barbican-kms-plugin.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/roles/install-csi-manila/tasks/main.yaml

Update docker image tag and Chart version for release v1.23.0.
The cinder-csi-plugin chart major version is increased because commit 9a9976f0e618a634c01198651cba01af107568f6 introduced backward incompatible change.
fixes #
```release-note
NONE
```

[All] Update docker image tag and Chart version for release v1.23.0

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml

Make the chart versions the same with those in release-1.23.
Again, the chart version policy is, only increase the version (either minor or major) when doing release.
fixes #
```release-note
NONE
```

[helm charts] Make the chart versions consistent with release-1.23

---

Makefile

darwin/amd64 is blocking the build-cross target in Makefile, we don't have a proper reason to keep that.
The related error:
```
1 errors occurred:
--> darwin/amd64 error: exit status 2
Stderr: # k8s.io/cloud-provider-openstack/pkg/csi/cinder
pkg/csi/cinder/nodeserver.go:419:23: r.NeedResize undefined (type *"k8s.io/mount-utils".ResizeFs has no field or method NeedResize)
make: *** [Makefile:311: build-cross] Error 1
```
fixes #
```release-note
NONE
```

Remove darwin/amd64 from OS arch support

---

pkg/openstack/loadbalancer.go

Currently if service uses externalClusterPolicy: Local the loadbalancers will not work. It works for few minutes but after that loadbalancers will go to `ERROR` state. Read issue #1749 
fixes #1749 
```release-note
[openstack-cloud-controller-manager] Fix the monitor port for pool members when updating loadbalancer.
```

[occm] Fix updating octavia port when using externalClusterPolicy Local

---

pkg/openstack/loadbalancer.go

This was introduced by https://github.com/kubernetes/cloud-provider-openstack/pull/1658/files#diff-89af30f72ae5c8aefb464330d654b95dc41544d558d9c04c9e728a8ea9a94793R1828
fixes #
```release-note
NONE
```

[occm] Fix monitor name

---

pkg/openstack/openstack.go

We were using incorrect service account name which causes service creation failure.
fixes #1722
```release-note
NONE
```

[occm] Fix the service account name

---

pkg/openstack/loadbalancer.go

Currently if service uses externalClusterPolicy: Local the loadbalancers will not work. It works for few minutes but after that loadbalancers will go to `ERROR` state. Read issue #1749 
cherry-pick #1750 
```release-note
[openstack-cloud-controller-manager] Fix the monitor port for pool members when updating loadbalancer.
```

[occm] Fix updating octavia port when using externalClusterPolicy Local, cherry-pick to 1.23

---

pkg/openstack/openstack.go

What this PR does / why we need it:
We were using incorrect service account name which causes service creation failure.
Which issue this PR fixes(if applicable):
fixes #1722
Special notes for reviewers:
Release note:
```release-note
NONE
```

[occm] cherry pick of #1755: Fix the service account name

---

tests/e2e/csi/manila/manilavolume.go
tests/e2e/csi/manila/testdriver.go
tests/e2e/csi/manila/testsuite.go
tests/playbooks/roles/install-csi-manila/tasks/main.yaml

This PR adds rest of the tests from e2e storage test suite.
Problems I've experienced:
* FsGroupChangePolicyTestSuite:
* It seems like it's trying to delete a PVC that's still in use by a Pod, and then fails due to timeout when attempting to delete that PVC.
* It also deleted storage class of a PVC before deleting that PVC, which then causes deletion of that PVC to fail (can't access the provisioner secrets anymore).
* EphemeralTestSuite:
* Pod: `Warning  FailedMount  16s (x10 over 4m25s)  kubelet            MountVolume.NewMounter initialization failed for volume "my-volume-0" : volume mode "Ephemeral" not supported by driver cephfs.manila.csi.openstack.org (only supports ["Persistent"])`
* The test doesn't check for this, and is stuck on `STEP: …

[manila-csi-plugin] more e2e tests

---

charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/cinder-csi-plugin/values.yaml
docs/cinder-csi-plugin/using-cinder-csi-plugin.md

My apologies for messing up the previous one.
**What this PR does / why we need it**: 
Currently the openstack-ccm helm chart [hardcodes its key name](https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/openstack-cloud-controller-manager/templates/secret.yaml#L8) when creating its secret as `cloud.conf`. Due to the different secret keys, you must create two separate secrets if running both the CCM and CSI plugin. This change would allow the `cinder-csi-plugin` reuse the existing secret created by the CCM.
```release-note
[cinder-csi-plugin] Make CLOUD_CONFIG secret keys consistent in helm chart for better re-usability 
```

[cinder-csi-plugin] Updated CLOUD_CONFIG in helm chart.

---

pkg/csi/manila/controllerserver.go
pkg/csi/manila/share.go
pkg/csi/manila/util.go

`ControllerExpandVolume` doesn't round up new size to GiB leading to an error described in #1764. This PR fixes `bytesToGiB` which `ControllerExpandVolume` uses to convert the input size in bytes to GiB.
fixes #1764 
Logs:
```
I0124 13:50:37.660046       1 driver.go:314] [ID:15] GRPC call: /csi.v1.Controller/ControllerExpandVolume
I0124 13:50:37.660069       1 driver.go:315] [ID:15] GRPC request: {"capacity_range":{"required_bytes":2000000000},"secrets":"***stripped***","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":5}},"volume_id":"b9eeed27-a1f8-4de2-8161-9af786ba24b8"}
I0124 13:50:37.660393       1 client.go:252] Using user-agent …
```

[manila-csi-plugin] ControllerExpandVolume rounds up size to GiB

---

pkg/openstack/instances.go

There is one call that is missing prometheus metrics
fixes #
```release-note
NONE
```

[occm] add missing metric to InstanceMetadata

---

pkg/autohealing/cloudprovider/register/register.go

Cinder v2 has been deprecated since Pike release, let's use v3.
Fixes #1738
```release-note
[magnum-auto-healer] Remove Cinder V2 support. Action required.
```

[magnum-auto-healer] use Cinder v3

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
pkg/openstack/loadbalancer.go
pkg/openstack/loadbalancer_test.go
pkg/util/openstack/loadbalancer.go

**What this PR does / why we need it**: Currently it is possible to define loadbalancer health monitor values only in Kubernetes cluster level. This is not optimal for all workloads. If we want applications to have minimal downtime these parameters should be configurable in service level.
fixes https://github.com/kubernetes/cloud-provider-openstack/issues/1763
```release-note
[openstack-cloud-controller-manager] LoadBalancer health monitor values configurable by using annotations `loadbalancer.openstack.org/health-monitor-delay`, `loadbalancer.openstack.org/health-monitor-timeout` and `loadbalancer.openstack.org/health-monitor-max-retries`
```

[occm] update lb monitoring params via annotations

---

pkg/autohealing/cloudprovider/register/register.go

Cinder v2 has been deprecated since Pike release, let's use v3.
Cherry-pick of #1769 
fixes #
```release-note
[magnum-auto-healer] Remove Cinder V2 support. Action required.
```

magnum-auto-healer: use Cinder v3 (#1769)

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go

One of the CNI plugins that can be used when Kubernetes runs on OpenStack is Kuryr-Kubernetes. If it's configured, K8s pods will get wired using OpenStack Neutron and trunk ports. Services, on the other hand, will get represented by internal-facing Octavia load balancers. In case of LoadBalancer Services, Kuryr will use the same approach, only adding a FIP to such an LB. This means that when running with Kuryr the Services controller in cloud-provider-openstack should be disabled, as Kuryr handles that on his own.
This commit adds `enabled` option to the `LoadBalancerOpts`, that will default to `true`. If explicitly disabled, the `EnsureLoadBalancer()` and `UpdateLoadBalancer()` functions will only raise `ImplementedElsewhere` error, effectively …

[occm] Add ability to disable Service controller

---

charts/manila-csi-plugin/templates/_helpers.tpl
charts/manila-csi-plugin/templates/controllerplugin-clusterrole.yaml
charts/manila-csi-plugin/templates/controllerplugin-clusterrolebinding.yaml
charts/manila-csi-plugin/templates/controllerplugin-role.yaml
charts/manila-csi-plugin/templates/controllerplugin-rolebinding.yaml
charts/manila-csi-plugin/templates/controllerplugin-rules-clusterrole.yaml
charts/manila-csi-plugin/templates/controllerplugin-service.yaml
charts/manila-csi-plugin/templates/controllerplugin-serviceaccount.yaml
charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
charts/manila-csi-plugin/templates/nodeplugin-clusterrole.yaml
charts/manila-csi-plugin/templates/nodeplugin-clusterrolebinding.yaml
charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/manila-csi-plugin/templates/nodeplugin-rules-clusterrole.yaml
charts/manila-csi-plugin/templates/nodeplugin-serviceaccount.yaml
charts/manila-csi-plugin/values.yaml

Extra labels are optional and applied to all resources already sporting labels
Having the possibility of adding optional extra labels to K8s resources would make the Helm chart more flexible.
fixes #1786
I've tested it setting extraValues.enabled to true and adding some dummy labels as well as with no values and extraValues.enabled set to false. Both times I've run helm3 template . 
```release-note
[Manila-CSI-plugin]
Adding optional extra labels to be set in .Values.extraLabels.labels. Enable the usage of extra labels setting .Values.extraLabels.enable to true
```

[manila-csi-plugin] Add extra labels to k8s resources

---

charts/cinder-csi-plugin/templates/_helpers.tpl
charts/cinder-csi-plugin/values.yaml

As per comment in PR#1788 (https://github.com/kubernetes/cloud-provider-openstack/pull/1788#issuecomment-1038868091) it's been considered a good idea to provide extraLabels capability yo Cinder plugin too.
N/A
This has been tested templating the Cinder plugin Helm chart with and without a test.yaml file containing extra labels
```helm3 template . -f test.yaml```
```release-note
[Cinder-CSI-plugin]
Adding optional extra labels to be set in .Values.extraLabels. Enable the usage of extra labels adding the desired labels to Values.extraLabels
```

[Cinder-csi-plugin] Provide capability to add extra labels for Cinder

---

docs/cinder-csi-plugin/using-cinder-csi-plugin.md
docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
manifests/controller-manager/cloud-config
pkg/openstack/openstack_test.go
tests/playbooks/roles/install-cpo-occm/tasks/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

`bs-version` config option is not supported anymore and by default
v3 api is used. This PR is to remove the same from the code.
This PR also removes the reference to identity v2 in docs as its support is  removed.
fixes #
```release-note
NONE
```

[all] Remove deprecated option `bs-version`

---

charts/openstack-cloud-controller-manager/templates/service-sm.yaml

The `occm.labels` helm helper in the occm chart doesn't match the pods of the DS as they instead uses the `occm.controllermanager.labels` helper. By changing the service selector to use the `occm.controllermanager.matchLabels` helper we ensure that it matches the occm DS pods.

[occm] The service monitor svc should select the pods of the occm DS

---

charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/cinder-csi-plugin/values.yaml

Making the change from #1747 backwards-compatible, when using `secret.enabled: true` and `secret.create: false`, and thus creating the secret externally (referred from `secret.name`). Some users might even be sharing the same secret between OCCM and Cinder CSI out of convenience.
```yaml
$ helm template cinder-csi-plugin charts/cinder-csi-plugin | grep "value: /etc/kubernetes"
value: /etc/kubernetes/cloud-config
value: /etc/kubernetes/cloud-config
```
```yaml
$ helm template cinder-csi-plugin charts/cinder-csi-plugin | grep "value: /etc/kubernetes"
value: /etc/kubernetes/cloud.conf
value: /etc/kubernetes/cloud.conf
```
```yaml
$ helm template cinder-csi-plugin charts/cinder-csi-plugin | grep "value: /etc/kubernetes"
value: /etc/kubernetes/cloud.conf
value: /etc/kubernetes/cloud.conf
``` …

[cinder-csi-plugin] Configurable secret filename

---

charts/manila-csi-plugin/templates/_helpers.tpl
charts/manila-csi-plugin/templates/controllerplugin-clusterrole.yaml
charts/manila-csi-plugin/templates/controllerplugin-clusterrolebinding.yaml
charts/manila-csi-plugin/templates/controllerplugin-role.yaml
charts/manila-csi-plugin/templates/controllerplugin-rolebinding.yaml
charts/manila-csi-plugin/templates/controllerplugin-rules-clusterrole.yaml
charts/manila-csi-plugin/templates/controllerplugin-service.yaml
charts/manila-csi-plugin/templates/controllerplugin-serviceaccount.yaml
charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
charts/manila-csi-plugin/templates/nodeplugin-clusterrole.yaml
charts/manila-csi-plugin/templates/nodeplugin-clusterrolebinding.yaml
charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/manila-csi-plugin/templates/nodeplugin-rules-clusterrole.yaml
charts/manila-csi-plugin/templates/nodeplugin-serviceaccount.yaml

This PR moves various `labels` listings from individual Kubernetes component manifests into common named templates, into `_helpers.tpl`. This is inspired by (borrowed / stolen from :)) cinder-csi's chart that does this too, and I think is nicer than what manila-csi currently does.
No effective change in rendered YAML output, please see https://gist.github.com/gman0/5b711294cdbbbc7445f426bfd0b44c3f (only some key-value pairs are reordered but that has no real effect).
fixes #
```release-note
NONE
```

[manila-csi-plugin] added helper named templates for labels

---

tests/playbooks/roles/install-csi-manila/tasks/main.yaml
tests/playbooks/test-csi-manila-e2e.yaml

This PR updates e2e job of manila csi plugin to reuse existing occm role
fixes #
```release-note
NONE
```

[manila-csi-plugin] Update e2e tests to re-use occm role

---

docs/cinder-csi-plugin/features.md
docs/cinder-csi-plugin/using-cinder-csi-plugin.md

1) update output of kubectl get csidrivers.storage.k8s.io
2) a incorrect link
fixes #
```release-note
NONE
```

[cinder-csi-plugin]update doc on minor issues

---

charts/openstack-cloud-controller-manager/templates/clusterrole.yaml
manifests/controller-manager/cloud-controller-manager-roles.yaml

This modification allows the Openstack Cloud Controller Manager to send `PATCH` requests specifically for the Status field of a Service (across all namespaces).
This is required when the OCCM uses it's own service account to modify the Service resource (i.e. with `--use-service-account-credentials=false`).
Without this permission I encountered the following error message when installing the Helm chart (from master) and using `--use-service-account-credentials=false`:
```
E0228 11:04:53.120584       1 controller.go:310] error processing service default/my-lb (will retry): failed to add load balancer cleanup finalizer: services "my-lb" is forbidden: User "system:serviceaccount:NAMESPACE:openstack-cloud-controller-manager" cannot patch resource …
```

[occm] Allow service status changes in ClusterRole

---

tests/e2e/csi/cinder/cinder-testdriver.go

we allow volume resize when pod is using it ,so add this test into e2e
```
should resize volume when PVC is edited while pod is using it
```
fixes #
```release-note
NONE
```

[cinder-csi-plugin]Add CapOnlineExpansion e2e test

---

pkg/openstack/loadbalancer.go

This logs a warning when `internal-lb=false` is set and external service is requested. The documentation [here](https://github.com/kubernetes/cloud-provider-openstack/tree/master/examples/loadbalancers) says `service.beta.kubernetes.io/openstack-internal-load-balancer` is `false` by default. But `internal-lb` is also `false` by default. We spent some time debugging it without any indication in the logs.
This is my first PR here, so sorry if I messed up with something. Also for me it could be an error, but I'm not sure how important is backward-compatibility here.
```release-note
NONE
```

[openstack-cloud-controller-manager] Log warning when internal-lb=true and requesting external LB

---

charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/values.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml

fixes #1807 
```release-note
NONE
```

[OCCM] Add --cluster-name=$(CLUSTER_NAME) support

---

tests/ci-csi-cinder-e2e.sh
tests/playbooks/roles/install-csi-cinder/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

This PR enables logs  of e2e tests for debugging purpose
fixes #
```release-note
NONE
```

[cinder-csi-plugin] Enable logs for e2e tests

---

Makefile
hack/verify-golint.sh

fixes #1816 
```release-note
NONE
```

Fix lint issue

---

docs/cinder-csi-plugin/examples.md
docs/cinder-csi-plugin/features.md

Add Doc for Topo for CSI
fixes #
```release-note
NONE
```

[cinder-csi-plugin] Add Doc for topology

---

tests/e2e/csi/cinder/cinder-testdriver.go
tests/e2e/csi/cinder/csi-volumes.go
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

fixes #1661 
```release-note
NONE
```

[cinder-csi-plugin]add snapshot test back into CI 

---

go.mod
go.sum

fixes #1819 
```release-note
NONE
```

update prometheus goclient to 1.11.1 to address CVE-2022-21698

---

pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go
pkg/csi/cinder/openstack/openstack_snapshots.go

… create
fixes #1812 
```release-note
NONE
```

[cinder-csi-plugin]add 'force-create' into tag param to support force 

---

Makefile

fixes #1502
```release-note
NONE
```

[occm] Fix the binary version

---

tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-cpo-occm/tasks/main.yaml

Currently when the CI job fails, we can't see the pod logs, making it hard for troubleshooting.
This PR also fixes the image tag issue.
fixes #
```release-note
NONE
```

[occm] Get occm pod logs when CI job fails

---

tests/ci-csi-cinder-e2e.sh
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

add more logs for Cinder CSI pod for debug purpose
fixes #
```release-note
NONE
```

[cinder-csi-pluging] Add pod logs for cinder e2e

---

OWNERS

fixes #
```release-note
NONE
```

clean up inactive owners and reviewers 

---

pkg/openstack/loadbalancer.go

Move the remove of the listener at the end of the loop.
Since the listener is a pointer and needed during the loop the removal will mess up the logic.
We observed on a k8s service with 4 ports that a load balancer listener pool were updated on every reconcile loop.
fixes https://github.com/kubernetes/cloud-provider-openstack/issues/1795
```release-note
NONE
```

[OCCM] fix listener pop during iteration

---

charts/cinder-csi-plugin/templates/secret.yaml

fixes #1834 
```release-note
NONE
```

[cinder-csi-plugin][charts] typo secret.namespace

---

go.mod
go.sum

Upgrade golang.org/x/crypto to latest (pushed on Apr 11, 2022).
This commit is the result of running:
```
go get golang.org/x/crypto/ssh@latest \
&& go mod tidy && go mod vendor
```
See https://groups.google.com/g/golang-announce/c/-cp44ypCT5s/m/wmegxkLiAQAJ
Upgrades golang.org/x/crypto/ssh to latest, where the vulnerability has been fixed.
```
Address CVE-2022-27191 by bumping golang.org/x/crypto and golang.org/x/net.
```

fix: Address CVE-2022-27191

---

pkg/openstack/loadbalancer.go

I noticed that OCCM would create healthmonitors named like this (note the trailing bracket)
> monitor_1_kube_service_CLUSTER_NAMESPACE_SERVICE)
It turns out there is minor typo in the code, fixed with this patch.
```release-note
NONE
```

[occm] Remove trailing bracket from healthmonitor

---

charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml

cause Deployment and DaemonSet are namespaced resource
fixes #1837 
```release-note
NONE
```

[cinder-csi-plugin][charts] add metadata.namespace

---

cluster/images/barbican-kms-plugin/Dockerfile
cluster/images/barbican-kms-plugin/Dockerfile.build
cluster/images/k8s-keystone-auth/Dockerfile
cluster/images/k8s-keystone-auth/Dockerfile.build
cluster/images/magnum-auto-healer/Dockerfile
cluster/images/magnum-auto-healer/Dockerfile.build
cluster/images/manila-csi-plugin/Dockerfile
cluster/images/manila-csi-plugin/Dockerfile.build
cluster/images/octavia-ingress-controller/Dockerfile
cluster/images/octavia-ingress-controller/Dockerfile.build
cluster/images/openstack-cloud-controller-manager/Dockerfile
cluster/images/openstack-cloud-controller-manager/Dockerfile.build

fixes #1847
```release-note
NONE
```

[All] update docker version from alpine:3.15 to 3.15.4

---

manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
tests/playbooks/roles/install-cpo-occm/tasks/main.yaml

related #1839 
```release-note
NONE
```

[OCCM]switch to node-role.kubernetes.io/control-plane

---

docs/cinder-csi-plugin/troubleshooting.md

In the past I saw this question bubbling up several times and it is hard
to find an good answer on the internet.
fixes #
```release-note
NONE
```

[cinder-csi-plugin] Add doc for volume expansion

---

pkg/openstack/loadbalancer.go

fixes #1830 
```release-note
NONE
```

OCCM: add sec group logic for octavia

---

cluster/images/barbican-kms-plugin/Dockerfile
cluster/images/barbican-kms-plugin/Dockerfile.build
cluster/images/k8s-keystone-auth/Dockerfile
cluster/images/k8s-keystone-auth/Dockerfile.build
cluster/images/magnum-auto-healer/Dockerfile
cluster/images/magnum-auto-healer/Dockerfile.build
cluster/images/manila-csi-plugin/Dockerfile
cluster/images/manila-csi-plugin/Dockerfile.build
cluster/images/octavia-ingress-controller/Dockerfile
cluster/images/octavia-ingress-controller/Dockerfile.build
cluster/images/openstack-cloud-controller-manager/Dockerfile
cluster/images/openstack-cloud-controller-manager/Dockerfile.build

for release 1.23
fixes #1847 
```release-note
NONE
```

update docker version from alpine:3.15 to 3.15.4

---

README.md

fixes #
```release-note
NONE
```

Add jichen as co-leader

---

.github/workflows/release-cpo.yaml
.github/workflows/release-occm.yaml
Makefile
go.mod
go.sum
release-procedure.md

fixes #
```release-note
NONE
```

Add Github Actions release pipeline

---

pkg/client/client.go

This patch extend the authentication configuration by the possibility to use
application credentials.
fix_auth_dependencies_for_application_credentials
Signed-off-by: Sven Haardiek <sven.haardiek@uni-muenster.de>
This patch extend the authentication configuration by the possibility to use
application credentials.
Without this PR the dependencies are not properly satisfied, if application credentials are used.
fixes #1857
```release-note
NONE
```

Fix for Authentication Dependencies for Application Credentials

---

.github/workflows/release-cpo.yaml

fixes #
```release-note
NONE
```

fix on push tags

---

.github/workflows/release-cpo.yaml

fixes hopefully https://github.com/kubernetes/cloud-provider-openstack/runs/6505458649?check_suite_focus=true issue with the version number in build
```release-note
NONE
```

read version from github ref

---

docs/magnum-auto-healer/using-magnum-auto-healer.md
manifests/magnum-auto-healer/magnum-auto-healer.yaml
pkg/autohealing/controller/controller.go

fixes #
```release-note
NONE
```

fix magnum master references

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/barbican-kms-plugin/using-barbican-kms-plugin.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

fixes #
```release-note
NONE
```

update images and charts to v1.24.0

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml

fixes #
```release-note
NONE
```

update chart versions to master

---

cmd/client-keystone-auth/main.go
cmd/k8s-keystone-auth/main.go
pkg/identity/keystone/authenticator.go
pkg/identity/keystone/authorizer.go
pkg/identity/keystone/keystone.go
pkg/identity/keystone/sync.go
pkg/identity/keystone/token_getter_test.go
tests/ci-keystone-e2e.sh

Refactor identity to make golangci-lint happy.
This PR includes the components client-keystone-auth and
k8s-keystone-auth, which both use pkg/identity.
```release-note
NONE
```

[client-keystone-auth] Refactor identity components to improve code climate

---

cmd/barbican-kms-plugin/main.go
pkg/kms/barbican/barbican.go
pkg/kms/client/client.go
pkg/kms/encryption/aescbc/aescbc_test.go
pkg/kms/server/server.go

Refactor barbican-kms-plugin to make golangci-lint happy.
```release-note
NONE
```

[barbican-kms-plugin] Refactor barbican-kms-plugin to improve code climate

---

pkg/autohealing/cloudprovider/openstack/provider.go
pkg/autohealing/cloudprovider/register/register.go
pkg/autohealing/cmd/root.go
pkg/autohealing/controller/controller.go
pkg/autohealing/healthcheck/plugin_nodecondition.go

Refactor magnum-auto-healer to make golangci-lint happy.
```release-note
NONE
```

[magnum-auto-healer] Refactor autohealing to improve code climate

---

pkg/openstack/instances.go
pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go
pkg/openstack/openstack_loadbalancer_subnet_match_test.go
pkg/openstack/openstack_test.go
pkg/openstack/routes_test.go

Refactor occm to make golangci-lint happy.
```release-note
NONE
```

[occm] Refactor occm to improve code climate

---

pkg/ingress/controller/controller.go
pkg/ingress/controller/openstack/neutron.go

Refactor octavia-ingress-controller to make golangci-lint happy.
```release-note
NONE
```

[octavia-ingress-controller] Refactor ingress to improve code climate

---

pkg/csi/cinder/identityserver.go
pkg/csi/cinder/openstack/openstack.go
pkg/csi/cinder/openstack/openstack_mock.go
pkg/csi/cinder/openstack/openstack_volumes.go
tests/sanity/cinder/fakecloud.go

Remove all sorts of downstream dependency on cinder from probe. Probe is
the one called by the liveness sidecar to determine the health of the
csi plugin. Including downstream services in a health check can result
in unfortunate behavior in cluster. For example, over and over restarts
of daemonsets/deployments just because the downstream api is not
available at the moment... e.g. because of a maintenance.
On the other hand, just because the downstream api is available doesn't
tell us anything about whether or not the downstream works as expected.
Therefore there are facilities in place that reports errors when they
happen all over the place.
fixes #1903 …

[cinder-csi-plugin] Remove downstream from probe

---

pkg/csi/cinder/identityserver.go
pkg/csi/cinder/openstack/openstack.go
pkg/csi/cinder/openstack/openstack_mock.go
pkg/csi/cinder/openstack/openstack_volumes.go
tests/sanity/cinder/fakecloud.go

Remove all sorts of downstream dependency on cinder from probe. Probe is
the one called by the liveness sidecar to determine the health of the
csi plugin. Including downstream services in a health check can result
in unfortunate behavior in cluster. For example, over and over restarts
of daemonsets/deployments just because the downstream api is not
available at the moment... e.g. because of a maintenance.
On the other hand, just because the downstream api is available doesn't
tell us anything about whether or not the downstream works as expected.
Therefore there are facilities in place that reports errors when they
happen all over the place.
fixes # …

[cinder-csi-plugin] Remove downstream from probe (#1904)

---

tests/playbooks/roles/install-k3s/defaults/main.yaml
tests/playbooks/roles/install-k3s/tasks/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml
tests/playbooks/test-csi-manila-e2e.yaml
tests/playbooks/test-occm-e2e.yaml

This PR pinns k3s to v1.23.6+k3s1. We stick with that as long as we
can't reliably say that newer versions work well enough for us.
In the future, we must change code for k3s-v1.24.0 anywayse, because
docker is not supported there anyways. Until we change away from docker
we can't update to v1.24.
We must have a fixed version for now, to unblock our gates.
fixes #1902
I deliberately removed the guessing of the correct k3s release, because
any change in dependencies might cause trouble in our gating.
```release-note
NONE
```

[ci] Pin k3s to v1.23.6+k3s1

---

pkg/csi/cinder/controllerserver.go

updated some logs to make log clear
fixes #
```release-note
NONE
```

[cinder-csi-plugin] nit: improve logs

---

pkg/openstack/loadbalancer.go

/kind bug
Fixes https://github.com/kubernetes/cloud-provider-openstack/issues/1912
```release-note
[openstack-cloud-controller-manager] An issue preventing Service of type LoadBalancer to be deleted when the corresponding OpenStack LoadBalancer does no longer exists is now fixed.
```

occm: Fix LoadBalancer deletion when the underlying LoadBalancer does not exist

---

pkg/ingress/controller/controller.go

[octavia-ingress-controller] PKCS8 keys
#1910 
#1910 (I am not suggesting you use this code)
This is probably more relevant:
https://github.com/golang/go/blob/master/src/crypto/tls/tls.go#L336
```release-note
NONE
```

OpenSSL PEM generates PKCS #8 keys

---

pkg/ingress/controller/controller.go

* POC PKCS8
* formatting fix with gofmt
cherry pick from #1910
fixes #
```release-note
NONE
```

OpenSSL PEM generates PKCS #8 keys (#1911)

---

cmd/manila-csi-plugin/main.go
pkg/csi/manila/controllerserver.go
pkg/csi/manila/csiclient/builder.go
pkg/csi/manila/driver.go
pkg/csi/manila/nodeserver.go
pkg/csi/manila/share.go
pkg/csi/manila/snapshot.go
pkg/csi/manila/util.go
pkg/csi/manila/validator/valueexpr.go
pkg/csi/manila/volumesource.go
tests/ci-csi-manila-e2e.sh
tests/e2e/csi/manila/manilavolume.go
tests/e2e/csi/manila/testsuite.go
tests/playbooks/roles/install-csi-manila/tasks/main.yaml

Refactor manila-csi-plugin to make golangci-lint happy.
```release-note
NONE
```

[manila-csi-plugin] Refactor csi-manila to improve code climate

---

tests/playbooks/roles/install-k3s/defaults/main.yaml
tests/playbooks/roles/install-k3s/tasks/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml
tests/playbooks/test-csi-manila-e2e.yaml
tests/playbooks/test-occm-e2e.yaml

Backport pinning of k3s version in our ci, to un-block test runs.
fixes #
```release-note
NONE
```

Backport to v1.24 [ci] Pin k3s to v1.23.6+k3s1 (#1907)

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml

image update for all containers
fixes #
```release-note
NONE
```

make 1.24.0=>1.24.2

---

release-procedure.md

fixes #
```release-note
NONE
```

update release procedure file

---

charts/manila-csi-plugin/templates/csidriver.yaml
charts/manila-csi-plugin/values.yaml
tests/playbooks/roles/install-csi-manila/tasks/main.yaml

The fsGroupPolicy option can now be defined per protocol,
enforcing a different behavior to the driver [1]
[1] https://kubernetes-csi.github.io/docs/support-fsgroup.html
Signed-off-by: Francesco Pantano <fpantano@redhat.com>
fixes #1893
```release-note
Set fsGroupPolicy (None by default) for the CSIDriver object
```

Improve manila csi driver chart adding fsGroupPolicy

---

charts/openstack-cloud-controller-manager/values.yaml

As explained in https://github.com/kubernetes/cloud-provider-openstack/issues/1923 this mount breaks OCCM on Flatcar, and doesn't bring any value on Ubuntu.
fixes https://github.com/kubernetes/cloud-provider-openstack/issues/1923
I tested it on Flatcar and Ubuntu.
```release-note
[occm] Remove mostly broken default ca-certs mount from helm chart
```

[occm] Remove mostly broken default ca-certs mount from helm chart

---

pkg/openstack/loadbalancer.go

Cherry pick of #1793 on release-1.23.
#1793: fix listener pop during iteration
```release-note
[openstack-cloud-controller-manager] An issue causing for Services of type LoadBalancer with multiple ports OCCM to mix up the different listeners of a loadbalancer and start assigning the members to the wrong listener/pool is now fixed.
```

Automated cherry pick of #1793: fix listener pop during iteration

---

cluster/images/cinder-csi-plugin/Dockerfile.build

This PR adds the necessary binaries (via the corresponding deb-package) to be able to mount volumes containing btrfs. ( see [issue #1934](https://github.com/kubernetes/cloud-provider-openstack/issues/1934) and [this comment](https://github.com/kubernetes/cloud-provider-openstack/issues/1934#issuecomment-1186910206) ).
fixes #1934 
```release-note
[cinder-csi-plugin] added capability to mount btrfs volumes.
```

[cinder-csi-plugin] btrfs-volumes not mountable by cinder-csi-plugin

---

pkg/util/errors/errors.go

fixes #1935 
```release-note
Fixes IsNotFound checklist when LB is queried by Name instead of Id
```

occm: Fix not found checks for LoadBalancers do not cover all possible cases

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go

For heavely customized Openstack installation it may be helpful to disable `tls-container-ref` format validation.
Official [terraform-provider-openstack](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/lb_listener_v2#default_tls_container_ref) and [python-octaviaclient](https://docs.openstack.org/python-octaviaclient/pike/usage/osc/v2/load-balancer.html#cmdoption-loadbalancer-listener-create-default-tls-container-ref) do not have such validation mechanism
Now we have `container-store` parameter in `cloud.conf` which can be one of two values:
- `barbican` - Default. `tls-container-ref` format validation **enabled**
- `external` - `tls-container-ref` format validation **disabled**
**Which issue this …

[occm] Implement `container-store` configuration setting

---

pkg/autohealing/cloudprovider/openstack/provider.go
pkg/autohealing/healthcheck/plugin_endpoint.go
pkg/csi/cinder/driver.go
pkg/csi/cinder/nodeserver_test.go
pkg/csi/cinder/openstack/openstack_snapshots.go
pkg/csi/cinder/openstack/openstack_volumes.go
pkg/csi/manila/runtimeconfig/runtimeconfig.go
pkg/csi/manila/validator/validator.go
pkg/identity/keystone/sync.go
pkg/identity/keystone/token_getter.go
pkg/identity/keystone/token_getter_test.go
pkg/ingress/controller/controller.go
pkg/kms/barbican/barbican.go
pkg/openstack/instances.go
pkg/openstack/loadbalancer.go
pkg/openstack/openstack_test.go
pkg/util/blockdevice/blockdevice_linux.go
pkg/util/errors/errors.go
pkg/util/metadata/metadata.go
pkg/util/mount/mount.go
tests/sanity/cinder/fakemount.go
tests/sanity/cinder/sanity_test.go
tests/sanity/manila/sanity_test.go

fixes #
```release-note
NONE
```

fix gate issue

---

docs/cinder-csi-plugin/features.md

Improve documentation
```release-note
Improved documentation of the topology FeatureGate when using helm
```

[cinder-csi-plugin] mention Helm value for disabling topology feature

---

pkg/client/client.go

Constraints for application credential configuration don't allow setting
(os-applicationCredentialSecret and os-applicationCredentialID) or
(os-applicationCredentialSecret and os-applicationCredentialName). This
reverts the constraints from PR #1857 and add new ones for application
credentials.
Fixes #1956
```release-note
```

[manila-csi-plugin] Fix constraints configuration for application cred

---

charts/openstack-cloud-controller-manager/templates/secret.yaml

What this PR does / why we need it:
This PR is fixing the absence of LoadBalancerClass parsing from the helm chart
This is a helm chart change only
Which issue this PR fixes(if applicable):
fixes #
Isue 1856
Special notes for reviewers:
Just pass a values.yaml containing a .Values.cloudConfigContents field
For example:
cloudConfigContents: |
[Global]
auth-url=""
username=""
user-domain-id=""
password=""
tenant-id=""
project-domain-name=""
region=""
ca-file=""
[Networking]
internal-network-name=""
[LoadBalancer]
enable-ingress-hostname="true"
use-octavia="true"
create-monitor="true"
floating-network-id=""
subnet-id=""
[LoadBalancerClass "testclass"]
floating-network-id = ""
subnet-id = ""
[BlockStorage]
ignore-volume-az=""
```release-note
None
```

custom secret file for cloud.conf

---

charts/openstack-cloud-controller-manager/templates/_helpers.tpl

When a value in `cloud.conf`  (e.g. password) starts with `#` character, it becomes a comment since `#` starts comment section in `.conf` files. We need to add quotes around values to have valid conf files.
```release-note
Add quotes to values in cloudConfig
```

[occm] Add quotes to values in cloud.conf file in helm chart

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/ingress/utils/utils.go
pkg/openstack/instances.go
pkg/openstack/openstack.go
pkg/openstack/openstack_test.go

Change ProviderID to magic sting ```${ProviderName}://${REGION}/${instance-id}```
Which helps to find an instance in a multi-region setup.
It also support old magic string (without region). 
In this case OCCM works as before (can be used only in the one-zone cluster).
fixes #1900
```release-note
NONE
```

Add region to providerID magic string.

---

charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/templates/secret.yaml
charts/openstack-cloud-controller-manager/templates/service-sm.yaml
charts/openstack-cloud-controller-manager/templates/serviceaccount.yaml
charts/openstack-cloud-controller-manager/templates/servicemonitor.yaml

Namespaced API resources should have the namespace value set explicitly.
This commit updates the OCCM Helm chart to add this field to each template, inheriting the value of `Release.Namespace`.
```release-note
NONE
```
Signed-off-by: Nick Jones <nick@dischord.org>

[occm] Ensure namespaced objects have namespace set

---

pkg/ingress/utils/utils.go
pkg/openstack/instances.go

Fix definition instanceID from providerID.
Revert to the previous version with small changes.
Based on the conversation #1909.
Thanks @anguslees

fix: Add region to providerID magic string

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go

This patch introduces the possibility to configure the member-subnet-id
independent from the subnet-id.
This way it is possible to create load balancer with several network ports in
different subnet. For example to create load balancer with IPv6 frontend and
IPv4 backend.
Signed-off-by: Sven Haardiek <sven.haardiek@uni-muenster.de>
This patch introduces the possibility to configure the member-subnet-id
independent from the subnet-id.
This way it is possible to create load balancer with several network ports in
different subnet. For example to create load balancer with IPv6 frontend and
IPv4 backend.
It was already possible in a hacky way by using different `subnet-id`s in the
class configuration and the annotation. This way the annotation only …

[occm] Option to configure member-subnet-id for Load Balancer

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
pkg/openstack/loadbalancer.go

This patch makes it possible to explicitly configure the hostname of a
load balancer via annotation.
This hostname is used in the load balancer instead of the IP address or the
*fake* hostname.
Similar to `enabie-ingress-hostname`, this can be used with proxy protocol to preserve the IP, **but** this also works for IPv6 load balancer (<ipv6>.nip.io is no valid hostname).
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md#use-proxy-protocol-to-preserve-client-ip
fixes #1859
```release-note
Add option to set hostname on load balancer via …
```

[occm] Introduce Hostname Annotation

---

go.mod
go.sum

* openstack-cloud-controller-manager (occm)
* cinder-csi-plugin
* manila-csi-plugin
* k8s-keystone-auth
* client-keystone-auth
* octavia-ingress-controller
* magnum-auto-healer
* barbican-kms-plugin
Bumps gophercloud to v1.0.0
```release-note
NONE
```

Bump gophercloud to v1.0.0

---

tests/playbooks/roles/install-golang/defaults/main.yml

This PR sets golang version to 1.19 in install-golang role. The download location was also changed because 1.19 doesn't seem to be available in https://storage.googleapis.com/golang.
We need 1.19 golang toolchain because k/k 1.25 dependencies are already using some parts of its std lib which are not available in previous verisions (see https://github.com/kubernetes/cloud-provider-openstack/pull/1975#issuecomment-1232711142).
fixes #
```release-note
NONE
```

[ci] bump golang version to 1.19 in install-golang role

---

tests/playbooks/roles/install-golang/defaults/main.yml

Reverts kubernetes/cloud-provider-openstack#1981
looks like this causing issue now ..
```release-note
None
```

Revert "[ci] bump golang version to 1.19 in install-golang role"

---

pkg/openstack/loadbalancer.go

This patches fixes a small inconsistency in `getMemberSubnetID` where
`svcConf.configClassName` is used instead of `configClassName`.
fixes #
```release-note
NONE
```

[occm] Fix minor Inconsistency in `getMemberSubnetID`

---

pkg/util/errors/errors.go

fixes #
```release-note
NONE
```

Cherry pick test for ErrNotFound in IsNotFound checklist (#1942) to 1.24

---

tests/sanity/manila/fakecsiclient.go
tests/sanity/manila/fakemanilaclient.go

This PR fixes a couple of missing things in fakecsiclient and fakemanilaclient used in sanity CSI tests.
fixes #
```release-note
NONE
```

[manila-csi-plugin] Fix fake csi and manila clients for sanity-csi test

---

docs/cinder-csi-plugin/using-cinder-csi-plugin.md
pkg/csi/cinder/openstack/openstack.go
pkg/csi/cinder/openstack/openstack_volumes.go

When dealing with some older clouds we need to allow for ignoring the cinder microversion.
With this change, cloud users pre OpenStack Pike can once again create volumes by setting the new `ignore-volume-microversion` to `true`.
This PR affects two paths:
* Volume resize, we fail early if the new `ignore-volume-microversion` option is set and we return a error message explaining that this feature is not available with this option set.
* Filter volume by name, skips setting the microversion on the ServiceClient and makes it behave like it did pre #1488
fixes #1967 
* Run the cinder-csi-plugin against an older cloud with a cinder API version older than 3.34
* Create a …

[cinder-csi-plugin] Add option to ignore blockstorage microversion on older clouds

---

cluster/images/cinder-csi-plugin/Dockerfile.build
pkg/autohealing/cloudprovider/openstack/provider.go
pkg/csi/cinder/openstack/openstack_snapshots.go
pkg/csi/cinder/openstack/openstack_volumes.go
pkg/csi/manila/validator/validator.go
pkg/ingress/controller/controller.go
pkg/kms/barbican/barbican.go
pkg/openstack/loadbalancer.go
pkg/util/errors/errors.go
pkg/util/mount/mount.go
tests/sanity/cinder/fakemount.go

cherry pick #1941
update go fmt with all files
fixes #
```release-note
NONE
```

cherry pick support mounting btrfs volumes by the cinder-csi-plugin (#1941) to 1.24

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
pkg/openstack/loadbalancer.go

This patch make the `EnsureLoadbalancer` honor the settings for network-id and subnet-id made in the load balancer classes.
Otherwise subnet-id and network-id are not settable from the class and only from annotations, but according to the docs (at least part of the docs) this should work:
fixes #1961
I only fixed this for the octavia load balancer not for the legacy ones.
```release-note
Honor network-id and subnet-id in load balancer classes
```

[occm] network-id and subnet-id in class settings

---

.github/workflows/release-cpo.yaml

fixes #
```release-note
NONE
```

update go version in GHA

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml

fixes #
```release-note
NONE
```

update image tags to v1.25.0

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/openstack/loadbalancer.go

This patch makes it possible to use the manage-security-groups with octavia
load balancer.
It creates a new function `ensureAndUpdateOctaviaSecurityGroup` which is called
on `EnsureLoadBalancer` and `UpdateLoadBalancer` and handles the security group
and security rule creation for Octavia Load Balancer.
To make the changes not bigger than needed, it hooks into the
`updateSecurityGroup` and `ensureSecurityGroup` function first, checks if
Octavia is used and uses the new code. Otherwise the legacy code is called. So
the removal of the legacy code should be quite easy.
Also it adds a missing security rule for the HealthCheckNodePort and therefore supersedes  PR #1972.
fixes #1976 
fixes #1971
**Special …

[occm] Manage Security Groups for Octavia

---

pkg/ingress/controller/controller.go
pkg/ingress/controller/openstack/octavia.go
pkg/openstack/loadbalancer.go
pkg/util/errors/errors.go
pkg/util/openstack/keymanager.go
pkg/util/openstack/loadbalancer.go

Deprecates `ErrNotFound` and `ErrMultipleResults` errors in `k8s.io/cloud-provider-openstack/pkg/util/openstack`
as the same are defined in `k8s.io/cloud-provider-openstack/pkg/util/errors`.
Fix not found check for LoadBalancers in  `k8s.io/cloud-provider-openstack/pkg/util/openstack.ensureLoadBalancerDeleted` method.
fixes #1935
```release-note
Errors `ErrNotFound` and `ErrMultipleResults` in `k8s.io/cloud-provider-openstack/pkg/util/openstack` are deprecated, please use `ErrNotFound` and `ErrMultipleResults` from `k8s.io/cloud-provider-openstack/pkg/util/errors` instead
```

[occm] Remove duplicate errors

---

tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/roles/install-csi-manila/tasks/main.yaml

Resolve the following warning seen in CI runs:
You're using deprecated Ginkgo functionality:
=============================================
--ginkgo.noColor is deprecated, use --ginkgo.no-color instead
Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed-command-line-flags
N/A
N/A
```release-note
NONE
```

[tests] Replace use of deprecated ginkgo flag

---

pkg/openstack/loadbalancer.go

**What this PR does / why we need it**: we are currently facing issue when reusing the ip address (same openstack port) with newer instance. We are using kOps for provisioning our cluster. kOps is reusing ports and the only thing that is changing is instance name. 
this leads to following situation https://gist.github.com/zetaab/4f28c515d1d1dd792d526dbd6a69e4aa (loadbalancer member names does not match to kubernetes node names and weight of pool members are 0). When we force the update if node / instance name is updated at least this got solved and names are in-sync between k8s and openstack lb members. Also operating status changes ONLINE after names are updated.
fixes #
kops executes rolling update to …

[occm] add member name as key when comparing pool members

---

pkg/openstack/loadbalancer.go

Cherry pick of #2008 on release-1.25.
#2008: add member name as key when comparing pool members
```release-note
Pool members are forced to update if the instance name is modified
```

Automated cherry pick of #2008: add member name as key when comparing pool members

---

pkg/openstack/loadbalancer.go

Cherry pick of #2005 on release-1.25.
#2005: Fix panic when setting fake proxy protocol LB hostname
```release-note
NONE
```

Automated cherry pick of #2005: Fix panic when setting fake proxy protocol LB hostname

---

pkg/openstack/loadbalancer.go

With #1968 the execution order changed such that `status.Ingress` is `nil` leading to a panic. Instead, `addr` can be used directly.
```release-note
NONE
```

[occm] Fix panic when setting fake proxy protocol LB hostname

---

tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/roles/install-csi-manila/tasks/main.yaml

fixes #
```release-note
NONE
```

fix cinder and manila CI issue

---

tests/playbooks/test-csi-cinder-e2e.yaml

fixes #
```release-note
NONE
```

switch k8s test suite from 1.24.0 to 1.25.3 for currency

---

pkg/openstack/loadbalancer.go
pkg/util/openstack/loadbalancer.go

Octavia API before 2.16 doesn't support HTTP monitors on UDP pools. It will however allow creation of such if all-in-one LB creation call is used. This is a problem for UDP `ETP=Local` Services, where `healthCheckNodePort` is allocated and CCM will try to create HTTP monitor there. This monitor will be completely not functional.
OVN Octavia provider doesn't support HTTP health monitors either.
This commit fixes that by making sure we're checking Octavia API version
and if it's lower than 2.16 we fall back to creating UDP-CONNECT health
monitors on a regular port instead. Moreover same is done when provider
is set to "ovn".
fixes #1999
```release-note
NONE
```

[occm] Do not create HTTP monitors for UDP on old Octavia

---

charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
charts/manila-csi-plugin/values.yaml
pkg/csi/manila/controllerserver.go
pkg/csi/manila/controllerserver_test.go

This PR adds support for recognizing volume parameters when csi-provisioner sidecar is run with `--extra-create-metadata`, and adds those as share metadata.
```
$ kubectl get pvc
NAME                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS            AGE
new-cephfs-share-pvc   Bound    pvc-755d6df7-b29c-40c6-9df6-9008c8db5339   1Gi        RWX            geneva-cephfs-testing   56s
$ openstack share show pvc-755d6df7-b29c-40c6-9df6-9008c8db5339 -c properties -f value
{'csi.storage.k8s.io/pv/name': 'pvc-755d6df7-b29c-40c6-9df6-9008c8db5339', 'csi.storage.k8s.io/pvc/name': 'new-cephfs-share-pvc', 'csi.storage.k8s.io/pvc/namespace': 'default', 'manila.csi.openstack.org/cluster': …
```

[manila-csi-plugin] Add csi-provisioner's --extra-create-metadata as share metadata

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/openstack/instances.go
pkg/openstack/instances_test.go
pkg/openstack/openstack.go
pkg/openstack/openstack_test.go

This introduces a configuration key which influences the way the provider reports the node addresses to the Kubernetes node resource.
The default order depends on the hard-coded order the provider queries the addresses and what the cloud returns, which does not guarantee a specific order.
To override this behavior it is possible to specify a comma separated list of CIDRs. Essentially, this will sort and group all addresses matching a CIDR in a prioritized manner, where the first item having a higher priority than the last. All non-matching addresses will remain in the same order they are already in.
For example, this option can be useful when having multiple or dual-stack interfaces attached to a node and needing a user-controlled, deterministic way …

[occm] Support specifying a sort order for node addresses

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/openstack/instances.go
pkg/openstack/instances_test.go
pkg/openstack/openstack.go
pkg/openstack/openstack_test.go

Cherry pick of #1946 on release-1.24.
#1946: Support specifying a sort order for node addresses
```release-note
```

Automated cherry pick of #1946: Support specifying a sort order for node addresses

---

pkg/openstack/loadbalancer.go

In practice Octavia is quite an unreliable system. We should expect that load balancers will occasionally go into ERROR state for reasons as elaborate as race conditions and as simple as lack of resources to spawn a new Amphora VM.
This commit makes sure that we allow deleting LBs in ERROR state, so that Services served by such LBs could be deleted and their creation retried.
Obviously there's room for improvement, as we should probably detect LBs going into ERROR and attempt to delete and recreate them ourselves, but this patch is a low hanging fruit fix for the issue.
fixes #2036
```release-note
NONE
```

[occm] Allow deleting LBs in ERROR status

---

pkg/openstack/loadbalancer.go

PR #2000 had added falling back to regular nodePort healthchecks when Octavia wouldn't support HTTP monitor, but ommitted healthmonitor update code, resulting in constant delete-and-recreate cycles. This commit fixes this by making sure update code correctly checks if HTTP monitor is expected.
fixes #2039
```release-note
NONE
```

[occm] LB: Stop recreating monitors if no-HTTP is forced

---

tests/playbooks/roles/install-devstack/defaults/main.yaml

fixes #
```release-note
NONE
```

[all] update openstack version to zed

---

go.mod
go.sum

fixes #
```release-note
NONE
```

[all] upgdate gophercloud to 1.1.0

---

charts/cinder-csi-plugin/values.yaml

Remove leftover from https://github.com/kubernetes/cloud-provider-openstack/pull/1705
-
-
```release-note
NONE
```

fix: remove leftover from bundled snapshot controller

---

manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

v5 log for detailed log info 
fixes #
```release-note
NONE
```

[cinder-csi-plugin]  Add log v5 for CI 

---

charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
charts/cinder-csi-plugin/values.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml

fixes #
```release-note
NONE
```

[cinder-csi-plugin] Update csi version

---

pkg/openstack/instances.go

Related to #2062 
```release-note
NONE
```

[OCCM] log about obtain instance ID failure

---

pkg/openstack/loadbalancer.go
pkg/util/openstack/loadbalancer.go

`createFullyPopulatedOctaviaLoadBalancer()` ends with a call to `WaitLoadbalancerActive()`. It'll only exit without error if that function succeeded. But later on `ensureOctaviaLoadBalancer()` checks the LB's `ProvisioningStatus` again and exits if it's not ACTIVE. The problem is that the comparison is done on LB instance returned from POST call and not from one of the GET calls done in
`WaitLoadbalancerActive()`, so it's always `PENDING_CREATE`. This means that for LB to be completely created, `ensureOctaviaLoadBalancer()` always needs to be called twice, increasing number of Octavia calls made, time for LBs to be created and user experience by creating false positive warning Event.
In case multiple LBs are created in a short period - …

[occm] Make sure LB status is updated immediately

---

go.mod
go.sum
pkg/identity/keystone/keystone.go

Gorilla projects are not maintained anymore and therefore not recommended for production usage. Currently there is a dependency on [github.com/gorilla/mux](https://github.com/gorilla/mux). This commit replaces it with another popular lightweight solution - [github.com/go-chi/chi](https://github.com/go-chi/chi), which is being actively maintained.
```release-note
NONE
```

[k8s-keystone-auth] Replace gorilla/mux with chi

---

go.mod

After #2052 we see build failures like these:
```
mdulko:cloud-provider-openstack/ (master) $ go list -v -mod readonly -m all                                               
get "k8s.io/dynamic-resource-allocation": found meta tag vcs.metaImport{Prefix:"k8s.io/dynamic-resource-allocation", VCS:"git", RepoRoot:"https://github.com/kubernetes/dynamic-resource-allocation"} at //k8s.io/dyn
amic-resource-allocation?go-get=1
go: k8s.io/dynamic-resource-allocation@v0.0.0: invalid version: unknown revision v0.0.0
```
This comes from https://github.com/kubernetes/kubernetes/blob/master/go.mod#L109 and by comparison of other v0.0.0 modules we replace I added dynamic-resource-allocation as well. I'm not 100% sure this is the correct way to go, please advise if …

[all] Add k8s.io/dynamic-resource-allocation to replaced deps 

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml

fixes #
```release-note
NONE
```

update tags to v1.26.0 release

---

cluster/images/cinder-csi-plugin/Dockerfile
cluster/images/cinder-csi-plugin/Dockerfile.build

**What this PR does / why we need it**: update base cinder image for less CVEs
fixes #1994
```release-note
NONE
```

[cinder-csi-plugin] use newer base image for CSI cinder (#1994)

---

.github/workflows/release-cpo.yaml

Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find .github/workflows -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yml
run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
```
**TO-BE**
```yml
run: echo VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT
```
**Which issue this PR fixes(if …

Replace deprecated command with environment file

---

Makefile
cmd/openstack-cloud-controller-manager/main.go
pkg/identity/keystone/token_getter.go
tests/playbooks/roles/install-devstack/tasks/main.yml

fixes #
```release-note
NONE
```

fix test gate

---

docs/octavia-ingress-controller/using-octavia-ingress-controller.md
pkg/ingress/config/config.go
pkg/ingress/controller/controller.go
pkg/ingress/controller/openstack/octavia.go

Adds a new `octavia.flavor-id` option. It uses the given flavor id to create the LB rather than auto-selecting the default. Especially useful for Openstack installations where multiple Octavia flavors exist.
Add the flavor id of the load-balancer to be created in octavia-ingress-controller configuration
```
octavia:
flavor-id: XXX
```
```release-note
NONE
```

[octavia-ingress-controller] Add octavia.flavor-id option

---

pkg/openstack/loadbalancer.go
pkg/util/openstack/loadbalancer.go

fixes #
```release-note
NONE
```

[OCCM]nit: rename function WaitLoadbalancerActive

---

Makefile
cmd/openstack-cloud-controller-manager/main.go
pkg/identity/keystone/token_getter.go
tests/playbooks/roles/install-devstack/tasks/main.yml
tests/playbooks/test-csi-cinder-e2e.yaml

fixes #
```release-note
NONE
```

Automated cherry pick of #2100: fix testgate

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/cinder-csi-plugin/values.yaml

This PR adds support for `imagePullSecrets` into helm chart of `cinder-csi-plugin`. This implementation is backwards compatible. Only patch version of helm chart was increased - if it's necessary I can bump minor version instead.
No GH issue.
```release-note
NONE
```

[cinder-csi-plugin] helm: Add imagePullSecret support

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/clusterrole.yaml
charts/openstack-cloud-controller-manager/templates/clusterrolebinding-sm.yaml
charts/openstack-cloud-controller-manager/templates/clusterrolebinding.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/templates/secret.yaml
charts/openstack-cloud-controller-manager/templates/service-sm.yaml
charts/openstack-cloud-controller-manager/templates/serviceaccount.yaml
charts/openstack-cloud-controller-manager/templates/servicemonitor.yaml
charts/openstack-cloud-controller-manager/values.yaml

When deploying all the services from one cluster with a central chart, it might be that applications can alter the lifecicle deployment of helm  due to the use of helm hooks. 
Some examples of this applications include:
- kube-prometheus-stack
- ingress-nginx
A chart cannot change it's subcharts hook implementations. Because occm is required to untaint nodes from `node.cloudprovider.kubernetes.io/uninitialized`, the other applications will stall helm deployment and eventually deployment will fail due to timeout (race condition)
One way to circunvent this, is by making occm be deployed as a critical component, previous to all other components by using a hook with higher priority. See [upstream …

[occm] Allow user to specify common annotations

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
pkg/openstack/loadbalancer.go

Cherry pick of #2097 on release-1.25.
#2097: add annotation for real address
#2110: add load-balancer-address annotation doc
```release-note
NONE
```

[occm] add annotation for real loadbalancer address cherry pick to 1.25

---

release-procedure.md

see https://github.com/kubernetes/cloud-provider-openstack/issues/2085 and https://github.com/kubernetes/cloud-provider-openstack/issues/2094
so we need to update manifests before making the tag
fixes #
```release-note
NONE
```

Update release process

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
pkg/openstack/loadbalancer.go

Cherry pick of #2097 on release-1.26.
#2097: add annotation for real address
#2110: add load-balancer-address annotation doc
```release-note
NONE
```

[occm] add annotation for real loadbalancer address cherry-pick to 1.26

---

tests/playbooks/roles/install-k3s/defaults/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml
tests/playbooks/test-csi-manila-e2e.yaml
tests/playbooks/test-occm-e2e.yaml
tests/scripts/create-gce-vm.sh

fixes #
```release-note
NONE
```

Update k3s and test image to ubuntu 22

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md

feature were added https://github.com/kubernetes/cloud-provider-openstack/pull/2097 but we are missing docs 
fixes #
```release-note
NONE
```

[occm] add load-balancer-address annotation doc

---

cmd/cinder-csi-plugin/main.go
pkg/csi/cinder/openstack/openstack.go
pkg/csi/cinder/openstack/openstack_instances.go
pkg/csi/cinder/openstack/openstack_snapshots.go
pkg/csi/cinder/openstack/openstack_volumes.go
pkg/metrics/metrics.go
pkg/openstack/openstack.go

Could we now just add this feature that people could use metrics? This has been waiting for now quite long time.
fixes #
```release-note
Add support for metrics in cinder-csi-plugin
```

[cinder-csi-plugin] add support for cinder openstack api metrics

---

docs/cinder-csi-plugin/troubleshooting.md

related to #2059 
```release-note
NONE
```

cinder-csi doc: update trouble shooting with volume not extended

---

docs/cinder-csi-plugin/examples.md

fixes #
```release-note
NONE
```

doc: cinder-csi-plugin - add general ephemeral disk usage

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml

fixes #
```release-note
NONE
```

update tags to v1.24.6

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml

fixes #
```release-note
NONE
```

update tags to v1.25.4

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

fixes #
```release-note
NONE
```

update tags to v1.26.1

---

Makefile
cmd/openstack-cloud-controller-manager/main.go

In Go v1.20, `rand.Seed` is deprecated and `math/rand`'s is automatically seeded. However, that doesn't happen in Go v1.19 that is used to build this branch.
With this change, the global source for `math/rand` is seeded again in `main.go`.
In a separate commit, this PR bumps `golangci-lint` to v1.51.2, which handles the deprecation more gracefully.
Partially reverts https://github.com/kubernetes/cloud-provider-openstack/pull/2102
rand.Seed was prematurely removed in a previous commit.
fixes #2120
```release-note
NONE
```

[occm] Reintroduce seeding of math/rand source

---

Makefile
cmd/openstack-cloud-controller-manager/main.go

In Go v1.20, `rand.Seed` is deprecated and `math/rand`'s is automatically seeded. However, that doesn't happen in Go v1.19 that is used to build this branch.
With this change, the global source for `math/rand` is seeded again in `main.go`.
In a separate commit, this PR bumps `golangci-lint` to v1.51.2, which handles the deprecation more gracefully.
rand.Seed was prematurely removed in a previous commit.
Cherry-pick of https://github.com/kubernetes/cloud-provider-openstack/pull/2121
```release-note
NONE
```

[release-1.26][occm] Reintroduce seeding of math/rand source

---

Makefile
cmd/openstack-cloud-controller-manager/main.go

In Go v1.20, `rand.Seed` is deprecated and `math/rand`'s is automatically seeded. However, that doesn't happen in Go v1.19 that is used to build this branch.
With this change, the global source for `math/rand` is seeded again in `main.go`.
In a separate commit, this PR bumps `golangci-lint` to v1.51.2, which handles the deprecation more gracefully.
rand.Seed was prematurely removed in a previous commit.
Cherry-pick of https://github.com/kubernetes/cloud-provider-openstack/pull/2121
```release-note
NONE
```

[release-1.25][occm] Reintroduce seeding of math/rand source

---

charts/cinder-csi-plugin/values.yaml
charts/manila-csi-plugin/values.yaml
cluster/images/cinder-csi-plugin/Dockerfile
cluster/images/cinder-csi-plugin/Dockerfile.build
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml

This PR will update the uses of deprecating `[k8s.gcr.io](http://k8s.gcr.io/)` registry to `[registry.k8s.io](http://registry.k8s.io/)` prior to the planned April freeze.
fixes # https://github.com/kubernetes/k8s.io/issues/4738
Search results: https://cs.k8s.io/?q=k8s.gcr.io&i=nope&files=&excludeFiles=vendor%2F&repos=kubernetes/cloud-provider-openstack
```release-note
NONE
```

Update registry k8s.gcr.io -> registry.k8s.io

---

cloudbuild.yaml

Adds a `cloudbuild.yaml` so we can start pushing things out of DockerHub
related to https://github.com/kubernetes/cloud-provider-openstack/issues/1540
```release-note
NONE
```

Add cloudbuild.yaml for staging

---

cluster/images/cinder-csi-plugin/Dockerfile
cluster/images/cinder-csi-plugin/Dockerfile.build

**What this PR does / why we need it**: update base cinder image for less CVEs
for your information, here are the vulnerability checks done with the 3 versions:
| version | critical | high | medium | low |
|:-------:|---------:|-----:|-------:|----:|
| v1.26.1 | 15       | 62   | 52     | 111 |
| master  | 9        | 42   | 25     | 77  |
| this MR | 5        | 33   | 22     | 77  |
fixes (not entirely) #1994 
```release-note
NONE
```

[cinder-csi-plugin] use base image v1.4.3 for CSI cinder

---

cluster/images/cinder-csi-plugin/Dockerfile
cluster/images/cinder-csi-plugin/Dockerfile.build

**What this PR does / why we need it**: update base cinder image for less CVEs
for your information, here are the vulnerability checks done with the 3 versions:
| version | critical | high | medium | low |
|:-------:|---------:|-----:|-------:|----:|
| v1.26.1 | 15       | 62   | 52     | 111 |
| master  | 9        | 42   | 25     | 77  |
| this MR | 5        | 33   | 22     | 77  |
fixes (not entirely) #1994 
```release-note
NONE
```

use base image v1.4.3 for CSI cinder

---

pkg/openstack/instances.go
pkg/openstack/instancesv2.go
pkg/openstack/openstack.go

instance v2 should use less API queries towards cloud provider APIs. Also nowadays when this is external ccm, external ccms should implement instance v2 instead of v1. For instance, AWS CCM has only instance v2 nowadays.
fixes #
Solution in this PR is caching `InstanceMetadata` data for one hour. Cache key is node name. Why I am thinking this is a good solution? Currently at least we do have small problem with usage of openstack apis, when we are running 100+ kubernetes clusters. 
InstanceMetadata contains following info
```
data := &cloudprovider.InstanceMetadata{
ProviderID:    i.makeInstanceID(&server.Server),
InstanceType:  instanceType,
NodeAddresses: addresses, …
```

Implement instance v2 interfaces

---

pkg/csi/cinder/controllerserver.go

Fix snapshots package being imported twice.
```release-note
NONE
```

cinder csi: fix double snapshots package import

---

pkg/openstack/instances.go
pkg/openstack/openstack.go
pkg/openstack/routes.go
pkg/util/errors/errors.go

the `openstack.Routes`' `ListRoutes` method must not loop over all project servers just to resolve a couple of route's next hops to node names. This PR resolves the node name only when it's found in the route's next hop using cached k8s API calls for nodes listing.
fixes #2089 
```release-note
Improve performance of the `ListRoutes` method, especially when an OpenStack project contains hundreds of non-k8s nodes
```

Optimize route reconciliation logic

---

OWNERS
README.md

I propose that we will move @lingxiankong to emeritus_approvers. If you disagree and want to continue actively contributing to project, feel free to comment.
Statistics from last 9 months
```
approves:
jichenjc 58
chrigl 7
zetaab 6
ramineni 2
reviews:
jichenjc 20
zetaab 11
chrigl 6
ramineni 4
mdbooth 3
olemarkus 1
stephenfin 1
dulek 1
mandre 1
joepvd 1
```
Also PR contains adding me as co-lead to project and removing @lingxiankong.
```release-note
NONE
```
cc @jichenjc

Cleanup OWNERS and change co-lead in project

---

pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go

Like https://github.com/kubernetes/cloud-provider/blob/master/cloud.go#L48 says, we can return `nil, false` already in LoadBalancer() interface and that will disable the support for LoadBalancer.
cc @dulek as you did the original PR
fixes #
```release-note
NONE
```

simplify loadbalancer enable

---

pkg/openstack/instances.go
pkg/openstack/openstack.go
pkg/openstack/routes.go
pkg/util/errors/errors.go

Cherry pick of the #2090 to 1.26 release
fixes #2089
fixes #
```release-note
NONE
```

Optimize route reconciliation logic cherry-pick to 1.26 (#2090)

---

pkg/openstack/instances.go
pkg/openstack/openstack.go
pkg/openstack/routes.go
pkg/util/errors/errors.go

Cherry pick of the #2090 to 1.25 release
fixes #2089
fixes #
```release-note
NONE
```

Optimize route reconciliation logic cherry-pick to 1.25 (#2090)

---

Makefile
cloudbuild.yaml

cloudbuild is failing, e.g.: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-openstack-push-images/1632991558871552000
This PR addresses 2 issues with cloudbuild.
The immediate cause of the above error is a quirk in the build environment: HOME is set to /builders/root but buildx is installed in /root, so we need to set HOME correctly for buildx to work. [Discussion](https://kubernetes.slack.com/archives/CCK68P2Q2/p1678184220721889).
Secondly we need to initialise the buildx environment before running make. If we were using the image's buildx entrypoint it would do this for us. We don't want to do that, though: because we re-use the compilation build stage for all image targets, building them all in separate builders would mean we …

[all] Fix cloudbuild

---

cloudbuild.yaml

Fixes the next discovered error in cloudbuild. We were missing:
```yaml
options:
dynamic_substitutions: true
```
This prevented `_SHORT_TAG` from being defined correctly, as it is defined in terms of `_GIT_TAG`.
fixes #2143
```release-note
NONE
```

[all] Fix substitution of _SHORT_TAG in cloudbuild

---

pkg/openstack/loadbalancer.go

[occm] Do not send the subnet-id if it is empty for members during the creation of fully populated loadbalancer.
Prevents sending an empty string to the Octavia API for members in creating fullyPopulatedLoadBalancer when there is no subnet-id defined.
fixes #2124
```release-note
NONE
```

[occm] Support members without subnet in fully populated LB

---

Dockerfile
cmd/openstack-cloud-controller-manager/main.go
go.mod
tests/playbooks/roles/install-golang/defaults/main.yml

fixes #
```release-note
NONE
```

use go 1.20

---

cloudbuild.yaml

We can't use the vanilla docker image because we also need the `gcloud` binary.
```release-note
NONE
```

[all] Revert cloudbuild to gcr.io/k8s-testimages/gcb-docker-gcloud

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
go.mod
go.sum
pkg/openstack/openstack.go
pkg/openstack/routes.go
pkg/openstack/routes_test.go

Cherry pick of the #2134 to 1.25 release
fixes #2089
```release-note
NONE
```

occm: implement a support for atomic routes update cherry-pick to 1.25 (#2134)

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
go.mod
go.sum
pkg/openstack/openstack.go
pkg/openstack/routes.go
pkg/openstack/routes_test.go

Cherry pick of the #2134 to 1.26 release
fixes #2089
```release-note
NONE
```

occm: implement a support for atomic routes update cherry-pick to 1.26 (#2134)

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

fixes #
```release-note
NONE
```

update tags to v1.26.2

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml

fixes #
```release-note
NONE
```

update tags to v1.25.5

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/cinder-csi-plugin/values.yaml

Add an extraArgs value to the various containers that are deployed by cinder-csi. Implementation is similar to occm helm chart
fixes #2159 
```release-note
NONE
```

[cinder-csi-plugin] Helm: Add extraArgs support for containers

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/cinder-csi-plugin/values.yaml

Add an extraArgs value to the various containers that are deployed by cinder-csi. Implementation is similar to occm helm chart
Cherry-pick: #2160 to release-1.23
```release-note
Enable passing extra arguments to containers being deployed by cinder-csi helm chart
```

helm: cinder-csi: Add extraArgs support for containers

---

charts/cinder-csi-plugin/values.yaml
charts/manila-csi-plugin/values.yaml
charts/openstack-cloud-controller-manager/values.yaml
docs/barbican-kms-plugin/using-barbican-kms-plugin.md
docs/cinder-csi-plugin/using-cinder-csi-plugin.md
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

fixes #
see https://github.com/kubernetes/k8s.io/pull/4959
I am going to include this change to release-1.26, release-1.25 and release-1.24 as well. registry.k8s.io does not support latest tags, so in many places it uses current latest which is v1.27.0-alpha.0
```release-note
NONE
```

move to use registry.k8s.io

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/cinder-csi-plugin/values.yaml

Add an extraArgs value to the various containers that are deployed by cinder-csi. Implementation is similar to occm helm chart
Cherry-pick: https://github.com/kubernetes/cloud-provider-openstack/pull/2160 to release-1.24
```release-note
Enable passing extra arguments to containers being deployed by cinder-csi helm chart
```

helm: cinder-csi: Add extraArgs support for containers (#2160)

---

charts/cinder-csi-plugin/values.yaml
charts/manila-csi-plugin/values.yaml
charts/openstack-cloud-controller-manager/values.yaml
docs/barbican-kms-plugin/using-barbican-kms-plugin.md
docs/cinder-csi-plugin/using-cinder-csi-plugin.md
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

fixes #
```release-note
NONE
```

modify images to use registry.k8s.io

---

charts/openstack-cloud-controller-manager/Chart.yaml

This removes me as maintainer of the ccm chart. I have not been working with OpenStack since mid 2021 and have in fact not been contributing to the chart since its inception.
```release-note
Removes morremeyer as chart maintainer
```

chore: remove morremeyer as maintainer

---

.github/workflows/pr.yaml
.github/workflows/release.yaml
charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/manila-csi-plugin/templates/controllerplugin-clusterrole.yaml
charts/manila-csi-plugin/templates/controllerplugin-rules-clusterrole.yaml
charts/manila-csi-plugin/templates/nodeplugin-clusterrole.yaml
charts/manila-csi-plugin/templates/nodeplugin-rules-clusterrole.yaml
charts/openstack-cloud-controller-manager/Chart.yaml

fixes #
```release-note
NONE
```

update helm github actions and versions release-1.26

---

.github/workflows/pr.yaml
.github/workflows/release.yaml
charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/manila-csi-plugin/templates/controllerplugin-clusterrole.yaml
charts/manila-csi-plugin/templates/controllerplugin-rules-clusterrole.yaml
charts/manila-csi-plugin/templates/nodeplugin-clusterrole.yaml
charts/manila-csi-plugin/templates/nodeplugin-rules-clusterrole.yaml
charts/openstack-cloud-controller-manager/Chart.yaml

fixes #
```release-note
NONE
```

update helm github actions and versions release-1.24

---

.github/workflows/pr.yaml
.github/workflows/release.yaml
charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/manila-csi-plugin/templates/controllerplugin-clusterrole.yaml
charts/manila-csi-plugin/templates/controllerplugin-rules-clusterrole.yaml
charts/manila-csi-plugin/templates/nodeplugin-clusterrole.yaml
charts/manila-csi-plugin/templates/nodeplugin-rules-clusterrole.yaml
charts/openstack-cloud-controller-manager/Chart.yaml

fixes #
```release-note
NONE
```

update helm github actions and versions release-1.25

---

.github/workflows/pr.yaml
.github/workflows/release.yaml
charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/manila-csi-plugin/templates/controllerplugin-clusterrole.yaml
charts/manila-csi-plugin/templates/controllerplugin-rules-clusterrole.yaml
charts/manila-csi-plugin/templates/nodeplugin-clusterrole.yaml
charts/manila-csi-plugin/templates/nodeplugin-rules-clusterrole.yaml
charts/openstack-cloud-controller-manager/Chart.yaml

fixes #
```release-note
NONE
```

update helm github actions and versions

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml

fixes #
```release-note
NONE
```

fix lint of charts

---

go.mod
go.sum

steal from CAPO, make sense to upgrade gophercloud time to time in order to catchup latest stuff
to both fix but and potential for other code change as base
fixes #
```release-note
NONE
```

update: update gophercloud

---

.github/workflows/release-cpo.yaml
Makefile
release-procedure.md

as we are now publishing images to gcr.io and using that we can promote those to registry.k8s.io. I see that starting from 1.27.0 we could publish images ONLY to official registry.k8s.io. Older release branches will still be using docker hub for new images (if we make new patch releases), but I need to manually also upload those to gcr.io. That is what the community wants currently. Also read https://blog.alexellis.io/docker-is-deleting-open-source-images/ it makes me feel that docker does not want to support opensource anymore. So our home is not there.
Currently all images from 1.24.6, 1.25.5 and 1.26.2 are already located in registry.k8s.io
fixes # …

drop support for docker hub

---

manifests/barbican-kms/ds.yaml

This manifest deploys a barbican-kms-plugin on every control plane node. This is desirable in Kubernetes configurations with multiple control plane nodes to have a KMS endpoint on each control plane node.
This is just an additional kubernetes manifest.
```release-note
NONE
```

[barbican-kms-plugin] Add manifest for barbikan-kms daemoset

---

pkg/openstack/loadbalancer.go

Feature of sharing LBs seems to have some logic flaws. One of them is the problem of mixing internal and external Services on a single LB. As a FIP is tied to the LB and not individual listener, it means that if one Service attached the FIP to the Service, all the other Services will be available on that FIP. This may lead to accidental exposure of an internal Service which can potentially be pretty bad.
This commits attempts to limit the number of cases when the user can shoot themselves in the foot and makes it impossible for the internal Services to be secondary on a share load balancer. Moreover a condition is added that prevents secondary Services to create FIPs at all, so that accidental exposure of primary internal service by a secondary …

[occm] Don't allow internal Services to share an LB

---

Dockerfile

fixes #
```release-note
NONE
```

update base images

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md

I'm clarifying that 2.5 is and Octavia *API* version, adding a note about FIP being shared too and explaining changes from #2190.
```release-note
NONE
```

[occm] Shared LBs - improve docs

---

tests/scripts/create-gce-vm.sh

Drop support for `FLAVOR=preinstalled` in our CI. This never worked and the image in question is no longer available.
N/A.
This is test-only.
```release-note
NONE
```

tests: Remove support for preinstalled images

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/values.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml

update CSI external container version
make manifest/charts consistent
fixes #
```release-note
NONE
```

Cinder CSI general update: update csi external container version

---

docs/octavia-ingress-controller/using-octavia-ingress-controller.md
pkg/ingress/controller/openstack/octavia.go

In Octavia the names of the providers are completely free-form and up to cloud administrator. While the standard names are "amphora" (aliased as "octavia") and "ovn", we cannot be guaranteed these names will work with every OpenStack cloud.
This commit makes sure we do not default the Provider name to "octavia" when creating an LB for the ingress-controller as this may not work for every cloud. Instead when option is unset we will pass an empty value causing Octavia to use whatever is configured as the cloud's default.
I also added docs explaining that option a bit better.
fixes #2201
```release-note
[octavia-ingress-controller] When creating the load …
```

[octavia-ingress-controller] Do not default Octavia provider to "octavia"

---

cloudbuild.yaml

partly fixes #2209 but we still need new release and cherry-pick to release-1.27 branch
```release-note
NONE
```

ignore others than v1.* tags

---

cloudbuild.yaml

fixes #2209 
```release-note
NONE
```

remove version

---

cloudbuild.yaml

fixes #
```release-note
NONE
```

remove version from cloudbuild

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

fixes #
```release-note
NONE
```

release 1.27.1

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

Updates all v1.27.0 tag references to v1.27.1.
```release-note
NONE
```

[all] update image tags to v1.27.1

---

pkg/util/metadata/metadata.go
pkg/util/metadata/metadata_test.go

Prior to this change, the call to the Nova Metadata service used HTTP proxies as directed by the environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY (or the lowercase versions thereof).
However, the call to the Metadata well-known IP must originate from the requesting server directly to be correctly served.
With this change, calls to the Nova Metadata service ignore proxy settings.
fixes #2217
```release-note
NONE
```

[util] Ignore proxies when calling Nova Metadata

---

pkg/util/openstack/loadbalancer.go

Up the timeout for LB create, in some environments this can take a bit longer than ~150s increase it to ~320s
Fixes #2222
```release-note
NONE
```

[octavia-ingress-controller] Increase timeout for LB to get to ACTIVE state

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/util/openstack/loadbalancer.go

fixes #
```release-note
NONE
```

[OCCM] add environment variable for timeout

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md

fixes #
```release-note
NONE
```

[OCCM] Doc: update statement about neutron lbaas removeal

---

tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml
tests/playbooks/test-csi-manila-e2e.yaml
tests/playbooks/test-occm-e2e.yaml

Previously in e2e tests we only used ci-built occm for the occm e2e test. The cinder and manila e2e tests used the latest release occm image. With this change all e2e tests deploy a ci-built occm.
This came about because we were surprised that cinder and manila e2e tests were broken by an issue in the release images.
There are pros and cons to doing this:
Pros:
* You can test changes which may affect the interaction of CPO and CSI, e.g. node labels.
Cons:
* We might accidentally merge commits which require the simultaneous upgrade of both CSI and OCCM.
Ideally we'd test both, of course. If we pick one, which is better? If we decided not to merge this, we should at least add documentation and/or comments explaining the decision for posterity.
**Which …

Use ci-built occm in all e2e tests

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml

**What this PR does / why we need it**: Fix helm template double annotations keyword
fixes #2231 
**Special notes for reviewers**: (none)
```release-note
NONE
```

[occm] fix daemonset annotations

---

tests/playbooks/roles/install-k3s/tasks/main.yaml

The `storage.googleapis.com/kubernetes-release` URL is a hard coded path to a GCS bucket location. To allow redirecting and spreading the load across multiple hosting locations, the `dl.k8s.io` URL has been introduced.
Related PRs:
- https://github.com/kubernetes-sigs/image-builder/pull/656
- https://github.com/kubernetes-sigs/cluster-api/pull/4958
None
```release-note
NONE
```

Use dl.k8s.io instead of hardcoded GCS URIs

---

Dockerfile
tools/csi-deps-check.sh
tools/csi-deps.sh

fixes #2233
I've added small shell script `tools/csi-deps.sh`. 
It copies add utils which go-modules calls.
```release-note
NONE
```

[cinder-csi-plugin] shrink image, remove unnecessary utils (#2233)

---

Makefile

It sets the `cloud-provider-openstack/pkg/version` package `Version` variable during the build
fixes #2251 
```release-note
Set git version variable during the build
```

Set git version variable during the build

---

pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go

Seems like there was some dead code related to handling of the security groups in the implementation of the LoadBalancer Services support. This commit removes it. In particular:
* `LoadBalancerOpts.NodeSecurityGroupIDs` is never populated, so we can remove it as well as code using it.
* `IsAllowAll` function is never used. Moreover I have no idea why it was exported.
Please, please double-check if I'm right that this code is not used anywhere.
```release-note
`[LoadBalancer]NodeSecurityGroupIDs` is completely removed from the configuration options. The option was deprecated and unsupported, but remained accessible as `nodesecuritygroupids`. This won't be true anymore.
```

[occm] LoadBalancers: Remove dead SG code

---

pkg/openstack/routes.go

Orphaned blackhole routes are not deleted with atomic route update due to `NextHop` is empty.
fixes #2256
See #2134
```release-note
Correctly delete oprhaned blackhole routes when atomic routes extension is enabled
```

[occm]: fix blackhole route atomic delete logic

---

pkg/openstack/routes.go

Orphaned blackhole routes are not deleted with atomic route update due to `NextHop` is empty.
fixes #2256
See #2134
```release-note
Correctly delete oprhaned blackhole routes when atomic routes extension is enabled
```

[occm]: fix blackhole route atomic delete logic (1.27 cherry-pick)

---

pkg/openstack/routes.go

Orphaned blackhole routes are not deleted with atomic route update due to `NextHop` is empty.
fixes #2256
See #2134
```release-note
Correctly delete oprhaned blackhole routes when atomic routes extension is enabled
```

[occm]: fix blackhole route atomic delete logic (1.25 cherry-pick)

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/values.yaml
charts/manila-csi-plugin/Chart.yaml
charts/manila-csi-plugin/values.yaml
docs/cinder-csi-plugin/using-cinder-csi-plugin.md
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
pkg/csi/cinder/driver.go
pkg/csi/manila/driver.go
pkg/csi/manila/identityserver.go
tests/playbooks/roles/install-csi-manila/tasks/main.yaml

The PR aligns the go.mod CSI spec version with CSI driver variables.
fixes #2253
```release-note
Align the go.mod CSI spec version with CSI driver variables
```

Fix CSI spec versions

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/templates/secret.yaml
charts/openstack-cloud-controller-manager/values.yaml

This PR adds the abbility to disable the secret mount into the daemonset. 
This allows to mount the secrets with init-containers (like vault-agent-injector). 
none
```release-note
[openstack-cloud-controller-manager] add secret enabled option
```

[occm] add secret enabled option

---

pkg/openstack/instances.go
pkg/openstack/instancesv2.go
pkg/openstack/loadbalancer.go
pkg/openstack/openstack_test.go

os-interfaces is a proxy API for neutron's ports list. This has 2 significant disadvantages to us:
* It adds the overhead of an extra API call every time it is used
* It doesn't contain all the information returned by Neutron
This is a non-functional change, although is does reduce the load on nova-api without reducing functionality.
The primary motivation for this is to enable additional filtering using information from ports, e.g. filtering by port tag or the addition of subports as in #2228.
```release-note
NONE
```

[occm] Replace call to Nova os-interfaces with direct Neutron call

---

go.mod
go.sum

Bumps the gophercloud dep to the latest release
```release-note
NONE
```

[all] Update to gophercloud 1.4.0

---

tests/playbooks/roles/install-csi-manila/tasks/main.yaml

the csi driver images are built with a prefix "v0.0."; but the script isn't using this script when
starting the driver.
related to issue #2142 and pr #2065
```release-note
NONE
```

manila-csi: Fix image tag in e2e test scripts

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/README.md

[occm] Fixed the typo in the load balancing section in the README
All the currently maintained binaries are:
* openstack-cloud-controller-manager (occm)
If you set the variable with a lowercase "b", the template will not catch that and the secret that is created via the helm chart will lack the [LoadBalancer] section. the correct value should be "loadBalancer", instead of "loadbalancer", as you can see from the values.yaml.
```release-note
NONE
```

[occm] Fixed the typo in the load balancing section in the README

---

cmd/barbican-kms-plugin/main.go

This PR refactors and enhances the codebase of the Barbican KMS plugin. It improves code readability, simplifies flag parsing and klog initialization, handles errors gracefully, updates signal handling, applies proper logging, and performs general code cleanup.
fixes #
```release-note
[barbican-kms-plugin] Refactor and enhance codebase
This pull request refactors and enhances the codebase of the Barbican KMS plugin. It improves code readability, simplifies flag parsing and klog initialization, handles errors gracefully, updates signal handling, applies proper logging, and performs general code cleanup.
No user action is required.
For more information, …
```

(barbican-kms-plugin)Refactor and enhance Barbican KMS plugin codebase. 

---

pkg/openstack/loadbalancer.go
pkg/util/openstack/loadbalancer.go

This commit makes sure that on exit from UpdateHealthMonitor() the LB is ACTIVE so that next operations can be called safely.
fixes #2267
```release-note
NONE
```

[occm] Wait for LB to be ACTIVE on HM update

---

cmd/cinder-csi-plugin/main.go

Improved the codebase for the cinder-CSI plugin  for better readability. 
fixes #
```release-note
None
```

Refactors and enhances the codebase of the cinder csi  plugin

---

docs/barbican-kms-plugin/using-barbican-kms-plugin.md

Improved and fixed Grammatical mistakes in barbican-kms-plugin
fixes #
```release-note
NONE
```

fixed Grammatical mistakes in barbican-kms-plugin

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/cinder-csi-plugin/values.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/values.yaml

* Add podSecurityContext, securityContext to the Cinder-CSI
* Volumes cosmetic fixes
fixes #
```release-note
NONE
```

[helm] occm cinder-csi securityContext

---

cmd/manila-csi-plugin/main.go

Added comments and arranged the variable names for better understanding and readability to users.
fixes #
```release-note
NONE
```

Added  comments and arranged the variable names

---

docs/cinder-csi-plugin/sidecarcompatibility.md

I improved some sentences which are misspelt and some grammar as well for a better user experience. 
```release-note
NONE
```

Improved the grammar in sidecarcompatibility.md

---

pkg/openstack/loadbalancer.go
pkg/openstack/loadbalancer_test.go

This is iteration of #2033. The PR makes sure unnecessary SG rules are removed when we're
reconciling a Service.
fixes #2003
You need to enable `[LoadBalancer]manage-security-groups` to test this.
```release-note
NONE
```

[occm] Delete unused SG rules with manage-security-groups

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md

Corrected & improved some grammar.
fixes #
```release-note
NONE
```

Corrected the grammar

---

pkg/csi/cinder/driver.go
pkg/csi/manila/driver.go
pkg/identity/keystone/authenticator.go
pkg/identity/keystone/keystone.go
pkg/ingress/controller/openstack/octavia.go
pkg/openstack/instances.go
pkg/openstack/routes.go

This PR allocates slice memory in advance instead of reallocating the slice memory in a loop
Inspired by #2296 
```release-note
NONE
```

[all]: Allocate array capacity in advance

---

pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go
pkg/csi/cinder/openstack/openstack_snapshots.go
pkg/csi/cinder/openstack/openstack_volumes.go

This PR addresses a couple of findings from the #2295 
Improves memory allocation and adds extra logs helping to debug volume pagination issues.
```release-note
Fixed pagination issue in Cinder CSI ListVolumes and ListSnapshots calls
```

[cinder-csi-plugin]: fix pagination, avoid unnecessary memory allocation, add more logs

---

pkg/openstack/loadbalancer.go

This commit makes sure that in all instances of reading Nova instance ID from the `.Spec.ProviderID` field, we're using
`instanceIDFromProviderID()` function which is designed for that purpose.
fixes #
```release-note
NONE
```

[occm] Use `instanceIDFromProviderID()` function

---

pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go

Matt noticed several optimizations that can be done in `applyNodeSecurityGroupIDForLB()` function. I added a few more refactorings. In particular:
* We don't need to lookup servers by name as we have `.spec.providerID` in the nodes passed to the function.
* We don't need to lookup servers at all when we have the ID, we can fetch ports by `deviceID`.
* This means we don't need a Nova client in the LB instance anymore.
* `slices.Contains()` from K8s utils can be used to check if SG is in the list.
* It's better to tag the port with SG before we actually apply it. This will protect us from situations when the SG is applied, but tagging the port failed and now when deleting the SG CPO would be unable to find the port and therefore delete the SG. …

[occm] Optimize `applyNodeSecurityGroupIDForLB()`

---

pkg/openstack/loadbalancer.go

If we reconfigure CPO to set `manage-security-groups=true`, it will
correctly reconcile LBs to make sure SGs are created and associated with the
nodes. This commit makes sure that SGs are properly deleted when CPO is
reconfigured in the opposite direction, with `manage-security-groups=false`.
Also a small refactoring of the SG deletion code is added in a separate commit.
fixes #
`[LoadBalancer]manage-security-groups` option needs to be manipulated.
```release-note
NONE
```

[occm] Delete sgs on reconfiguration

---

pkg/openstack/instances.go
pkg/openstack/instancesv2.go
pkg/openstack/openstack.go
pkg/openstack/openstack_test.go

Vlan-aware VMs are commonly used in telecom.
Those VMs are plugged into flat networks and use neutron trunk:
https://docs.openstack.org/neutron/latest/admin/config-trunking.html
Currenlty, nodeAddresses() only returns neutron ports directly attached to VM. For vlan-aware VMs, IP addresses are assigned on neutron subports. Subports are attached to the trunk; they are not attached to the VM directly. This pull request changes nodeAddresses() to return IP addresses of neutron subports when they exist. Without this change, Kubernetes is unable to IP addresses of vlan-aware VMs. This change is transparent to VMs not using neturon trunk.
This is a rebase of the following PR:
https://github.com/kubernetes/cloud-provider-openstack/pull/2270 …

[occm] Get IP addresses of neutron subports v3

---

pkg/openstack/loadbalancer.go
pkg/openstack/loadbalancer_test.go

K8s denotes protocol names in uppercase (TCP) while Neutron uses lowercase (tcp) on the security group rules. This created conflicts and caused occm to incorrectly compare SG rules and make unnecessary creates and deletes.
This commit fixes that by making sure we're always comparing `ToLower()` version of the protocol name. Also I made sure that we're always passing lowercase to the Neutron SG rule creation API too.
fixes #2319
Enable `manage-security-groups=true`
```release-note
NONE
```

[occm] Fix protocol case mismatch (tcp vs TCP)

---

docs/octavia-ingress-controller/using-octavia-ingress-controller.md
docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/ingress/config/config.go
pkg/ingress/controller/openstack/octavia.go
pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go
pkg/util/openstack/loadbalancer_serial.go
pkg/util/util.go

Add support for LB providers that do not implement the bulk create/update API call.
fixes https://github.com/kubernetes/cloud-provider-openstack/issues/2271
As this PR adds new configuration options for both Octavia ingress and Loadbalancers, additional configuration is required to test:
```
[LoadBalancer]
provider-requires-serial-api-calls=true
```
and
```bash
cat <<EOF > /etc/kubernetes/octavia-ingress-controller/config.yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
name: octavia-ingress-controller-config
namespace: kube-system
data:
config: |
cluster-name: ${cluster_name}
openstack:
auth-url: ${auth_url}
domain-name: ${domain-name}
username: ${user_name}
password: …
```

[occm] Support for LB providers that do not implement the bulk update/create API call

---

cmd/barbican-kms-plugin/main.go
cmd/cinder-csi-plugin/main.go
cmd/client-keystone-auth/main.go
cmd/k8s-keystone-auth/main.go
cmd/manila-csi-plugin/main.go
pkg/autohealing/cmd/root.go
pkg/ingress/cmd/root.go

Provide a quick and easy way to check the version of the binaries from the CLI. This is already present for `openstack-cloud-controller-manager` but not for any of the other binaries.
N/A
N/A
```release-note
All binaries now provide a `--version` option.
```

✨ Add --version flags to binaries

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/values.yaml

This PR implements `imagePullSecrets` for the `openstack-cloud-controller-manager` helm chart.
fixes #
```release-note
NONE
```

Add imagePullSecret support

---

charts/manila-csi-plugin/Chart.yaml
charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/manila-csi-plugin/values.yaml

[manila-csi-plugin] Add support for imagePullSecrets to helm chart
This PR adds support for imagePullSecrets into all necessary resources in manila helm chart.
Implementation is backwards compatible.
```release-note
[manila] Add support for ImagePullSecrets
```
Based on Related/Similar PRs: 
- https://github.com/kubernetes/cloud-provider-openstack/pull/2105
- https://github.com/kubernetes/cloud-provider-openstack/pull/2317

Manila: Add support for imagePullSecrets to helm chart

---

Dockerfile
Makefile

fixes #
```release-note
NONE
```

update docker base images. update newer golint

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

fixes #
```release-note
NONE
```

update tags to 1.28.0

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

fixes #
```release-note
NONE
```

update tags master

---

tools/csi-deps.sh

The libs copied into cinder-csi-plugin image are named and placed differently across platforms. This commit attempts to solve this by differentiating where we take them from.
fixes #
```release-note
NONE
```

[cinder-csi-plugin] Fix multiarch builds of Cinder CSI

---

pkg/util/openstack/loadbalancer.go

Just removal of vars not needed anymore.
fixes #
```release-note
NONE
```

[occm] Remove unused vars

---

charts/openstack-cloud-controller-manager/templates/clusterrole.yaml
charts/openstack-cloud-controller-manager/templates/clusterrolebinding.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/templates/serviceaccount.yaml
charts/openstack-cloud-controller-manager/values.yaml

This removes the `openstack-` prefix from the service account name used by the cloud-controller-manager.
The change is motivated by the following:
- Create suitable service accounts, cluster roles and cluster role bindings for use with `--use-service-accounts-credentials=true`
- Normalise service account names in the helm chart and plain manifests
- Adhere to naming conventions across external cloud controller managers for different clouds (e.g. AWS, GCP, ...)
Specifically the first point deserves further details. Prior to this change, users who install the cloud controller manager with helm, would run into the following error when creating load balancers:
```
E0818 08:27:33.802407      11 controller.go:291] error processing service …
```

[occm] Use standard service account name in OCCM helm chart

---

release-procedure.md

Seems like we no longer need to modify k8s.gcr.io, it's registry.k8s.io instead.
```release-note
NONE
```

[docs] :seedling: Update image repo in the release procedure

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/values.yaml

The spurious space character was sadly introduced in an earlier PR and had not been picked up by the helm linter, presumably because the GHA did not run.
```release-note
NONE
```

[occm] Remove spurious space in OCCM values file

---

tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-cpo-occm/tasks/main.yaml

fixes #
```release-note
NONE
```

build occm always in e2e test

---

go.mod
go.sum
pkg/openstack/loadbalancer.go

When creating an SG for an LB we tag the ports we attach the SG to in order to be able to find them easily later on when the SG will be getting deleted. We do that to simulate an API allowing us to filter ports by attached SGs, but turns out - such an API already exists in Neutron and Gophercloud v1.6.0 allows to use it.
This commit makes sure that when deleting an SG we're discovering ports to remove it from by querying the Neutron filtering by SG. Moreover tagging the ports with the SGs is removed to as not being necessary anymore.
I've left the code removing the SG tags from ports for backward compatibility.
fixes #
```release-note …
```

[occm] Lookup ports by SG and not tags

---

pkg/openstack/loadbalancer.go
pkg/util/openstack/loadbalancer.go

This commit implements deleting the LB when it goes into ERROR state on creation. This will allow us to be less prone to transient Octavia issues.
A possible improvement could be to extend this behavior to all cases when we wait for the LB to become ACTIVE. The problem with that is that attempt to implement that complicates the code a lot, so let's start with this first step.
fixes #
```release-note
[openstack-cloud-controller-manager] OCCM will attempt to retry creation of load balancers that have gone into ERROR state.
```

[occm] Delete LB that gone into ERROR state

---

tests/playbooks/roles/install-cpo-occm/tasks/main.yaml
tests/playbooks/roles/install-devstack/defaults/main.yaml
tests/playbooks/roles/install-devstack/templates/local.conf.j2
tests/playbooks/test-occm-e2e.yaml

/hold
This aims to update DevStack configs to deploy OVN instead of ML2/OVS. OVN is the Neutron default for several releases and I believe we should test against it. Also it will enable us to test the OVN Octavia Provider too which is not available when DevStack is configured with ML2/OVS.
fixes #
```release-note
OCCM is now tested against OpenStack Antelope configured with OVN.
```

[occm] Switch DevStack to use OVN

---

pkg/csi/cinder/nodeserver.go

CSI inline ephemeral volumes are deprecated for the *Cinder CSI driver*, not k8s as a whole. Clarify this, linking back to the original issue.
n/a
n/a
```release-note
NONE
```

[cinder-csi-plugin] Add comment about deprecation

---

pkg/openstack/loadbalancer.go
tests/e2e/cloudprovider/test-lb-service.sh

In `test-lb-service.sh` we do `trap "delete_resources" EXIT` to make sure we cleanup resources on a test failure. In there, we only fetched the `$?` after making a check for `${AUTO_CLEAN_UP}`, which itself alters the code to 0, so function always returns success. This means tests can never really fail.
This commit fixes it by making sure `$ERROR_CODE` is fetched at the very beginning of the cleanup function.
Some additional fixes needed to be made to make tests passing again. In particular:
* Deleting listeners when the secondary shared Service is deleted is fixed now by making sure we're comparing the correct tag.
* Tests no longer create Services as internal in order to make shared LB tests work after #2190.
* FIP is added to the user LB in the …

[occm] Make sure we don't mask LB tests failures and fix what was failing

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go
pkg/openstack/openstack_test.go

The PR adds new `max_retries_down` option support for Octavia health monitors.
fixes #2371 
n/a
```release-note
[occm] Add `max_retries_down` health monitors option support for OCCM LoadBalancer global config and service annotations
```

[occm] add `max_retries_down` support for octavia health monitors

---

cmd/barbican-kms-plugin/main.go
cmd/cinder-csi-plugin/main.go
cmd/client-keystone-auth/main.go
cmd/k8s-keystone-auth/main.go
cmd/manila-csi-plugin/main.go

Everything in k8s has switched to klog for some time now. Lots more context in the individual commit messages.
Some minor issues introduced in #2324 are addressed. Again, there's lots more context in the commit messages.
N/A
N/A
```release-note
NONE
```

Remove handling code for glog

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go
pkg/openstack/openstack_test.go

This is a cherry-pick of #2372
```release-note
[occm] Add `max_retries_down` health monitors option support for OCCM LoadBalancer global config and service annotations
```

[release-1.26] [occm] add `max_retries_down` support for octavia health monitors

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/cinder-csi-plugin/values.yaml
charts/manila-csi-plugin/Chart.yaml
charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/manila-csi-plugin/values.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/values.yaml

This PR allows to specify hostAliases in the nodeplugin-daemonset to allow for setting custom hosts. This functionality is off by default in the PR and has appropriate comments to structure and enable. 
The reason for submitting this PR is because this chart is not using hosts from coredns' corefile.
fixes #
```release-note
NONE
```

Specify hostAliases in the cinder-csi-plugin nodeplugin-daemonset

---

tests/ci-occm-e2e.sh

Seems like the CI OS changed and now it won't allow installing Python packages in the system without explicitly requesting that. This commit solves this by installing needed packages through `apt-get`.
fixes #2412
```release-note
NONE
```

CI: Fix "error: externally-managed-environment"

---

tests/ci-csi-cinder-e2e.sh
tests/ci-csi-manila-e2e.sh

PR #2414 missed fixing this for Cinder and Manila e2e tests, this makes sure these tests work too.
fixes #2412
```release-note
NONE
```

CI: Fix "error: externally-managed-environment" in CSI

---

pkg/openstack/loadbalancer.go
pkg/util/util.go

The PR reconciles reconciles health monitors on cluster scale up/down events.
The fix also improves the readability of the `ensureOctaviaHealthMonitor` method and now reconciles the monitor name as well.
fixes #2370 
```release-note
[occm] Ensure Octavia health monitors are updated on `UpdateLoadBalancer` k8s service controller call.
```

[occm] ensure octavia monitor is always updated

---

pkg/openstack/loadbalancer_test.go

this pr adds unit test for buildPoolCreateOpt LbaasV2 method in loadbalancer.go 
refers #2400 
```release-note
NONE
```

test: LbaasV2 method buildPoolCreateOpt

---

pkg/openstack/loadbalancer.go
pkg/util/util.go

This is a cherry-pick of #2373
/assign kayrus
```release-note
[occm] Ensure Octavia health monitors are updated on `UpdateLoadBalancer` k8s service controller call.
```

[release-1.27] [occm] ensure octavia monitor is always updated

---

pkg/openstack/loadbalancer.go
pkg/util/util.go

This is a cherry-pick of #2373
/assign kayrus
```release-note
[occm] Ensure Octavia health monitors are updated on `UpdateLoadBalancer` k8s service controller call.
```

[release-1.26] [occm] ensure octavia monitor is always updated

---

pkg/openstack/loadbalancer_test.go

fixes #
```release-note
NONE
```

test : getSecurityGroupName ()

---

pkg/openstack/loadbalancer.go
pkg/util/util.go

This is a cherry-pick of #2373
```release-note
[occm] Ensure Octavia health monitors are updated on `UpdateLoadBalancer` k8s service controller call.
```

[release-1.28] [occm] ensure octavia monitor is always updated

---

pkg/openstack/loadbalancer_test.go

Add unit test for getting bool from service annotation
To run the test, on your terminal run  `make unit`
```release-note
NONE
```

Add Test for  getting bool from service annotation

---

pkg/openstack/loadbalancer_test.go

fixes #
```release-note
NONE
```

test : UpdateServiceAnnotations 

---

pkg/openstack/loadbalancer_test.go

fixes #
```release-note
NONE
```
cover all possible edge cases that can during the use of this function and test for behavour of function giving hardcoded value incase there is a change in the logic of the function

test : getStringFromServiceAnnotation() 

---

pkg/openstack/loadbalancer_test.go

refers #2400
```release-note
NONE
```

feat: add unit test for createLBStatus

---

pkg/ingress/controller/controller.go
pkg/ingress/controller/openstack/octavia.go

This PR basically adds the ability to configure timeout via ingress annotations in ingress-controller.
fixes https://github.com/kubernetes/cloud-provider-openstack/issues/2243
```release-note
- Added support for configurable timeouts via ingress annotation in octavia-ingress-controller
```

[octavia-ingress-controller]feat: add configurable listener timeout via ingress annotation

---

hack/bump-release.sh
release-procedure.md

This PR adds a script for easy release management. It was already tested with 1.26.x, 1.27.x and 1.28.x releases
n/a
example usage: `hack/bump_release.sh 28 28 1` should replace 1.28.x with 1.28.1 / 2.28.x with 2.28.1 strings in docs/manifests/tests/examples
The script was tested in GNU/Linux. Needs to be tested on *BSD (e.g. MacOS) as well.
```release-note
NONE
```

[occm] add a new `hack/bump-release.sh` script

---

.github/workflows/release-cpo.yaml
cloudbuild.yaml

fixes #
```release-note
NONE
```

[1.26.4] Switch to a new CI

---

pkg/openstack/loadbalancer_test.go

this pr adds unit test for getSubnetID LbaasV2 method in loadbalancer.go
refers #2400 
```release-note
NONE
```

Test get subnet

---

pkg/openstack/loadbalancer_test.go

fixes #
```release-note
NONE
```
test for the important and complex logic n the getNetwork ID method, wrote unit test indepth edge cases in the program

test : getNetworkID method

---

pkg/openstack/loadbalancer_test.go

It increase unit test coverage for LB file
refers https://github.com/kubernetes/cloud-provider-openstack/issues/2400
```release-note
NONE
```

enh: add tests for checkListenerPorts

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/README.md

Extend documentation for the occm helm chart.
fixes #2432
reading
```release-note
- adds an example for external secret (how to use and create)
- adds notes on tolerations when the controlplane runs isolated
```

[occm] chore: improve documentation

---

pkg/openstack/loadbalancer.go

Improve logging for bool service annotation
fixes #
```release-note
NONE
```

Improve logging for boolean Service Annotations

---

docs/cinder-csi-plugin/using-cinder-csi-plugin.md
docs/developers-guide.md

Updates the image build command
fixes #2269
```release-note
NONE
```

Documentation Update: New Image Build Command 

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/clusterrole.yaml
charts/openstack-cloud-controller-manager/templates/clusterrolebinding.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/templates/serviceaccount.yaml
charts/openstack-cloud-controller-manager/values.yaml

This is a cherry-pick of:
- #2332
- #2347
fixes #2440
At the time #2332 was merged the CI was sadly somewhat broken and missed a spurious space. This has been fixed in #2347 which is also included here to ensure that CI is passing.
As discussed, I bumped the helm chart version to `2.27.6`.
I've also tested this helm chart version in a new 1.27 cluster and was unable to reproduce the bug fixed in #2332.
Please let me know if you'd like me to combine (i.e. squash/fixup) both commits in here into a single, correct, one.
```release-note
ACTION REQUIRED: Please note that you might have to delete the `cloud-controller-manager` service account in the …
```

[release-1.27] [occm] Use standard service account name in OCCM helm chart

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/clusterrole.yaml
charts/openstack-cloud-controller-manager/templates/clusterrolebinding.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/templates/serviceaccount.yaml
charts/openstack-cloud-controller-manager/values.yaml

This is a cherry-pick of:
- #2332
- #2347
fixes #2440
At the time #2332 was merged the CI was sadly somewhat broken and missed a spurious space. This has been fixed in #2347 which is also included here to ensure that CI is passing.
As discussed, I bumped the helm chart version to `2.28.2`.
I've also tested this helm chart version in a new 1.28 cluster and was unable to reproduce the bug fixed in #2332.
```release-note
ACTION REQUIRED: Please note that you might have to delete the `cloud-controller-manager` service account in the `kube-system` namespace if it exists, as upgrading with helm would fail otherwise.
```

[release-1.28] [occm] Use standard service account name in OCCM helm chart

---

pkg/openstack/loadbalancer_test.go

this pr adds unit test for buildMonitorCreateOpts LbaasV2 method in loadbalancer.go
refers #2400
```release-note
NONE
```

Test buid monitor create opts

---

pkg/openstack/loadbalancer.go

Octavia accepts secrets and containers for `default_tls_container_ref` [ref](https://docs.openstack.org/api-ref/load-balancer/v2/index.html#create-listener). Validation currently checks a secret UUID against the containers endpoint.
```release-note
NONE
```

[occm] fix: octavia tlsContainerRef validation for barbican secrets

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/values.yaml

Add a new configuration option `extraEnv` in the cloud-controller-manager helm chart, which are passed to the daemonset.
This allows setting `OS_CCM_REGIONAL`, or perhaps other config options as needed.
```release-note
Add optional `extraEnv` configuration to the openstack-cloud-controller-manager helm chart
```

[charts/occm] Support `extraEnv` on the cloud-controller-manager helm chart

---

pkg/openstack/events.go
pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go

We often find situations when it's useful to use events to warn user about implicit choices that the OCCM makes, e.g. when a provided option is ignored because Octavia does not support it.
This commit adds `eventRecorder` to the `LbaasV2` interface that can be used to create events in these cases. In addition a few places when we just logged a warning are now extended to create events on Services that users will be able to read.
fixes #
```release-note
[openstack-cloud-controller-manager] OCCM will now emit events on Services regarding various implicit decisions it makes.
```

[occm] Add ability to add Events by OCCM

---

pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go
pkg/util/openstack/network.go

Previous code for manage-security-groups were adding the SGs to all the ports attached to the Node. That doesn't make a lot of sense, we only need this traffic opened to the LB members and we only add one port of the Node as the LB member. Moreover we've even tried to add SGs to the ports that had `port_security_enabled=false` which obviously failed.
This patch makes sure that we only add the SG opening NodePort traffic to the port that is actually plugged into the LB. Moreover it adds a check for `port_security_enabled` to make sure that ports with it disabled are ignored.
fixes #2454
```release-note
[openstack-cloud-controller-manager] …
```

[occm] manage-security-groups: Only add SGs to LB members

---

pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go
pkg/util/openstack/network.go

Previous code for manage-security-groups were adding the SGs to all the ports attached to the Node. That doesn't make a lot of sense, we only need this traffic opened to the LB members and we only add one port of the Node as the LB member. Moreover we've even tried to add SGs to the ports that had `port_security_enabled=false` which obviously failed.
This patch makes sure that we only add the SG opening NodePort traffic to the port that is actually plugged into the LB. Moreover it adds a check for `port_security_enabled` to make sure that ports with it disabled are ignored.
fixes #2454
```release-note
[openstack-cloud-controller-manager] …
```

[release-1.28] manage-security-groups: Only add SGs to LB members (#2455)

---

cmd/client-keystone-auth/main.go
cmd/k8s-keystone-auth/main.go

This is a partial backport of #2325, namely the fixes for issues introduced by #2324. This will fix #2464.
Fixes #2464
```release-note
NONE
```

[release-1.28] Remove duplicate pflag.Parse calls

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/values.yaml

This PR implements `imagePullSecrets` for the `openstack-cloud-controller-manager` helm chart on master branch.
None applicable
```release-note
NONE
```

[charts/occm] Implement imagePullSecret support for master branch

---

pkg/openstack/loadbalancer_test.go

adds test case for protocol forced to http in the `buildListenerCreateOpt` function
```release-note
NONE
```

Add Test Case for Protocol Forced to HTTP in `buildListenerCreateOpt` function [OCP]

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/values.yaml

This PR implements `imagePullSecrets` for the `openstack-cloud-controller-manager` helm chart on release 1.28 branch.
None applicable
```release-note
NONE
```

[charts/occm] Implement imagePullSecret support for release 1.28

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md

fixes #
```release-note
NONE
```

Doc: Update doc link to more suitable place

---

cmd/cinder-csi-plugin/main.go
docs/cinder-csi-plugin/using-cinder-csi-plugin.md

fixes #
```release-note
NONE
```

DoC: update doc to include --http-endpoint

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md

fixes #
```release-note
NONE
```

[occm] update doc to fix typos and better description `router-id`

---

docs/cinder-csi-plugin/features.md

fixes #
```release-note
NONE
```

Doc: update doc to be a better link with examples

---

tools/csi-deps.sh

A follow-up fix for the #2486. It appeared that dmesg logs were not collected in the recent build: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/cloud-provider-openstack/2486/openstack-cloud-csi-cinder-e2e-test/1734190366644506624/artifacts/logs/dmesg.log
fixes #
```release-note
NONE
```

[cinder-csi-plugin] Fix dmesg binary in the container image

---

pkg/openstack/openstack.go
pkg/openstack/routes.go

Without this PR controller will not be able to create routes and end up errors with message like
```json
{"NeutronError": {"type": "HTTPBadRequest", "message": "Unrecognized attribute(s) 'allowed_address_pairs'", "detail": ""}}
```
This PR makes route controller skip updates to `allowed_address_pairs` if such extensions is not available or `PortSecurityEnabled` is false
fixes #2491
Bootstrap k8s cluster on OpenStack with disabled `allowed_address_pairs` feature. 
```release-note
[openstack-cloud-controller-manager] skip editing allowed_address_pairs on routes updates if not supported by Neutron 
```

[occm] Not all OpenStack providers support AllowedAddressPairs

---

docs/developers-guide.md
tests/ci-csi-cinder-e2e.sh
tests/ci-csi-manila-e2e.sh
tests/ci-occm-e2e.sh
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-cpo-occm/tasks/main.yaml
tests/playbooks/roles/install-csi-cinder/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/roles/install-csi-manila/defaults/main.yaml
tests/playbooks/roles/install-csi-manila/tasks/main.yaml
tests/playbooks/test-occm-e2e.yaml

This commit enhances the CI playbooks to allow deploying from `master` branch and adds documentation on how to use them to deploy a development environment.
```release-note
NONE
```

Add instructions on how to build dev environment

---

tests/playbooks/roles/install-k3s/tasks/main.yaml

Quite frequently tests are failing because ubuntu image cannot be downloaded:
```
curl -sSL https://cloud-images.ubuntu.com/releases/jammy/release/ubuntu-22.04-server-cloudimg-amd64.img -o ubuntu-jammy.img
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to cloud-images.ubuntu.com:443
```
This PR adds a retry 
fixes #
```release-note
NONE
```

[tests] retry ubuntu image download on temp error

---

tests/playbooks/roles/install-devstack/tasks/main.yml
tests/playbooks/roles/install-k3s/defaults/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml
tests/playbooks/test-csi-manila-e2e.yaml
tests/playbooks/test-occm-e2e.yaml

This PR bumps k3s version to the recent v1.28.4+k3s2
fixes #
```release-note
NONE
```

[tests] bump k3s

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md

This PR updates the occm docs regarding the current state of the ovn load balancer provider support.
fixes #2225
**Special notes for reviewers:**
```release-note
NONE
```

[occm] update docs in order to reflect the current state of the ovn lb-provider support

---

tests/playbooks/test-csi-cinder-e2e.yaml

We were using k8s e2e for 1.25, while we're already on 1.29
fixes #
```release-note
NONE
```

[tests] bump k8s e2e test to 1.29

---

tests/playbooks/roles/install-cpo-occm/tasks/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

don't use static version in sed replacement rules
fixes #
```release-note
NONE
```

[tests] don't use static version in sed replacement rules

---

pkg/ingress/controller/openstack/octavia.go

This commit makes sure that listener timeouts are updated when their values are changed on the Ingress resource annotations.
cc @sakshi-1505 
fixes #2243
```release-note
NONE
```

[octavia-ingress-controller] Update listener timeouts

---

pkg/openstack/loadbalancer.go
pkg/util/openstack/loadbalancer.go

After loadbalancer creation, the controller calls a wait function that polls the Octavia API until its state turns ACTIVE, or timeout is reached.
Before this patch, a failure to GET the loadbalancer in the wait function would result in a nil loadbalancer to be returned to the caller, resulting in an immediate panic when accessing its members.
With this patch:
* GET failures are logged and don't break the polling;
* if the wait timeout is reached while GET is failing, the behaviour exactly matches what happens when reaching the timeout.
```release-note
NONE
```

[occm] Fix panic on failure to get loadbalancer status

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md

**What this PR does / why we need it**: Since eeba48501bf743e3992093bd806a513ad103a347, occm now accepts barbican secrets (https://<keymanager_host>/v1/secrets/<uuid>) in addition to container ref (https://<keymanager_host>/v1/containers/<uuid>) for the `default-tls-container-ref` option.
This commit updates the doc to reflect the change.
fixes #
```release-note
NONE
```

[occm] Update docs for default-tls-container-ref

---

tests/ci-csi-cinder-e2e.sh
tests/ci-csi-manila-e2e.sh
tests/ci-occm-e2e.sh
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-cpo-occm/tasks/main.yaml
tests/playbooks/roles/install-csi-cinder/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/roles/install-csi-manila/defaults/main.yaml
tests/playbooks/roles/install-csi-manila/tasks/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml
tests/playbooks/test-csi-manila-e2e.yaml
tests/playbooks/test-occm-e2e.yaml

I'm not exactly sure why our e2e tests attempted to pull the code on their own based on the `PULL_NUMBER` envvar passed from the test system, but it should be unnecessary. We should expect the code to test is placed properly in the `GOPATH`.
This should help with issues with merging multiple PRs at the same time, when tide tends to bind them together to make sure our daily merge capacity is higher than `24h/<time-to-execute-longest-tests>.`
fixes #2513
```release-note
NONE
```

[e2e] Remove depending on `PULL_NUMBER` in e2e

---

tests/playbooks/roles/install-docker-registry/tasks/main.yml
tests/playbooks/roles/install-docker-registry/templates/ca-config.json.j2
tests/playbooks/roles/install-k3s/tasks/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml
tests/playbooks/test-csi-manila-e2e.yaml
tests/playbooks/test-occm-e2e.yaml

Seems like in 1.29 there are issues with cri-dockerd. There's no reason to use Docker anymore and this commit makes sure k3s uses containerd.
fixes #2528
```release-note
NONE
```

CI: Use k3s with containerd

---

tests/ci-csi-cinder-e2e.sh
tests/ci-csi-manila-e2e.sh
tests/ci-occm-e2e.sh
tests/playbooks/fetch-logs.yaml
tests/playbooks/roles/fetch-logs/README.md
tests/playbooks/roles/fetch-logs/defaults/main.yaml
tests/playbooks/roles/fetch-logs/tasks/main.yaml

This commit makes sure we're fetching and putting the logs of the DevStack services as well as k3s into the artifacts for every CI job.
fixes #
```release-note
NONE
```

[ci] CI: Fetch DevStack and k3s logs

---

pkg/ingress/controller/openstack/octavia.go

PR #2468 used an incorrect condition when updating the listener timeout values and only updates them when listener's allowedCIDRs are updated. This commit fixes this by making sure timeout values are checked too.
fixes #
```release-note
NONE
```

[octavia-ingress-controller] Ingress: Fix listener timeout updates

---

go.mod
go.sum
pkg/openstack/loadbalancer.go

This is a cherry-pick of #2355.
```release-note
NONE
```

[release-1.28] [occm] Lookup ports by SG and not tags (#2355)

---

Makefile

The test image was recently changed and now ships with go1.22rc2. We need to use a version of golangci-lint that is compatible with it.
fixes #
See explanation at https://github.com/kubernetes/cloud-provider-openstack/pull/2537#issuecomment-1933598767
```release-note
NONE
```

[ci] Bump golangci-lint for go 1.22

---

pkg/openstack/loadbalancer.go
tests/e2e/cloudprovider/test-lb-service.sh

This is a cherry-pick of #2360
```release-note
NONE
```
/hold

[release-1.28] [occm] Make sure we don't mask LB tests failures and fix what was failing

---

docs/cinder-csi-plugin/using-cinder-csi-plugin.md
pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go
pkg/csi/cinder/fake.go
pkg/csi/cinder/nodeserver.go
pkg/csi/cinder/nodeserver_test.go
pkg/csi/cinder/openstack/openstack.go
pkg/csi/cinder/openstack/openstack_backups.go
pkg/csi/cinder/openstack/openstack_mock.go
pkg/csi/cinder/openstack/openstack_snapshots.go
pkg/csi/cinder/openstack/openstack_volumes.go
tests/sanity/cinder/fakecloud.go

This allows for creating and deleting cinder backups from K8S via VolumeSnapshot objects that have a VolumeSnapshotClass with `parameters.type = "backup"`. 
Backups are different from snapshots in that they are usually stored off-site, for example via S3 or NFS.
fixes #2473 
Create a VolumeSnapshotClass that has parameters.type equal to "backup"
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
name: csi-cinder-snapclass
driver: cinder.csi.openstack.org
deletionPolicy: Delete
parameters:
force-create: "false"
type: "snapshot"
```
Create a volumeSnapshot that has a Cinder PVC as the Source. This creates a Backup. Deleting this also deletes the …

cinder-csi: Adds support for managing backups (kubernetes#2473)

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/_helpers.tpl
charts/openstack-cloud-controller-manager/templates/clusterrole.yaml
charts/openstack-cloud-controller-manager/templates/clusterrolebinding-sm.yaml
charts/openstack-cloud-controller-manager/templates/clusterrolebinding.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/templates/secret.yaml
charts/openstack-cloud-controller-manager/templates/service-sm.yaml
charts/openstack-cloud-controller-manager/templates/serviceaccount.yaml
charts/openstack-cloud-controller-manager/templates/servicemonitor.yaml

Currently the chart doesn't contain the required labels on the applied resources, this makes it impossible to update the chart without manual intervention
I introduced the common chart from bitnami to standardly handle labels. The chart could also be used to handle resource names, secrets, matchlabels, ... . But I wanted to have this change be backwards-compatible and non-intrusive
```release-note
- adds missing labels to enable helm upgrades
```

fix: add missing labels to resources

---

pkg/kms/server/server.go

**What this PR does / why we need it:**
The `KMSv2` API requires to pass the remote `KeyID` in the `EncryptResponse` object. Indeed, the documentation of the `EncryptResponse` ProtoBuf object says:
```proto
message EncryptResponse {
// The encrypted data.
// ciphertext must satisfy the following constraints:  
// 1. The ciphertext is not empty.  
// 2. The ciphertext is less than 1 kB.
bytes ciphertext = 1;
// The KMS key ID used to encrypt the data. This must always refer to the KMS KEK and not any local KEKs that may be in use.
// This can be used to inform staleness of data updated via value.Transformer.TransformFromStorage.
// keyID must satisfy the following constraints:
// 1. The keyID is not empty.
// 2. The size of keyID is less than 1 kB.
string key_id = 2;
// Additional metadata …
```

[barbican-kms-plugin] Pass KeyId to EncryptResponse

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md

`subnet-id` is cumbersome to use in dual-stack environments, this commit
documents that.
fixes #
```release-note
NONE
```

[occm] Improve CCM docs in dual-stack context

---

docs/barbican-kms-plugin/using-barbican-kms-plugin.md
manifests/barbican-kms/encryption-config.yaml

KMS v1 API is deprecated and in v1.29 core K8s won't allow it with default feature gates set. This commit makes sure we're proposing configuration of v2 API in example EncryptionConfigs.
fixes #
```release-note
KMS EncryptionConfig examples are updated to configure barbican-kms-plugin with v2 API.
```

[barbican-kms-plugin] Update KMS API to v2

---

pkg/openstack/events.go
pkg/openstack/loadbalancer.go

In OpenStack IPv6 that uses GUAs don't require NAT
to access the outside world, so IPv6 can be
rechable without Floating IPs, which makes the
enforcement of IPv6 LB as internal in CPO not necessary.
This commit removes this enforcement, which results in
IPv6 load-balancers being allowed to be shared between
Services. Also, now it's possible to make the load-balancer
use the IPv6 stateful address defined in the loadBalancerIP
of the Service.
fixes #
```release-note
It's now possible to share the load balancer for IPv6 Services and to use IPv6 addresses pre-defined in the `loadBalancerIP`. When using `loadBalancerIP` with IPv6, only stateful addresses are …
```

[openstack-cloud-controller-manager] Remove enforcement of IPv6 LB as internal

---

pkg/openstack/events.go
pkg/openstack/loadbalancer.go

In OpenStack IPv6 that uses GUAs don't require NAT to access the outside world, so IPv6 can be
rechable without Floating IPs, which makes the
enforcement of IPv6 LB as internal in CPO not necessary. This commit removes this enforcement, which results in IPv6 load-balancers being allowed to be shared between Services. Also, now it's possible to make the load-balancer use the IPv6 stateful address defined in the loadBalancerIP of the Service.
fixes #
```release-note
NONE
```

[release-1.29] Remove enforcement of IPv6 LB as internal (#2557)

---

pkg/openstack/events.go
pkg/openstack/loadbalancer.go
pkg/openstack/loadbalancer_rename.go
pkg/openstack/loadbalancer_rename_test.go
pkg/openstack/loadbalancer_test.go
pkg/util/openstack/loadbalancer.go

It's a common issue that clusters are deployed with the default `--cluster-name=kubernetes` and later on it's discovered that next deployments on the same cloud will have conflicts when trying to manage LBs of the same namespace and name.
This commit aims at allowing to change the cluster-name on a running environment and handling all the renames of the LB resources and their tags.
fixes #2241
```release-note
It's now allowed to change the `--cluster-name` on existing deployments and OCCM will handle all the LB renames.
```

[occm] Allow changing cluster-name on existing deployments

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/_helpers.tpl
charts/openstack-cloud-controller-manager/values.yaml

This PR adds the Route section to the cloud-config secret. This allows the Cloud Controller to add routes to Openstack routers. 
This fixes the issue that it is currently not possible to add a Route section to the cloud-config secret via the helm chart.
```release-note
NONE
```

[occm] helm chart - added route section to cloud-config secret

---

docs/cinder-csi-plugin/using-cinder-csi-plugin.md
pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/openstack/openstack.go
pkg/csi/cinder/openstack/openstack_backups.go
pkg/csi/cinder/openstack/openstack_mock.go
pkg/csi/cinder/openstack/openstack_snapshots.go
pkg/csi/cinder/openstack/openstack_volumes.go
tests/sanity/cinder/fakecloud.go

**What this PR does / why we need it**: Original snapshot backup support was added in https://github.com/kubernetes/cloud-provider-openstack/pull/2480. However, it assumes that openstack volume backup zones will match to cinder zones. In our case, that is not true. We have different names for cinder zones than backup zone. That is why availability zone parameter is needed.
fixes #
```release-note
NONE
```

[cinder-csi-plugin] define availability zone for snapshot backup

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml

The above option seems to be causing CCM to create clients using ServiceAccount from the `kube-system` namespace, so requires users to either run in `kube-system` namespace, or manage 2 ServiceAccounts, one in `kube-system` and other in regular CCM namespace. See [1].
This commit changes this setting.
/hold
[1] https://github.com/kubernetes/cloud-provider/blob/c3862938334ba18226098015193374fda40ab7a9/options/options.go#L230-L237
fixes #2560
```release-note
OCCM is by default no longer run with `--use-service-account-credentials=true`, meaning that it will use the ServiceAccount specified in the DaemonSet. This means that you can stop managing the …
```

[occm] Set `--use-service-account-credentials=false`

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml

The GitHub account @brtknr does not exist anymore and our chart linter complains about this. This commit adds me as the maintainer.
fixes #2582
```release-note
Maintainer for Cinder and Manila CSI charts is updated.
```

[cinder-csi-plugin] [manila-csi-plugin] Update Cinder and Manila CSI charts maintainers

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-k3s/defaults/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml

fixes #
```release-note
NONE
```

Bump versions for 1.30

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/values.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml

this PR adds dnsPolicy configuration to occm which should be changed if deployed in a cluster with a custom coredns configuration like internal dns domain.
fixes #2592
```release-note
[openstack-cloud-controller-manager] Add dnsPolicy configuration to manifests and charts
```

[occm] add dnsPolicy feature 

---

docs/manila-csi-plugin/developers-csi-manila.md

Snapshotting and cloning CephFS shares is supported (#2299) so is Topology via Manila AZs (#939, #2255)
```release-note
NONE
```

[manila-csi-plugin] Update manila dev doc regarding implemented features

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/openstack/loadbalancer.go
pkg/openstack/loadbalancer_test.go
pkg/openstack/openstack.go
pkg/util/util.go
pkg/util/util_test.go

This PR adds an ability to specify loadbalancer service with a node selector.
Big thanks to @ririko-nakamura for the [initial code](https://github.com/ririko-nakamura/cloud-provider-openstack/tree/target-node-labels-selector).
A new OCCM `node-selector` option is added into the `[LoadBalancer]` config section.
And a new `loadbalancer.openstack.org/node-selector` service annotation support is added.
fixes #1770
```release-note
added a node selector support for loadbalancer services
```

[occm] add a node selector support for loadbalancer services

---

tests/playbooks/roles/install-devstack/defaults/main.yaml

This PR fixes the 1.28 CI. OpenStack Zed release is not maintained anymore.
fixes #
```release-note
NONE
```

[tests]: fix 1.28 release CI

---

tests/playbooks/roles/install-k3s/defaults/main.yaml

This PR fixes the 1.29 CI. This should deploy a k3s that supports new docker releases.
fixes #
```release-note
NONE
```

[tests]: fix 1.29 tests CI

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/cinder-csi-plugin/values.yaml
charts/manila-csi-plugin/Chart.yaml
charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/manila-csi-plugin/values.yaml

Add `extraEnv` support on the cinder-csi-plugin helm chart.
One example use case of extraEnv:  In some of our private customer cloud, cinder-csi-plugin must access the openstack API endpoint with following env variable  `http_proxy, https_proxy, no_proxy`.
```release-note
NONE
```

[cinder-csi-plugin] Add extraEnv support on cinder-csi-plugin and manila-csi-plugin helm charts

---

pkg/csi/cinder/nodeserver.go
pkg/util/blockdevice/blockdevice_linux.go

If the initial formatting and mounting fails in NodeStageVolume try to rescan the device and retry the operation.
This prevents failures if the device information is reported wrongly which would otherwise be blocking the mounting.
fixes #2588 
Hi, I thought I would add this as a retry mechanism in case the mounting has already failed to minimize the impact on the current flow, also do not think this rescan should be causing any issues. If there is other ideas or concerns I am all ears, thanks!
```release-notes
None
```

[cinder-csi-plugin] retry mount operation with rescan incase of failure

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/values.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml

**What this PR does / why we need it**: reverts the behaviour that was added https://github.com/kubernetes/cloud-provider-openstack/pull/2594
fixes #2611
if dnsPolicy is defined the default value is not `Default` its `ClusterFirst`. See https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
```release-note
NONE
```

[occm] Revert dnsPolicy to Default for occm

---

cmd/cinder-csi-plugin/main.go
docs/cinder-csi-plugin/multi-region-clouds.md
pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go
pkg/csi/cinder/driver.go
pkg/csi/cinder/nodeserver.go
pkg/csi/cinder/nodeserver_test.go
pkg/csi/cinder/openstack/fixtures/clouds.yaml
pkg/csi/cinder/openstack/openstack.go
pkg/csi/cinder/openstack/openstack_test.go
pkg/csi/cinder/utils.go
tests/sanity/cinder/sanity_test.go

**Affected binaries:**
- cinder-csi-plugin
Enable multi region / multi clouds support on cinder-csi-plugin controllerServer.
fixes #2035
I have a kubernetes cluster stretch on multiples openstack clusters (3 OVH and 1 onPremise linked by a private dark fiber).
That why my approche is more "multi clouds" than only "multi region"
I don't touch nodeServer behavior (I simply deploy a Daemonset with a nodeSelector on a label whitch select nodes based on their hypervisor, and mount a dedicated secret with openstack creds associated)
The purpose is on controllerServer which handle all kube requests to manage pvc, he had be able to CRUD volumes on all managed openstack cluster.
I …

[cinder-csi-plugin] Multi region/clouds support for controllerServer

---

pkg/csi/cinder/nodeserver.go
pkg/csi/cinder/nodeserver_test.go

Disable creating new deprecated ephemeral volumes
Remove deprecated ephemeral volumes.
fixes #2599
Hi, @dulek i've disabled only ephemeral volume creation stage.
What do you think, we should remove all code or make it in two steps (releases)?
Thanks.
```release-note
In-line ephemeral is no longer available.
```

[cinder-csi-plugin] ephemeral volume removal

---

tests/e2e/cloudprovider/test-lb-service.sh

fixes #
```release-note
NONE
```

[occm] fix e2e tests

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
pkg/openstack/loadbalancer.go
pkg/openstack/loadbalancer_test.go

The PR brings the ability of choosing the ProxProtocol in version 2 (instead of v1).
Two new values are supported for `loadbalancer.openstack.org/proxy-protocol`
```yaml
loadbalancer.openstack.org/proxy-protocol: "true" # Enable ProxyProtocolv1
loadbalancer.openstack.org/proxy-protocol: "false" # Default value, no proxy protocol enable 
loadbalancer.openstack.org/proxy-protocol: "v1" # NEW - Enable ProxyProtocolv1
loadbalancer.openstack.org/proxy-protocol: "v2" # NEW - Enable ProxyProtocolv2
```
fixes #2585
N/A
```release-note
[openstack-cloud-controller-manager] Support LoadBalancer ProxyProtocol v2 feature
```

[occm] LoadBalancer ProxyProtocol v2 feature

---

pkg/openstack/instancesv2.go
pkg/util/metadata/metadata.go
pkg/util/util.go

**What this PR does / why we need it**: AZ names can contain unicode characters, for example "Württemberg". The current behaviour is that this causes the occm pod to crash: 
```
$ crictl logs a358b0388996d (openstack-cloud-controller-manager)
error syncing 'test-hshu2jf73dym-default-worker-6s4mq-s9swb': Node "test-hshu2jf73dym-default-worker-6s4mq-s9swb" is invalid: metadata.labels: Invalid value: "Württemberg Test": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), requeuing
```
This PR sanitizes the label value before it is applied. 
We also see the same problem in …

[occm] [cinder-csi-plugin] Sanitize AZ name

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/templates/controllerplugin-podmonitor.yaml
charts/cinder-csi-plugin/values.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/servicemonitor.yaml
charts/openstack-cloud-controller-manager/values.yaml

* feat: support additionalLabels for occm serviceMonitor
* feat: support additionalLabels for cinder-csi-plugin podMonitor
This may be used to add custom labels to theses resources. In environments with multiple prometheus this is typically used to specify which prometheus will be collect metrics of which serviceMonitors/podMonitors.
* fixes - 
```release-note
[charts/occm] support additionalLabels for occm serviceMonitor in helm chart
[charts/cinder-csi-plugin] support additionalLabels for cinder-csi-plugin podMonitor in helm chart
```

[charts] support additionalLabels for occm serviceMonitor and cinder-csi-plugin podMonitor

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
docs/release-procedure.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-k3s/defaults/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml

fixes #
```release-note
NONE
```

release 1.31

---

docs/release-procedure.md

fixes #
```release-note
NONE
```

fix instructions

---

.golangci.yaml
Makefile
cmd/manila-csi-plugin/main.go
pkg/util/blockdevice/blockdevice_linux.go

fixes #
```release-note
NONE
```

Bump golangci to 1.61

---

docs/cinder-csi-plugin/multi-region-clouds.md

Simple typo fix on the multi-region documentation. 
I was getting "Error: unknown flag: --additionnal-topology" errors because I copy/pasted the examples in the documentation. 
Indeed, the correct option is  "--additional-topology", with a single N
```release-note
NONE
```

fix typo in the multi-region documentation

---

cmd/cinder-csi-plugin/main.go
docs/cinder-csi-plugin/using-cinder-csi-plugin.md
pkg/csi/cinder/openstack/noop_openstack.go
pkg/csi/cinder/openstack/openstack.go

This PR allows to run cinder-csi-plugin node service without requiring the openstack credentials.
fixes #2599
backport of the #2655 
This PR will be used to make backports to 1.29, 1.28
This PR is intended to improve the cinder CSI driver security.
```release-note
[cinder-csi]: allow node service to run without openstack client
```

[release-1.30] [cinder-csi]: allow node service to run without openstack client

---

cmd/cinder-csi-plugin/main.go
docs/cinder-csi-plugin/using-cinder-csi-plugin.md
pkg/csi/cinder/openstack/noop_openstack.go
pkg/csi/cinder/openstack/openstack.go

This PR allows to run cinder-csi-plugin node service without requiring the openstack credentials.
fixes #2599
supersedes #2640
This PR will be used to backport to 1.31
This PR is intended to improve the cinder CSI driver security.
```release-note
[cinder-csi]: allow node service to run without openstack client
```

[cinder-csi]: allow node service to run without openstack client

---

cmd/cinder-csi-plugin/main.go
docs/cinder-csi-plugin/using-cinder-csi-plugin.md
pkg/csi/cinder/openstack/noop_openstack.go
pkg/csi/cinder/openstack/openstack.go

This is a manual cherry-pick of #2656. Need to adjust noop methods according to an old `IOpenStack` interface.
Supersedes #2668
```release-note
[cinder-csi]: allow node service to run without openstack client
```

[release-1.29] [cinder-csi]: allow node service to run without openstack client

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/cinder-csi-plugin/multi-region-clouds.md
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/test-csi-cinder-e2e.yaml

fixes #
Needs to be cherry-picked to release-1.31
```release-note
NONE
```

[release-1.31]: prepare a new release

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-k3s/defaults/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml

fixes #
```release-note
NONE
```

[release-1.29]: prepare a new release

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-k3s/defaults/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml

fixes #
```release-note
NONE
```

[release-1.30]: prepare a new release

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/roles/install-k3s/defaults/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml

fixes #
```release-note
NONE
```

[release-1.28]: prepare a new release

---

pkg/identity/keystone/sync.go
pkg/openstack/instances.go
pkg/openstack/loadbalancer.go
pkg/openstack/openstack.go
pkg/util/util.go

Fixed nested conditions logic and switched to `slices.Contains`, removed `Contains` func from util package.
n/a
```release-note
NONE
```

[core] improved readability of lb funcs, switch to slices.Contains

---

Dockerfile

fixes #2689
```release-note
NONE
```

Update DEBIAN_IMAGE to bookworm

---

pkg/openstack/loadbalancer.go
pkg/openstack/loadbalancer_sg.go
pkg/openstack/loadbalancer_subnet_match.go
pkg/openstack/loadbalancer_subnet_match_test.go
pkg/openstack/openstack.go
pkg/openstack/routes.go
pkg/util/openstack/network.go

This is a yet another code cleanup and #2692 follow-up. This PR removes unused arguments in functions, uses `SplitTrim` helper, where it's needed, and adds context passthrough.
fixes #
```release-note
NONE
```

[occm] passthrough context to gophercloud calls

---

pkg/openstack/openstack.go

This PR stops OCCM controller, when a loadbalancer config was provided, but the endpoint is absent or not reachable.
fixes #2704
```release-note
[occm] exit on unreachable loadbalancer endpoint
```

[occm]: exit on unreachable loadbalancer endpoint

---

tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/roles/install-csi-manila/tasks/main.yaml

Add more logging capabilities, fix collecting the cinder CSI logs on error, disable LBaaS support in CSI tests (due to #2706)
fixes #
```release-note
NONE
```

Fix CSI tests

---

pkg/openstack/loadbalancer.go

**What this PR does / why we need it**: the main reason for #2699 was that `svcConf.allowedCIDR` was not passed to `ensureAndUpdateOctaviaSecurityGroup` from updateloadbalancer (it was passed from ensureloadbalancer). However, I compined some of the creating values for svcConf to new function to make it little bit easier to read and remove duplicates
fixes #2699
```release-note
NONE
```

[occm] fix ovn security groups

---

go.mod
go.sum
pkg/autohealing/cloudprovider/openstack/provider.go

Drop support of the updated github.com/pborman/uuid
Drop support of the outdated github.com/pborman/uuid
fixes #
```release-note
NONE
```

[magnum-auto-healer] use github.com/google/uuid package

---

tests/playbooks/roles/install-devstack/defaults/main.yaml
tests/playbooks/roles/install-devstack/tasks/main.yml
tests/playbooks/roles/install-devstack/templates/local.conf.j2

the `stable/2023.1` was removed in some openstack repos, now the `stable/2023.2` is the stable one. also we need to update pip and setuptools
fixes #
```release-note
NONE
```

[tests] bump devstack branch to stable/2023.2, fix python issues

---

Dockerfile

Fixes the warnings reported while building container images
fixes #2691 
```release-note
NONE
```

Fix warnings reported while building container images

---

pkg/openstack/loadbalancer.go
pkg/openstack/loadbalancer_test.go

This PR fixes a regression introduced in #2688, unit tests ensure that the internal/external IP order works as expected.
fixes #2718 
```release-note
NONE
```

[occm] fix node internal/external IP order

---

tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/roles/install-devstack/defaults/main.yaml

fixes #
```release-note
NONE
```

[tests] bump openstack branch to stable/2024.2

---

docs/developers-guide.md
tests/playbooks/roles/install-docker/defaults/main.yml
tests/playbooks/roles/install-k3s/defaults/main.yaml
tests/scripts/create-gce-vm.sh

Bump test env to ubuntu 24.04 jammy, bump k3s to v1.31.2+k3s1
fixes #
```release-note
NONE
```

[tests] bump ubuntu to 24.04 jammy

---

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
pkg/openstack/events.go
pkg/openstack/loadbalancer.go
pkg/openstack/loadbalancer_test.go

Adds the ability to change the LB Algorithm of an Octavia using an annotation.
This PR brings a new annotation:
```yaml
loadbalancer.openstack.org/lb-method: "" # Default value: the one defined in the OCCM configuration file
```
N/A
```release-note
[occm] Octavia - ability to change the load balancing method using an annotation.
```

[occm] Support Octavia load balancing method via annotation

---

tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/roles/install-devstack/defaults/main.yaml

Reverts kubernetes/cloud-provider-openstack#2720
tests against the stable/2024.2 are running too slow. we need to analyze [logs](https://gcsweb.k8s.io/gcs/kubernetes-ci-logs/pr-logs/pull/cloud-provider-openstack/2720/openstack-cloud-csi-cinder-e2e-test/1858895961917493248/artifacts/logs/) and clarify why.
```release-note
NONE
```

Revert "[tests] bump openstack branch to stable/2024.2"

---

Dockerfile
tests/playbooks/roles/install-cpo-occm/README.md
tests/playbooks/roles/install-cpo-occm/tasks/main.yaml
tests/playbooks/roles/install-csi-cinder/README.md
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/roles/install-csi-manila/README.md
tests/playbooks/roles/install-csi-manila/tasks/main.yaml
tests/playbooks/roles/install-golang/tasks/main.yml
tests/playbooks/roles/install-k3s-bare-single/tasks/main.yaml
tests/playbooks/roles/install-k3s/tasks/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml
tests/playbooks/test-csi-manila-e2e.yaml
tests/playbooks/test-occm-e2e.yaml

We're seeing failures in CI related to goproxy.io. There's no need to set this so simply don't. Doing this highlights a couple of issues with our jobs: namely that we're not actually testing code in the PR due to a missing `GOPATH` env var. This is mitigated with a temporary fix, but a larger fix that involves building the controllers locally before pushing them to the cluster should and will be done separately.
none.
Discussed this on Slack [here](https://kubernetes.slack.com/archives/C0LSA3T7C/p1733405450278309).
```release-note
NONE
```

Stop setting GOPROXY in Dockerfile

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/openstack/openstack.go

Add `f5` to `supportedLBProvider `
Openstack api support `f5` as LB provider, but OCCM will block at first place as `f5` is not in the supported list.
fixes #
1. In OCCM cloud-config, add below setting:
```
[LoadBalancer]
lb-provider = f5
```
OCCM can start without error
2. Add LB service, openstack with f5 can create LB
```release-note
Add f5 to supportedLBProvider
```

add f5 as supported LB

---

pkg/openstack/openstack.go
pkg/openstack/openstack_test.go

Since InstancesV1 was removed, we need to clean up the zone methods.
Zones() uses only if InstancesV1 interface exists. https://github.com/kubernetes/cloud-provider/blob/master/controllers/node/node_controller.go#L579-L606
All zone information expose by InstancesV2 in InstanceMetadata()
And
https://github.com/kubernetes/cloud-provider/blob/master/cloud.go#L274
```go
// DEPRECATED: Zones is deprecated in favor of retrieving zone/region information from InstancesV2.
// This interface will not be called if InstancesV2 is enabled.
type Zones interface {
```
#2692
```release-note
NONE
```

[occm]: remove InstancesV1 Zones method

---

pkg/csi/manila/driver.go
pkg/csi/manila/nodeserver.go

Trivial fixes for things highlighted in https://github.com/kubernetes/cloud-provider-openstack/pull/2743
(none)
(none)
```release-note
NONE
```

[manila-csi-plugin] Trivial fixups

---

docs/cinder-csi-plugin/multi-region-clouds.md

Added missing parameters csi.storage.k8s.io/controller-expand-secret-name and csi.storage.k8s.io/controller-expand-secret-namespace to the StorageClass configuration in the Multi-AZ/Region/OpenStack documentation. These parameters were missing, causing issues with PVC expansion. After some time spent troubleshooting, I found these parameters in the [Kubernetes CSI documentation on StorageClass secrets](https://kubernetes-csi.github.io/docs/secrets-and-credentials-storage-class.html#storageclass-secrets). After adding them, PVC expansion works as expected.
```release-note
NONE
```

[docs] add missing parameters to StorageClass in multi-region-clouds.md

---

cmd/cinder-csi-plugin/main.go
docs/cinder-csi-plugin/using-cinder-csi-plugin.md
pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go
pkg/csi/cinder/driver.go
pkg/csi/cinder/nodeserver.go
pkg/csi/cinder/nodeserver_test.go
tests/sanity/cinder/sanity_test.go

Many clouds do not have a 1:1 mapping of compute and storage AZs. As we generate topology information from the metadata service on the node (i.e. a compute AZ), this can prevent us from being able to schedule VMs.
Add a new boolean, '--with-topology', to allow users to disable the topology feature where it does not make sense. An identical option already exists for the Manila CSI driver. However, unlike that option, this one defaults to 'true' to retain current behavior.
(none)
(none)
```release-note
A new option, `--with-topology`, can be used to configure whether the driver and controller services of the `cinder-csi-plugin` report and respect topology …
```

[cinder-csi-plugin] Add --with-topology opt

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/templates/controllerplugin-rbac.yaml
charts/cinder-csi-plugin/values.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml

[cinder-csi-plugin] Bump CSI sidecar versions to latest. Update related RBAC.
Volume doesn't get deleted from OpenStack if related PV is deleted by a user.
fixes #
```release-note
NONE
```

[cinder-csi-plugin] bump CSI sidecar versions to latest

---

tests/playbooks/roles/install-devstack/templates/local.conf.j2

Copy host tuning from:
https://opendev.org/openstack/devstack/src/commit/05f7d302cfa2da73b2887afcde92ef65b1001194/.zuul.yaml#L645-L662
Enable `ENABLE_SYSCTL_MEM_TUNING`, `ENABLE_SYSCTL_NET_TUNING` and
`ENABLE_ZSWAP` for the reasons explained in comments.
```release-note
NONE
```

ci: host tuning in devstack

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml

**What this PR does / why we need it**: as release-1.31 is released, master should use 1.32 (in case of helm charts 2.32) versions.
fixes #
```release-note
NONE
```

fix helm chart versions

---

Makefile

fixes 
```
level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
exit status 4
make: *** [Makefile:84: check] Error 1
```
```release-note
NONE
```

tests: increase golangci-lint timeout

---

.github/dependabot.yml

fixes #
```release-note
NONE
```

group all dependabot updates to one pr

---

pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go
pkg/csi/cinder/openstack/openstack_volumes.go
pkg/csi/cinder/utils.go
pkg/csi/cinder/utils_test.go

Fixes the linked issue and in addition does a small refactoring simplifying the code for the list volumes. In particular it changes the behavior slightly in 2 ways:
- if the list operation returns any page token even with max-entries == 0, we will respect the token and return it in the response.
- in the case of multiple cloud envs, we will no longer do the discovery for "the first cloud with volumes", instead we return the next cloud env. The discovery costs additional Cinder API calls which are more costly than simply issuing an additional local grpc call from the external-attacher.
Regarding point 2: the external-attacher will continue sending requests to list volumes while the response contains a token: …

[cinder-csi-plugin] Refactor list volumes

---

pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go
pkg/csi/cinder/openstack/openstack_volumes.go
pkg/csi/cinder/utils.go
pkg/csi/cinder/utils_test.go

This is a manual cherry-pick of #2766
/assign kayrus
the difference between the original PR and the backport:
```
diff -u <(git show) <(git show 29f3f0b92955e6da94e7a014af04cee0c6ce6be6) | egrep -v '@@|-index|+index' | colordiff
```
```release-note
NONE
```

[release-1.31] [cinder-csi-plugin] Refactor list volumes

---

tests/playbooks/roles/install-k3s/defaults/main.yaml
tests/playbooks/test-csi-cinder-e2e.yaml

fixes #
```release-note
NONE
```

upgrade test dependency versions

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/cinder-csi-plugin/multi-region-clouds.md
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml

fixes #
```release-note
NONE
```

release 1.32.0

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml

fixes #
```release-note
NONE
```

2.33 alpha charts

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_report.md
Makefile

fixes #
for some reason this change was implemented too soon https://github.blog/changelog/2025-02-18-github-issues-projects-february-18th-update/#single-issue-templates-issue_template-md-will-be-retired
```release-note
NONE
```

Update issue templates

---

pkg/csi/cinder/driver.go
pkg/csi/cinder/identityserver.go
pkg/csi/manila/driver.go
pkg/csi/manila/identityserver.go

The `PluginCapability_Service_VOLUME_ACCESSIBILITY_CONSTRAINTS` capability flag determines whether the provisioner attempts to look up topology information from the node or not [1][1] [2][2]. If we report it but don't return topology information from the node, we end up with failures to provision [3][3]. Fix the issue by optionally reporting the capability, like Manila already does.
In addition to the main fix, we also duplicate some helpful logs from Cinder to Manila, plus we fix a minor issue in the startup logging for both. More information on all these changes is provided in [the commits](https://github.com/kubernetes/cloud-provider-openstack/pull/2862/commits).
[1]: https://github.com/kubernetes-csi/external-provisioner/blob/17e2429e9f/pkg/contr …

[cinder-csi-plugin] Don't report topology capability when --with-topology=False

---

pkg/openstack/loadbalancer.go

When lb renaming fails it's hard to track down the root cause, because the real error is swallowed.
I couldn't test this, as this project just doesn't build for me, but the change is small enough that I hope it just works 🤞
```release-note
NONE
```

[openstack-cloud-controller-manager (occm)] fix: wrap error to bubble it up

---

pkg/identity/keystone/authenticator.go

Don't panic in case, when a token doesn't contain a project scope. Return a proper error message instead.
fixes #2760
```release-note
k8s-keystone-auth: properly handle tokens with no project scope
```

k8s-keystone-auth: properly handle token with no project scope

---

OWNERS

As discussed [on Slack](https://kubernetes.slack.com/archives/C0LSA3T7C/p1744287140817049?thread_ts=1741621902.079559&cid=C0LSA3T7C), I'd like to step up and help with the maintenance of CPO. I expect my focus to mainly be maintenance of CI and occasional bug fixes to cloud-provider and the CSI drivers (though I'd like to explore the other components as time allows). I have contributed sporadically in the past, but I have been very active in
upstream OpenStack for over a decade and have also been involved in Gophercloud and to a lesser degree CAPO in recent times, so rest assured I am "vouched for" and won't be self-approving things or ignoring CI failures on PRs 😄
None. …

Add stephenfin to approvers, reviewers

---

charts/manila-csi-plugin/Chart.yaml
charts/manila-csi-plugin/templates/controllerplugin-role.yaml
charts/manila-csi-plugin/templates/controllerplugin-rolebinding.yaml
charts/manila-csi-plugin/templates/controllerplugin-service.yaml
charts/manila-csi-plugin/templates/controllerplugin-serviceaccount.yaml
charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/manila-csi-plugin/templates/nodeplugin-serviceaccount.yaml
charts/manila-csi-plugin/templates/runtimeconfig-cm.yaml

This PR sets release namespace in manila-csi helm chart.
fixes #
```release-note
[manila-csi-plugin] set release namespace explicitly in helm chart
```

[manila-csi-plugin] helm: add release namespace in manila csi chart

---

charts/manila-csi-plugin/Chart.yaml
charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml
charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/manila-csi-plugin/values.yaml

This PR supports additional volumes in manila csi chart. Typical use case is to mount ca cert of openstack api.
fixes #
```release-note
[manila-csi-plugin] add support for additional volumes in helm chart. 
Typical use case is to mount ca cert of openstack api.
```

[manila-csi-plugin] helm: support additional volumes in manila csi chart

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/templates/controllerplugin-deployment.yaml
charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
charts/cinder-csi-plugin/values.yaml

[cinder-csi-plugin] helm charts: Use /etc/config/ for cloud.conf
This path is used by default in the deployment manifests for cinder-csi as well as in manifests and helm charts for occm.
It does not matter much until you reference another file via ca-file=/etc/config/cacert
in your cloud.conf and assume that to work.
So better align the volumeMount location everywhere. As there is a canonical location where most artifacts already agree on, let's use it in cinder-csi helm charts as well.
Make the cinder-csi-plugin helm charts work if we pass a secret with `cloud.conf` and a `cacert` referenced from there assuming the `/etc/config` path.
This works with occm (deployment manifests and helm charts) and cinder-csi deployment manifests, but not currently …

[cinder-csi-plugin]: helm-charts: use /etc/config/ for cloud.conf

---

Dockerfile

fixes #
```release-note
NONE
```

update build images

---

tests/playbooks/roles/install-devstack/defaults/main.yaml
tests/playbooks/roles/install-devstack/templates/local.conf.j2

We currently have no less than three PRs in-flight attempting to bump the DevStack version used in the gate (and a possible forth one need for Epoxy):
* https://github.com/kubernetes/cloud-provider-openstack/pull/2888
* https://github.com/kubernetes/cloud-provider-openstack/pull/2742
* https://github.com/kubernetes/cloud-provider-openstack/pull/2903
While we continue work on these and investigate the performance regressions seen in Dalmatian (and possibly Caracal), unblock the gate by relying on the `2023.2-eol` tags rather than the (now deleted) `stable/2023.2` branches.
Note that `python-barbicanclient` does not have a `2023.2-eol` tag so we can't use install from Git. Since we're not hacking on though there's no good reason to be installing from …

tests: Temporarily unblock gate with use of EOL Bobcat tags

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/cinder-csi-plugin/multi-region-clouds.md
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml

fixes #2884
```release-note
NONE
```

release 1.33.0

---

pkg/client/client.go
pkg/csi/manila/manilaclient/builder.go
pkg/csi/manila/validator/validator.go
pkg/csi/manila/validator/validator_test.go

1. Fixes a bug where `AuthOps` and `Region` were incorrectly required when using `clouds.yaml` for authentication.
2. Resolves an issue where the validator could not properly handle boolean values retrieved from secrets.
3. Adds a new test case to cover the boolean validation fix.
4. Introduces support for authenticating the Manila CSI driver via `clouds.yaml`
fixes #2886
```release-note
Now support configuration from a clouds.yaml file for the Manila CSI driver.
```

[manila-csi-plugin] Add support for authentication via clouds.yaml

---

pkg/client/client.go
pkg/csi/manila/manilaclient/builder.go
pkg/csi/manila/validator/validator.go
pkg/csi/manila/validator/validator_test.go

This is a manual cherry-pick of [#2883](https://github.com/kubernetes/cloud-provider-openstack/pull/2883)
```release-note
NONE
```

[release-1.33][manila-csi-plugin] Add support for authentication via clouds.yaml

---

pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go
pkg/csi/cinder/openstack/openstack.go
pkg/csi/cinder/openstack/openstack_volumes.go
pkg/util/errors/errors.go

If OpenStack quotas for volumes are exceeded, the driver currently returns the gRPC call with code `Internal`. This is not propagated to the PVC as an event and is not traceable very easily.
Cinder returns with a HTTP 413 response code if the quota for volumes is exceeded:
https://github.com/openstack/cinder/blob/c4f61c11ef9b590606a2a276bdf256622516181f/cinder/quota_utils.py#L130-L140
CSI spec defines that on a quota limit error, the driver should return a `ResourceExhausted` grpc error code:
https://github.com/container-storage-interface/spec/blob/master/spec.md#createvolume-errors
```release-note
Updated the error code to ResourceExhausted for CreateVolume calls if the volume quota is exceeded.
```

[cinder-csi-plugin]: ResourceExhausted code for CreateVolume

---

tools/csi-deps-check.sh
tools/csi-deps.sh

fixes #2875
```release-note
[cinder-csi-plugin] add POSIX shell to docker image
```

[cinder-csi-plugin] add POSIX shell to docker image

---

manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml

The OpenStack Cloud Controller Manager is a critical component of the Kubernetes control plane when running on OpenStack. It should ideally run on control-plane nodes for better isolation, security, and to fulfill its role effectively. These changes ensure that OCCM pods:
- Are scheduled on the intended control-plane nodes.
- Can operate on nodes protected by the CriticalAddonsOnly=true:NoExecute taint, as OCCM is considered a critical add-on.
- This leads to a more robust and correctly configured deployment of OCCM.
fixes #2093 
Addresses an issue where OCCM may fail to schedule on control-plane nodes due to the CriticalAddonsOnly taint.
- Please verify that the updated …

[occm] Target control-plane nodes and tolerate CriticalAddonsOnly taint

---

go.mod
go.sum

fixes #
```release-note
NONE
```

update gophercloud v2.7.0

---

pkg/openstack/loadbalancer.go

To avoid `loadbalancer.go:1478] "Target node label %s=%s is set to LoadBalancer service %s" env="production" default/openstack-loadbalancer="(MISSING)"`
fixes #
Introduced in #2601 
```release-note
NONE
```

[occm] fix lbaas logs

---

pkg/csi/cinder/driver.go
pkg/csi/cinder/identityserver.go
pkg/csi/manila/driver.go
pkg/csi/manila/identityserver.go

This is a manual backport of #2862 (`master`) and #2871 (`release-1.32`). As noted in the first commit, the merge conflict was trivial and due to the absence of #2734, which added a log into the Manila CSI Driver.
```release-note
NONE
```

[release-1.31] [cinder-csi-plugin] Don't report topology capability when --with-topology=False

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/cinder-csi-plugin/multi-region-clouds.md
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml

prepare a new 1.33.1 release
```release-note
NONE
```

[release-1.33] prepare new 1.33.1 release

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/cinder-csi-plugin/multi-region-clouds.md
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml

prepare a new 1.32.1 release
```release-note
NONE
```

[release-1.32] prepare new 1.32.1 release

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/cinder-csi-plugin/multi-region-clouds.md
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml

prepare a new 1.31.4 release
```release-note
NONE
```

[release-1.31] prepare new 1.31.4 release

---

Dockerfile
go.mod

Update alpine to the latest patch release available
fixes #
```release-note
Update alpine image used to v1.17.10
```

[release-1.31] update alpine to latest patch release

---

Dockerfile
go.mod

Bump golang to 1.24.5 and bump alpine image.
fixes #
```release-note
NONE
```

Bump golang to 1.24.5

---

Dockerfile
go.mod

Bump golang to 1.23.11 and bump alpine image.
fixes #
```release-note
NONE
```

[release-1.32] Bump golang to 1.23.11

---

docs/release-procedure.md
hack/bump-charts.sh
hack/release-image-digests.sh
hack/verify-image-digests.sh

This PR adds a script that checks release images checksums along gcr.io/k8s-staging-provider-os and registry.k8s.io/provider-os registries with a https://github.com/kubernetes/k8s.io/blob/main/registry.k8s.io/images/k8s-staging-provider-os/images.yaml file contents
fixes #2930
```release-note
NONE
```

release: add verify-image-digests.sh and release-image-digests.sh scripts

---

tests/ci-csi-cinder-e2e.sh
tests/ci-csi-manila-e2e.sh
tests/ci-occm-e2e.sh
tests/playbooks/roles/install-cpo-occm/tasks/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/roles/install-csi-manila/tasks/main.yaml
tests/playbooks/roles/install-devstack/defaults/main.yaml
tests/playbooks/roles/install-devstack/templates/local.conf.j2
tests/playbooks/test-occm-e2e.yaml
tests/scripts/create-gce-vm.sh

Bump the version of DevStack used in CI from Bobcat (2023.2), which is now EOL, to Epoxy (2025.1).
(none)
(none)
```release-note
NONE
```

tests: Bump DevStack to Epoxy (2025.1)

---

tests/playbooks/roles/install-devstack/tasks/main.yml

Devstack starting from epoxy renamed cinder volume types
```release-note
NONE
```

[release-1.33] tests: create volumev3 service type

---

tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/roles/install-csi-manila/tasks/main.yaml
tests/playbooks/roles/install-devstack/tasks/main.yml

We have worked around Nova bug #2119114 by lowering the device detach threshold to 1 second. Unfortunately this still leaves us with a N seconds of additional runtime, where N is the number of device detaches incurred by our test suite (since we run tests serially). This has put us right on the cusp of timeouts, meaning our jobs occasionally pass and occasionally fail, depending on the node we end up on. Add a bit more breathing room for the jobs while we wait for the Nova fix.
Note that we do this for both Cinder and Manila to try keep those jobs consistent where possible.
[1] https://bugs.launchpad.net/nova/+bug/2119114
n/a
```release-note
NONE
```

Bump CSI test timeouts

---

pkg/openstack/openstack.go

Add amphorav2 as a valid loadbalancer provider
fixes #2952 
```release-note
[openstack-cloud-controller-manager] Support `amphorav2` as loadbalancer type
```

[occm] Add amphorav2 as a supported loadbalancer provider

---

docs/cinder-csi-plugin/features.md
docs/cinder-csi-plugin/multi-region-clouds.md
docs/cinder-csi-plugin/troubleshooting.md
docs/cinder-csi-plugin/using-cinder-csi-plugin.md

This option is only useful if you are manually configuring volume AZs using the `topology` Storage Class parameter. Update docs to reflect this and suggest (likely better) alternatives for working around AZ mismatches.
fixes #2185
https://github.com/kubernetes/cloud-provider-openstack/pull/2865 makes the topology code easier (IMO) to grok, if anyone doubts my testing notes from https://github.com/kubernetes/cloud-provider-openstack/issues/2185#issuecomment-1488353753.
```release-note
NONE
```

[cinder-csi-plugin] Update ignore-volume-az docs

---

pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go
pkg/csi/cinder/nodeserver_test.go
pkg/csi/cinder/openstack/openstack_mock.go

This is a patch that came out of my work on https://github.com/kubernetes/cloud-provider-openstack/issues/2861. Currently, generation of the topology request for the Cinder Volume is logically separated from the generation of the topology request for the CSI Volume. This makes things harder to understand. Move some things around to resolve this and make everything a little easier to grok. This is kept separate from https://github.com/kubernetes/cloud-provider-openstack/pull/2862 since I don't expect we'll want to backport this.
n/a
I have a decoder of the logic embedded in the commit message. Hopefully this helps with review, but please don't assume the decoder itself is …

[cinder-csi-plugin] Rationalise all things topology

---

docs/keystone-auth/using-auth-data-synchronization.md

* The keystone auth sync doc contains a typo in one of the examples, which may lead to a non-working configuration. The fields were not following the specification on sync struct[1]
[1] https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/identity/keystone/sync.go#L54
```
Fix typo in the keystone authentication sync example docs, which led to a non-working configuration.
```

doc: fix typo in keystone sync example

---

pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go

This is currently backwards from what you'd expect when the value is `false`, with the topology information always being ignored for the Cinder requests but never ignored for the k8s CSI requests.
Modify the former so that we respect the 'availability' parameter when set - regardless of the value of `--with-topology` - and ensure that we never set topology requirements on the CSI Volume when `--with-topology=false`.
(none)
```release-note
The behavior of the `--with-topology` option for `cinder-csi-plugin` has changed.
Previously, when this was `false` and the `availability` parameter was set on a storage class, the `availability` parameter would be …
```

cinder-csi-plugin: Tweak behavior of --with-topology flag

---

charts/cinder-csi-plugin/Chart.yaml
charts/cinder-csi-plugin/values.yaml
charts/manila-csi-plugin/Chart.yaml
charts/manila-csi-plugin/values.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml

Bump the images to the latest version in both the manifests and Helm charts. Per https://github.com/kubernetes/cloud-provider-openstack/pull/3004#issuecomment-3377610731, this should resolve the issues we are seeing with https://github.com/kubernetes/cloud-provider-openstack/pull/3004 and allow us to merge that and cut a new release.
(none)
(none)
```release-note
NONE
```

[cinder-csi-plugin][manila-csi-plugin] Bump sidecar image versions
