kubernetes/cloud-provider-openstack

OWNERS

Adding dklyle to help review and maintain

---

OWNERS

Added hogepodge to OWNERS and alphabetized contributor list.
NONE
```NONE
```

Added hogepodge to OWNERS, alphabetized listing

---

Makefile
hack/update-gofmt.sh
hack/verify-gofmt.sh
hack/verify-golint.sh

* Run `make fmt` or `make lint` to run these
* Use hack/update-gofmt.sh to fix problems with fmt

Add code cleanup utils - gofmt and golint

---

OWNERS

Signed-off-by: Melvin Hillsman <mrhillsman@gmail.com>

mrhillsman volunteer as reviewer

---

Makefile
pkg/csi/cinder/controllerserver_test.go
pkg/csi/cinder/nodeserver_test.go
pkg/identity/keystone/authenticator.go
pkg/volume/cinder/attacher.go
pkg/volume/cinder/cinder_util.go
pkg/volume/cinder/provisioner/iscsi_test.go
pkg/volume/cinder/provisioner/rbd_test.go

Several tests had unused err variables. Removed them to fix `make vet fmt`
fixes #6 
```release-note
NONE
```

Fix make vet fmt

---

OWNERS

**What this PR does / why we need it**: 
Thanks very much.
```release-note
```

Add edisonxiang to review and collaborate

---

OWNERS

As asked in slack, here it is :)

add me to owners file

---

pkg/identity/keystone/authenticator.go
pkg/identity/keystone/authorizer.go
pkg/identity/keystone/keystone.go
pkg/identity/keystone/policy.go

This patch makes the code look better and conform to the standards of the go language.
1. All variables var_name were renamed to varName.
2. Comments were added for all public facing entities.
3. Entities that are not used outside of the module were declared as private.
4. Several small typos were fixed as well.

Prettify identity code

---

OWNERS

add rootfs as volunteer 
```release-note
NONE
```
@dims

add rootfs to OWNERS

---

OWNERS

/assign @dims 
```release-note
None
```

add dixudx to OWNERS

---

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go

Sync a couple of commits
70c2baaff8 fix isnotfound
97b4110d9f Stabilize openstack_test when running against real cloud

Update latest k/k - Mar 27

---

docs/using-cinder-standalone-provisioner.md

fix clound to cloud
```release-note
NONE
```

fix clound to cloud

---

.zuul.yaml

Signed-off-by: Melvin Hillsman <mrhillsman@gmail.com>

Update .zuul.yaml with correct job name

---

.zuul.yaml

- Add jobs trigger for triggering all the jobs by commenting "/retest" or "/test all" under a PR
- Add jobs trigger for triggering unit tests job by commenting "/test cloud-provider-openstack-unit" under a PR
- Add jobs trigger for triggering K8S+LBaaS(Octavia) scenario testing by commenting "/test cloud-provider-openstack-lb" under a PR
- Add jobs trigger for triggering K8S+keystone authentication/authorization scenario testing by comment "/test cloud-provider-openstack-auth" under a PR
```release-note
```

Add more testing scenarios jobs against K8S+OpenStack

---

docs/cloud-providers.md

from
https://github.com/kubernetes/website/blob/master/docs/concepts/cluster-administration/cloud-providers.md

copy doc from main repo

---

docs/using-cinder-csi-plugin.md

**What this PR does / why we need it**: Fix the path to the cinder sample.
```release-note
```

Fix the path to the cinder sample.

---

manifests/controller-manager/cloud-config
pkg/cloudprovider/providers/openstack/openstack.go
pkg/cloudprovider/providers/openstack/openstack_instances.go
pkg/cloudprovider/providers/openstack/openstack_routes.go
pkg/cloudprovider/providers/openstack/openstack_test.go

- allows to customize public network name
according to the cloud provider
- allows disabling ipv6 at config level
Fixes #89 #88
/assign @dims

Add support for networking opts

---

.zuul.yaml

We had our first e2e all green run here:
https://github.com/kubernetes/cloud-provider-openstack/pull/92#issuecomment-379556696

Add conformance e2e test pipeline

---

manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml

Fix #110 
Add pull policy for driver-registrar image to support local image built from latest source code

Add pull policy for driver-registrar image to support local image built from latest source code

---

.zuul.yaml

Add periodic jobs for E2E conformance tests
- test against kubernetes master
- test against kubernetes latest release(v1.10.0)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #103 
@dims 
```release-note
```

Add periodic jobs for E2E conformance tests

---

pkg/cloudprovider/providers/openstack/MAINTAINERS.md

since we are using OWNERS file we don't need this file

Remove unnecessary MAINTAINERS.md file

---

Makefile

We have had several problems:
- folks checking out to a random directory outside their GOPATH
- CI jobs checking out directory to github.com/kubernetes/xyz
both resulting in problems with build, problems updating dependencies, sometimes things work on the dev environment and fail in CI causing folks to scratch their heads.
So let's standardize on the best practice "this git repo should be checked out under $GOPATH/src/k8s.io" and enforce it. Makefile will bail out when the directory is not correct (either because we checked out to the wrong repo, bad symlinks or wrong PWD)

Enforce running Makefile from $DEST

---

.gitignore

Typo fix: commited->committed

---

examples/cinder-flexvolume/nginx.yaml

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #131 
```release-note
```

Add cinder flexvolume test example

---

.zuul.yaml

Add a job to check cinder flexvolume functionality for each PR.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes theopenlab/openlab#33
Depends on #130 #132 
```release-note
```

Add cinder flexvolume test job

---

examples/persistent-volume-provisioning/cinder/cinder-in-tree-full.yaml

Use default volume type in k8s cinder test

---

Gopkg.lock

Moving both the main k/k repo and this repo to latest

Switch to latest gophercloud

---

Gopkg.lock
Makefile

example:
`VERSION=0.1.0 make build-cross dist`
The command line above should build a bunch of tars and zips that can
be uploaded when we cut a release.
Code was borrowed from https://github.com/kubernetes/helm/blob/master/Makefile

Makefile targets for cross build and distributions

---

docs/cloud-providers.md
docs/using-cinder-csi-plugin.md
docs/using-cinder-standalone-provisioner.md

Typo fix: fix some word error

---

pkg/ingress/OWNERS

As the author of octavia-ingress-controller, I'm willing to maintain this folder and keep improving the controller.

Create OWNERS file in pkg/ingress

---

Makefile
cluster/images/octavia-ingress-controller/Dockerfile

Add octavia-ingress-controller image build task in Makefile
fixes #159

Add octavia-ingress-controller image build task in Makefile

---

docs/using-octavia-ingress-controller.md

octavia-ingress-controller doc is missing
**Which issue this PR fixes** :
fixes #149

Add doc for octavia-ingress-controller

---

.zuul.yaml

Thanks to Mohammed Naser <mnaser@vexxhost.com>
This reverts commit c4027dc07560fa5f460566d4a154bcf1beb5dc60.

Revert "Disable test-lb-octavia openlab job"

---

pkg/cloudprovider/providers/openstack/openstack_instances.go
pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
pkg/cloudprovider/providers/openstack/openstack_routes.go
pkg/cloudprovider/providers/openstack/openstack_volumes.go
pkg/volume/cinder/cinder.go

Sync a few commits from master that did not make it here yet

Sync latest master to cpo may 14

---

.zuul.yaml
cmd/client-keystone-auth/main.go
hack/verify-gofmt.sh
pkg/ingress/controller/controller.go

Add a new test to
* run gofmt checking
* checking normal typos
Depends on theopenlab/openlab-zuul-jobs#200
/assign dims
```release-note
add cloud-provider-openstack-format job
```

add cloud-provider-openstack-format job

---

docs/using-keystone-webhook-authenticator-and-authorizer.md

Improve the doc of k8s-keystone-auth

---

SECURITY_CONTACTS

Adding Security Contacts to Repositories under Kubernetes per request on kubernetes-dev from @jessfraz

Add SECURITY_CONTACTS for k/cpo

---

docs/using-keystone-webhook-authenticator-and-authorizer.md

Since kubectl v1.11 we will use "exec" [1]  mode to receive user tokens
from Keystone. This patch add documentation about how to configure
kubectl to be able to use this feature.
[1] https://kubernetes.io/docs/admin/authentication/#client-go-credential-plugins

Update Kubernetes webhook auth documentaion

---

Gopkg.lock
pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go

**What this PR does / why we need it**: We need possibility to specify connection limits instead of default ones
**Which issue this PR fixes**: fixes #184
```release-note
NONE
```

add possibility to specify connection limit in lbaas listener

---

.zuul.yaml

So that we can add it to release blocking dashboard!

Add a conformance job for 1.11 release branch

---

pkg/volume/util/util.go

Line 326: fromat->format
Line 665: to to->to

Typo fix fromat->format/to to->to

---

docs/using-keystone-webhook-authenticator-and-authorizer.md

It was a little difficult to understand what command I should run
as a webhook process. This adds the command name of the webhook
for easy understanding.
**Release note**: `NONE`.

Write the command name of webhook

---

docs/using-cinder-standalone-provisioner.md

Document cloning in the standalone-cinder provisioner

---

Makefile

It takes a while to fetch everything to the network,
it is nice to give a progress indication of what is
going on

make dep ensure verbose

---

docs/using-keystone-webhook-authenticator-and-authorizer.md

Sometimes we had questions how to configure keystone-webhook-auth
on ubuntu 16.04, because that is a little far from current doc
explanation. So this adds the sample configuration for ubuntu 16.04
users.

Add keystone-webhook-auth sample for ubuntu 16.04

---

cmd/client-keystone-auth/main.go

Fix authentication error for client-auth-plugin
fixes #240
With this patch, the client-keystone-auth could work the same with the traditional way. You can config the kubeconfig file as the following, you can use environment variables and don't need to add any params:
```yaml
users:
- name: openstackuser-clientauth
user:
exec:
command: "/home/ubuntu/client-keystone-auth"
apiVersion: "client.authentication.k8s.io/v1alpha1"
```
Then run `kubectl get pods`.
```release-note
```

Fix authentication error for client-auth-plugin

---

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go

Cascading delete loadbalancer resources for Octavia when deleting LoadBalancer type service.
fixes #264
Reasons to use cascading delete:
- Reduce API calls to Octavia from 10+ to only 1. More API calls means
more exception risk.
- Simplify the code logic
Tested on my k8s environment on top of OpenStack.
NONE

Cascading delete loadbalancer resources for Octavia

---

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go

**Which issue this PR fixes**: fixes #245
Tested with following yaml:
```
kind: Service
apiVersion: v1
metadata:
name: demoapp-lb1
spec:
loadBalancerIP: "10.222.134.126"
type: LoadBalancer
selector:
name: demoapp-test
ports:
- protocol: TCP
port: 80
targetPort: 5000
---
kind: Service
apiVersion: v1
metadata:
name: demoapp-lb2
spec:
type: LoadBalancer
selector:
name: demoapp-test
ports:
- protocol: TCP
port: 80
targetPort: 5000
---
kind: Service
apiVersion: v1
metadata:
name: demoapp-lb3
spec:
loadBalancerIP: "10.222.134.121"
type: LoadBalancer
selector:
name: demoapp-test
ports:
- protocol: TCP
port: 80
targetPort: 5000
```
Where demoapp-lb1 ip "10.222.134.126" did not exist in openstack project before 
demoapp-lb2 dynamic floating provisioning …

try to search floatingip first before creating it

---

pkg/cloudprovider/providers/openstack/openstack_instances.go

k/k https://github.com/kubernetes/kubernetes/pull/67982

implement InstanceShutdownByProviderID to openstack

---

CONTRIBUTING.md

Update contributing.md with link of getting started document.

Refer getting started document in contributing.md

---

docs/using-auth-data-synchronization.md
docs/using-client-keystone-auth.md

Improves documentation about Auth data synchronization between Keystone and Kubernetes

Improve docs about auth data syncronization

---

.zuul.yaml

- Fixup 1.11 as we have a release-1.11 branch
- Add new job for 1.12
Change-Id: Ida552559ad4dc130586654d666bdf347d8221720
```release-note
NONE
```

Add/Update more CI jobs

---

Gopkg.lock
manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml
pkg/csi/cinder/nodeserver.go

This PR Fixes CSI CI Tests, It updates driver registrar configurations and add NodeGetInfo, NodeGetCapabilties rpc calls
**Which issue this PR fixes** : fixes #297 
`NONE`.

Fix csi test

---

Gopkg.lock
Gopkg.toml
cmd/openstack-cloud-controller-manager/main.go
pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
pkg/csi/cinder/nodeserver_test.go
pkg/volume/cinder/attacher.go
pkg/volume/cinder/cinder.go
pkg/volume/cinder/cinder_util.go
pkg/volume/cinder/doc.go

- sync latest changes to cinder-csi
- pick up changes from: https://github.com/kubernetes-csi/drivers/tree/master/pkg/cinder
- pick up changes from main k/k repo
- update docker/docker and docker/distribution to newer versions

Update to latest 1.12 release dependencies

---

pkg/cloudprovider/providers/openstack/openstack_volumes.go
pkg/volume/cinder/attacher_test.go
pkg/volume/cinder/cinder.go
pkg/volume/cinder/cinder_test.go
pkg/volume/cinder/cinder_util.go

- https://github.com/kubernetes/kubernetes/commit/093e231289f8cfabe7cb18500b73c6b12606da80
- https://github.com/kubernetes/kubernetes/commit/8f7fcd5adc9c8fd8dfd6c932b76076c870af5487

Sync from Kubernetes master

---

cmd/client-keystone-auth/main.go

fix nits in client-keystone-auth

---

docs/using-cinder-csi-plugin.md

Add detail info about controller publish/unpublish
This doc does not have enough info.
Adding more description for someone who is familiar with
openstack but not with cloud provider.

Add detail info about controller public/unpublish

---

manifests/cinder-csi-plugin/csi-attacher-cinderplugin.yaml
manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml
manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml

Change-Id: I4d7f4781bdcb4b6427de1363c680d2fb21de2753
Let us be explicit about the path of the binary for the cinder-csi-plugin
fixes #306
```release-note
NONE
```

Fix up path to executable for cinder-csi-plugin

---

Gopkg.lock
Gopkg.toml

Change-Id: I9bb8a1bcb47a08bf76fa19e3a83ae38e30a6dbe1
```release-note
NONE
```

Update to Kubernetes 1.12.0 release

---

cmd/client-keystone-auth/main.go

This PR makes possibile to login using Keystone Application Credentials.
fixes #232 
This PR requires this gophercloud PR to be merged first 
https://github.com/gophercloud/gophercloud/pull/1224

Get a token using Keystone Application Credential

---

pkg/volume/cinder/attacher.go

Fix typos issue in attacher.go 
```release-note
NONE
```

Fix typos issue in attacher.go

---

pkg/ingress/controller/controller.go
pkg/ingress/controller/openstack/octavia.go

Support to specify backend service port name
fixes #309
```release-note
```

[Ingress] Support to specify backend service port name

---

docs/using-cinder-csi-plugin.md

This commit adds uniform command prompt.
This PR updates prompt as $ for uniformity with a little bit of explanation.
None.
None.
None.

Uniform command prompt

---

docs/using-manila-provisioner.md

Signed-off-by: Rui Cao <ruicao@alauda.io>

Typo fix: exisiting -> existing

---

Makefile

Change-Id: I33942bf37e03889c52a0215f39d1a4b5e264a7ff
```release-note
NONE
```

New url for golint

---

pkg/ingress/cmd/root.go
pkg/ingress/controller/controller.go
pkg/ingress/controller/openstack/octavia.go

Use batch members update operation to save the api calls to Octavia.
This PR doesn't fix any bug, just improve the node sync operation and some trivial fixes for the log.
```release-note
```

octavia-ingress-controller: Node sync improvement

---

Gopkg.lock
Gopkg.toml
pkg/cloudprovider/providers/openstack/openstack.go
pkg/cloudprovider/providers/openstack/openstack_instances.go
pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
pkg/cloudprovider/providers/openstack/openstack_routes.go
pkg/cloudprovider/providers/openstack/openstack_routes_test.go
pkg/cloudprovider/providers/openstack/openstack_volumes.go
pkg/volume/cinder/attacher_test.go
pkg/volume/cinder/cinder.go

Change-Id: Ie9c510c6901d2259aa9fff539403a13136ec3f62
```release-note
Update to kubernetes 1.13.0-alpha.1 version
```

Update to k/k 1.13.0-alpha.1 version

---

pkg/ingress/controller/openstack/octavia.go

Use TCP protocol when creating the listener and pool.
NONE

[Ingress] Use TCP protocol for the lb

---

pkg/ingress/controller/controller.go

Add event support for octavia-ingress-controller.
fixes #334
Following are the events happened during an ingress creation:
```
Events:
Type    Reason    Age   From                          Message
----    ------    ----  ----                          -------
Normal  Creating  1m    openstack-ingress-controller  Ingress default/test-octavia-ingress-full
Normal  Updated   4s    openstack-ingress-controller  Successfully associated IP address 172.24.4.14 to ingress default/test-octavia-ingress-full
Normal  Created   3s    openstack-ingress-controller  Ingress default/test-octavia-ingress-full
```
```release-note
Support ingress events in octavia-ingress-controller. …
```

[Ingress] Add event support

---

manifests/cinder-csi-plugin/csi-attacher-cinderplugin.yaml
manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml
manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml

csi provisioner, attacher and driver-registrar v0.3.0 image last updated 3 months back, we should run csi CI against latest attacher, provisioner, driver-registrar.
In the CI scripts, we are building against latest but not testing with the latest build.
`NONE`.
```release-note
```

Update CSI Manifests

---

docs/using-cinder-csi-plugin.md

CSIPersistentVolume and MountPropagation Feature gates are default
enabled from kubernetes v1.10, updating CSI docs for the same
Reference: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
`NONE`.
```release-note
```

Update CSI Docs

---

.zuul.yaml

Update zuul.yaml to run e2e Conformance tests on v1.12
None.
`NONE`.
````release-note
````

Run e2e Conformance tests on v1.12

---

Gopkg.lock
Gopkg.toml
pkg/cloudprovider/providers/openstack/openstack.go
pkg/cloudprovider/providers/openstack/openstack_volumes.go
pkg/csi/cinder/openstack/openstack_volumes.go
pkg/volume/cinder/volumeservice/actions.go

Change-Id: Ic00a00dd6bfe02939bbbab0bde4cafdec527ee32
Periodic update to the latest k/k milestone
```release-note
Update to Kubernetes milestone v1.13-beta.0
```

Update to v1.13.0-beta.0

---

docs/using-cinder-csi-plugin.md
pkg/csi/cinder/driver.go

This PR will add more doc about the controller capabilities ,user should know the 
capability of the csi controller ,e.g what's it can do 
N/A
N/A
no release notes needed because it's doc change

Add capabilities

---

pkg/csi/cinder/driver.go

It updates cinder csi driver name in domain name notation format, as suggested (not enforced )by CSI specs.
`NONE`.
```release-note
```

Update Cinder CSI Driver Name

---

examples/webhook/keystone-rbac.yaml

Fixes the template used for rbac for the webhook keystone auth
```release-note
NONE
```

Fixing rbac template.

---

hack/verify-gofmt.sh

per
https://github.com/kubernetes/kubernetes/blob/843a67b215dcfa1781820a797c4c759e42e81d3a/hack/verify-gofmt.sh#L52-L56
sync verify fmt scripts with k8s
per commit message
```release-note
NONE
```

update format check scripts

---

OWNERS

add as reviewer should be ok ? (Just +1/-1 ?)
```release-note
NONE
```

Add me (jichenjc) into reviewer

---

pkg/csi/cinder/mount/mount.go
pkg/csi/cinder/nodeserver.go
pkg/util/mount/mount_linux.go

**What this PR does / why we need it**: 
If don't use formatted output,fix logging calls 
```release-note
NONE
```

fix logging calls

---

OWNERS

Adds @chaosaffe to `OWNERS`
N/A
N/A
```release-note
NONE
```
/cc @dims
/assign @flaper87

Add @chaosaffe to OWNERS

---

examples/loadbalancers/README.MD

**What this PR does / why we need it**: The README is out of date compared to the yams file.
Fixes #346 
```release-note
```

Move loadbalancer annotation to service in README file

---

.zuul.yaml

```yaml
irrelevant-files:
- ^docs/.*$
- ^.*\.md$
- ^OWNERS$
- ^SECURITY_CONTACTS$
```
Fixes: kubernetes/cloud-provider-openstack#400
Signed-off-by: Melvin Hillsman <mrhillsman@gmail.com>
```release-note
```

Do not run jobs for changes to documentation

---

cluster/addons/rbac/cloud-controller-manager-roles.yaml

Fix cloud-controller-manager role name and add configmaps resource permission
```release-note
```

Fix cloud controller manager role

---

cluster/addons/rbac/cloud-controller-manager-roles.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml

Remove the dependency of KCM's kubeconfig file and modify the RBAC roles for CCM.
```release-note
```

Fix the ccm manifest file and RBAC definition

---

docs/using-controller-manager-with-kubeadm.md
manifests/controller-manager/kubeadm.conf

Update documentation using-controller-manager-with-kubeadm.
```release-note
```

Update doc: using-controller-manager-with-kubeadm

---

docs/using-cinder-csi-plugin.md

some guide on how to use the csi plugin in the doc
enhance the doc
```release-note
NONE
```

Add doc for csi cinder usage

---

Gopkg.lock
Makefile
cluster/images/barbican-kms-plugin/Dockerfile
cmd/barbican-kms-plugin/main.go
manifests/barbican-kms/encryption-config.yaml
manifests/barbican-kms/pod.yaml
pkg/kms/barbican/barbican.go
pkg/kms/barbican/fake_barbican.go
pkg/kms/client/client.go
pkg/kms/encryption/aescbc/aescbc.go
pkg/kms/encryption/aescbc/aescbc_test.go
pkg/kms/server/server.go
pkg/kms/server/server_test.go

This PR adds Feature to use Barbican as Key manager service for kubernetes
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #44
```release-note
```

Implement Barbican as KMS provider for kubernetes

---

docs/using-barbican-kms-plugin.md

Doucment to Install and Use barbican KMS plugin
`NONE`
```release-note
```

Add Document to Install and Use Barbican KMS Plugin

---

pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go
pkg/csi/cinder/driver.go
pkg/csi/cinder/fake.go
pkg/csi/cinder/openstack/openstack.go
pkg/csi/cinder/openstack/openstack_mock.go
pkg/csi/cinder/openstack/openstack_snapshots.go

Add snapshot function for csi including:
add snapshot
delete snapshot
list snapshot
add snapshot functions for csi cinder volume
not a bug fix
```
add snapshot csi functions, create-snapshot, delete-snapshot and list-snapshot are added 
```

[csi] add snapshot support

---

pkg/ingress/controller/controller.go

Variable name now reflects the nodes returned by the list predicate. Prevents confusion in the codebase.
N/A
xref: https://github.com/kubernetes/cloud-provider-openstack/pull/392#issuecomment-450656838
```release-note
NONE
```

Rename newNodes to readyWorkerNodes

---

pkg/ingress/controller/controller.go

Removes getNodeConditionPredicate() and passes the predicate func directly to ListWithPredicate()
Improves code readability and reduces code surface
None
None
```release-note
NONE
```

Use worker node predicate directly

---

docs/using-octavia-ingress-controller.md
pkg/ingress/controller/openstack/octavia.go

Use HTTP load balancing protocol for Ingress implementation.
fixes #412
```release-note
```

[octavia-ingress-controller] Use HTTP for loadbalancing protocol

---

cmd/barbican-kms-plugin/main.go
pkg/kms/barbican/barbican.go
pkg/kms/encryption/aescbc/aescbc.go
pkg/kms/server/server.go

Changes KMS packages from using glog to using klog
N/A
N/A
```release-note
NONE
```

Move kms packages to klog

---

cmd/client-keystone-auth/main.go
pkg/identity/keystone/token_getter.go
pkg/identity/keystone/token_getter_test.go

**What this PR does / why we need it**: `client-keystone-auth` supports client certificate with `OS_CERT` and `OS_KEY` options.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #366
```release-note
```

client-keystone-auth supports client certificates

---

pkg/ingress/controller/controller.go
pkg/ingress/controller/openstack/octavia.go

General code cleanup based on some linter runs. Specifically focused on:
- Error checking and logging
- Removing dead code
- Deduplication
N/A
None
```release-note
NONE
```

Sanitation on pkg/ingress/

---

pkg/ingress/config/config.go
pkg/ingress/controller/openstack/client.go

Add/change some options for octavia ingress controller configuration, make most of the options consistent with cloud-config, so it's easy to config octavia-ingress-controller together with openstack-cloud-controller-manager.
```release-note
```

Improve the cfg options for octavia ingress controller

---

Gopkg.lock
pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go

**What this PR does / why we need it**: we need implement proxy protocol support. Also this old `extensions/lbaas_v2` is [deprecated](https://github.com/gophercloud/gophercloud/pull/1323#issuecomment-438342506)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #449 
```release-note
openstack loadbalancer now supports PROXY protocol
```
Example:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: nginx-development
spec:
replicas: 1
template:
metadata:
labels:
run: web
spec:
containers:
- name: nginx
image: jesseh/nginx:1.13
ports:
- containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
labels:
run: web-ext …
```

Implement proxy protocol support for lbaas v2

---

pkg/cloudprovider/providers/openstack/openstack.go
pkg/cloudprovider/providers/openstack/openstack_instances.go
pkg/cloudprovider/providers/openstack/openstack_test.go
pkg/cloudprovider/providers/openstack/openstack_volumes.go
pkg/util/metadata/metadata.go
pkg/util/metadata/metadata_test.go

metadata is widely used inside this project such as cloudprovider
and later on CSI or others, so move it to a common base will
be helpful to follow up usage
move metadata to util then we can reuse it later
```release-note
None
```

mv metadata to util

---

pkg/csi/cinder/driver.go
pkg/csi/cinder/fake.go
pkg/csi/cinder/mount/mount.go
pkg/csi/cinder/mount/mount_mock.go
pkg/csi/cinder/nodeserver.go
pkg/csi/cinder/nodeserver_test.go
pkg/csi/cinder/utils.go

This PR adds NodeStageVolume and NodeUnstageVolume capability to nodeserver.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #301 #473 
```release-note
```

Add STAGE_UNSTAGE_VOLUME node capability

---

pkg/ingress/controller/controller.go

Allow the k8s user choose to create internal or external Ingress by speficying an annotation `octavia.ingress.kubernetes.io/internal`, if it's true, the load balancer created in Octavia won't have floating IP associated. The default value is true.
```release-note
```

[octavia-ingress-controller] Support internal/external Ingress

---

pkg/cloudprovider/providers/openstack/openstack.go
pkg/cloudprovider/providers/openstack/openstack_instances.go
pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
pkg/csi/cinder/openstack/openstack.go
pkg/csi/cinder/openstack/openstack_volumes.go
pkg/ingress/controller/openstack/client.go
pkg/ingress/controller/openstack/neutron.go
pkg/ingress/controller/openstack/octavia.go
pkg/util/errors/errors.go

a set of isNotFound function exist in the pkg folder
This PR combine them and remove duplidated function defintion
```release-note
```

merge isNotFound inside cloud provider

---

pkg/csi/cinder/openstack/openstack.go
pkg/csi/cinder/openstack/openstack_test.go

currently, openstack client created in csi, doesn't support ca-file parameter . This PR is to update the same.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #498 #499
```release-note
```

support ca-file parameter in CSI

---

pkg/ingress/controller/controller.go
pkg/ingress/controller/openstack/neutron.go

Improve floating IP management in octavia-ingress-controller. Adds the method `EnsureFloatingIP` to handle adding and deleting floating IP for the Neutron port, just like the way security group is managed.
```release-note
```

[octavia-ingress-controller] Improve floating IP management

---

docs/using-octavia-ingress-controller.md

Make octavia-ingress-controller up to date.
```release-note
```

octavia-ingress-controller document

---

docs/using-octavia-ingress-controller.md

Fix two typos in the documentation
```release-note
```

Fix typo in documentation

---

pkg/ingress/controller/controller.go

This fixes typo of CIDR.
```release-note
NONE
```

Trivial: Fix typo of CIDR

---

docs/using-octavia-ingress-controller.md
pkg/ingress/config/config.go

This PR changes the argument format for the octavia ingress controller from snake case to kebab case to match the other argument formats in order to provide a consistent user experience.
fixes #519
```release-note
*Action required* Changed argument format for octavia ingress controller to kebab case
```

Change octavia ingress arguments from snake case to kebab case

---

Gopkg.lock
Gopkg.toml
cmd/barbican-kms-plugin/main.go
cmd/cinder-provisioner/main.go
cmd/client-keystone-auth/main.go
cmd/k8s-keystone-auth/main.go
cmd/openstack-cloud-controller-manager/main.go
pkg/cloudprovider/.import-restrictions
pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/mount/mount.go
pkg/share/manila/shareoptions/shareoptions.go
pkg/volume/cinder/attacher.go
pkg/volume/cinder/cinder.go
pkg/volume/cinder/cinder_block.go
pkg/volume/cinder/cinder_test.go
pkg/volume/cinder/cinder_util.go

Change-Id: Ief4b32f526ad49b2dfe588e2d2eec32f015cb4af
```release-note
NONE
```

Switch to Kubernetes v1.14.0-beta.1 and fix stale imports

---

pkg/csi/cinder/identityserver.go
pkg/csi/cinder/openstack/openstack.go

Add CSI identity CSI so that we can return CSI status back
fixes: #483 
some discussion might be considered , whether we need create a client to auth or use cinder to do some query etc...
```release-note
```

Add probe for CSI

---

Gopkg.lock

Fix gophercloud digest in Gopkg.lock
-->
```release-note
None
```

Fix gophercloud digest in Gopkg.lock

---

cmd/cinder-csi-plugin/main.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #539 
```release-note
```

initialize explictly to enable verbose option

---

Gopkg.lock
Gopkg.toml

Update kubernetes to latest release v1.14
```release-note
```

Update to k/k 1.14

---

docs/using-cinder-csi-plugin.md

Added Snapshot Example in Cinder CSI Docs
Updates  CSI Documentation for Snapshot Feature
`NONE`
```release-note
```

Add snapshot example in CSI doc

---

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go

Ignore the load balancers in deleting or deleted status when doing query from load balancing service.
fixes #576
```release-note
```

Do not get load balancers in deleted or deleting status

---

Gopkg.lock
Gopkg.toml
pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/nodeserver.go

update CSI to 1.1.0
```release-note
```

upgrade CSI to 1.1.0

---

docs/using-cinder-csi-plugin.md

Update CSI doc, as per new yaml
```release-note
```

Update CSI Doc as per New yamls

---

Makefile
docs/using-cinder-csi-plugin.md

Add test-csi-sanity target in Makefile
```release-note
```

Add CSI sanity target in Make

---

release-procedure.md

This PR, adds release procedure for cloud provider openstack repo.
```release-note
```

Add release procedure

---

docs/using-client-keystone-auth.md

It adds documentation for the changes pushed in #282

Improve Keystone Application Credential docs

---

pkg/cloudprovider/providers/openstack/openstack_routes.go

ref#https://github.com/kubernetes/kubernetes/pull/78250
```release-note
NONE
```

klog format error,follow kubernetes/kubernetes/pull/78250

---

cluster/images/cinder-csi-plugin/Dockerfile

fixing issue #592 
**Which issue this PR fixes** : 
fixes # 592

adding eudev to alpine image for udevadm

---

pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go
pkg/csi/cinder/fake.go
pkg/csi/cinder/openstack/openstack.go
pkg/csi/cinder/openstack/openstack_mock.go
pkg/csi/cinder/openstack/openstack_volumes.go
pkg/csi/cinder/sanity/fakecloud.go

Removing Volume Wrapper, directly using gophercloud wrapper
```release-note
```

Refactor CSI code

---

docs/using-auth-data-synchronization.md
pkg/identity/keystone/sync.go
pkg/identity/keystone/sync_test.go
pkg/identity/keystone/syncconfig.yaml

This pr implement https://github.com/kubernetes/cloud-provider-openstack/issues/577 issue.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #577
```release-note
```

k8s-keystone-auth:add projects_name_black_list parameter for sync namespace exclude project name

---

OWNERS

This PR is to add me as reviewer
My contributions : https://github.com/search?q=reviewed-by%3Aramineni+org%3Akubernetes+-author%3Aramineni
https://github.com/search?q=is%3Apr+author%3Aramineni+org%3Akubernetes 
```release-note
```

Add ramineni as reviewer to OWNERS file

---

docs/using-cinder-csi-plugin.md

1) the storage.k8s.io/v1 is out , we can use instead of storage.k8s.io/v1alpha
2) update the doc according to recently update
```release-note
```

enhance CSI doc

---

docs/using-magnum-auto-healer.md
manifests/magnum-auto-healer/magnum-auto-healer.yaml
pkg/autohealing/healthcheck/plugin_endpoint.go
pkg/autohealing/healthcheck/plugin_nodecondition.go

This PR changes the health check config options format for magnum-auto-healer from snake case to kebab case in order to provide a consistent user experience.
**Which issue this PR fixes***:

magnum-auto-healer: Change health check plugin options from snake case to kebab case

---

pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/identityserver.go
pkg/csi/cinder/nodeserver.go
pkg/csi/cinder/openstack/openstack.go
pkg/csi/cinder/openstack/openstack_mock.go
pkg/csi/cinder/sanity/fakecloud.go
pkg/csi/cinder/sanity/fakemount.go
pkg/csi/cinder/sanity/sanity_test.go

Fixed most of the csi-sanity tests
only 8 failures remaining that are related with validated volume capabilities and list snapshots,
A followup PR will be created for remaining failures, validated volume capabilities needs to be implemented, and list snapshots is the tricky one,
```release-note
`NONE`
```

Fixing CSI Sanity tests

---

OWNERS

contributions
https://github.com/search?q=is%3Apr+author%3Aadisky+org%3Akubernetes
https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=SIG%20Cloud%20Provider&var-country_name=All
```release-note
```
`NONE`

Add adisky as approver to owners file

---

.gitignore

Add magnum-auto-healer binary to gitignore

---

docs/using-cinder-csi-plugin.md

1) add a tip on where to run CSI
2) adjust the location of snapshot examples
```release-note
```

Add additional doc update for CSI doc

---

Gopkg.lock
Gopkg.toml
cmd/openstack-cloud-controller-manager/main.go
pkg/volume/cinder/attacher.go
pkg/volume/cinder/cinder.go
pkg/volume/cinder/cinder_test.go

This PR updates to latest kubernetes release 1.15.0
`NONE`
```release-note
```

Update to k/k 1.15.0

---

manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-nodeplugin-manilaplugin.yaml
manifests/manila-provisioner/deployment.yaml
manifests/provisioner/deployment.yaml
manifests/webhook/k8s-keystone-auth-ds.yaml
manifests/webhook/k8s-keystone-auth-pod.yaml

pinned images to v1.15 for release branch v1.15 to avoid version compatibility issues
https://github.com/kubernetes/cloud-provider-openstack/issues/431
```release-note
```
`NONE.`

Update manifests to v1.15 images

---

docs/using-cinder-csi-plugin.md

list-volumes
create-snapshot
list-snapshots
delete-snapshot
are covered by using csc tools.
```release-note
```

Add additional doc for CSI command:

---

.zuul.yaml

Add v1.15 release job and remove v1.12 job
```release-note
```

Add v1.15 release job and remove v1.12 job

---

examples/cinder-csi-plugin/nginx.yaml
examples/cinder-csi-plugin/snapshot/example.yaml
examples/cinder-csi-plugin/topology/example.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml

This commit is to update csi sidecars to latest versions
```release-note
```

Update sidecar to latest versions

---

Gopkg.lock
docs/using-octavia-ingress-controller.md
pkg/ingress/controller/controller.go

Ingress resources in extensions/v1beta1 are deprecated and will be
removed in v1.18, it is updated to  networking.k8s.io/v1beta1.
```release-note
```
`NONE`

Update Ingress Resource API version

---

.zuul.yaml

This commit makes sure not to run test jobs which irrelavent while
updating .gitignore
```release-note
```

Don't run jobs when .gitignore is updated

---

.gitignore

Add manila-csi-plugin binary to gitignore
```release-note
```
`NONE`

trivial: Add manila-csi-plugin to .gitignore

---

cluster/images/cinder-csi-plugin/Dockerfile

This PR updates base image to debian 
Motivation:
Officilally supported distro by kubernetes and recommended .
Some of the functionalities like resize doesnt work properly on Alpine.
```release-note
```

Update base image to debian

---

pkg/csi/cinder/nodeserver.go

This PR returns precise error info, specify exact missing
arguments from request.
```release-note
```

Return Precise Error Info NodePublishVolume

---

pkg/autohealing/cloudprovider/openstack/provider.go

Wait for the server to be powered off before updating the Heat stack, otherwise, the update operation could fail because of interface detach failure.
**Which issue this PR fixes**: fixes #696
```release-note
```

magnum-auto-healer: Ensure the server is powered off before updating the Heat stack

---

pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go
pkg/csi/cinder/sanity/fakecloud.go

this decrease the sanity error check failure to 5
```release-note
```

Fix sanity test (part)

---

pkg/cloudprovider/providers/openstack/openstack_instances.go

https://github.com/kubernetes/cloud-provider/blob/master/cloud.go#L139
don't have this anymore
```release-note
```

remove ExternalID function

---

docs/using-cinder-csi-plugin.md

This PR adds documentation for volume resize feature.
```release-note
NONE
```

Add documentation for Resize feature

---

.zuul.yaml

This PR skips conformance jobs to run on every PR and to run only on cloudprovider changes.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #699 
```release-note
```

Run conformance jobs only on cloudprovider changes

---

cmd/cinder-csi-plugin/main.go

given error info by default to make admin/user easier to find
where's wrong settings
fixes #659 
```release-note
```

provide error log by default

---

pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/nodeserver.go

Wrapped all CSI errors to status.Error()
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #717 
None.
```release-note
NONE.
```

Wrap Errors Cinder CSI

---

docs/expose-applications-using-loadbalancer-type-service.md
docs/getting-started-provider-dev.md

Add creating service by specifying a floating IP example.
Give explanation for service annotations.
Approve doc.
```release-note
```

Add creating service by specifying a floating IP example

---

README.md

Since all cloud-provider-* sigs dissolved into sig-cloud-provider, 
slack channel has been renamed to `provider-openstack`
```release-note
```

Update slack channel link

---

.zuul.yaml
Gopkg.lock
Gopkg.toml
cmd/openstack-cloud-controller-manager/main.go
pkg/csi/cinder/mount/mount.go
pkg/csi/cinder/mount/mount_mock.go
pkg/csi/cinder/nodeserver.go
pkg/csi/cinder/sanity/fakemount.go
pkg/share/manila/manila_test.go
pkg/share/manila/provisioner.go
pkg/share/manila/share.go
pkg/share/manila/shareoptions/openstackoptions.go
pkg/share/manila/shareoptions/shareoptions.go
pkg/volume/cinder/cinder.go
pkg/volume/cinder/provisioner/iscsi.go
pkg/volume/cinder/provisioner/iscsi_test.go
pkg/volume/cinder/provisioner/mapper.go
pkg/volume/cinder/provisioner/mapper_test.go
pkg/volume/cinder/provisioner/mapperbroker.go
pkg/volume/cinder/provisioner/provisioner.go
pkg/volume/cinder/provisioner/provisioner_test.go
pkg/volume/cinder/provisioner/rbd.go
pkg/volume/cinder/provisioner/rbd_test.go
pkg/volume/cinder/provisioner/testutils_test.go

Update to k/k v1.16.0-beta.1

---

pkg/cloudprovider/providers/openstack/openstack_volumes.go

Add capability to use Cinder V3 online resize feature: https://docs.openstack.org/cinder/rocky/contributor/api_microversion_history.html#id40
Cinder CSI plugin already introduced this feature, however not in the built-in plugin.
* You have to enable `allowVolumeExpansion: true` in the storage class.
* You have to enable the `ExpandInUsePersistentVolumes=true` feature gate in the kube-controller-manager
This PR depends on https://github.com/kubernetes/kubernetes/issues/82319, which allows kubelet to poll new block device geometry note**:
```release-note …
```

Allow cinder volume live resize

---

pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go

Implement Volume Capabilities
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #636 
Currently we are advertising one mode only, `csi.VolumeCapability_AccessMode_SINGLE_NODE_WRITER`, so we are validating only this capability in `ValidateVolumeCapabilities`, but cinder can support multi attach in RO/RW mode, we need to add support for this later.
```release-note
```
`NONE`

Implement ValidateVolumeCapabilities

---

docs/using-octavia-ingress-controller.md

Add Requirements and Caveats description for octavia-ingress-controller

octavia-ingress-controller: [doc] Add Requirements and Caveats

---

docs/using-cinder-csi-plugin.md

Update compatibility matrix for cinder CSI

---

manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml

This commit updates sidecar images to latest versions
```release-note
```

Update sidecar image versions

---

manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
manifests/provisioner/deployment.yaml
manifests/webhook/k8s-keystone-auth-pod.yaml

update docker image version in manifests to v1.16
```release-note
NONE
```

Update docker image version

---

docs/expose-applications-using-loadbalancer-type-service.md

Add document for `loadBalancerSourceRanges` support for creating Service.

occm: Add doc for loadBalancerSourceRanges support

---

.zuul.yaml
README.md
docs/using-cinder-standalone-provisioner.md

Deprecate standalone cinder
```release-note
```

Deprecate Standalone cinder

---

pkg/share/manila/OWNERS

Ownership for Manila CSI driver
```release-note
NONE.
```

Add OWNERS for manila CSI driver

---

pkg/share/manila/OWNERS

**What this PR does / why we need it**: Update the new manila share OWNERS file with the current active set.
```release-note
```

Update share OWNERS file

---

docs/using-octavia-ingress-controller.md

It allows others to deploy octiava with the correct configurations
Documentation / the template  ConfigMap octavia-ingress-controller-config for the latest octavia-ingress-controller image
Current template will fail as the old value with the latest build.

Update octavia config

---

pkg/csi/cinder/mount/mount.go
pkg/flexvolume/cinder_util.go

fix golint failures

---

OWNERS

This PR is add ramineni to approvers list.
My contributions include : 
https://github.com/search?q=is%3Apr+author%3Aramineni+org%3Akubernetes
https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=SIG%20Cloud%20Provider&var-country_name=All
And also I'm the author of the multiple features in CSI to get the driver in-par with intree and one of the maintainer of gate to make sure its always green :)
```release-note
```

Add ramineni to approvers

---

OWNERS

Add chrigl as approver, chrigl has been active in this project from long with currently leading the efforts of cloud provider migration, also they are the active users of this project.
cc @chrigl 
https://github.com/search?q=is%3Apr+author%3Achrigl+org%3Akubernetes
https://github.com/search?q=org%3Atheopenlab+is%3Apr+author%3Achrigl+org%3Aopenlab&unscoped_q=is%3Apr+author%3Achrigl+org%3Aopenlab
```release-note
NONE
```

Add chrigl as a approver

---

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go

Support UDP loadbalancing with Octavia. This should also work with mixed protocols, as soon as supported in k/k. See #603 
Fixed: #834
```release-note
```

Implemented UDP support for Octavia LB

---

manifests/webhook/k8s-keystone-auth-ds.yaml
manifests/webhook/k8s-keystone-auth-pod.yaml

the current manifest is not align with doc and example,
update this and later patch will update doc accordingly.
```release-note
```

fix webhook manifests

---

docs/using-cinder-csi-plugin.md

Inline Volume support PR is in progress, it adds doc for the same
```release-note
```
`NONE`

Document for Inline Support

---

manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
manifests/manila-provisioner/deployment.yaml
manifests/provisioner/Makefile
manifests/provisioner/deployment.yaml
manifests/webhook/k8s-keystone-auth-ds.yaml
manifests/webhook/k8s-keystone-auth-pod.yaml

This PR updates manifests to use v1.17.0 image .
```release-note
NONE
```

Update manifests to use 1.17.0 image

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Improve the issue and PR template.
```release-note
NONE
```

Improve the issue and PR templates

---

docs/using-cinder-csi-plugin.md

fixes #
```release-note
NONE
```

[cinder-csi-plugin]: add additional info for CSI doc

---

OWNERS

Removing myself from OWNERS as I am no longer actively participating
```release-note
NONE
```

Remove chaosaffe from OWNERS

---

CONTRIBUTING.md

https://github.com/kubernetes/cloud-provider-openstack/issues/890
fixes #
```release-note
NONE
```

update link of cloud-provider-openstack sig

---

pkg/ingress/controller/controller.go

Small rewrite of comment that earlier had a typo in it.
```release-note
NONE
```

Rewrite IngressClass comment

---

examples/mysql-cinder-pd/README.md

NONE
fixes #
```release-note
NONE
```

repair url in mysql-cinder-pd

---

docs/using-keystone-webhook-authenticator-and-authorizer.md
examples/webhook/keystone-policy-configmap.yaml
manifests/webhook/k8s-keystone-auth-ds.yaml
manifests/webhook/k8s-keystone-auth-pod.yaml

fixes #
```release-note
NONE
```

modify webhook doc

---

examples/cinder-csi-plugin/clone/example-clone.yaml
examples/cinder-csi-plugin/clone/sc.yaml
examples/cinder-csi-plugin/clone/source-pvc.yaml
pkg/csi/cinder/controllerserver.go
pkg/csi/cinder/controllerserver_test.go
pkg/csi/cinder/driver.go
pkg/csi/cinder/fake.go
pkg/csi/cinder/nodeserver.go
pkg/csi/cinder/nodeserver_test.go
pkg/csi/cinder/openstack/openstack.go
pkg/csi/cinder/openstack/openstack_mock.go
pkg/csi/cinder/openstack/openstack_volumes.go
pkg/csi/cinder/sanity/fakecloud.go

This PR adds support for cloning in cinder CSI driver
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #644
```release-note
Volume Cloning support added for Cinder CSI driver
```

CinderCSI: Add cloning support

---

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go

Delete the floating IP only if it was created dynamically by the controller manager.
The openstack-cloud-controller-manager now supports to specify an existing floating IP in `Spec.LoadBalancerIP` field, but that IP address is deleted by openstack-cloud-controller-manager when the Service is deleted which is not the expected behavior.
fixes #
```release-note
NONE
```

[openstack-cloud-controller-manager] Delete the floating IP only when needed

---

OWNERS
pkg/cloudprovider/providers/openstack/OWNERS

Since i do not have time to maintain this separate repo, remove myself from both reviewer and approver lists in order not to block the reviewing process.
Sorry for all the guys whose PRs are blocked because of my late reply
```release-note
NONE
```

Remove myself from the maintainer list

---

docs/using-manila-csi-plugin.md

This PR improves the docs by bringing some more details about the handling of AZs / topology in CSI Manila.
* Added a note about Manila providing a default AZ if `availability` volume parameter is empty
* Added a diagram illustrating the fact that if a share provisioned into some Manila AZ is not equally accessible from all nodes of the cluster, the admin must specify which compute AZs are able to access this storage. This should hopefully dissolve confusion about when to use which (`availability` or topology awareness)
* Path to topology examples was wrong
```release-note
NONE
```
/cc @ramineni @tsmetana @tombarron @gouthampacha

[manila-csi-plugin] improvements for docs regarding AZs / topology

---

pkg/autohealing/cloudprovider/openstack/provider.go

When there are volumes attached on nodes, the auto healing action
will fail because the node has been powered off. This patch fixes
it by detaching volumes before power-off the node.
fixes #1070 
```release-note
[magnum-auto-healer] Detaching volumes before power-off nodes when doing auto-healing.
```

[magnum-auto-healer] Detaching volumes before power-off nodes

---

docs/using-openstack-cloud-controller-manager.md

update some doc for additional tips which is easy to make mistake
fixes #
```release-note
NONE
```

[occm] update doc for some easy to miss parts

---

docs/using-cinder-csi-plugin.md

Fixes minor typo
```release-note
NONE
```

[docs] Fix typo in header

---

OWNERS
docs/getting-started-provider-dev.md

Cleans up out of date references
```release-note
NONE
```

Cleanup old references in owners and docs.

---

docs/developers-csi-manila.md
docs/expose-applications-using-loadbalancer-type-service.md
docs/getting-started-provider-dev.md
docs/migrate-to-ccm-with-csimigration.md
docs/using-auth-data-synchronization.md
docs/using-barbican-kms-plugin.md
docs/using-cinder-csi-plugin.md
docs/using-client-keystone-auth.md
docs/using-keystone-webhook-authenticator-and-authorizer.md
docs/using-magnum-auto-healer.md
docs/using-manila-csi-plugin.md
docs/using-octavia-ingress-controller.md
docs/using-openstack-cloud-controller-manager.md

update doc format
fixes #
```release-note
NONE
```

[all][doc] Adjust doc by using doctoc tool

---

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go

cherry-pick #1055 fix in release-1.18 branch
fixes #1162 
```release-note
NONE
```

fix nil pointer dereference in create loadbalancer func (#1055)

---

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go

Cherry pick from #1198
fixes #
```release-note
NONE
```

[occm] Fix bug where pointer from local loop variable instead of array variable is used

---

docs/using-keystone-webhook-authenticator-and-authorizer.md

Fix something in the doc.
fixes #
```release-note
NONE
```

[k8s-keystone-auth] Improve doc

---

go.sum
pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go

Adding some missing logs for level 2.
fixes #
```release-note
NONE
```

[occm] Adding some log (level 2)

---

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go

All the currently maintained binaries are:
* openstack-cloud-controller-manager (occm)
There is currently a difference between `deleteListeners` in `ensureOctaviaLoadBalancer` and the implementation in `ensureLoadBalancerDeleted`. The implementation in `ensureLoadBalancerDeleted` also deletes pool members. As this is not required, because a pool deletion also deletes all members (and it does it considerable faster), I would suggest reusing the `deleteListeners` method. This will speed up loadbalancer deletion in case Neutron LBaaS v2 is used.
```release-note
NONE
```
<sub>Stefan Büringer <stefan.bueringer@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub …

[occm] reuse deleteListeners in EnsureLoadBalancerDeleted

---

docs/using-octavia-ingress-controller.md
pkg/ingress/controller/controller.go

Support Ingress v1 spec. Improve the doc a little bit.
extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+
fixes #
```release-note
NONE
```

[octavia-ingress-controller] Support Ingress v1

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
pkg/cloudprovider/providers/openstack/openstack.go

[occm]: add support for "tls-insecure", "trustee-id" and "trustee-password" options

---

docs/keystone-auth/using-client-keystone-auth.md

Fixes broken link.
fixes # N/A
```release-note
NONE
```

[docs] Fix broken link in Keystone docs

---

pkg/autohealing/cloudprovider/openstack/provider.go

fixes #1333 
```release-note
[magnum-auto-healer] Fix magnum-auto-healer restart issue
```

[magnum-auto-healer] Fix autohealer restart issue

---

docs/cinder-csi-plugin/examples.md

documentation example
fixes #1141 
```release-note
disaster recovery example of cinder-csi-plugin PVC recovery
```

[cinder-csi-plugin] Example of Cinder CSI PVC Recovery

---

docs/metrics.md

[occm] add metrics documentation

---

pkg/autohealing/cloudprovider/openstack/provider.go
pkg/autohealing/cloudprovider/register/register.go

Fix k8s master node auto repair if the node is volume-based.
fixes #1446 
```release-note
[magnum-auto-healer] Fixed an issue that k8s master node repair failed when the node is boot from volume.
```

[magnum-auto-healer] Fix k8s master node repair if it's volume-based

---

pkg/autohealing/cloudprovider/register/register.go

Fix a bug introduced in a cherry pick.
fixes #
```release-note
NONE
```

[magnum-auto-healer] Fix undefined param

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md

Signed-off-by: maoyangLiu <liumaoyang@inspur.com>
[occm] Fix the outdate link in using-openstack-cloud-controller-manager.md

fix the outdate  link in  using-openstack-cloud-controller-manager.md 

---

pkg/autohealing/cloudprovider/openstack/provider.go
pkg/autohealing/config/config.go
pkg/autohealing/controller/controller.go
pkg/autohealing/healthcheck/healthcheck.go

There are several changes in this commit:
1) Fix the duplicated repair actions
2) Change default health check period from 30s to 60s
(cherry picked from commit db60e005ce04ecccf84bcaa9140182dbf7ab8fb7)
fixes #1529
```release-note
[magnum-auto-healer] Fix duplicated auto-healing actions and the default health check period is changed from 30s to 60s.
```

[magnum-auto-healer] Fix duplicated repair action (#1530)

---

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md

update documentation, since #1431, the url has changed
```release-note
NONE
```
Signed-off-by: Thorsten Schifferdecker <ts@systs.org>

[occm] update url - moving CCM to manifests/

---

.github/workflows/pr.yaml

Chart linter is broken, lets fix it.
fixes #
```release-note
NONE
```

Fix chart linter

---

OWNERS
SECURITY_CONTACTS
pkg/openstack/OWNERS

Thanks you all for still keeping me around! still! 
Signed-off-by: Davanum Srinivas <davanum@gmail.com>

Drop dims from OWNERS etc.

---

pkg/openstack/loadbalancer.go

As ensureLoadBalancer deferes to ensureOctaviaLoadBalancer for the octavia use case right away we can remove all references to octavia specific code in ensureLoadBalancer. This code is not used anymore.
Signed-off-by: Fabian Ruff <fabian.ruff@sap.com>
Remove unused code
```release-note
NONE
```

[occm] remove unused code

---

pkg/csi/cinder/controllerserver_test.go

fixes #
```release-note
NONE
```

[cinder-csi-plugin]Add UT for create volumes with volume type and az

---

pkg/openstack/instances.go

instanceV2 need those functions, to avoid write stuffs in 2 different functions
consolidate them and use one path for both v1/v2
fixes #
```release-note
NONE
```

[OCCM]refactory code to prepare instance V2 implementation

---

pkg/openstack/loadbalancer.go

This patch introduces names for listener, pools and monitors during creating in
`createFullyPopulatedOctaviaLoadBalancer`.
Those names are currently missing or different to the names during updates.
fixes #1965
```release-note
NONE
```

[occm] Fix Naming of listener, pools and monitors during Creation

---

pkg/openstack/loadbalancer.go

This patch introduces the usage of the /healthz Endpoint in the monitor.
Documentation for this is hard to find, but you can see in the kubernetes
repository
https://github.com/kubernetes/kubernetes/blob/26842bb0c8fcf89885798a2ebd9a97cd104e78bf/staging/src/k8s.io/cloud-provider/service/helpers/helper.go#L87
that /healthz is the prefered endpoint here.
I did not create a issues for this, since it is not really a bug or a feature, but I can, if needed.
I did not touch the legacy code not necessary for octavia load balancer.
```release-note
NONE
```

[occm] Use healthz Endpoint in HTTP Monitor

---

pkg/util/openstack/network.go

OpenStack does not support creation of floating IPs
with IPv6. However, it's still possible to exist external
networks with IPv6 Subnets, which could break the creation
of Floating IPs for a load-balancer if CCM uses it.
This commit avoids this issue by making sure only external
networks with IPv4 Subnets are used when creating a Floating IP.
**Which issue this PR fixes(if applicable):**
fixes https://github.com/kubernetes/cloud-provider-openstack/issues/1993
```release-note
NONE
```

[occm] Skip External network with IPv6 for FIPs creation

---

docs/developers-guide.md

Add initial documentation on running unit and e2e tests. This needs to be
expanded out more but tbh the infrastructure isn't really there for users to
run this stuff manually yet.
(Side note: How *are* people doing this? Are they using a private GCE project
or simply relying on CI for all testing?)
N/A
N/A
```release-note
NONE
```

[docs] Add docs on running tests

---

pkg/util/openstack/network.go

When attempting to fetch an external Network with IPv4 Subnets to
create a Floating IP, it's possible that no Subnets from that Network
are shared with the tenant, consequently it would not be possible to
filter them by IPVersion and no Network would be used. This commit
improve the detection of external Network by only allowing usage of
Networks that is possible to detect at least one IPV4 Subnet or that
is not possible to detect any info about the Subnets.
fixes #2015
```release-note
NONE
```

[occm]  Improve retrival of external Network

---

pkg/util/openstack/network.go

#2014 
When attempting to fetch an external Network with IPv4 Subnets to
create a Floating IP, it's possible that no Subnets from that Network
are shared with the tenant, consequently it would not be possible to
filter them by IPVersion and no Network would be used. This commit
improve the detection of external Network by only allowing usage of
Networks that is possible to detect at least one IPV4 Subnet or that
is not possible to detect any info about the Subnets.
#1992 
OpenStack does not support creation of floating IPs
with IPv6. However, it's still possible to exist external
networks with IPv6 Subnets, which could break the creation
of Floating IPs for a load-balancer if CCM uses it.
This commit avoids this issue by making sure only external …

[occm] cherrypick: LB - Fix floating ip subnet detection and ipv6 handling

---

pkg/openstack/loadbalancer.go

When aforementioned option is set to `false` on the Service `.spec`, the
NodePorts stop being allocated and set for that Service, effectively
defaulting all `.spec.ports[*].nodePort` to 0. Similar situation happens
with `healthCheckNodePort`. When cloud provider tries to create a member
or SG with such a port, Octavia fails.
This commit makes sure we are not adding members when `nodePort` value
is 0. We also omit the SG manipulations for such ports.
It's to make sure we are not making requests to Octavia that it cannot fulfill.
fixes #1996
```release-note
NONE
```

[occm] Protect from `AllocateLoadBalancerNodePorts=false`

---

pkg/openstack/loadbalancer.go

We need somekind of way to see the real ip address especially when using hostname annotation
fixes https://github.com/kubernetes/cloud-provider-openstack/issues/2095
```release-note
NONE
```

[occm] add annotation for real loadbalancer address

---

OWNERS

Add dulek and mdbooth as reviewers

---

docs/barbican-kms-plugin/using-barbican-kms-plugin.md

This PR updates the `barbican-kms-plugin` documentation.
As noted by @jichenjc in #2188 the Barbican KMS plugin documentation needed some updates. This is a rewrite of the later half of the documentation. There now exist manifests to deploy barbican-kms in Kubernetes and the container image does not need to be built in most cases.
Does the cloud-provider-openstack tag correspond to the Kubernetes version it is intended for?
```release-note
NONE
```

[barbican-kms-plugin] Update Barbican KMS plugin documentation

---

pkg/openstack/loadbalancer.go

When the service.beta.kubernetes.io/openstack-internal-load-balancer annotation gets added to a Service we do not reconcile in terms of removal of a FIP that may already exist. This commit fixes that by making sure FIP attached to an LB VIP is deleted.
fixes #2167
```release-note
NONE
```

[occm] Remove FIP on internal annotation addition

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml
charts/openstack-cloud-controller-manager/values.yaml

**What this PR does / why we need it:**
ability to add priority class for occm 
```release-note
NONE
```

[occm] add priorityClassName to helm chart

---

pkg/openstack/loadbalancer.go

OVN keeps the source IP of the incoming traffic. This means that the SG
on the members of the LB (nodes) needs to have a rule opening traffic
not only from inside the cluster, but also elsewhere. This can
restricted by using the `Service.Spec.LoadBalancerSourceRanges` and this
commit also makes sure the setting is taken into account.
fixes #
```release-note
[openstack-cloud-controller-manager] Implemented support for `loadBalancerSourceRanges` for OVN Octavia Provider (with manage-security-groups enabled).
```

[occm] Make manage-security-groups work with OVN

---

OWNERS
README.md

- Adds @dulek and @kayrus as approvers.
- Moves @chrigl and @ramineni to emeritus_approvers and removes them from reviewers.
- Removes @Fedosin from reviewers.
```release-note
NONE
```

[all] Add dulek and kayrus as approvers

---

pkg/autohealing/cloudprovider/openstack/provider.go
pkg/autohealing/controller/controller.go

Based on unfinished PR #2054
Fixes problem with Worker Nodes getting stuck in Ready,SchedulingDisabled status after repair by reboot.
fixes #2053 
Steps to test:
- build an image for magnum-auto-healer from the code with these changes
- use this image in the Magnum K8S cluster
- simulate a failure on one of the cluster's working nodes, as follows:
`sudo systemctl stop kubelet`
- confirm that repair by reboot now works fine, Worker Node status is set to Ready
After approval and merge of this PR, PR #2054 can be closed.
```release-note
[magnum-auto-healer] Fixed Worker Nodes stuck in Ready,SchedulingDisabled status after repair by reboot
```

[magnum-auto-healer] Fix Worker Nodes stuck in Ready,SchedulingDisabled status  after repair by reboot

---

OWNERS
README.md

Cherry pick of https://github.com/kubernetes/cloud-provider-openstack/pull/2318.
```release-note
NONE
```

[release-1.26] [all] Add dulek and kayrus as approvers

---

charts/openstack-cloud-controller-manager/Chart.yaml
charts/openstack-cloud-controller-manager/templates/daemonset.yaml

I hope this is correct 😅
Originated from https://github.com/kubernetes/cloud-provider-openstack/issues/2364
```release-note
NONE
```

Backport https://github.com/kubernetes/cloud-provider-openstack/pull/2237

---

tests/ci-occm-e2e.sh
tests/e2e/cloudprovider/test-lb-service.sh
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-cpo-occm/tasks/main.yaml
tests/playbooks/test-occm-e2e.yaml

We want to test with ovn-octavia-provider too, this commit makes sure
it's possible.
fixes #
```release-note
NONE
```

[occm] e2e: Add options to configure Octavia provider 

---

pkg/openstack/loadbalancer_test.go

fixes #
```release-note
NONE
```
implemented a testcase for the getListenerProtocol function to test all logic and possible outcome of the function, so as to prevent bug

Test get listener protocol function [ Cloud Provider OpenStack ]

---

pkg/openstack/loadbalancer_test.go

refers https://github.com/kubernetes/cloud-provider-openstack/issues/2400
```release-note
NONE
```

enh: add test for get int from service annotation

---

pkg/openstack/loadbalancer_test.go

fixes #
```release-note
NONE
```
implement the test to GetLoadBalanceName method and test all logical part of the code including edge cases
i found out the if all the input are empty, it returns `kube_service___` ; i think this should be looked into since it failed during test
// i think there should be a check for "kube_service___ and an error should be returned if the important input are empty"

test : GetLoadBalancerName method

---

tests/e2e/cloudprovider/test-lb-service.sh

In `test-lb-service.sh` we do `trap "delete_resources" EXIT` to make sure we cleanup resources on a test failure. In there, we only fetched the `$?` after making a check for `${AUTO_CLEAN_UP}`, which itself alters the code to 0, so function always returns success. This means tests can never really fail.
This commit fixes it by making sure `$ERROR_CODE` is fetched at the very beginning of the cleanup function.
Some additional fixes needed to be made to make tests passing again. In particular:
* Tests no longer create Services as internal in order to make shared LB tests work after #2190.
* FIP is added to the user LB in the sharing test in order for CPO to not complain about not being able to create it for a secondary Service.
**Which issue this PR …

[occm] Make sure we don't mask LB tests failures and fix what was failing

---

pkg/openstack/instances_test.go

Adds unit test for fun instanceIDFromProviderID in instances.go file
```release-note
NONE
```

enh: add unit test for instanceID from providerID

---

pkg/openstack/loadbalancer_test.go

fixes #
```release-note
NONE
```
implemented unitest for all possible edge case that this function can encounter checking in strategic range

test : nodeAddressForLB()

---

pkg/openstack/loadbalancer_test.go

fixes #
```release-note
NONE
```
implemented the unit test for the complex  `getMemberSubnetID`
test for possible edge cases in the program lbaasv2 method

test : getMemberSubnetID

---

pkg/openstack/loadbalancer_test.go

Add unit test to build batch update member opts
To run the test, on your terminal run ```make unit```
```release-note
NONE
```

test-buildbatchupdatememberopts

---

pkg/openstack/loadbalancer_test.go

fixes #
```release-note
NONE
```

Add Test to generate listener options [OCP]

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
hack/bump-release.sh
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
release-procedure.md
tests/playbooks/roles/install-k3s/defaults/main.yaml

This updates images and charts versions for 1.29
fixes #
```release-note
NONE
```

Update versions for 1.29

---

charts/cinder-csi-plugin/Chart.yaml
charts/manila-csi-plugin/Chart.yaml
charts/openstack-cloud-controller-manager/Chart.yaml
docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
docs/magnum-auto-healer/using-magnum-auto-healer.md
docs/octavia-ingress-controller/using-octavia-ingress-controller.md
examples/webhook/keystone-deployment.yaml
manifests/barbican-kms/ds.yaml
manifests/barbican-kms/pod.yaml
manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml
manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
manifests/magnum-auto-healer/magnum-auto-healer.yaml
manifests/manila-csi-plugin/csi-controllerplugin.yaml
manifests/manila-csi-plugin/csi-nodeplugin.yaml
tests/playbooks/roles/install-cpo-occm/defaults/main.yaml
tests/playbooks/roles/install-csi-cinder/tasks/main.yaml

This is to include fixes to #2531 in a release.
fixes #2531
```release-note
NONE
```

Cut 1.28.2

---

OWNERS

fixes #2700
```release-note
NONE
```
cc @jichenjc

remove jichenjc from approvers

---

OWNERS

Remove mdbooth as a reviewer

---

tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/roles/install-csi-manila/tasks/main.yaml
tests/playbooks/roles/install-devstack/tasks/main.yml

Manual cherry-pick of the #2966
```release-note
NONE
```

[release-1.33] Bump CSI test timeouts

---

tests/playbooks/roles/install-csi-cinder/tasks/main.yaml
tests/playbooks/roles/install-csi-manila/tasks/main.yaml
tests/playbooks/roles/install-devstack/tasks/main.yml

Manual cherry-pick of the #2966
```release-note
NONE
```

[release-1.32] Bump CSI test timeouts

---

.golangci.yaml
Makefile
pkg/autohealing/cloudprovider/openstack/provider.go
pkg/autohealing/healthcheck/plugin_endpoint.go
pkg/csi/cinder/openstack/openstack_volumes.go
pkg/csi/cinder/utils.go
pkg/csi/manila/manilaclient/builder.go
pkg/identity/keystone/authenticator.go
pkg/identity/keystone/authorizer.go
pkg/identity/keystone/keystone.go
pkg/identity/keystone/sync.go
pkg/identity/keystone/sync_test.go
pkg/ingress/controller/controller.go
pkg/ingress/controller/openstack/octavia.go
pkg/kms/encryption/aescbc/aescbc.go
pkg/kms/server/server.go
pkg/openstack/instances_addresses.go
pkg/openstack/loadbalancer.go
pkg/openstack/loadbalancer_test.go
pkg/util/blockdevice/blockdevice_linux.go
pkg/util/mount/mount.go
pkg/util/openstack/loadbalancer.go

Bump golangci-lint to latest major version and address issues seen.
n/a
Issues are addressed on a commit-by-commit basis. They are mostly trivial, save for the "Simplify conditionals" patch which might warrant a closer review.
```release-note
NONE
```

Bump golangci-lint to v2
