MAINTAINERS.md
The Kubernetes development community favors OWNERS with approver and reviewer entries over maintainers file and entries. Remove outdated and unmaintained MAINTAINERS.md file.
**Which issue this PR fixes** 
NONE
https://github.com/kubernetes/community/blob/master/community-membership.md#maintainer
```
NONE
```
=> Remove MAINTAINERS.md

OWNERS
We asked new additions to the OWNERS files to submit their additions individually, but with the reviews stuck in constant conflict this patch adds all of the current approvals to one file.
https://github.com/kubernetes/cloud-provider-openstack/pull/10
https://github.com/kubernetes/cloud-provider-openstack/pull/12
https://github.com/kubernetes/cloud-provider-openstack/pull/26
https://github.com/kubernetes/cloud-provider-openstack/pull/27
https://github.com/kubernetes/cloud-provider-openstack/pull/29
```
NONE
```
=> Batch adding OWNERS to prevent merge conflicts

pkg/identity/keystone/keystone.go
It is a duplicate of another handler, located several lines above. 
Therefore, this code will never be executed.
=> Remove useless error handler

pkg/cloudprovider/providers/openstack/openstack_instances.go
**What this PR does / why we need it**: Originally these filtering was removed in https://github.com/kubernetes/kubernetes/pull/59931 but there is still left one function which is used only in ccm.
**Special notes for your reviewer**: This is little bit stupid now, but I was thinking that we need to have similar behavior in this ccm than what we have in normal controller-manager. So I fixed this function that is used in ccm part. Sorry for making this now, it would have been better to implement in same PR.
So this PR means that kubernetes cluster node is not deleted from cluster if the instance still exist in openstack. If instance is deleted from openstack - the node is deleted from cluster as well
```release-note
NONE
```
/assign …
=> remove filtering by server status

OWNERS
This change adds v1k0d3n as a reviewer, if the project is willing.
- v1k0d3n
**What this PR does / why we need it**: This PR adds a reviewer to the OWNERS file.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # N/A
**Special notes for your reviewer**: N/A
```N/A
```
=> OWNERS: add user v1k0d3n as reviewer

devstack/plugin.sh
Calling 'systemctl status' halts execution on systems that have
SYSTEMD_PAGER set or do not use the --no-pager option.
Using the k8s-cloud-provider devstack plugin in ubuntu 16.04 (I guess other distributions are affected as well) causes the devstack run to be stuck in a pagination view of `systemctl status docker`.
Since the call shouldn't be needed AFAIK, I propose to remove it.
As an alternative, we could also replace the call with `systemctl --no-pager status docker` to prevent the usage of a pager.
=> Remove 'systemctl status' call from devstack plugin

cluster/addons/rbac/cloud-controller-manager-role-bindings.yaml, cluster/addons/rbac/cloud-controller-manager-roles.yaml
CCM has a couple of ClusterRoleBinding/ClusterRole(s) that it needs
for cloud-controller-manager, cloud-node-controller, pvl-controller
and shared-informers service accounts.
Fixes #25
```release-note
NONE
```
=> RBAC info for external cloud provider / CCM

manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml, manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
**What this PR does / why we need it**: default user for cloud controller manager 1001 which is not uid of root.
**Which issue this PR fixes**: fixes #40 partly
**Special notes for your reviewer**: 
```release-note
```
=> use occm without root

pkg/identity/webhook/webhook.go
To fix the bug in keystone webhook authorization
fixes #56
The k8s authorizer is expecting a bool type value from WebhookAuthorizer response.
NONE
=> Use bool type for 'allowed' field in authorization response

examples/persistent-volume-provisioning/cinder/cinder-in-tree-full.yaml
Add kubernetes.io/cinder example, make it easy for beginner to understand the difference with openstack.org/standalone-cinder provisioner.
fixes #62
NA
NA
=> Add full example for kubernetes.io/cinder provisioner

pkg/volume/cinder/OWNERS
Hi all.  I just noticed that the standalone-cinder provisioner that I've been maintaining in the kubernetes incubator has been copied over here.  Adding my name to the list of collaborators.
Signed-off-by: Adam Litke <alitke@redhat.com>
```release-note
```
=> Add Adam Litke to the OWNERS file

pkg/volume/cinder/volumeservice/actions.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #72 
```release-note
```
=> Change default az to empty when create cinder volume

docs/using-keystone-webhook-authenticator-and-authorizer.md, examples/webhook/policy.json, pkg/identity/keystone/authorizer.go, pkg/identity/keystone/authorizer_test.go, pkg/identity/keystone/authorizer_test_policy.json, pkg/identity/keystone/policy.go, pkg/identity/webhook/webhook.go
- Support flexible authorization policy configuration like the following:
```
[
{
"resource": {
"verbs": [
"get",
"list",
"watch"
],
"resources": [
"pods"
],
"version": "*",
"namespace": "default"
},
"match": [
{
"type": "role",
"values": [
"k8s-admin",
"k8s-viewer",
"k8s-editor"
]
},
{
"type": "project",
"values": [
"c1f7910086964990847dc6c8b128f63c"
]
}
]
}
]
```
- Change the example policy file and the doc accordingly
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #64
**Special notes for your reviewer**: None
=> Keystone authorization improvement

Makefile, pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_routes_test.go, pkg/cloudprovider/providers/openstack/openstack_test.go, pkg/cloudprovider/providers/openstack/openstack_volumes.go, pkg/volume/cinder/attacher.go, pkg/volume/cinder/attacher_test.go, pkg/volume/cinder/cinder.go, pkg/volume/cinder/cinder_util.go
In TestRoutes, let's make sure we get an active instance and use
that. If the instance is not active, then it will not have an ip address
and hence fail.
In TestVolumes, we should actually wait for a total of 30 seconds. We
are bailing out in one second right now. Make sure we sleep for the
initial delay before we start as well.
=> Fix reliability of TestRoutes and TestVolumes

pkg/volume/cinder/volumeservice/connection.go
during some refactoring, lost support for OS_CINDER_ENDPOINT, so adding
that back and also pick up other env vars.
=> Better environment vars support for standalone cinder service

pkg/volume/cinder/volumeservice/connection.go, pkg/volume/cinder/volumeservice/connection_test.go
When the config file is not present, we should just use what is in the
env variables. during some refactoring, we lost that ability.
=> getConfig should work when config file is absent

OWNERS
**What this PR does / why we need it:**
Adds ghugo (gagehugo) to the list of reviewers/approvers.
**Special notes for your reviewer:**
I've been following the kubernetes/keystone webhook for a while and as a core contributor to keystone I would like to help review and contribute to this project.
=> Add ghugo as reviewer

cmd/openstack-cloud-controller-manager/main.go
we were getting some bad prefixes to actual logging because of the way flags are setup. just squash them. 
```
ERROR: logging before flag.Parse: W0411 08:27:21.065165   52319 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
ERROR: logging before flag.Parse: W0411 08:27:21.065296   52319 client_config.go:538] error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PO
```
=> Squash unnecessary ERROR prefixes in logs

pkg/cloudprovider/providers/openstack/openstack.go, pkg/csi/cinder/openstack/openstack.go, pkg/flexvolume/cinder_client.go, pkg/volume/cinder/volumeservice/connection.go
We have a few data structures to load Configuration, until we have
a single package, let's make sure we can read a cloud conf file with
extra sections. (example cinder csi plugin fails when we feed it a
cloud.conf with LoadBalancer section)
=> Tolerate unknown sections / variables

manifests/cinder-csi-plugin/csi-attacher-cinderplugin.yaml, manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml, manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml
Since kubernetes csi images has bumped to v0.2.0,
we should update them in csi cinder manifests.
```release-note
NONE
```
=> bump csi manifests to v0.2.0

.zuul.yaml
openstack-cloud-controller-manager-unittest have been deprecated
in OpenLab side, use cloud-provider-openstack-unittest to instead,
all of these job name have been updated in master, only release-1.9
branch should be updated. This change do not impact real code of
cloud-provider-openstack.
Related-Bug: theopenlab/openlab#21
@dims
=> Switch to new OpenLab unit test job in release-1.9 branch

manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml, manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
Fix some small issues in controller-manager manifests
DaemonSet manifest:
- Remove double hostNetwork attribute
- Set nodeSelector to only schedule pods on master nodes
Pod manifest:
- Set correct component label
=> Small fixes in controller-manager manifests

README.md, hack/make.sh
This just adds a simple hack/make.sh script to run make directives in a
Docker container.  This means you can run build, test, vet etc on a
repod checked out into any directory on any machine that has Docker.
You aren't required to have a Golang environment or dev environment
setup on your system.
Some may find this useful to simplify the development and test process. 
It's not as useful for dev environments because you presumably will need
a proper Go env to do any dev work, but it's a very lightweight and easy
way to provide a testing environment or to generate builds without any
pre-requisites.
=> Provide a hack a script to run make in a Container

Makefile, cmd/octavia-ingress-controller/main.go, pkg/ingress/cmd/root.go, pkg/ingress/config/config.go, pkg/ingress/controller/controller.go, pkg/ingress/controller/openstack/client.go, pkg/ingress/controller/openstack/neutron.go, pkg/ingress/controller/openstack/octavia.go, pkg/ingress/controller/utils.go
An ingress controller implementation based on OpenStack Octavia service. A demo: <https://youtu.be/ASSUMDvH_aE>
fixes #114
This is the initial commit that can only be used for PoC purpose, a lot of things need to be improved such as:
- Add documentation for how to deploy and test the ingress controller.
- The unit test is missing
- Add functional test
- TLS support
- Service name support
```release-note
Add OpenStack(Octavia) based ingress controller implementation.
```
=> Add octavia-ingress-controller

pkg/ingress/config/config.go, pkg/ingress/controller/controller.go
Make the ingress controller configuration more readable
Before this change, the config file looks like:
```yaml
kubernetes:
apiserverHost:
kubeConfig: /etc/kubernetes/ingress-openstack.conf
openStack:
username: demo
password: password
projectID: ${project_id}
authURL: ${auth_url}/v3
region: RegionOne
octavia:
subnetID: ${subnet_id}
allocateFloatingIP: true
floatingIPNetwork: ${public_net_id}
```
After this change, it will be:
```yaml
kubernetes:
apiserverHost:
kubeconfig: /etc/kubernetes/ingress-openstack.conf
openstack:
username: demo
password: password
project_id: 02c5e04d91b44987bb791d74a36654d4
auth_url: http://10.0.19.151/identity/v3
region: RegionOne
octavia:
subnet_id: bfe392ad-aa5b-464b-acfa-7bb476e66bc6 …
```
=> Improve the config option for ingress controller

cmd/k8s-keystone-auth/main.go
Magnum team is try to integrate k8s-keystone-auth when creating
k8s cluster so that user can get keystone authN and authZ for k8s
out of box. However, Magnum is not running kubelet on master(for
flannel network driver) or doesn't allow running workingload on
master(for calico network driver). So we need a good way (env
variables) to pass in those necessary arguments. This patch adds
the env variables support for those must-have arguments.
```release-note
```
=> Support env variables for more arguments

Makefile
Currently, make build doesn't work for go1.9.1 and possibly other
older versions, user will see error like below when buiding:
//////////////////////////////////////////////////////////
CGO_ENABLED=0 GOOS=linux go build \
-ldflags '"-w -s -X 'main.version=c206dbe2'"' \
-o k8s-keystone-auth \
cmd/k8s-keystone-auth/main.go
flag provided but not defined: -w -s -X main.version
......
Makefile:88: recipe for target 'k8s-keystone-auth' failed
make: *** [k8s-keystone-auth] Error 2
/////////////////////////////////////////////////////////
It "works" with go1.10. However, with the binary built on go1.10,
when run the command like './k8s-keystone-auth -v 1', you will see
the version is empty, because -ldflags is not well parsed due to
the outer single quotation marks. The patch removes the outer …
=> Fix ldflags format for build

cmd/client-keystone-auth/main.go, docs/using-client-keystone-auth.md
Now, in case of interactive session, users have to enter their
logins and passwords every time in the interactive sessions.
This is not very convenient, so it's better to allow to store
this data in env variables and ask to enter the values only if
they are unset.
This commit adds two new flags for the client-keystone-auth executable:
--user-name and --password, which are defaulted to OS_USERNAME and
OS_PASSWORD respectively.
Addtionally, this commit fixes several small issues:
1. Since Stdout is redirected the executable cannot write data there,
when the user is asked for his login or password. Therefore, Stderr
should be used for the output in the interactive sessions.
2. The Exec plugin expects to get expiresAt data in RFC3339Nano format,
otherwise it is ignored. So the executable …
=> Allow to read username and password from env variables

pkg/cloudprovider/providers/openstack/metadata.go, pkg/cloudprovider/providers/openstack/metadata_test.go, pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_instances.go
Sync with the change from @liggitt in k/k master - https://github.com/kubernetes/kubernetes/pull/63903/commits
=> Restore pre 1.10 openstack instance naming behavior

pkg/volume/cinder/provisioner/clusterbroker.go, pkg/volume/cinder/provisioner/iscsi.go, pkg/volume/cinder/provisioner/iscsi_test.go, pkg/volume/cinder/provisioner/mapper.go, pkg/volume/cinder/provisioner/mapper_test.go, pkg/volume/cinder/provisioner/provisioner.go, pkg/volume/cinder/provisioner/provisioner_test.go, pkg/volume/cinder/provisioner/testutils_test.go, pkg/volume/cinder/provisioner/vsbroker.go, pkg/volume/cinder/volumeservice/actions.go
**What this PR does / why we need it**: Apply a few fixes that have been queued while the provisioner code was moved to this repo from the kubernetes-incubator.  I would like to focus my development effort now on this repository instead of the old location.
**Which issue this PR fixes**: This PR fixes the provisioning flow when cinder.create takes longer than 5 seconds.  It also makes it easier to use certain iscsi storage where initiatorName is verified during volume attachment.  The rest of the commits make small fixes and refactors to prepare for the addition of cloning support.
```release-note
Usability and reliability improvements to the cinder-provisioner.
```
=> Cinder provisioner fixes

tools/install-distro-packages.sh
Fixes issue that install-distro-packages.sh checks for make but
never installs it.
=> Install also make if not installed

pkg/volume/cinder/provisioner/clusterbroker.go, pkg/volume/cinder/provisioner/provisioner.go, pkg/volume/cinder/provisioner/provisioner_test.go, pkg/volume/cinder/provisioner/testutils_test.go
This PR enables provisioning new volumes as a clone of an existing PVC.  To
request a clone, the user should add a clone request annotation to the PVC:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: clone-claim
annotations:
k8s.io/CloneRequest: default/source-pvc
```
The provisioner will locate the indicated PVC and determine the underlying
associated cinder volume ID.  The provisioner will use this ID as the
source-vol-id parameter when provisioning the new volume resulting in a clone
at the storage level.
Cloning will only work if the cinder backend supports "smart-cloning".  This
means that the clone will complete without the need for cinder to perform a
bit-for-bit copy using the host.  Because of this, the cinder provisioner will
not attempt to clone unless the …
=> Add cloning via PVC annotation

docs/using-keystone-webhook-authenticator-and-authorizer.md
policy.json exists under examples/webhook/, not examples directly.
This fixes the path for avoiding confusion.
=> Trivial: Fix the path of policy.json

.gitignore
In commit 61f07b188579c2a20b735db06258e3edd973306a we introduced a new binary file `client-keystone-auth` but we forgot to add it to the `.gitignore` like the other binaries
=> Add binary file name to .gitignore

docs/using-keystone-webhook-authenticator-and-authorizer.md
On some environments, kube-apiserver restarts automatically just after
changing the manifest (/etc/kubernetes/manifests/kube-apiserver.yaml, etc).
Before restarting, k8s-keystone-auth process needs to exist.
So this changes the config sort of k8s-keystone-auth to make the condition
easily for readers.
=> Fix the config sort of k8s-keystone-auth

pkg/identity/keystone/authenticator.go, pkg/identity/keystone/authenticator_test.go
When user authenticates there is no information about his domain,
but having it could be useful for data synchronization. For instance,
when admin may want to disable the synchronization for some specific
domains.
This patch adds information about user's domain to the Extra data,
that can be found by "alpha.kubernetes.io/identity/user/domain/id" and
"alpha.kubernetes.io/identity/user/domain/name" keys respectively.
Also missing unit tests were added to check unmarshaling of keystone
responses.
=> Add information about user's domain to the Extra data

pkg/identity/keystone/authenticator.go, pkg/identity/keystone/authenticator_test.go, pkg/identity/keystone/config.go, pkg/identity/keystone/keystone.go, pkg/identity/keystone/sync.go, pkg/identity/keystone/sync_test.go, pkg/identity/keystone/syncconfig.yaml
To improve integration between keystone and k8s it's recommended
to add a possibility to synchronize projects/namespaces.
In other words, if the user belongs to the project in Keystone, then, when
he attepts to authenticate in Kubernetes using k8s-keystone-auth, a k8s
namespace with the same name as the project id will automatically be
created for him.
To enable the feature two new arguments were added to the k8s-keystone-auth binary:
"--sync-config-file" - points to a local file with sync configuration.
"--sync-configmap-name" defines a configmap containing the configuration.
If any of them is set, new namespace will be automatically created when the user is
authenticated in Keystone.
fixes: #192
=> Allow synchronization between Keystone projects and K8s namespaces

README.md
Since glide dependency management was replaced by "go dep" [1], we need
to update README.md accordingly.
Also this patch improves the formatting of the file by following the
rules described in [2].
The rules that were violated:
- MD022 - Headings should be surrounded by blank lines;
- MD032 - Lists should be surrounded by blank lines;
- MD034 - Bare URL used.
[1] https://github.com/kubernetes/cloud-provider-openstack/pull/86
[2] https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md
=> Small README.md improvements

pkg/identity/keystone/authenticator.go, pkg/identity/keystone/authenticator_test.go, pkg/identity/keystone/keystone.go, pkg/identity/keystone/sync.go
When new namespace is automatically created from a Keystone project, new role
bindings are also should be created to allow the user having the same rights
as in the keystone project.
fixes #45
=> Sync role assignments

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Add cluster name to the description of Loadbalancers to help operators with the differentiation of clusters.
The cluster name is passed to the cloud-controller-manager using the `--cluster-name` parameter. If it is not set 'kubernetes' is used as default cluster name.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #222
```
Add cluster name to LB description
```
=> Add cluster name to LB description

pkg/identity/keystone/authorizer_test.go, pkg/identity/keystone/authorizer_test_policy.json
This patch adds unit tests verifying that if version = "" in the policy file,
then the authorizer must ensure that access is allowed to Core Group API
resources only.
fixes #216
=> Ensure that authorizer supports core api group validation

Makefile
This fixs the missing operation of image manila-provisioner building in Makefile to avoid image does not exist error during image uploading.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #217 
```release-note
```
=> Missing image manila-provisioner during uploading images in Makefile

docs/using-manila-provisioner.md
Tables used to describe configuration options in Manila provisoner 
document are not easily readable, This patch corrects the 
table formatting
This PR fixes table formatting in manila provisioner doc
```release-note
```
=> Format tables in manila provisioner doc

docs/openstack-kubernetes-integration-options.md, docs/using-auth-data-synchronization.md, pkg/identity/keystone/syncconfig.yaml
This commit adds documentation describing the use of the new feature for auth data synchronization.
=> Add auth data sync documentation

docs/using-keystone-webhook-authenticator-and-authorizer.md
This adds the building way of k8s-keystone-auth binary.
In addition, the follwoing two option names are similar and the
passed files are the same on the doc.
--authorization-webhook-config-file
--authentication-token-webhook-config-file
It is easy to cause confusion with current describing way.
This makes the description of authorization config flags align for
the above authentication way for easy understanding.
=> Add building way of k8s-keystone-auth binary

pkg/identity/keystone/keystone.go
There were duplicated createKubernetesClient calls for conditions.
Then this merges them into a single call for the code cleanup.
=> Merge multiple createKubernetesClient calls

CONTRIBUTING.md
This patch adds general contributing guidelines for cloud-provider-openstack.
This PR adds document for general contributing guidelines to cloud-provider-openstack
**Which issue this PR fixes** : 
fixes #230
=> Add Contributor Guidelines doc

docs/using-manila-provisioner.md, pkg/share/manila/client.go, pkg/share/manila/provisioner.go, pkg/share/manila/shareoptions/common.go, pkg/share/manila/shareoptions/openstack.go, pkg/share/manila/shareoptions/parseoptions.go, pkg/share/manila/shareoptions/shareoptions.go, pkg/share/manila/shareoptions/util.go
Adds support for trustee authentication and supplying custom CAs.
The OpenStack Secret may now contain:
- `os-trustID`, `os-trusteeID` and `os-trusteePassword` for trustee auth
- `os-certAuthority` and `os-TLSInsecure` for supplying a custom CA, and optionally allowing it to be insecure
```release-note
NONE
```
/cc @dims @hogepodge @flaper87
=> Manila: trustee authentication + custom CAs

docs/using-keystone-webhook-authenticator-and-authorizer.md
Add the missing documentation for k8s-keystone-auth service. It only covers how to config and run the k8s-keystone-auth as a k8s service rather than the static pod.
N/A
N/A
```release-note
```
=> Add documentation for k8s-keystone-auth

pkg/cloudprovider/providers/openstack/openstack_volumes.go
Fix that fails to resize pvc of cinder volume. See also #[66687](https://github.com/kubernetes/kubernetes/issues/66687).
fixes #[66705](https://github.com/kubernetes/kubernetes/issues/66705)
```release-note
NONE
```
=> Fix that fail to resize pvc of cinder volume.

.zuul.yaml
It is not necessary to run both master and release 1.10 branch
cloud-provider-openstack to test against k8s master, v1.10 and v1.11
in OpenLab periodic jobs, that allocate lots of testing vm resources.
Add branches option into job define in order to limiting specific job
just run on specific branch.
```release-note
```
=> Run conformance periodic jobs on specific branches for master

.zuul.yaml
It is not necessary to run both master and release 1.10 branch
cloud-provider-openstack to test against k8s master, v1.10 and v1.11
in OpenLab periodic jobs, that allocate lots of testing vm resources.
Add branches option into job define in order to limiting specific job
just run on specific branch.
```release-note
```
=> Run conformance periodic jobs on specific branches for 1.10

manifests/provisioner/deployment.yaml
If not specifying OS_DOMAIN_NAME on standalone-cinder-provisioner
manifest, the deployment is not deployed and the log is like:
F0810 02:28:02.332034       1 main.go:86] Error creating Cinder
provisioner: failed to get volume service: You must provide
exactly one of DomainID or DomainName to authenticate by Username
So this adds the OS_DOMAIN_NAME on the manifest.
**Release note**: NONE
=> Add OS_DOMAIN_NAME on the manifest

cluster/addons/storage-class/openstack/default.yaml, docs/openstack-kubernetes-integration-options.md, examples/persistent-volume-provisioning/cinder/cinder-storage-class.yaml
External provisioner name is "openstack.org/standalone-cinder" which
is hardcoded in this repo. And "kubernetes.io/cinder" is the one of
kubernetes/kubernetes in-tree provisioner which is already deprecated.
So this replaces the old name with a new one which is the external
cloud-provider-openstack to avoid confusion.
In addition, this removes the volume type from the example because
the provisioner cannot create a volume if the volume type doesn't
exist on Cinder side and it is hard to debug it.
**Release note**: NONE
=> Replace internal provisioner name with external one

.gitignore, snapcraft.yaml
Adds snap building to build a snap for the client-keystone-auth plugin. [Snaps](https://snapcraft.io) are a new package system by Ubuntu. Snaps will run on almost any distro and it's super easy to update them. Snaps will update on the user's machine periodically, so the users will always have the latest version that you publish.
I have also created a [launchpad team](https://launchpad.net/~cloud-provider-openstack) and a [snap store snap](https://dashboard.snapcraft.io/snaps/client-keystone-auth/) for this. The team owns the [launchpad …
=> Adding snap building support to client-keystone-auth plugin.

snapcraft.yaml
Fixing the snap build process. The launchpad builders didn't like using docker, so I switched it out to just build directly.
=> Pulling docker for the build

pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_test.go
Cherry pick #67748
Cloud-provider-reported addresses are authoritative in 1.12, this
preserves default behavior that used the internal dns name as
the "Hostname" address on Node status.
```release-note
The OpenStack cloud provider now reports a `Hostname` address type for nodes
```
=> Make OpenStack cloud provider report a node hostname address

.gitignore
This PR adds Manila Provisioner binary to .gitignore
=> Add Manila Provisioner binary to .gitignore

Gopkg.lock, Gopkg.toml, manifests/cinder-csi-plugin/csi-attacher-cinderplugin.yaml, manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml, manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml, pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/controllerserver_test.go, pkg/csi/cinder/driver.go, pkg/csi/cinder/fake.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_mock.go, pkg/csi/cinder/openstack/openstack_volumes.go
This PR adds support for CSI v.0.3.0 in cinder CSI plugin
https://github.com/container-storage-interface/spec/releases/tag/v0.3.0
**Which issue this PR fixes** : 
fixes #242
```release-note
NONE
```
=> Update Cinder CSI driver to 0.3.0

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
**What this PR does / why we need it**: we need possibility to keep floatingip after service delete
**Which issue this PR fixes**: fixes #273 
```release-note
Now it is possible to keep service type: LoadBalancer floatingip address in openstack by defining annotation `loadbalancer.openstack.org/keep-floatingip` to service.
```
=> implement keep floatingip annotation

docs/getting-started-provider-dev.md
cloud-provider-openstack uses dep for dependency management,
This  PR adds step to install dep in getting started document.
=> Install dep instead of glide in getting started doc

cmd/client-keystone-auth/main.go, docs/using-client-keystone-auth.md
Recently client authentication api was updated from v1alpha1 to v1beta1.
https://github.com/kubernetes/client-go/commit/f58a8f4fd079a6e2d027afeba4eb8c2ef3a233f5
This commit switches keystone-client-auth on the new api and removes the outdated
one.
The difference between two versions is that in alpha interactive mode was checked
in client-go and provided to the plugin with the environment variable
KUBERNETES_EXEC_INFO. In beta the plugin uses a TTY check to determine if it's
appropriate to prompt a user interactively. That's why KUBERNETES_EXEC_INFO is
not used anymore and can be removed.
Another change is that ExecCredentialSpec struct doesn't contain any fields now,
which means the plugin shouldn't write anything in this section during printing
response output. …
=> Start using client.authentication.k8s.io/v1beta1 api for the client auth plugin

pkg/csi/cinder/controllerserver_test.go, pkg/csi/cinder/nodeserver_test.go
Try to avoid those error in UT output:
ok      k8s.io/cloud-provider-openstack/pkg/cloudprovider/providers/openstack   (cached)
ERROR: logging before flag.Parse: I0920 15:25:14.382972   31350 driver.go:49] Driver: csi-cinderplugin version: 0.3.0
ERROR: logging before flag.Parse: I0920 15:25:14.383122   31350 driver.go:80] Enabling controller service capability: CREATE_DELETE_VOLUME
ERROR: logging before flag.Parse: I0920 15:25:14.383135   31350 driver.go:80] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
ERROR: logging before flag.Parse: I0920 15:25:14.383147   31350 driver.go:92] Enabling volume access mode: SINGLE_NODE_WRITER
ERROR: logging before flag.Parse: I0920 15:25:14.383161   31350 driver.go:49] Driver: csi-cinderplugin version: 0.3.0
ERROR: logging before …
=> Avoid ERROR: logging before flag.Parse in UT

docs/getting-started-provider-dev.md
The doc is not enough for the cloud-controller-manager to startup
=> Add doc to indicate the roles/bindings need to be created

pkg/cloudprovider/providers/openstack/metadata.go
Per openstack update, some links should be updated as well for metadata services
=> Enhance comment about document

CONTRIBUTING.md
This commit adds URL for logging new issues related to
cloud-provider-openstack.
This PR adds URL for logging new issue in this repository.
None.
None.
None
=> Adds url to log new bug in contributing.md

.zuul.yaml
Signed-off-by: Melvin Hillsman <mrhillsman@gmail.com>
Update periodic job runs to use master branch since there is not a 1.12 branch/tag yet. Currently the 1.12 conformance does not run due to branch 1.11 being used.
@dims
=> Set e2e to master until cpo 1.12 branch/tag is cut

examples/webhook/keystone-apiserver-webhook.yaml, examples/webhook/keystone-auth-certs-secret.yaml, examples/webhook/keystone-deployment.yaml, examples/webhook/keystone-policy-configmap.yaml, examples/webhook/keystone-rbac.yaml, examples/webhook/keystone-service.yaml
Adding templates from the documentation(with some rbac changes). This makes it easier for people to deploy by cloning the repo.
https://github.com/kubernetes/cloud-provider-openstack/issues/271
RBAC changes to create a new service account specifically for keystone auth. Not sure where the tests are or if you want to use these templates in those tests.
```release-note
Added keystone auth templates to examples/webhook.
```
=> First pass at adding templates for keystone auth

pkg/ingress/controller/controller.go, pkg/ingress/controller/openstack/octavia.go
Use batch operation API to reduce API calls to Octavia
<https://developer.openstack.org/api-ref/load-balancer/v2/index.html#batch-update-members>
```release-note
```
=> Batch update members in octavia-ingress-controller

Gopkg.lock, pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_metrics.go, pkg/cloudprovider/providers/openstack/openstack_routes_test.go, pkg/cloudprovider/providers/openstack/openstack_test.go
Cherry pick of #317 on release-1.12.
#317: Export some methods in anticipation of a standalone cinder
=> Automated cherry pick of #317: Export some methods in anticipation of a standalone cinder

Gopkg.lock, pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_metrics.go, pkg/cloudprovider/providers/openstack/openstack_routes_test.go, pkg/cloudprovider/providers/openstack/openstack_test.go
We seem to have a longer runway for removing the cinder in-tree volume
provider. These changes will help us experiment with vendoring code from
cloud-provider-openstack back into kubernetes/kubernetes.
Change-Id: Ie49fe43ebc8b68295bbeb3a192a948dfbe6cd975
```release-note
NONE
```
=> Export some methods in anticipation of a standalone cinder provider

Makefile
Adds manila-provisioner to `make clean`
```release-note
NONE
```
=> Add Manila Provisioner binary to Makefile clean

pkg/ingress/cmd/root.go, pkg/ingress/controller/controller.go, pkg/ingress/controller/openstack/neutron.go, pkg/ingress/controller/openstack/octavia.go, pkg/ingress/controller/utils.go
If the ingress resource doesn't change, nothing needs to do when the
ingress controller restarts. In order to do that we need to store
the ingress resource version information in the load balancer's
description field.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #311
With this PR, when the ingress controller restarts, for existing ingress that not changed, you can see the log below:
```
INFO[0000] ingress created or updated, will create or update octavia resources  ingress=default/test-octavia-ingress
DEBU[0000] loadbalancer exists                           name=k8s-default-test-octavia-ingress-lb …
```
=> [Ingress] Do not recreate octavia resources when the controller restarts

pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/openstack/openstack_metadata.go
Currently cinder csi plugin gets nodeID from cloud-init mounted data, but the plugin fails if the instance image does not have cloud-init or data is at some other location, This commit adds to get the data from metadata service as a fallback option.
**Which issue this PR fixes** : fixes #325 
As of now separate code is written in cinder-csi-plugin to get metadata from openstack metadata service, In future we should import some common functionality from provider/openstack 
`NONE`
```release-note
```
=> Get NodeID from Metadata Service as fallback

pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/controllerserver_test.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_mock.go, pkg/csi/cinder/openstack/openstack_volumes.go
previously volume list will show something like:
not implemented
now it will have
$ csc controller list-volumes  --endpoint tcp://127.0.0.1:10000
"05477623-0355-4229-80d0-dd695f40d748"  2147483648
"c0a0c1da-c4aa-49e0-8900-f67dbfb01dfd"  1073741824
=> Add volume list functions

OWNERS
Adds adisky as reviewer to OWNERS file.
```NONE
```
=> Add adisky as reviewer to OWNERS file

pkg/cloudprovider/providers/openstack/openstack_volumes.go
**What this PR does / why we need it**: 
When the `openstack-cloud-controller-manager` is running with PV label initializing controller
and NFS volume is created, it causes nill reference error.
**Which issue this PR fixes** 
`OpenStack` version of kubernetes/kubernetes#68996
This is a cherry-pick of kubernetes/kubernetes#70459
```release-note
NONE
```
=> fix GetLabelsForVolume to handle only Cinder volumes

manifests/cinder-csi-plugin/csi-attacher-cinderplugin.yaml, manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml, manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml
Cinder CSI is breaking with sidecar containers update to CSIv1.0.0
Using older version until cinder driver updated to 1.0.0
`NONE`
```release-note
```
=> Fix CSI CI (Update CSI Sidecar versions)

examples/loadbalancers/external-http-nginx.yaml, examples/loadbalancers/internal-http-nginx.yaml
For the loadbalancer annotations to have any effect, they need to be in
the service definition not in the deployment.
It moves the loadbalancer annotations in the loadbalancers examples to the right resource. These annotations hint to the provider if the loadbalancer should grab a floating IP for the loadbalancer or if its meant to remain internal.
fixes #375
=> Move loadbalancer annotations to the service

docs/using-manila-provisioner.md, pkg/share/manila/sharebackends/nfs.go, pkg/share/manila/shareoptions/backend.go
The NFS share created by Manila provisioner is by default read/write by the world. This is not always welcome behaviour. I have added a new StorageClass option that allows to specify the NFS clients that would have access to the share.
Moreover the default value ('0.0.0.0/0') doesn't work with Ganesha NFS server as it doesn't seem to like the '/0' part so I changed the default to '0.0.0.0'
```release-note
Manila provisioner recognizes a new StorageClass option to specify allowed NFS share client.
```
=> Manila: Add StorageClass parameter to specify NFS share client

pkg/ingress/controller/openstack/octavia.go
No members to be updated and calling openstack API will leads to
update error, instead of provide internal error to end user
we can provide more helpful info here.
Closes: #378
enhancing log output when no node existing and creating a LB
fixes #378 
```release-note
NONE
```
=> Add a member number check

pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/openstack/openstack_volumes.go
when create a volume with name already there,
we don't give the size of the volume in output and lack of log.
Fix bug #361 
```release-note
create volume with same name will get the actual size other than 0 now
```
=> Add size into output

pkg/ingress/controller/controller.go
when failed to update, still get a 'updated' event
28s         Normal    Updating   Ingress   Ingress default/test-ingress1
28s         Warning   Failed     Ingress   Failed to update openstack.....
28s         Normal    Updated    Ingress   Ingress default/test-ingress1
avoid incorrect event generation
minor changes
```release-note
NONE
```
=> Enhance event of ingress

pkg/cloudprovider/providers/openstack/openstack.go
first, let's try use metadata to retrieve data then use cloud-init data
after all, the data in metadata/config drive won't be changed but
it's likely the data in cloud-init generated might be changed.
use metadata/config drive first then cloud-init generated data
**Which issue this PR fixes** *
fixes #372 
```release-note
None
```
=> Fix part of bug 372, try to use metadata to retrieve data first

docs/using-manila-provisioner.md, pkg/share/manila/sharebackends/csicephfs.go, pkg/share/manila/sharebackends/sharebackend_test.go, pkg/share/manila/shareoptions/backend.go
Adds a new StorageClass param for the csi-cephfs backend, users can now choose whether to use the Ceph kernel client or Ceph FUSE driver for mounting.
```release-note
Manila provisioner recognizes a new StorageClass option to specify mount tool for csi-cephfs backend
```
=> manila-provisioner: added mounter option for csi-cephfs backend

pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_instances.go
Fix the code to set the correct availability zone for the instance, otherwide the pvc cannot bind to the pod because the zone doesn't match(using `ignore-volume-az=false`).
```release-note
```
=> Fix getting instance availability zone from Nova

manifests/controller-manager/kubeadm.conf
to make the version consistent
to make the network settings by default
to make ccm create have network settings by default
to make sample use consistent version to kubeadm
```release-note
None
```
=> enhance ccm configuration file

pkg/ingress/controller/openstack/octavia.go
Fixes a typo in the Octavia logs, specifically replacing ` listenserID` with `listenerID`
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: N/A
None
```release-note
NONE
```
=> Fix Octavia typo

Gopkg.lock, docs/provider-configuration.md, pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_test.go, pkg/flexvolume/cinder_client_test.go
**What this PR does / why we need it**:  enables use of clouds.yaml in place of environment variables
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: Fixes: https://github.com/kubernetes/cloud-provider-openstack/issues/323
**Special notes for your reviewer**: First pr in this repo :1st_place_medal: 
@flaper87
=> Add support for reading clouds.yaml

Gopkg.lock, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_volumes.go
add a check when the volume detach failed, if it's a volume
not found, ignore the error and return false
Fix bug 381, add a check for the volume not found error for a race
**Which issue this PR fixes** 
fixes #381 
```release-note
None
```
=> add a check when the volume detach failed,

pkg/util/mount/mount_linux.go
1. "unformated" to "unformatted".
2. "fieds" to "fields".
3. "Recusively" to "Recursively".
4. "thet" to "that".
=> Fix some typos in comment

docs/provider-configuration.md, pkg/cloudprovider/providers/openstack/openstack.go
clouds.yaml files can contain more than one cloud entry. Allow a user
to configure the named cloud from the file explicitly.
=> Add support for selecting a specific cloud from clouds.yaml

Gopkg.lock, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go, pkg/ingress/controller/openstack/octavia.go
fixes #432
When creating floating ip for external service, add the cluster and service information in the floating ip description field, so it's easy to query and delete outside of the cluster.
```release-note
```
=> Add description for the floating ip created for external service

.gitignore
make build generates barbican-kms-plugin binary , which comes
under untracked files. Make git to ignore the same.
```release-note
```
=> Add barbican-kms-plugin to gitignore

Gopkg.lock, Gopkg.toml, pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/driver.go, pkg/csi/cinder/driver_test.go, pkg/csi/cinder/identityserver.go, pkg/csi/cinder/identityserver_test.go, pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/server.go, pkg/csi/cinder/utils.go, pkg/csi/cinder/utils_test.go
This PR removes dependency of cinder csi driver from
https://github.com/kubernetes-csi/drivers/tree/master/pkg/csi-common.
This is necessary to have own identity rpc plugin.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #359
partialfixes: #301 
`NONE`
```release-note
```
=> Remove dependency from csi-common

pkg/ingress/controller/controller.go, pkg/ingress/controller/openstack/neutron.go, pkg/ingress/controller/openstack/octavia.go
This patch adds the ingress information, e.g. namespace, name and
cluster name into openstack resource description, in order to identify
the corresponding openstack resources created for the ingress and make
it easy to do clean up.
**Which issue this PR fixes** : fixes #
```release-note
```
=> octavia-ingress-controller: Add ingress information to openstack resources description

pkg/util/mount/mount.go, pkg/volume/cinder/cinder_block_test.go
1. "symblolic" to "symbolic" in line 187.
2. "volNamne" to "volName" in line 143.
=> Fix t.Errorf() error message

docs/provider-configuration.md, pkg/cloudprovider/providers/openstack/openstack.go
This will help in case of multi-nic k8s node deployments.
Previously, cloud provider was assigning all addresses in random
order and k8s was selecting only one of them. But usually,
multi-nic scenario requires to specify which network is
"control" and admins want to bind kubelet listening address only
to that "control" net.
This commit will not affect previous logic until
internal-network-name is specified in cloud-config file.
**Which issue this PR fixes**: fixes #407 
```release-note
```
=> Add internal-network-name networking option

OWNERS
Add myself to the cloud-provider-openstack owners. I've been contributing the repo for almost half a year, the motivation of my contribution comes from the adoption of CPO(as part of Kubernetes as a Service) in our public cloud. I'm also the author of octavia-ingress-controller and maintainer of k8s-keystone-auth service. Being one of the owners doesn't mean more power but more responsibilities.
```release-note
```
=> Add lingxiankong to the OWNERS

pkg/cloudprovider/providers/openstack/metadata.go, pkg/csi/cinder/openstack/openstack_metadata.go
Currently defaultMetadataVersion is set to 2012-08-10 which is
very old. This commit updates the same.
```release-note
```
=> Update defaultMetadataVersion to latest

docs/using-cinder-csi-plugin.md, manifests/barbican-kms/pod.yaml, manifests/cinder-csi-plugin/csi-attacher-cinderplugin.yaml, manifests/cinder-csi-plugin/csi-attacher-rbac.yaml, manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml, manifests/cinder-csi-plugin/csi-nodeplugin-rbac.yaml, manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml, manifests/cinder-csi-plugin/csi-provisioner-rbac.yaml, manifests/cinder-csi-plugin/csi-secret-cinderplugin.yaml
Use the same secret like the `cloud-controller-maanger` does to reduce the management overhead of Openstack secrets.
Follow up of: https://github.com/kubernetes/cloud-provider-openstack/pull/430
=> Make usage of CCM cloud-config secret in CSI examples

pkg/ingress/controller/controller.go
Fix the the load balancer vip floating ip description, mainly changed EnsureFloatingIP method parameters order.
**Which issue this PR fixes** : 
fixes #460
```release-note
```
=> octavia-ingress-controller: Fix the floating ip description

cmd/client-keystone-auth/main.go
This PR fixes the error output in `client-keystone-auth`. Before the patch:
```bash
Failed to read openstack env vars: Missing environment variable [OS_AUTH_URL]Failed to read openstack env vars: Missing environment variable [OS_AUTH_URL]Failed to read openstack env vars: Missing environment variable [OS_AUTH_URL]Failed to read openstack env vars: Missing environment variable [OS_AUTH_URL]Failed to read openstack env vars: Missing environment variable [OS_AUTH_URL]Unable to connect to the server: getting credentials: exec: exit status 1
```
after the patch:
```bash
Failed to read openstack env vars: Missing environment variable [OS_AUTH_URL]
Failed to read openstack env vars: Missing environment variable [OS_AUTH_URL]
Failed to read openstack env …
```
=> Fix error output in client-keystone-auth

cmd/cinder-csi-plugin/main.go, docs/using-cinder-csi-plugin.md, manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml, pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/controllerserver_test.go, pkg/csi/cinder/driver.go, pkg/csi/cinder/driver_test.go, pkg/csi/cinder/fake.go, pkg/csi/cinder/identityserver_test.go, pkg/csi/cinder/nodeserver_test.go, pkg/csi/cinder/openstack/openstack_volumes.go
Add `cluster` parameter for the driver, admin user could specify the CO's identifier, e.g.  in Magnum, the `cluster` could be the magnum cluster id.
When using cinder-csi-plugin together with kubernetes in the cloud environment, we need some information to recognize the volumes created for the PVs from different kubernetes clusters, which is important for the cloud resource management.
This PR is only adding cluster name to the driver, so that the driver could pass the cluster name to the cinder volume metadata.
**Which issue this PR fixes** : fixes #450
This PR is only adding cluster name to the driver, so that the driver could pass the cluster name to the cinder volume metadata.
There are several ways to inject …
=> cinder-csi-plugin: Add cluster argument to the driver

docs/using-controller-manager-with-kubeadm.md, manifests/controller-manager/cloud-config-secret.yaml, manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml, manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
The PR changes the Volume type of the Openstack `cloud-config` used by the Openstack-ccm from `ConfigMap` to `Secret` since the configuration file contains sensible data. I know that secrets are not encrypted but at least they are more restrictive from an RBAC perspective.
I already use this "patch" in my repo: https://github.com/johscheuer/kubernetes-on-openstack/blob/master/scripts/master.cfg.tpl#L501
```release-note
action required: The volume type for the `cloud-config` used by the `openstack-cloud-controller-mananager` has changed from `ConfigMap` to `Secret`. Ensure that the `Secret exists if you update your Kubernetes manifest.
```
=> Openstack cloud-config as Kubernetes secret

Gopkg.lock, Gopkg.toml, manifests/cinder-csi-plugin/csi-attacher-cinderplugin.yaml, manifests/cinder-csi-plugin/csi-nodeplugin-cinderplugin.yaml, manifests/cinder-csi-plugin/csi-provisioner-cinderplugin.yaml, pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/controllerserver_test.go, pkg/csi/cinder/driver.go, pkg/csi/cinder/driver_test.go, pkg/csi/cinder/identityserver.go, pkg/csi/cinder/identityserver_test.go, pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/nodeserver_test.go, pkg/csi/cinder/server.go, pkg/csi/cinder/utils.go
Update cinder csi driver to csi specs 1.0.0
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #365
CSI v0.3.0 support is deprecated with kubernetes 1.13 and will be removed in v1.15
```release-note
```
`NONE`
=> Update Cinder CSI Driver to CSI Spec 1.0.0

Gopkg.lock, Gopkg.toml, cmd/cinder-provisioner/main.go, cmd/manila-provisioner/main.go, pkg/share/manila/manila_test.go, pkg/share/manila/provisioner.go, pkg/share/manila/share.go, pkg/share/manila/shareoptions/shareoptions.go, pkg/volume/cinder/provisioner/iscsi.go, pkg/volume/cinder/provisioner/iscsi_test.go, pkg/volume/cinder/provisioner/mapper.go, pkg/volume/cinder/provisioner/mapperbroker.go, pkg/volume/cinder/provisioner/provisioner.go, pkg/volume/cinder/provisioner/provisioner_test.go, pkg/volume/cinder/provisioner/rbd.go, pkg/volume/cinder/provisioner/rbd_test.go, pkg/volume/cinder/provisioner/testutils_test.go
This commit is to update code to use
kubernetes-sigs/sig-storage-lib-external-provisioner instead of
kubernetes-incubator/external-storage.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #454
```release-note
```
=> Update to use kubernetes-sigs/sig-storage-lib-external-provisioner

pkg/identity/keystone/config.go, pkg/identity/keystone/keystone.go
This PR fix an obvious bug in keystone config.
when set parameter like this:
`  - ./bin/k8s-keystone-auth
- --v=10
- --tls-cert-file
- /etc/kubernetes/pki/cert-file
- --tls-private-key-file
- /etc/kubernetes/pki/key-file
- --sync-configmap-name
- k8s-sync-config`
I got eorrors like this:
`I0211 06:17:47.079308       1 keystone.go:544] Kubernetes API client created, server version v1.13`
`E0211 06:17:47.079361       1 sync.go:126] yamlFile get err   #open k8s-sync-config: no such file or directory`
`E0211 06:17:47.079384       1 main.go:60] failed to extract data from sync config file …
=> Fix get SyncConfigMapName in config.go bug

Gopkg.lock, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
**What this PR does / why we need it**: When creating loadbalancer(Lbaas v2) resources to network which do have more than one external subnets attached, we need somekind of way to define from which external floatingip subnet we want the ip address coming from.
```release-note
```
Example:
```
openstack network list
+--------------------------------------+---------------------+------------------------------------------------------------------------------------------------------------------+
| ID                                   | Name                | Subnets …
```
=> support multiple subnets in lbaas

docs/using-manila-provisioner.md, pkg/share/manila/share.go, pkg/share/manila/shareoptions/shareoptions.go
Adds an optional StorageClass field `osShareNetworkID`
fixes #420
```release-note
manila-provisioner: added a new StorageClass option osShareNetworkID
```
=> manila: added osShareNetworkID option

pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/controllerserver_test.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_mock.go, pkg/csi/cinder/openstack/openstack_snapshots.go, pkg/csi/cinder/openstack/openstack_volumes.go
While Testing the snapshot feature, VolumeSnapshot does not bind VolumeSnapshotContent, as we are not returning snapshot status from driver, this PR fix this and also adds support for volume restore from snapshot
```release-note
```
`NONE`
=> Fix Snapshot Feature, and Add volume restore from snapshot

Gopkg.lock, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
This PR focuses on the scenario of using Octavia, it does several things:
- When creating service, create a new security group and add rules to allow traffic coming from the load balancer subnet IP address range while going to the service nodeport on the nodes. Associate the security group with all the Neutron ports on the nodes, add a tag to the ports.
- When deleting service, disassociate the security group from the Neutron ports on the nodes before removing.
fixes #490
Test process for thie PR:
1. Using image `lingxiankong/openstack-cloud-controller-manager:improve-sg`
1. Configuration
```
[Global]
auth-url=http://192.168.206.8/identity
user-id=94a665016c3e4d44a315b14d92f9ef49 …
```
=> Improve security group management for service provision

docs/using-cinder-csi-plugin.md
Various user facing issues related to compatibility while deploying cinder csi driver 
#486, https://github.com/kubernetes/kubernetes/issues/74162
This PR adds compatibilty tables between cinder csi driver, sidecar and k8s
`NONE`
```release-note
```
=> Add document section about csi version compatibility

pkg/cloudprovider/providers/openstack/openstack.go
spend a couple of time in finding why the error:
Cloud provider could not be initialized: could not init
cloud provider "openstack": Authentication failed
turn out if we can log those with -v flag it will be helpful
=> Add debug output for cfg options

cmd/client-keystone-auth/main.go
Without this PR it's not possible to only use arguments in the `client-keystone-auth` and a pipe.
Fixes: https://github.com/kubernetes/cloud-provider-openstack/issues/476
```release-note
client-keystone-auth: change the default behavior to use cli arguments if set otherwise use env variables for authentication
```
=> Implement arguments fallback for client-keystone-auth

Gopkg.lock, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Support to specify port ID to create Service of LoadBalancer type.
Use case:
Sometimes, we need to know the service IP address before a Service is actually created, so other applications who replies on the Service external IP could be deployed with no dependencies, e.g. the kube-apiserver certificate could be created before the service is actually created.
In order to specify port ID to create Service, a new annotation for Service is introduced, e.g.:
```yaml
annotations:
loadbalancer.openstack.org/port-id: "849ee2ed-72a6-44a4-911e-6a8be46dbe8e"
```
Please be aware that after the Service is created, port ID cannot be changed.
```release-note
Introduce a new …
```
=> Support new annotation for Service

.zuul.yaml
Required to run 1.13 and 1.14 stable e2e conformance tests.
Adds pipelines that exist in CI for 1.13 and 1.14 conformance testing.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #511
```release-note
```
=> Add 1.13 and 1.14 pipelines

Gopkg.lock, Gopkg.toml, cmd/cinder-provisioner/main.go, cmd/manila-provisioner/main.go, cmd/openstack-cloud-controller-manager/main.go, pkg/identity/keystone/sync.go, pkg/share/manila/manila_test.go, pkg/share/manila/provisioner.go, pkg/share/manila/share.go, pkg/share/manila/shareoptions/shareoptions.go, pkg/volume/cinder/provisioner/iscsi.go, pkg/volume/cinder/provisioner/iscsi_test.go, pkg/volume/cinder/provisioner/mapper.go, pkg/volume/cinder/provisioner/mapperbroker.go, pkg/volume/cinder/provisioner/provisioner.go, pkg/volume/cinder/provisioner/provisioner_test.go, pkg/volume/cinder/provisioner/rbd.go, pkg/volume/cinder/provisioner/rbd_test.go, pkg/volume/cinder/provisioner/testutils_test.go
This PR updates the k8s version to v1.14.0-beta.2 
and also updates to use vanity url of sig-storage-lib-external-provisioner
Ref: https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/31
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #522
```release-note
```
=> Update kubernetes to v1.14.0-beta.2

cluster/images/cinder-csi-plugin/Dockerfile
Cinder CSI Driver currently uses centos as the base image, which is heavier
This PR proposes to use Alpine as the base image
```release-note
```
`NONE`
=> Use Alpine for Cinder CSI

.zuul.yaml
Conformance jobs should only be running relevant to the branch they appear on. The periodic job is being disabled due to release-1.10 being EOL and when run it pushes the wrong binaries with the tag latest to dockerhub.
We need to merge this as soon as possible due to it pushing the wrong binaries to dockerhub using the latest tag. I recommend ignoring OpenLab CI errors and forcing it.
```release-note
NONE
```
=> Update CI conformance jobs

cluster/addons/rbac/cloud-controller-manager-roles.yaml
In [kubernetes/kubernetes/pkg/controller/client_builder.go](https://github.com/kubernetes/kubernetes/blob/bdc013ad57df721a148a5e15953c5a8b67efdeec/pkg/controller/client_builder.go#L174) it attempts to start a watch for new secrets if the secret containing a token for a service account does not exist the first time it checks. Without the watch permission for secrets this crashes the cloud-controller-manager and the pod restarts until the secret does exist.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #545 
```release-note
```
=> Give cloud-controller-manager permission to watch secrets

docs/expose-applications-using-loadbalancer-type-service.md, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
- Using a more meaningful name for load balancer created by Service.
- Support backward compatibility.
- Adding doc for LoadBalancer type Service guide.
```release-note
The load balancer name created by Service has been changed, now the name includes cluster name, Service namespace and Service name. The services created before this change are not affected.
```
=> Improve load balancer name

Gopkg.lock, docs/expose-applications-using-loadbalancer-type-service.md, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Add `X-Forwarded-For` support for the backend HTTP service. A new Service annotation `loadbalancer.openstack.org/x-forwarded-for` is introduced.
Test steps:
1. Create the echoserver service
```
$ kubectl run echoserver --image=gcr.io/google-containers/echoserver:1.10 --port=8080
$ cat <<EOF | kubectl apply -f -
kind: Service
apiVersion: v1
metadata:
name: echoserver
annotations:
loadbalancer.openstack.org/x-forwarded-for: "true"
spec:
type: LoadBalancer
selector:
run: echoserver
ports:
- protocol: TCP
port: 80
targetPort: 8080
EOF
```
1. Waiting for the service to get an external IP.
```
$ kubectl get svc
NAME         TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S) …
```
=> Support to keep original client IP for the Service

README.md
The link to the KEP that describes the original cloud controller
manager work was pointing to the generic KEPs repository. This commit
fixes the link so that readers don't have to go hunting for the link
in the new location.
=> trivial: Fix link in README.md

Gopkg.lock, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
**What this PR does / why we need it**: Extends support for listener [timeout values](https://developer.openstack.org/api-ref/load-balancer/v2/index.html?expanded=create-listener-detail#id34) to Kubernetes services via annotation
**Which issue this PR fixes**: fixes #588 by allowing the default listener timeout values of the loadbalancer Octavia creates for each Kubernetes LoadBalancer service to be individually overridden. For longer-living connections, unexpected disconnects/RST can be observed when a successfully negotiated connection reaches the [default timeout](https://github.com/kubernetes/cloud-provider-openstack/issues/588#issuecomment-482819223) values without activity. For example, if the `kube-apiserver` is placed behind an Octavia loadbalancer with the default listener …
=> Support listener timeouts as service annotations

Gopkg.lock, Makefile, cmd/cinder-csi-plugin/main.go, pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/controllerserver_test.go, pkg/csi/cinder/driver.go, pkg/csi/cinder/driver_test.go, pkg/csi/cinder/fake.go, pkg/csi/cinder/identityserver_test.go, pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/nodeserver_test.go, pkg/csi/cinder/sanity/fakecloud.go, pkg/csi/cinder/sanity/fakemetadata.go, pkg/csi/cinder/sanity/fakemount.go, pkg/csi/cinder/sanity/sanity_test.go, pkg/csi/cinder/utils.go
This PR adds support for running csi sanity tests, from csi-test/sanity, It adds a package sanity which provides fake cloud provider, fake metadata and fake mount
and instantiate cinder csi driver for running sanity tests.
This PR does not fix sanity test failures, for this a separate PR will be created. 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #469
Using Existing mock package for cloud provider, metadata and mount was not possible as mock function arguments comes csi-test/sanity package, and also it does not support conditional mocking.
```release-note
```
`None.`
=> Add Support for Running CSI Sanity Tests

cmd/client-keystone-auth/main.go, pkg/identity/keystone/token_getter.go
This PR adds the ability to specify a CA that isn't installed on the system to use for the client-kubernetes-auth plugin. Handled the same way that client cert and key are handled and keys off the OS_CACERT environment variable.
```release-note
Added support for specifying a certificate authority that isn't installed on the client machine via OS_CACERT environment variable.
```
=> Adding support for CA specfication

docs/using-keystone-webhook-authenticator-and-authorizer.md, pkg/identity/keystone/authenticator.go, pkg/identity/keystone/authenticator_test.go, pkg/identity/keystone/authorizer.go, pkg/identity/keystone/authorizer_test.go, pkg/identity/keystone/authorizer_test_policy_version2.json, pkg/identity/keystone/keystone.go, pkg/identity/keystone/policy.go, pkg/identity/keystone/sync.go
Improve k8s-keystone-auth authorization policy definition.
The current authorization policy setting is too complex and not flexible, especially for the fine-grained resource access control. With this PR, the cluster admin could define authorization policy as described in docs/using-keystone-webhook-authenticator-and-authorizer.md
The new version policy definition is still based on whitelist, which means the operation is allowed if any rule in the permissions is satisfied.
Version 1 definition is still supported and could be used together with version 2.
**Which issue this PR fixes**: fixes #550
You can use the image: docker.io/lingxiankong/k8s-keystone-auth:policy-version2 for testing. …
=> k8s-keystone-auth authorization policy definition version 2

pkg/csi/cinder/mount/mount.go, pkg/csi/cinder/mount/mount_mock.go, pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/nodeserver_test.go, pkg/csi/cinder/sanity/fakemount.go, pkg/util/metadata/metadata.go
This PR is to get the real device path from the node and not
to trust the device path returned by cinder which often leads to failed mount
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #531 
```release-note
```
=> Get real device path from node

docs/using-cinder-csi-plugin.md
Update the documentation to instruct the user to remove the place-holder
cloud config if it's already applied.  If this place-holder cloud config
is not removed, it will replace the valid cloud config when
manifests/cinder-csi-plugin is applied.
```release-note
```
=> Don't replace cloud config with place holder

docs/using-keystone-webhook-authenticator-and-authorizer.md, pkg/identity/keystone/authorizer.go, pkg/identity/keystone/authorizer_test.go, pkg/identity/keystone/authorizer_test_policy_version2.json
Support project ID in Keystone auth policy v2 definition.
In the current implementation, only project name is supported. With this PR,
the cluster admin could specify project ID or project name in the policy, e.g.
```
{
"users": {
"roles": ["viewer"],
"projects": ["demo", "cd08a539b7c845ddb92c5d08752101d1"]
},
"resource_permissions": {
"default/['*']": ["get", "list"]
}
}
```
So user in the project demo(project name) or
cd08a539b7c845ddb92c5d08752101d1(project ID) with the `viewer` role has the
permission to query resources in the default namespace.
Please use `lingxiankong/k8s-keystone-auth:policy-version2` for testing.
```release-note
```
=> k8s-keystone-auth: Support project ID in policy v2

manifests/cinder-csi-plugin/cinder-csi-nodeplugin-rbac.yaml, manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
This PR updates node-driver-registrar version to 1.1.0 and also
removes rbac policies which are not needed.
```release-note
```
=> Update node-driver-registrar version

cluster/images/flex-volume-driver/flexvolume-ds.yaml, examples/loadbalancers/README.MD, examples/loadbalancers/external-http-nginx.yaml, examples/loadbalancers/internal-http-nginx.yaml, examples/manila-provisioner/csi-cephfs/daemonsets.yaml, examples/manila-provisioner/csi-cephfs/statefulsets.yaml
DaemonSet, Deployment, and ReplicaSet resources will
no longer be served from extensions/v1beta1, apps/v1beta1,
or apps/v1beta2 and removed in v1.16. Migrate to the apps/v1 API,
available since v1.9. Existing persisted data can be retrieved
via the apps/v1 API.
```release-note
```
=> Migrate to the apps/v1 API group

docs/provider-configuration.md, pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_test.go
This commit adds a possibility to specify a domain name/id for a tenant other than the default one.
/kind feature
```release-note
Allow to specify a domain name/id for a tenant other than the default one for the OpenStack cloud provider.
```
=> Allow to specify a Tenant Domain Name/ID

docs/using-octavia-ingress-controller.md, pkg/ingress/config/config.go, pkg/ingress/controller/openstack/octavia.go, pkg/ingress/utils/utils.go
Add provider support in octavia-ingress-controller configuration.
For more details about provider in Octavia: <https://docs.openstack.org/octavia/latest/admin/providers.html>
An example config file:
```
cluster-name: devstack-k8s
kubernetes:
api-host:
kubeconfig: /home/ubuntu/.kube/config
openstack:
user-id: ${user_id}
password: password
project-id: ${project_id}
auth-url: ${auth_url}/v3
region: RegionOne
octavia:
subnet-id: ${subnet_id}
floating-network-id: ${public_net_id}
manage-security-groups: false
provider: amphora
```
**Which issue this PR fixes**: fixes #610
=> octavia-ingress-controller: Add provider configuration

docs/provider-configuration.md, pkg/csi/cinder/fake.go, pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/nodeserver_test.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_mock.go
This PR adds support for returning max volume limit in _CSI NodeGetInfo_ call, It returns MaxVolumesPerNode in CSINodeGetInfo response, which defaults to 256(same as intree driver), This can be configured via _node-volume-attach-limit_ from cloud config file.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #572
```release-note
```
=> Add Max Vol Limit for Cinder CSI

cluster/images/cinder-csi-plugin/Dockerfile
This PR adds support for the csi-node-plugin to format disks using xfs.
When building the csi-node-plugin using `make image-csi-plugin` there will currently be no `xfsprogs` installed.
```release-note
Added support for xfs to csi-node-provisioner
```
=> csi: Support xfs filesystem for csi-node-provisioner

docs/using-keystone-webhook-authenticator-and-authorizer.md
* Fix some typos
Documentation update: I ran into some issues following the documentation, because the name of the ConfigMap used was inconsistent.
fixes the name of the ConfigMap so it's consistent across the whole document, and some small typos.
=> keystone-webhook-documentation: Use consistent names for ConfigMap

Gopkg.lock, Makefile, cluster/images/magnum-auto-healer/Dockerfile, cmd/magnum-auto-healer/main.go, docs/using-magnum-auto-healer.md, manifests/magnum-auto-healer/magnum-auto-healer.yaml, pkg/autohealing/OWNERS, pkg/autohealing/cloudprovider/cloudprovider.go, pkg/autohealing/cloudprovider/openstack/provider.go, pkg/autohealing/cloudprovider/register/register.go, pkg/autohealing/cmd/root.go, pkg/autohealing/config/config.go, pkg/autohealing/controller/controller.go, pkg/autohealing/healthcheck/healthcheck.go, pkg/autohealing/healthcheck/plugin_endpoint.go, pkg/autohealing/healthcheck/plugin_nodecondition.go, pkg/autohealing/utils/utils.go
Add k8s-auto-healer for the Kubernetes cluster running on top of cloud environment, OpenStack is the default cloud provider implementation.
k8s-auto-healer ensures that the running Kubernetes nodes are healthy by monitoring the nodes’ status periodically, searching for unhealthy instances and triggering replacements when needed, maximizing your cluster’s efficiency and performance.
The cluster provider and health check mechanism are both pluggable and easy to integrate with other clouds and customized health check approaches.
For the openstack cloud provider:
- Only the Magnum cluster is supported, doesn't support the Kubernetes cluster created in other ways(kops, cluster-api, kubeadm, etc.)
- Auto-healing is achieved via Heat stack update, which …
=> Add magnum-auto-healer for the Kubernetes cluster

pkg/csi/cinder/mount/mount.go, pkg/csi/cinder/nodeserver.go
Handle teardown of cinder disks which return an "Input/Output" during `os.Stat` system call.
It is a reproducible problem which exists and persists if the disk is already detached via `nova volume-detach` but still mounted inside the operating system.
Fixes the issue on the Cinder CSI side mentioned in https://github.com/kubernetes/kubernetes/issues/77969
As discussed in Mattermost :-)
The problem is reproducible as follows:
* create statefulset [gist](https://gist.github.com/chrischdi/39141aaf5fc3b2cb48200d216b5ce7b4)
* detach cinder disk manually (to …
=> Fix csi cinder disk teardown on EIO errors

docs/using-controller-manager-with-kubeadm.md
This clarifies the kubeadm documentation for cloud-provider-openstack
This is based on troubleshooting assistance provided by a_sykim in the k8s slack channel #sig-cloud-provider 
- InitializerConfiguration was removed in v1.14 and is no longer referenced in the documentation linked. 
- A known issue related to a race condition causes external addresses to not be listed when checking on nodes. A notice was put in to prevent the user from wondering why this is occurring. https://github.com/kubernetes/kubernetes/pull/75229
=> kubeadm documentation update

pkg/csi/manila/shareadapters/nfs.go
kubernetes-csi/csi-driver-nfs expects the volumeContext passed in to it to have a map with "server" and "share" fields but we are passing "server" and "path" in the volumeContext map.  Because it looks for "share", "path" is ignored and the mount is done with "/" rather than the full export path.
So change the map here to provide the expected "share" instead of "path".
Fixes #673 
```release-note
```
=> Use ``share`` rather than ``path`` for NFS

pkg/csi/cinder/nodeserver.go
actually, err is not nil means node is not "",so
no need to double check here to make logic complicate
minor refactory
minor refactory to remove complex 
```release-note
NONE
```
=> Remove unnucessary log and adjust some logic

pkg/csi/cinder/sanity/fakecloud.go
Currently, error returned by getVolume is not recognized as
NotFound error, so still sanity test still shows the error.
This commit is to fix the same.
```release-note
```
=> Fix getVolume to return proper error

pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_instances.go, pkg/csi/cinder/openstack/openstack_mock.go, pkg/csi/cinder/sanity/fakecloud.go
This commit checks if server available with speified instanceID or
not in ControllerPublish/Unpublish Volume. This is in reference
to adhere to csi spec 1.0.0
```release-note
```
=> Add check for node to fix sanity errors

pkg/csi/cinder/driver.go, pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/nodeserver_test.go, pkg/csi/cinder/utils.go
This commit adds cloud instance to nodeserver to be able to query openstack and adds
error codes as per csi spec.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #661 
```release-note
```
=> Adds openstack instance to nodeserver

README.md
When reading the main README, readers could not understand manila-csi-plugin is implemented already because of the lack of the link.
This adds a link to using-manila-csi-plugin.md to main README.
```release-note
NONE
```
=> Add link to using-manila-csi-plugin.md

pkg/autohealing/controller/controller.go
Decrease the default log print when there is no issues, like the following:
```
I0714 11:35:23.622809       1 controller.go:232] No health check defined for master node, skip.
I0714 11:34:53.622667       1 controller.go:352] Master nodes are healthy
I0714 11:34:53.743112       1 controller.go:373] Worker nodes are healthy
```
It's impossible to improve all the log levels for the service in one patch, we will keep doing that. We use [this guide](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md) for the logging.
```release-note
```
=> Improve magnum-auto-healer log

pkg/autohealing/controller/controller.go
Removing the broken node from the current cluster before doing an actual repair which can avoid some potential conflicts on the cloud providers side.
Based on the current implementation for the OpenStack cloud provider, the new node may be failed to start due to a timing issue.
=> Remove broken node before repairing

pkg/share/manila/util.go
Corner cases like 1000G and 2000G were being translated
to 1G and 2G when sending to manila. Use ScaledValue to
round to Gigabytes.
Signed-off-by: Spyros Trigazis <spyridon.trigazis@cern.ch>
Corner cases like 1000G and 2000G were being translated
to 1G and 2G when sending to manila. 
reproducer:
```
package main
import (
"fmt"
"strconv"
v1 "k8s.io/api/core/v1"
"k8s.io/apimachinery/pkg/api/resource"
"k8s.io/client-go/kubernetes/scheme"
)
var filecontent = `
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: deleteme
spec:
accessModes:
- ReadWriteMany
resources:
requests:
storage: "1000G"
storageClassName: meyrin-cephfs-hyperconverged
`
func main() {
decode := scheme.Codecs.UniversalDeserializer().Decode …
```
=> Fix getStorageSizeInGiga

pkg/autohealing/cloudprovider/cloudprovider.go, pkg/autohealing/cloudprovider/openstack/provider.go, pkg/autohealing/cloudprovider/register/register.go, pkg/autohealing/controller/controller.go
Delete Kubernetes Node after updating the Heat stack, this is to avoid the following issues:
- If an error happens during the repairing process in the cloud provider, there is no chance to fix the failed node in the future because the Node object has been deleted from Kubernetes.
- If the magnum-auto-healer(master) is running on a failed node, there is no chance for the slaves to fix that node because the Node object has been deleted from Kubernetes.
**Which issue this PR fixes**: fixes #700
```release-note
```
=> magnum-auto-healer: Remove Node object after Heat stack update

pkg/cloudprovider/providers/openstack/openstack.go
accordingly to
https://developer.openstack.org/api-ref/identity/v3/index.html#application-credentials
we can add ccm application id into cloud.conf to do validation
fix bug 421 to add application cred validation
fixes 421
```release-note
to be add here:
```
=> Add application id into ccm

Makefile, cmd/cinder-csi-plugin/main.go, cmd/cinder-provisioner/main.go, cmd/k8s-keystone-auth/main.go, cmd/manila-csi-plugin/main.go, cmd/manila-provisioner/main.go, cmd/openstack-cloud-controller-manager/main.go, pkg/autohealing/cloudprovider/register/register.go, pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_test.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_test.go, pkg/csi/manila/manilaclient.go, pkg/csi/manila/manilaclient_test.go, pkg/flexvolume/cinder_client.go, pkg/identity/keystone/keystone.go, pkg/identity/keystone/keystone_test.go, pkg/identity/keystone/token_getter.go, pkg/ingress/controller/openstack/client.go, pkg/kms/barbican/barbican.go, pkg/share/manila/client.go, pkg/share/manila/client_test.go, pkg/version/version.go, pkg/volume/cinder/volumeservice/connection.go, pkg/volume/cinder/volumeservice/connection_test.go
Adds the cloud provider version string to gophercloud user-agent string, and adds a `user-agent` flag which can be used to add any other information.
I.e in Magnum, for the cloud controller manager configuration `--user-agent="cluster/${CLUSTER_UUID}"`, to be able to see which clusters are responsible for which requests.
If there are no objections to the code for the cloud controller manager then I will make the same changes for the keystone and barbican components (and any others that are suggested)
**Which issue this PR fixes** : fixes #606 
Since there is only a single flag, to add more than one thing to the user-agent would be like
`--user-agent="abc/123 cluster/${CLUSTER_UUID}"`
but in yaml it would look …
=> Add more information to gophercloud user-agent string

Gopkg.lock, pkg/csi/manila/controllerserver.go, pkg/csi/manila/manilaclient.go, pkg/csi/manila/share.go, pkg/csi/manila/snapshot.go, pkg/csi/manila/util.go, pkg/csi/manila/volumesource.go
csi-manila currently leaks Manila resources if an error occurs during share/snapshot provisioning, they're simply left on the backend without any sort of clean up.
This PR first determines the type of the error that has occurred using the Status field of the share/snapshot and [User messages API](https://developer.openstack.org/api-ref/shared-file-system/#user-messages-since-api-2-37) (better error reporting, easier troubleshooting for the users!) and then attempts to clean up the failed resource.
User messages API requires minimum Manila microversion 2.37 (Queens)
```release-note
CSI Manila now requires Manila version >=2.37
```
=> csi-manila: roll-back storage resources on failure

Makefile
manila-csi-plugin is missing from `make build`, similar to #655.
```release-note
```
=> Add manila-csi-plugin to make build

Gopkg.lock, docs/provider-configuration.md, pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_volumes.go
Cinder v1 is deprecated in Juno release of Openstack and removed completely in Queens (https://docs.openstack.org/releasenotes/cinder/queens.html) . This PR removes the support for the same in cloudprovider.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #695 
```release-note
Cinderv1 support is removed from cloudprovider.
```
=> Remove cinderv1 support from cloudprovider

docs/provider-configuration.md, pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_mock.go, pkg/csi/cinder/openstack/openstack_volumes.go, pkg/csi/cinder/sanity/fakecloud.go
Values of BlockStorageOpts set in config file are not getting
reflected as of now. This PR is to fix the same
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #633
```release-note
```
=> Fix GetMaxVolLimit to return correct value

docs/using-cinder-csi-plugin.md, manifests/cinder-csi-plugin/csi-cinder-driver.yaml
CSIDriver objects needs to created after v1.14 as
cluster-driver-registrar is deprecated
```release-note
NONE.
```
=> Add CSIDriver object

docs/provider-configuration.md
More description for `manage-security-groups` when using Octavia.
```release-note
```
=> OCCM doc: manage-security-groups not needed when Octavia is used

pkg/identity/keystone/authorizer.go, pkg/identity/keystone/authorizer_test.go, pkg/identity/keystone/authorizer_test_policy_version2.json
Make the namespace and resource name in the permission definition to be case insensitive.
**Which issue this PR fixes**: fixes #725
```release-note
```
=> k8s-keystone-auth: Resource name should be case insensitive

cmd/manila-csi-plugin/main.go, pkg/csi/manila/csiclient.go, pkg/csi/manila/csiclient/builder.go, pkg/csi/manila/csiclient/client.go, pkg/csi/manila/csiclient/interface.go, pkg/csi/manila/driver.go, pkg/csi/manila/nodeserver.go
Part of https://github.com/kubernetes/cloud-provider-openstack/issues/714
Continuing in an effort of integrating the csi-sanity test suite into CSI Manila, this is the second patch out of 4:
This PR moves the CSI client into a separate package, which brings `Node`, `Identity` and `Builder` interfaces. This in turn makes it possible to have various implementations for CSI clients - e.g. creating a fake CSI client which is a prerequisite for sanity/unit tests.
```release-note
NONE
```
=> [csi-manila] CSI client moved into a separate package

pkg/csi/manila/controllerserver.go, pkg/csi/manila/nodeserver.go, pkg/csi/manila/share.go, pkg/csi/manila/snapshot.go, pkg/csi/manila/util.go, pkg/csi/manila/volumesource.go
Part of #714
Continuing in an effort of integrating the csi-sanity test suite into CSI Manila, this is the third patch out of 4:
While testing the driver against the csi-sanity test suite, following errors were found:
* missing ValidateVolumeCapabilities in Controller Plugin
* validateNode{Unstage,Unpublish}Request functions were missing checks for empty staging/target paths
* verifySnapshotCompatibility's check for source volume ID was incorrect
this PR fixes the issues mentioned above and cleans up the codebase a bit
```release-note
NONE
```
=> [csi-manila] fixed incorrect behaviour discovered by csi-sanity test suite

docs/using-barbican-kms-plugin.md
Yields
```
-bash-4.2# openstack secret order create --name k8s_key --algorithm aes --mode cbc --bit-length 256 key  --payload-content-type=application/octet-stream key
usage: openstack secret order create [-h] [-f {json,shell,table,value,yaml}]
[-c COLUMN] [--max-width <integer>]
[--fit-width] [--print-empty]
[--noindent] [--prefix PREFIX]
[--name NAME] [--algorithm ALGORITHM]
[--bit-length BIT_LENGTH] [--mode MODE]
[--payload-content-type PAYLOAD_CONTENT_TYPE]
[--expiration EXPIRATION]
[--request-type REQUEST_TYPE]
[--subject-dn SUBJECT_DN]
[--source-container-ref SOURCE_CONTAINER_REF]
[--ca-id CA_ID] [--profile PROFILE]
[--request-file REQUEST_FILE]
type
```
When run with latest client
Set to
`-bash-4.2# openstack secret order create --name k8s_key --algorithm aes --mode cbc …
=> Bad cmd arg in doc

pkg/csi/cinder/controllerserver.go
we should allow volume not found error as it's normal case
and avoid return error
Fixes: #634 
```release-note
```
=> check not found before return error

pkg/autohealing/cloudprovider/openstack/provider.go, pkg/autohealing/cloudprovider/register/register.go, pkg/autohealing/controller/controller.go, pkg/autohealing/healthcheck/healthcheck.go
Use Magnum resize API for the worker node repair(resize doesn't support master node yet) which could change the cluster status as expected.
fixes #746
Partial-Implements: #648
=> magnum-auto-healer: Use Magnum resize API for the worker node repair

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
This fixes the lbaas control loop's EnsureLoadBalancer() function so it no longer deletes the LB if something went wrong when reconciling the LB's security groups. With the current master, if you have an LB service and associated LB already up and running and working fine, and then during a reconcile loop (which shouldn't change anything) e.g. the OpenStack API is down temporarily at the wrong moment (i.e. if it's still up during the LB and listener reconciliation, but then down during the SG reconciliation), then the whole LB will be deleted. We saw this exact thing happen in a real world customer application, which went offline because of if (the LB is recreated shortly after, but likely with a different floating IP).
Deleting the LB in case of …
=> Do not Delete LB in Case of Security Group Reconciliation Errors

.zuul.yaml
OpenLab team would not be able to run octavia CI job for sometime
Disable the job till then.
ref #750 
```release-note
```
`NONE`
=> Disable Octavia Job

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Upgraded k8s cluster cannot update the loadbalancer:
```
failed to update load balancer hosts for service kube-system/nginx-ingress-controller: failed to find object
```
When the LB has an old-style legacy name, the LB cannot be detected.
```release-note
fix loadbalancer name detection in the UpdateLoadBalancer func
```
=> Fix loadbalancer legacy name detection

Gopkg.lock, pkg/ingress/controller/controller.go
Completes the move of Ingress API from `extensions/v1beta1` to `networking/v1beta1`. When this was done in PR https://github.com/kubernetes/cloud-provider-openstack/pull/658 some parts of the code still used `extension/v1beta1` like the Ingress `Informer` initialization and the `Lister` import.
Fixes #754 
```release-note
NONE
```
=> Change to networking/v1beta1 on dependent components and packages

hack/make.sh
The Docker based build still references the golang:1.10 build container. The code references variables in `crypto/tls` that are only available stating with golang:1.12.
```release-note
Update Docker build to use Golang 1.12
```
=> Update Docker build to use Golang 1.12

docs/provider-configuration.md
Add no support in CSI cinder on cinder v2 API 
```release-note
```
=> Add info about v2 VPI not support in CSI

pkg/csi/cinder/driver.go, pkg/csi/cinder/driver_test.go
This PR is to bump the CSI cinder driver version to 1.1.0
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #683 
```release-note
```
=> Bump cinder CSI driver version to 1.1.0

docs/using-controller-manager-with-kubeadm.md
Adds export variable CLOUD_CONFIG so that the `kubectl create secret` command doesn't hang.
People can figure it out by their own, but it is just to be precise in the documentation
=> Add variable export in cloud controller doc

Gopkg.lock, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go, pkg/util/openstack/loadbalancer.go, pkg/util/util.go
Support 'loadBalancerSourceRanges' for Service(Octavia based).
If specified, the Service will be restricted to the specified client IP ranges.
Only Octavia(API version >= v2.12) is supported, otherwise `loadBalancerSourceRanges` is ignored.
Example:
```
kind: Service
apiVersion: v1
metadata:
name: test
namespace: default
spec:
type: LoadBalancer
loadBalancerSourceRanges:
- 192.168.32.1/24
selector:
run: echoserver
ports:
- protocol: TCP
port: 80
targetPort: 8080
```
fixes #770
This PR also contains a little bit refactoring by moving OpenStack API calls to a repo level util file. In the future, all OpenStack related API calls should live there to avoid code duplication.
**Release …
=> OCCM: Support 'loadBalancerSourceRanges' for Service

pkg/util/mount/mount_linux.go
This fixes the issue where "childFD" from syscall.Openat is assigned to
a local variable inside the for loop, instead of the correct one in the
function scope. This results in that when trying to close the "childFD"
in the function scope, it will be equal to "-1", instead of the correct
value.
See: https://github.com/kubernetes/kubernetes/pull/79534, https://github.com/kubernetes/kubernetes/pull/82873 & https://github.com/kubernetes/kubernetes/pull/82980
```release-note
Fix possible fd leak and closing of dirs in doSafeMakeDir
```
=> Fix closing of dirs in doSafeMakeDir

manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
Removes duplicate mount of /var/lib/kubelet and /var/lib/kubelet/pods which results in an error.
Duplicate https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml#L95 introduced by PR #563 
fixes #772
I left /var/lib/kubelet mounted and removed mounting /var/lib/kubelet/pods again
=> Fix error when mounting /var/lib/kubelet/pods

pkg/csi/cinder/openstack/openstack_volumes.go
In case, when the Cinder API doesn't support the **3.42** microversion, the whole cinder client can fail. This PR covers this case and restores the original microversion version, once the resize is performed. The similar change was already discussed in https://github.com/kubernetes/cloud-provider-openstack/pull/748#discussion_r321064005
```release-note
Cinder CSI: Restore the original microversion, when the resize was made
```
=> Cinder CSI: Restore the original microversion, when the resize was made

pkg/kms/barbican/barbican.go, pkg/kms/barbican/fake_barbican.go, pkg/kms/server/server.go, pkg/kms/server/server_test.go
It adds a persistent barbican client and avoid keystone auth on every Encryption/Decryption call.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #787
@adisky I'm probably missing some not obvious use cases, which led to the current logic. Feel free to correct me if I'm wrong.
```release-note
Barbican KMS: use persistent client
```
=> Barbican KMS: use persistent client

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go, pkg/util/openstack/network.go
Fix deleting the internal LoadBalancer service.
**Which issue this PR fixes**: fixes #794
Move some floating IP related functions to the project scope utility file.
=> occm: Fix deleting internal service

.zuul.yaml
This commit adds 1.16 e2e conformance job and removes 1.13 e2e
conformace job
Depends on : https://github.com/theopenlab/openlab-zuul-jobs/pull/676
```release-note
```
=> Add 1.16 conformance job

Gopkg.lock, cmd/manila-csi-plugin/main.go, examples/manila-csi-plugin/helm-deployment/templates/controllerplugin-statefulset.yaml, pkg/csi/manila/capabilities/manilacapabilities.go, pkg/csi/manila/capabilities/util.go, pkg/csi/manila/compatibility/compatibility.go, pkg/csi/manila/controllerserver.go, pkg/csi/manila/driver.go, pkg/csi/manila/manilaclient/client.go, pkg/csi/manila/manilaclient/interface.go, pkg/csi/manila/nodeserver.go, pkg/csi/manila/options/compatibilityoptions.go, pkg/csi/manila/sanity/fakemanilaclient.go, pkg/csi/manila/sanity/sanity_test.go, pkg/csi/manila/util.go, pkg/csi/manila/util/manila.go
Part of https://github.com/kubernetes/cloud-provider-openstack/issues/720
This PR:
* adds `capabilities` package: handles retrieval and recognizing of Manila capabilities from share types' extra specs
* adds `compatibility` package: contains an abstraction for compatibility layers. The idea is that if a certain capability is reported as missing, AND there exists compatibility layer for this capability of a certain share protocol, the driver will use the compatibility layer to fill in the missing caps.
* controller server now checks for available compat layers if necessary, specifically for the `create_share_from_snapshot_support` capability
* added `--compatibility-settings=...,SETTINGS` cmd flag - there are no actual compat settings yet so no …
=> [csi-manila] added a basis for compatibility layers

Gopkg.lock, Gopkg.toml, cmd/openstack-cloud-controller-manager/main.go
This commit updates k8s version to 1.17.0-alpha.1 .
It is required for enabling e2e tests.
```release-note
```
=> Update the dependencies to kubernetes-1.17.0-alpha.1

examples/cinder-csi-plugin/block/block.yaml
In ../nginx.yml you use the correct provisioner for the StorageClass:
provisioner: cinder.csi.openstack.org
```release-note
```
=> Fix wrong provisionor

pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_routes_test.go, pkg/cloudprovider/providers/openstack/openstack_test.go
Keystone V2 support was removed due to the auth code refactoring in #733. This PR should bring the support back.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #803
In #733 I accidentally used the `openstack.AuthenticateV3` instead of the `openstack.Authenticate` func. `openstack.Authenticate` is a wrapper around the `AuthenticateV2` and `AuthenticateV3`, therefore it should be fine to call it to keep the identity v2 support.
```release-note
Fix the bug, when keystone v2 support was removed
```
=> Auth: bring back identity v2 support

pkg/csi/cinder/mount/mount.go
This helps on Openstack envrionments using virtio-blk or virtio-scsi
where udev initially is not able to detect the serial attribute.
Executing probeVolume will execute `udevadm trigger` and by doing that
the serial attribute gets read and proper symlinks are getting created
by udev and csi will be able to detect the disk.
fixes #705 
```release-note
```
=> fix GetDevicePath to execute probeVolume

cluster/addons/rbac/cloud-controller-manager-roles.yaml
When deploying CCM with the RBAC settings from https://github.com/kubernetes/cloud-provider-openstack/tree/master/cluster/addons/rbac, it is not allowed to use the coordination API.
Also see comment: https://github.com/kubernetes/cloud-provider-openstack/issues/829#issuecomment-557504452
```release-note
```
=> Added permissions to coordination api for CCM

go.mod, go.sum, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go, pkg/util/openstack/loadbalancer.go
Only updating the listener when Octavia supports VIP ACL, also fixes the way for how to check if a feature is supported in the deployed Octavia version.
fixes #829
=> occm: Fix updating lb listener with allowed CIDR

docs/expose-applications-using-loadbalancer-type-service.md, docs/provider-configuration.md, pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Add support for creating loadbalancer's VIP using Neutron Network ID.
In addition to Subnet ID, Neutron LBaaS v2 API support creation of loadbalancers using Neutron Network ID. A subnet is chosen from network which has available IP addresses. In case of Octavia backend, IPv4 subnets are preferred over IPv6 subnets.
The network ID can be specified in cloud-config file or by using the annotation `loadbalancer.openstack.org/network-id`
```release-note
```
=> Add support for creating loadbalancer's VIP using Neutron Network ID

docs/migrate-to-ccm-with-csimigration.md
This is a step by step guide to show how to get from in-tree
cloud-provider to use the external one. This guide makes it possible to
migrate everything to CCM, but stay with in-tree volume provisioning for
a while, in order to enable CSIMigration after a while (e.g. when
CSIMigration is GA, or whatever policy one has).
We don't have documentation for the in-tree to openstack-cloud-controller-manager yet.
fixed: #374
```release-note
```
=> Documented migration to CCM with CSIMigration enabled

docs/using-cinder-csi-plugin.md
when doing CSI test, my openstack cloud has cacert defined
this is not clearly documented in the doc so I encountered
cert not found issue, this PR added that info for reference
```release-note
```
=> [doc] Add cacert using for cinder plugin

pkg/cloudprovider/providers/openstack/openstack_volumes.go, pkg/csi/cinder/mount/mount.go
candidateDeviceNodes now also accept the full volumeID.
This seems to be needed on OpenStack Train and/or newer versions of libvirt (See https://github.com/kubernetes/cloud-provider-openstack/issues/852#issuecomment-559105110)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #852 
```release-note
```
=> Added full cinder ID to candidateDeviceNodes

.zuul.yaml, Makefile, cmd/tests/cinder_csi_e2e_suite_test.go, go.mod, go.sum, test/cinder-testdriver.go, test/csi-volumes.go
This PR adds e2e test framework for cinder CSI driver.
This PR enables only dynamic provisioning tests.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #690 
PR to enable the job in openlab is here https://github.com/theopenlab/openlab-zuul-jobs/pull/690
```release-note
Adds e2e test framework for cinder csi driver.
```
=> Add e2e tests for cinder CSI

pkg/cloudprovider/providers/openstack/openstack_instances.go, pkg/cloudprovider/providers/openstack/openstack_test.go
Makes the cloudprovider cope with providerIDs that do not have a leading `provider://`, bandaid workaround for https://github.com/kubernetes/kubernetes/issues/85731 and works towards fixing https://github.com/kubernetes/cloud-provider-openstack/issues/856
```release-note
none
```
/kind bug
/assign @chrigl
=> Allow providerID without leading providerName

pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_test.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_test.go, pkg/volume/cinder/volumeservice/connection.go, pkg/volume/cinder/volumeservice/connection_test.go
This PR is to drop support to load config from Env .
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #823 
https://github.com/kubernetes/kubernetes/issues/81117
```release-note
Removed support to load config from env variables.
```
=> Remove loading config from Env Variables

manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
This PR adds sidecar timeouts to avoid error events like:
> connection.go:184] GRPC error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Default timeout is 15 seconds. 3 minutes should be enough to prepare a volume and attach it to a VM.
```release-note
Cinder CSI: added attach/detach timeouts
```
=> Cinder CSI: add attach/detach timeouts

pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_test.go
This PR sets permanent node IP addresses order, sorted by a network name.
This is a workaround for the #863 bug report. It doesn't help, when the first interface name appears at the very end after the alphabetical sorting. However this fix prevents LB members modification on each reconciliation loop.
```release-note
CCM: Set permanent node addresses order, sort networks by name
```
=> CCM: Set permanent node addresses order

.zuul.yaml
This PR removed 1.14 job from pipeline and adds 1.17 conformance job
fixes #
```release-note
NONE
```
=> Add 1.17 e2e conformance job

docs/getting-started-provider-dev.md, go.mod, pkg/cloudprovider/providers/openstack/openstack.go
This PR adds verbose OpenStack API request/response debugging, when `--v=6` (or higher) verbosity is set.
fixes #840 
```release-note
Core: Enable OpenStack API debugger, when verbosity is set to 6 or higher
```
=> Core: Enable OpenStack API debugger, when verbosity is set to 6

pkg/csi/cinder/nodeserver.go
NodeUnpublishVolume and NodeUnstageVolume should just return NotFound if
the volume with the volume_id does not exist. Meaning in this case...
does not exist in openstack any more. Not being mounted any more is a
valid case. Imaging e.g. umount, pv updated, another trigger of umount.
https://github.com/container-storage-interface/spec/blob/master/spec.md#nodeunpublishvolume-errors
https://github.com/container-storage-interface/spec/blob/master/spec.md#nodeunstagevolume-errors
This is also important to pass the k8s CSIMigration e2e test suite. We want to move …
=> [cinder-csi-plugin] Returned non-err if volume not mounted

pkg/share/manila/share.go
The AvailablityZone option was lost for creating manila share persistent volume. Such an option comes from StorageClass and used for the right location of created share (it depends from topology or StorageClass share options).
fixes https://github.com/kubernetes/cloud-provider-openstack/issues/899
```release-note
NONE
```
=> [manila-provisioner]: Added AvailabilityZone option to CreateOpts struct for manila share pv

go.mod, pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_instances.go, pkg/cloudprovider/providers/openstack/openstack_routes.go, pkg/cloudprovider/providers/openstack/openstack_test.go
This PR sets predictable server IP addresses order:
1) interfaces private IPs
2) access IPs
3) metadata hostname
4) server object Addresses
fixes #863
```release-note
CCM: set predictable and proper server IP addresses order
```
=> CCM: set predictable and proper server IP addresses order

.zuul.yaml
This PR adds Zuul CI job for the Manila CSI plugin
**Which issue this PR fixes**: fixes https://github.com/kubernetes/cloud-provider-openstack/issues/630
```release-note
NONE
```
=> add Zuul CI job for csi-manila

docs/using-cinder-csi-plugin.md
This PR adds documentation for Volume Cloning feature.
fixes #644
```release-note
NONE
```
=> [cinder-csi-plugin] Add cloning docs

pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_mock.go, pkg/csi/cinder/openstack/openstack_snapshots.go, pkg/csi/cinder/sanity/fakecloud.go
like volume, we need create description and prop for snapshot
(part) of the result looks like:
+--------------------------------------------+----------------------------------------------+
| created_at                                 | 2019-06-28T01:25:10.000000                   |
| description                                | Created by OpenStack Cinder CSI driver       |
| id                                         | 823c9947-b8ee-464a-9413-eff84869b098         |
| properties                                 | cinder.csi.openstack.org/cluster='ClusterID' |
+--------------------------------------------+----------------------------------------------+
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
=> create tags and descriptions for snapshot

.github/PULL_REQUEST_TEMPLATE.md
The binaries affected:
What this PR does / why we need it:
this PR fix inaccessible links in pr template
Which issue this PR fixes:
fixes https://github.com/kubernetes/cloud-provider-openstack/issues/888
Special notes for reviewers:
Release note:
NONE
=> update links in pr template

examples/manila-csi-plugin/helm-deployment/values.yaml, manifests/manila-csi-plugin/csi-controllerplugin.yaml
This PR bumps the versions for csi-provisioner and csi-snapshotter sidecar containers in csi-manila deployments. The update was supposed to be a part of https://github.com/kubernetes/cloud-provider-openstack/pull/846 but got lost along the way.
```release-note
manila-csi-plugin: bumped csi-provisioner to 1.4.0 and csi-snapshotter to 1.2.2
```
=> [manila-csi-plugin] CSI sidecar containers version bump

manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
during some debug found some logs are not enabled by default
and not consistent for all containers as well, add this PR
to make them verbose and consistent across pod
fixes #
```release-note
NONE
```
=> nit , cinder csi: remove default verbose flag

cluster/images/barbican-kms-plugin/Dockerfile, cluster/images/cinder-provisioner/Dockerfile, cluster/images/controller-manager/Dockerfile, cluster/images/flex-volume-driver/Dockerfile, cluster/images/magnum-auto-healer/Dockerfile, cluster/images/manila-csi-plugin/Dockerfile, cluster/images/manila-provisioner/Dockerfile, cluster/images/octavia-ingress-controller/Dockerfile, cluster/images/webhook/Dockerfile
The docker base image `alpine:3.7` is outdated and is replaced by the current release `3.11`.
There are several vulnerabilities reported in these old base images (e.g. for the included packages busybox-1.27.2-r11 and ssl_client-1.27.2-r11).
The affected images are:
- k8scloudprovider/openstack-cloud-controller-manager
- k8scloudprovider/barbican-kms-plugin
- k8scloudprovider/cinder-provisioner
- k8scloudprovider/cinder-flex-volume-driver
- k8scloudprovider/magnum-auto-healer
- k8scloudprovider/manila-csi-plugin
- k8scloudprovider/manila-provisioner
- …
=> Update alpine base image from 3.7 to 3.11

pkg/csi/cinder/controllerserver.go
At the moment we have a couple of flaky test in the CSIMigration effort.
During investigation, I found out that we have a race condition in the code in case of unattach a volume from a node. When either the OpenStack VM or Volume is gone, the `ControllerUnpublishVolume` function returns `csi.NotFound`. In case of CSIMigration this means being recalled over and over again with always the same result... `csi.NotFound`.
This PR changes: When either the volume or the instance in openstack is
already gone, the ControllerUnpublishVolume assumes the volume is not …
=> csi-cinder-controller: changed NotFound behaviour of ControllerUnpublishVolume

go.mod, go.sum
This PR updates gophercloud version to include the fix https://github.com/gophercloud/gophercloud/pull/1829
fixes #923
```release-note
NONE
```
=> Update gophercloud version

go.mod, go.sum, pkg/ingress/controller/controller.go, pkg/ingress/controller/openstack/client.go, pkg/ingress/controller/openstack/octavia.go, pkg/util/openstack/keymanager.go, pkg/util/openstack/loadbalancer.go
Support to create TLS Ingress.
This implementation for octavia-ingress-controller requires the TLS secret must exist when creating the Ingress. In the future, we could consider to create the secret on the fly with integration of e.g. cert-manager.
The TLS support requires OpenStack Barbican deployed in the cloud, TLS Ingress creation will fail if Barbican is not available.
fixes #287
Steps to test:
1. Preprae for the TLS secret, make sure to specify the server name in the CN field of the certificate, in this example, we use `www.example.com` as the server name.
```
$ ll
total 32
-rw-rw-r-- 1 ubuntu ubuntu 1346 Feb  7 11:01 ca.crt
-rw-rw-r-- 1 ubuntu ubuntu …
```
=> [octavia-ingress-controller] Support TLS in Ingress

docs/using-octavia-ingress-controller.md
Add document for creating TLS Ingress.
fixes #
```release-note
NONE
```
=> [octavia-ingress-controller]: TLS Ingress doc

.zuul.yaml, tests/e2e/cloudprovider/test-lb-service.sh
The script will be used for the CI job cloud-provider-openstack-acceptance-test-lb-octavia, the job will be re-enabled after the openlab change https://github.com/theopenlab/openlab-zuul-jobs/pull/792 is ready.
fixes #750
Currently, the test is running against an existing Kubernetes cluster in Catalyst Cloud, so the job has to be running in serial to avoid conflict, this is acceptable given the current development work of openstack-cloud-controller-manager is not so busy. …
=> [OCCM] Enable OCCM CI job

docs/expose-applications-using-loadbalancer-type-service.md
Docs update. Mention that x-forwarded-for is only supported in LBaas Octavia
```release-note
NONE
```
=> [openstack-cloud-controller-manager] Docs: Mention that x-forwarded-for is only supported in LBaas Octavia

.zuul.yaml, README.md, manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml, manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
As Cinder CSI Plugin has more advantages over the FlexVolume plugin. Although FlexVolume plugin is still maintained by Kubernetes developers, new functionality will only be added to CSI, not to FlexVolume.
This PR disables the CI job `cloud-provider-openstack-acceptance-test-flexvolume-cinder`.
fixes #
```release-note
NONE
```
=> [cinder-flexvolume-driver] Disable the CI job

pkg/csi/manila/csiclient/builder.go, pkg/csi/manila/csiclient/client.go, pkg/csi/manila/csiclient/interface.go, pkg/csi/manila/identityserver.go, pkg/csi/manila/sanity/fakecsiclient.go
csi-manila is built using proxy architecture - it relies on a partner node plugin to do the node operations (e.g. mounts) on behalf of csi-manila.
Querying csi-manila for its readiness ([`Probe` RPC](https://github.com/container-storage-interface/spec/blob/master/spec.md#probe) of the CSI Identity Service) means querying the partner node plugin as well.
This PR:
* adds `Probe` function to the `csiclient.Interface` interface
* forwards `Probe` to the partner node plugin
```release-note
NONE
```
=> [manila-csi-plugin] Probe() must be forwarded to partner node plugin

docs/using-cinder-csi-plugin.md, pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_instances.go, pkg/csi/cinder/openstack/openstack_mock.go, pkg/csi/cinder/sanity/fakecloud.go
fixes #859 
```release-note
for CSI cinder, the search-order defined in cloud.conf is honored , so you can
provide a string like `configDrive,metadataService` or `metadataService,configDrive` to
define the order to get meta from. 
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/cloud-provider-openstack/920)
=> [cinder-csi-plugin] Add metadata search order

docs/using-cinder-csi-plugin.md
- [*] cinder-csi-plugin
Updates the `ca-file` reference in the README + a link to parameters doc for more info
N/A
Just a simple doc update/change
```release-note
NONE
```
=> [cinder-csi-plugin] Fixing ca-file reference in README + adding link

cmd/openstack-cloud-controller-manager/main.go, pkg/version/version.go
Adds a custom `--version` flag to `openstack-cloud-controller-manager`.
Fixes #907 
I tried to do this as cleanly as possible, adding a new global `bool` var and a `BoolVar` flag to the already created `FlagSet` here: 
https://github.com/kubernetes/cloud-provider-openstack/blob/d38032ff1a7da28a0648d8f6e3ac5d3750f1a53f/cmd/openstack-cloud-controller-manager/main.go#L110
If you're running `--help` you'll see that the usage output includes the new flag:
```
...
--version Print version and exit
...
```
I removed the `verflag.PrintAndExitIfRequested()` which was the function that in the end printed something along the lines of: `Kubernetes …
=> [openstack-cloud-controller-manager]: Fix version flag

OWNERS, pkg/ingress/OWNERS
Remove inactive owners based on https://github.com/kubernetes/cloud-provider-openstack/graphs/contributors?from=2019-06-01&to=2020-03-06&type=c
fixes #
```release-note
NONE
```
=> Remove inactive repo owners

pkg/csi/cinder/nodeserver.go
Currently we ignore errors returned when we're not able to retrieve the az from the metadata service. Just wondered why my zone label was just empty (without errors anywhere) on nodes even though the metadata service was down :)
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Add error handling for errors during az retrieval from MetaData service

docs/getting-started-provider-dev.md
The doc of getting-started needs some updates:
1. Use go modules for dependency management since v1.17.
2. Need to update the go version from 1.13 to 1.13.4 because
k8s need it when make cross (https://github.com/kubernetes/kubernetes/pull/82809).
fixes #964
```release-note
NONE
```
=> Improve the guideline of getting started

docs/expose-applications-using-loadbalancer-type-service.md
**The binaries affected**: **N/A**
Fixes formatting of Service object annotations in `expose-applications-using-loadbalancer-type-service.md` docs.
```release-note
NONE
```
=> [docs] Fix formatting of Service annotations

.zuul.yaml, tests/e2e/k8s-keystone-auth/test-authz.sh
Add a test script for k8s-keystone-auth webhook.
Follow-up PRs:
* Change the k8s-keystone-auth CI job in openlab repo to call this script for testing.
fixes #954
```release-note
NONE
```
=> [k8s-keystone-auth] Add e2e test script

.zuul.yaml
- Do not run cloud-provider-openstack-unittest and cloud-provider-openstack-format for shell script
- Disable the job for Kubernetes in-tree cinder function. I don't know when and why it was added, but don't think it's needed for CPO.
- Add files filtering for the job cloud-provider-openstack-acceptance-test-csi-cinder
- Do not use `^` in the files regular expression for some jobs, I found sometimes that's not working
fixes #
```release-note
NONE
```
=> Fix the file filtering in CI jobs

.zuul.yaml, tests/e2e/k8s-keystone-auth/test-authz.sh
This PR is aiming to make sure the CI job for k8s-keystone-auth is working as expected.
fixes #954
```release-note
NONE
```
=> [k8s-keystone-auth] Fix e2e test script

pkg/cloudprovider/providers/openstack/openstack.go
Support Octavia by default as load balancer implementation in openstack-cloud-controller-manager.
fixes #
Document has already been changed in PR #962
```release-note
openstack-cloud-controller-manager: Support OpenStack Octavia by default as load balancer implementation
```
=> [OCCM] Set default value for some options

pkg/csi/cinder/identityserver.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_mock.go, pkg/csi/cinder/openstack/openstack_volumes.go, pkg/csi/cinder/sanity/fakecloud.go
This PR improves probe functionality 
fixes #637 
```release-note
NONE
```
=> [cinder-csi-plugin] Improve Probe() call

.github/PULL_REQUEST_TEMPLATE.md
Refine new PR description template to be more user-friendly.
Removed the contributor guide because it's unlikely the people don't know how to contribute in this step.
fixes #
```release-note
NONE
```
=> Refine new PR description template

.gitignore, .zuul.yaml, Makefile, cluster/images/barbican-kms-plugin/Dockerfile, cluster/images/barbican-kms-plugin/Dockerfile.build, cluster/images/cinder-csi-plugin/Dockerfile, cluster/images/cinder-csi-plugin/Dockerfile.build, cluster/images/cinder-flex-volume-driver/Dockerfile, cluster/images/cinder-provisioner/Dockerfile, cluster/images/cinder-provisioner/Dockerfile.build, cluster/images/k8s-keystone-auth/Dockerfile, cluster/images/k8s-keystone-auth/Dockerfile.build, cluster/images/magnum-auto-healer/Dockerfile, cluster/images/manila-csi-plugin/Dockerfile, cluster/images/manila-csi-plugin/Dockerfile.build, cluster/images/manila-provisioner/Dockerfile, cluster/images/manila-provisioner/Dockerfile.build, cluster/images/octavia-ingress-controller/Dockerfile, cluster/images/octavia-ingress-controller/Dockerfile.build, cluster/images/openstack-cloud-controller-manager/Dockerfile, cluster/images/openstack-cloud-controller-manager/Dockerfile.build
This provides os information to images, also provide correct arch
argument to arm and arm64 architecture.
relates to #883
- [*] openstack-cloud-controller-manager
- [*] cinder-csi-plugin
- [*] k8s-keystone-auth
- [*] client-keystone-auth
- [*] octavia-ingress-controller
- [*] manila-csi-plugin
- [*] manila-provisioner
- [*] magnum-auto-healer
- [*] barbican-kms-plugin
This provides OS information to images, also provide correct arch arguments to arm and arm64 architecture. Without this fix the image os/arch will depend on build environment which might not be …
=> Provide more manifest information

manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
CSI side car has some update which fix some bugs
and something like metrics are added, so we can consume it
- [x ] cinder-csi-plugin
update external attacher to 2.1.1
https://github.com/kubernetes-csi/external-attacher/releases/tag/v2.1.1
https://github.com/kubernetes-csi/external-attacher/blob/v2.1.0/CHANGELOG-2.1.md
there is no break changes
update external resizer to 0.4.0
https://github.com/kubernetes-csi/external-resizer/blob/v0.4.0/CHANGELOG-0.4.md
there is no breaking changes
update csi-node-driver-registrar to 1.2.0 …
=> [cinder-csi-plugin] Update side car container version

docs/getting-started-provider-dev.md, docs/using-barbican-kms-plugin.md, release-procedure.md
This update current docs with correct make commands,
also added more make commands information regarding build and push
images for multiple architectures.
relates to  #883 
This document  depends on [1]
[1] https://github.com/kubernetes/cloud-provider-openstack/pull/967
fixes #
```release-note
NONE
```
=> Update docs for make commands

docs/expose-applications-using-loadbalancer-type-service.md, docs/using-openstack-cloud-controller-manager.md, pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go, pkg/cloudprovider/providers/openstack/openstack_test.go
Add service annotation `loadbalancer.openstack.org/enable-health-monitor` to define whether or not to create health monitor for the load balancer pool, if not specified, use 'create-monitor' config. The health monitor can be created or deleted dynamically.
The scenaro to use this annotation is to deal with the pod that exposes TCP via SNI (e.g. Envoy) and is performing client certificate validation, in this case the health monitor created will fail. We need provide the capability to customize.
fixes #
```release-note
openstack-cloud-controller-manager: Added a service annotation `loadbalancer.openstack.org/enable-health-monitor` to define …
```
=> [OCCM] Add annotation for creating health monitor

cmd/client-keystone-auth/main.go, cmd/octavia-ingress-controller/main.go, pkg/cloudprovider/providers/openstack/openstack.go, pkg/identity/keystone/token_getter.go, pkg/ingress/cmd/root.go
This PR adds an ability to parse and follow klog CLI flags
fixes #981 
```release-note
Parse klog verbosity flags in octavia-ingress-controller and client-keystone-auth
```
=> Parse and follow klog CLI flags

tests/e2e/cloudprovider/test-lb-service.sh
Fix the load balancer service CI job. The new version of `kubectl run` can only create pod, what we expect is a deployment.
fixes #
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/cloud-provider-openstack/992)
=> [OCCM] Fix CI

cluster/images/manila-csi-plugin/Dockerfile.build, cmd/manila-csi-plugin/main.go, docs/using-manila-csi-plugin.md, examples/manila-csi-plugin/README.md, examples/manila-csi-plugin/helm-deployment/templates/controllerplugin-statefulset.yaml, examples/manila-csi-plugin/helm-deployment/templates/nodeplugin-daemonset.yaml, examples/manila-csi-plugin/helm-deployment/values.yaml, examples/manila-csi-plugin/nfs/topology-aware/pod.yaml, examples/manila-csi-plugin/nfs/topology-aware/pvc.yaml, examples/manila-csi-plugin/nfs/topology-aware/storageclass.yaml, pkg/csi/manila/controllerserver.go, pkg/csi/manila/driver.go, pkg/csi/manila/identityserver.go, pkg/csi/manila/nodeserver.go, pkg/csi/manila/options/shareoptions.go, pkg/csi/manila/sanity/sanity_test.go, pkg/csi/manila/util.go, pkg/csi/manila/volumesource.go
This PR adds support for Manila AZs and topology.
Documentation, examples, Helm chart and the sanity test have been updated as well.
fixes #938 
Our take on availability zones is two-fold:
* we provide users with a way of specifying Manila AZs via a storage class parameter
* this parameter is completely opaque to the CO and doesn't contribute to scheduling decisions on compute nodes
* this is sufficient because usually all compute nodes should have connectivity to the storage
* not always, though: if the nodes are partitioned into their own compute AZs and only certain compute AZs are able to reach a subset of Manila AZs, the cluster operator is able to deploy csi-manila with …
=> [manila-csi-plugin] added AZ/topology support

manifests/barbican-kms/pod.yaml, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml, manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml, manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml, manifests/magnum-auto-healer/magnum-auto-healer.yaml, manifests/manila-csi-plugin/csi-nodeplugin.yaml, manifests/webhook/k8s-keystone-auth-ds.yaml, manifests/webhook/k8s-keystone-auth-pod.yaml
Update docker image tag in the example manifest files for release v1.18.0
fixes #
```release-note
NONE
```
=> [All] Update docker image tag to v1.18.0

README.md
Clarified the situation of removing Manila Provisioner from master. 
fixes #
```release-note
NONE
```
=> [DOC] Extended the note for removing Manila Provider

pkg/csi/cinder/driver.go, pkg/csi/cinder/fake.go, pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/nodeserver_test.go, pkg/csi/cinder/sanity/fakemount.go, pkg/util/blockdevice/blockdevice_linux.go, pkg/util/mount/mount.go, pkg/util/mount/mount_mock.go
Knowing Volume capabilities helps to sleep at night (also, capacity planning).
fixes https://github.com/kubernetes/cloud-provider-openstack/issues/669
The test is ugly right now. Should I mock a `resizefs` call?
```release-note
cinder-csi-plugin: Added support for GET_VOLUME_STATS node capability
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/cloud-provider-openstack/941)
=> [cinder-csi-plugin] NodeGetVolumeStats() implementation

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Adding binary name in the title can make it clear for the reviewers, developers and other interested parties to understand better about what changed.
Remove `The binaries affected` section as it duplicates the purpose.
fixes #
```release-note
NONE
```
=> Improve the issue and PR template

.zuul.yaml
fixes #1000 
```release-note
NONE
```
=> [cinder-csi-plugin] Run e2e and acceptance when update manifest in cinder CSI

.zuul.yaml
Add job `cloud-provider-openstack-acceptance-test-e2e-conformance-stable-branch-v1.18` which is defined here https://github.com/theopenlab/openlab-zuul-jobs/blob/master/zuul.d/jobs.yaml#L721
fixes #
```release-note
NONE
```
=> [occm] Add e2e conformance job for release-v1.18

hack/make.sh
See #1007
Fixes #1007 
We could consider adding a argument to pass in the Go-version, not sure how this script is used out there though. I'm using it occasionally.
```release-note
None
```
=> Bump Go version in make.sh helper script

manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
The old csi-attacher resulted in stuck PVs. Real volumes had been deleted, but PVs remained in kubernetes in Terminating state. This is especially true for CSIMigration. See https://logs.openlabtesting.org/logs/12/1012/a6a26351a8f4fae2b50f8bf02f7624476ebf086d/cloud-provider-openstack-multinode-csi-migration-test/cloud-provider-openstack-multinode-csi-migration-test/13a275a/logs/kubernetes/e2e.log
csi-provisioner brings updates for topology support.
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Updated csi versions in cinder-csi-controllerplugin

pkg/util/blockdevice/blockdevice_unsupported.go, pkg/util/mount/mount.go
Currently the build for me on darwin OS fails with:
```
$ make cinder-csi-plugin
CGO_ENABLED=0 GOOS=darwin go build \
-ldflags "-w -s -X 'k8s.io/cloud-provider-openstack/pkg/version.Version=6567dc99'" \
-o cinder-csi-plugin \
cmd/cinder-csi-plugin/main.go
pkg/util/mount/mount.go:83:18: undefined: blockdevice.IsBlockDevice
pkg/util/mount/mount.go:86:16: undefined: blockdevice.GetBlockDeviceSize
pkg/util/mount/mount.go:107:40: invalid operation: int64(statfs.Bavail) * statfs.Bsize (mismatched types int64 and uint32)
pkg/util/mount/mount.go:108:40: invalid operation: int64(statfs.Blocks) * statfs.Bsize (mismatched types int64 and uint32)
pkg/util/mount/mount.go:109:64: invalid operation: (int64(statfs.Blocks) - int64(statfs.Bfree)) * statfs.Bsize …
```
=> Fix the build on non linux OS

examples/cinder-csi-plugin/inline/inline-example.yaml, pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/nodeserver_test.go
* cinder-csi-plugin
Add availability zone support for ephemeral storage.
fixes #1018
```release-note
[cinder-csi-plugin] Add availability zone topology awareness for ephemeral storage
```
=> [cinder-csi-plugin] Add availability zone topology awareness for ephemeral storage

pkg/csi/cinder/openstack/openstack_snapshots.go
align with other definitions in the code
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] nit: rename SnapshotReadyStatus to snapshotReadyStatus

.github/PULL_REQUEST_TEMPLATE.md, Makefile
To keep consistent with the PR title format to avoid confusion.
fixes #
```release-note
NONE
```
=> Fix the release note guide

.zuul.yaml
This PR enables csi migration test on every change related to cinder-csi
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Add csi-migration-test go .zuul.yaml

pkg/csi/manila/driver.go, pkg/csi/manila/identityserver.go
Currently, manila-csi-plugin is reporting only the driver's semantic version. This PR makes it so that the cloud-provider-openstack's version is part of the reported version too. This will help identify the exact version of the driver e.g. when troubleshooting a problem.
The format used for the fully qualified version is `{driver version}@{CPO version}`, where "CPO version" is passed in via linker flags in Makefile as a git hash:
https://github.com/kubernetes/cloud-provider-openstack/blob/b2335ad887a06e28acdf56e2d0933289bcb0ddfe/Makefile#L34-L35
It's advertised in:
* logs during initialization
* identity service's `GetPluginInfoResponse`
```release-note
NONE
```
=> [manila-csi-plugin] report fully qualified version

docs/getting-started-provider-dev.md
Update the instruction "./cluster/kubectl.sh create -f cluster/addons/rbac/"
to avoid error arised.
fixes #
```release-note
NONE
```
=> Update the doc of getting-started-provider-dev

docs/using-openstack-cloud-controller-manager.md, pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_test.go
In some intricate network designs, it is possible to have multiple networks on different hosts. This PR allows the user to specify multiple network names that may be considered public or private on cluster's nodes.
I've tried to maintain complete backward compatibility. Due to the way gcfg works, it is possible to specify arrays via repeated use of the same key.
```release-note
[openstack-cloud-controller-manager] Support multiple network names for config options `internal-network-name` and `public-network-name`.
```
=> [occm] Support multiple network names

examples/manila-csi-plugin/helm-deployment/values.yaml, manifests/manila-csi-plugin/csi-controllerplugin.yaml, manifests/manila-csi-plugin/csi-nodeplugin.yaml
Until now, the provided k8s manifests and the Helm chart have referenced `manila-csi-plugin` image, which is incorrect.
* reference images from the k8scloudprovider Docker hub repo
* also added notes about enabling topology awareness
fixes #
```release-note
NONE
```
/cc @adisky @ramineni
=> [manila-csi-plugin] updates to k8s manifests and helm chart

docs/using-cinder-csi-plugin.md
Fix cloud-controller-manager page which results in 404
Enrich manifests links to ease access
Add Links to examples to avoid confusion
Signed-off-by: rootsami <rootsami@gmail.com>
To fix issue with cinder-csi-plugin's doc
fixes #
=> [cinder-csi-plugin] Fix 404 Docs and Enrich links

.zuul.yaml
Disable this job only for release-1.17 branch because the job was refactored since release-1.18
fixes #
```release-note
NONE
```
=> [k8s-keystone-auth] Disable the CI job for k8s-keystone-auth in release-1.17

OWNERS
As requested https://github.com/kubernetes/cloud-provider-openstack/pull/969#pullrequestreview-397067830 , many of the contributors are not active in the project anymore over a year. Removing them from the reviewers list to avoid automatic assignment of PRs
Happy to add them if they are active in project again :) 
fixes #
```release-note
NONE
```
=> update reviewers list

pkg/cloudprovider/providers/openstack/openstack.go
Now OCCM prints error message, when a required endpoint cannot be found.
Due to #977 OCCM stopped to work silently, there were no errors showed in logs. It took a while to debug the root cause.
```release-note
None
```
/cc @rfranzke
/assign @lingxiankong
=> [OCCM] Print error messages, when OpenStack client returns error

pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/controllerserver_test.go, pkg/csi/cinder/fake.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_mock.go, pkg/csi/cinder/openstack/openstack_volumes.go, pkg/csi/cinder/sanity/fakecloud.go, pkg/util/errors/errors.go
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Add pagination support for ListVolumes

Makefile
Add target `image-csi-plugin` in Makefile which is used by CI jobs against previous branches (e.g. release-1.17).
fixes #
As a follow-up, I will change the openlab CI job to use `image-csi-plugin` so we don't break CI of previous branches.
```release-note
NONE
```
=> [cinder-csi-plugin] Support image-csi-plugin target in Makefile

examples/manila-csi-plugin/helm-deployment/values.yaml, manifests/manila-csi-plugin/csi-controllerplugin.yaml, manifests/manila-csi-plugin/csi-nodeplugin.yaml
this is inspired by https://github.com/kubernetes/cloud-provider-openstack/pull/1025
Cinder CSI better to contain those info for further usage
fixes #
```release-note
[cinder-csi-plugin] The CSI vendor version was changed from `<CSI spec version>` to `<driver version>@<cloud provider openstack version>`
```
=> [cinder-csi-plugin] Add version into cinder CSI driver info 

pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/controllerserver_test.go, pkg/csi/cinder/sanity/fakecloud.go, pkg/csi/cinder/sanity/fakemount.go, pkg/csi/cinder/sanity/sanity_test.go
This PR brings us closer to csi spec conformance of cinder csi driver. Failures are brought down to 2. Partially fixes #793 
Summarizing 2 Failures:
[Fail] ListSnapshots [Controller Server] [It] should return next token when a limited number of entries are requested 
/home/necuser/code/pkg/mod/github.com/kubernetes-csi/csi-test@v2.2.0+incompatible/pkg/sanity/controller.go:1827
[Fail] Node Service [It] should work 
/home/necuser/code/pkg/mod/github.com/kubernetes-csi/csi-test@v2.2.0+incompatible/pkg/sanity/node.go:781
The above failures require pagination …
=> [cinder-csi-plugin] Fix csi cinder sanity testing failures 

Makefile
This PR is a cherry-pick of #1045.
Add target `image-csi-plugin` in Makefile which is used by CI jobs against previous branches (e.g. release-1.17).
fixes #
As a follow-up, I will change the openlab CI job to use `image-csi-plugin` so we don't break CI of previous branches.
```release-note
NONE
```
=> [cinder-csi-plugin] Support image-csi-plugin target in Makefile - release-1.18

docs/using-cinder-csi-plugin.md, examples/cinder-csi-plugin/snapshot/example.yaml, pkg/csi/cinder/openstack/openstack_snapshots.go
fixes #832 
```release-note
[cinder-csi-plugin] Added `force-create` parameter in VolumeSnapshotClass to support creating snapshot for a volume in in-use status.
```
=> [cinder-csi-plugin] Allow force create snapshot

pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/controllerserver_test.go, pkg/csi/cinder/driver.go
For supporting VolumeAttachment reconcile, adding capability.
Related: https://github.com/kubernetes-csi/external-attacher/pull/184
```release-note
[cinder-csi-pugin] Support LIST_VOLUMES_PUBLISHED_NODES capability.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubernetes/cloud-provider-openstack/976)
=> [cinder-csi-pugin] Support reconcile volume attachements

docs/using-openstack-cloud-controller-manager.md, pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Make cascade deletion of load balancers configurable
If octavia is used, occm tries to perform cascade deletion of load balancers. Some Octavia provider drivers might not support cascade deletion, therefore this PR makes cascade deletion option configurable. By default, cascade deletion is enabled.
Cascade deletion can be enabled/disabled by setting `cascade-delete` option in cloud-config file.
```release-note
[openstack-cloud-controller-manager] Make cascade deletion configurable when Octavia is enabled.
```
=> [occm] make cascade deletion configurable

pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/nodeserver.go
Backport #925 , #897 to release-1.17 
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Backport fixes to 1.17

go.mod, go.sum, pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/nodeserver_test.go, pkg/csi/cinder/sanity/fakemount.go, pkg/csi/cinder/sanity/sanity_test.go, pkg/util/metadata/metadata.go, pkg/util/mount/mount.go, pkg/util/mount/mount_mock.go
1. updates csi-test 3.1.0
2. fix idempotent failures , if multiple calls to NodeUnpublish should be of same result.
3. cleanup mount
This brings down failures to 1
Summarizing 1 Failure:
[Fail] ListSnapshots [Controller Server] [It] should return next token when a limited number of entries are requested 
/home/necuser/code/pkg/mod/github.com/kubernetes-csi/csi-test/v3@v3.1.0/pkg/sanity/controller.go:1534
fixes #793 
IsLikelyNotMountPointDetach() , https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/util/mount/mount.go#L266 is not required which is causing idempotent failures , the same functionality is already being handled properly as part of …
=> [cinder-csi-plugin] Fix sanity test failures 2/3

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Fixes nil pointer dereference error in create load balancer func. 
If the load balancer creation fails then error should be returned instead of accessing VipSubnetID from nil
fixes #
```release-note
NONE
```
=> [occm] fix nil pointer dereference in create loadbalancer func

.zuul.yaml, pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/controllerserver_test.go, pkg/csi/cinder/fake.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_mock.go, pkg/csi/cinder/openstack/openstack_snapshots.go, pkg/csi/cinder/sanity/fakecloud.go
This PR fixes the sanity test failures, adds the job to the pipeline
fixes #793
```release-note
None
```
=> [cinder-csi-plugin] Fix sanity failures 3/3

pkg/autohealing/cloudprovider/openstack/provider.go
Magnum supports node group for its k8s cluster, and its resize API
has been updated accordingly. Therefore, magnum-auto-healer needs
to pass in the correct node group name and the node count.
fixes #1031 
```release-note
[magnum-auto-healer] Support Magnum node group when proforming autohealing.
```
=> [magnum-auto-healer] Support node group

go.mod, go.sum, pkg/autohealing/cloudprovider/cloudprovider.go, pkg/autohealing/cloudprovider/openstack/provider.go, pkg/autohealing/controller/controller.go, pkg/autohealing/healthcheck/healthcheck.go, pkg/autohealing/healthcheck/plugin_endpoint.go, pkg/autohealing/healthcheck/plugin_nodecondition.go
fixes #984 
```release-note
[magnum-auto-healer] Support updating the health status for Magnum cluster.
```
=> [magnum-auto-healer] Support updating cluster health status

charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml, docs/using-cinder-csi-plugin.md, docs/using-openstack-cloud-controller-manager.md, examples/cinder-csi-plugin/inline/inline-example.yaml, examples/cinder-csi-plugin/nginx.yaml, examples/cinder-csi-plugin/resize/example.yaml, examples/cinder-csi-plugin/snapshot/snapshotrestore.yaml, examples/loadbalancers/README.MD, examples/manila-csi-plugin/README.md, examples/manila-csi-plugin/helm-deployment/templates/nodeplugin-clusterrolebinding.yaml, examples/manila-csi-plugin/nfs/dynamic-provisioning/storageclass.yaml, examples/manila-csi-plugin/nfs/topology-aware/storageclass.yaml, examples/mysql-cinder-pd/mysql.yaml, manifests/barbican-kms/encryption-config.yaml, manifests/barbican-kms/pod.yaml, manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml, manifests/manila-csi-plugin/csi-nodeplugin-rbac.yaml, release-procedure.md
Remove trailing whitespace.
fixes #
```release-note
NONE
```
=> Remove trailing whitespace

docs/using-openstack-cloud-controller-manager.md
Fixes a typo in docs that I found while reading.
fixes #
```release-note
NONE
```
=> Fixed typo in `using-openstack-cloud-controller-manager.md`

.zuul.yaml, cluster/images/cinder-csi-plugin/Dockerfile, cluster/images/cinder-csi-plugin/Dockerfile.build
The PR updates the base image with us.gcr.io/k8s-artifacts-prod/build-image/debian-base-amd64:v2.1.0 as minimal base - ref https://github.com/kubernetes/kubernetes/tree/master/build/debian-base
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Update debian-base image

pkg/ingress/controller/controller.go
Fixes minor typo in the `octavia-ingress-controller` and the `controller.go` file.
N/A
N/A
```release-note
NONE
```
=> [octavia-ingress-controller] Fix typo in OIC code

docs/getting-started-provider-dev.md
fixes #1083
```release-note
NONE
```
=> [doc]update doc to link to docker setup

pkg/cloudprovider/providers/openstack/openstack.go
RegisterCloudProvider() calls NewOpenStack() but we cannot see the root cause if an error happens due to lack of actual error message.
This adds the error message in log output.
Now I am facing an issue failed to deploy occm from Kubespray and it is hard to debug it because of this lack of the error message.
```release-note
NONE
```
=> [occm] Add error message in RegisterCloudProvider()

charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml
It fixes the following error:
helm install cinder-csi cloud-provider-openstack/charts/cinder-csi-plugin
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec
fixes #
```release-note
NONE
```
=> Add serviceName to cinder-csi-plugin/templates/controllerplugin-statefulset.yaml

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
**Refactor/Improve logic for Floating IP creation**:
The PR fixes the following problems: 
* "service.beta.kubernetes.io/openstack-internal-load-balancer" annotation is ignored by occm:
If floating network ID and floating subnet ID is not found in load balancer class then occm sets the internal loadbalancer setting to True, it simply ignores the annotation set by the user [ref](https://github.com/hamzazafar/cloud-provider-openstack/blob/a7e33e5a83027f87c9781cb2cb21ab423fad99a4/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L860). openstack-internal-load-balancer annotation should be used as a source of truth.
* occm tries to fetch floating network and subnet ID from loadbalancer class in the beginning of EnsureLoadbalancer function …
=> [occm] improve logic for floating IP creation 

pkg/cloudprovider/providers/openstack/openstack.go
As seeing this PR, there was lack of error handling.
So this adds it for investigating issues easily.
```release-note
NONE
```
=> [occm] Add error handling for reading config

pkg/csi/manila/OWNERS
Commit 313fc67b856b8e21bebe1b4a45a55ca25070207e intended to set
up an OWNERS file for the manila-csi driver, but it was set up
under the old non-csi pkg/share/manila path and was lost when
that legacy path was dropped with 1.18.
Set up the OWNERS file in the right path with appropriate current
membership.
Adds an OWNERS file to delegate responsibility for the manila csi plugin.
fixes #
```release-note
NONE
```
=> [manila-csi-plugin] add OWNERS file

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/values.yaml
Use the latest version of the cinder-csi-plugin and related sidecars.
https://github.com/kubernetes/cloud-provider-openstack/releases/tag/v1.18.0
csi-attacher:v2.1.1
https://github.com/kubernetes/cloud-provider-openstack/blob/release-1.18/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml#L38
csi-provisioner:v1.4.0
https://github.com/kubernetes/cloud-provider-openstack/blob/release-1.18/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml#L50
csi-snapshotter:v1.2.2
https://github.com/kubernetes/cloud-provider-openstack/blob/release-1.18/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml#L62
csi-resizer:v0.4.0
https://github.com/kubernetes/cloud-provider-openstack/blob/release-1.18/manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml#L73 …
=> [cinder-csi-plugin] update plugin to v1.18.0

.zuul.yaml
the changes in `tests` folder will not trigger CSI e2e and sanity check
update zuul file on this
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Add test changes into zuul file

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Refactor/Improve processing of **loadbalancer.openstack.org/x-forwarded-for** and **loadbalancer.openstack.org/proxy-protocol** annotations
keepClientIP and useProxyProtocol options are only supported by Octavia. This PR fixes the following issues:
* For neutron lbaas, listener protocol should only be TCP [ref](https://github.com/kubernetes/cloud-provider-openstack/blob/a7e33e5a83027f87c9781cb2cb21ab423fad99a4/pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go#L900), however when **loadbalancer.openstack.org/x-forwarded-for** annotation is specified, regardless of Octavia or neutron LBaaS, occm sets listener protocol to HTTP [ref](https://github.com/kubernetes/cloud-provider-openstack/blob/a7 …
=> [occm] refactor keepClientIP and useProxyProtocol

charts/manila-csi-plugin/Chart.yaml, charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml, manifests/manila-csi-plugin/csi-nodeplugin.yaml
Make hostpath volumes DirectoOrCreate instead of Directory
for a more resilient installation.
```release-note
manila-csi-plugin chart v0.1.1 Change to DirectoryOrCreate for nodeplugin volume.
```
=> [manila-csi-plugin] Fix volume in nodeplugin

pkg/ingress/controller/openstack/neutron.go
fixes #1139
```release-note
NONE
```
=> Fix `conversion from int to string yields a string of one rune` issues

pkg/cloudprovider/providers/openstack/openstack.go
fixes #1132
```release-note
NONE
```
=> [occm] Remove compare between LB opts as it's useless

docs/expose-applications-using-loadbalancer-type-service.md, docs/using-openstack-cloud-controller-manager.md, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
In [PR ](https://github.com/kubernetes/cloud-provider-openstack/pull/1102) floating subnet was made mandatory, for backward compatibility we should make it optional again. I have also added docs to clearly specify that floating-subnet is an optional argument. 
```release-note
NONE
```
=> [occm] make floating subnet optional

docs/expose-applications-using-loadbalancer-type-service.md, docs/using-openstack-cloud-controller-manager.md, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go, pkg/util/openstack/loadbalancer.go
Refactor loadbalancer related functions, split the code when Octavia is enabled.
fixes #
Now, `ensureOctaviaLoadBalancer()` and `updateOctaviaLoadBalancer()` should be the two functions we need to maintain. Legacy code should be removed at some point in the future.
```release-note
NONE
```
=> [occm] Split Octavia related functions

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
In [PR](https://github.com/kubernetes/cloud-provider-openstack/pull/837) the change of the `connection-limit` was
limited to Octavia but should be updated without this restriction.
fixes #1147 
The intention of the mentioned [PR](https://github.com/kubernetes/cloud-provider-openstack/pull/837) was
to restrict `allowed_cidrs` to Octavia according to this [issue](https://github.com/kubernetes/cloud-provider-openstack/issues/829). Propably unintentional the `connection-limit` was included by the code change.
```release-note
[openstack-cloud-controller-manager] Update Neutron loadbalancer if service annoation `loadbalancer.openstack.org/connection-limit` …
```
=> [occm] changing connection-limit annotation not limited to Octavia

charts/cinder-csi-plugin/templates/cinder-csi-driver.yaml, manifests/cinder-csi-plugin/csi-cinder-driver.yaml
storage.k8s.io/v1beta1 CSIDriver object has been deprecated
Update to use v1.
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Update CSIDriver object version to v1

pkg/csi/manila/nodeserver.go, pkg/csi/manila/shareadapters/cephfs.go, pkg/csi/manila/shareadapters/nfs.go, pkg/csi/manila/shareadapters/shareadapter.go
This PR refactors the export location resolution code and moves it into individual share adapters. This is to prepare share adapters to employ their own logic into choosing an appropriate export location.
xref https://github.com/kubernetes/cloud-provider-openstack/issues/1136
```release-note
NONE
```
=> [manila-csi-plugin] Export location resolution moved into individual share adapters

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
This bug was introduced in PR: https://github.com/kubernetes/cloud-provider-openstack/pull/1144
How to reproduce?
Set `loadbalancer.openstack.org/network-id` annotation in service template. Cloud provider will not consume the value mentioned in the annotation!
```release-note
NONE
```
=> [occm] fix bug for network-id annotation

docs/expose-applications-using-loadbalancer-type-service.md, docs/using-openstack-cloud-controller-manager.md, pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
This pr adds an option to specify the flavor-id used for the octavia loadbalancer.
The flavor-id can be set in the config or via annotation.
fixes #
Flavors were being introduced in octavia version 4.0.0 if I am not mistaken.
I haven't found a way to check the octavia version from within the occm so if a check is needed here I would appreciate if someone can point me in the right direction here.
```release-note
[openstack-cloud-controller-manager] Add support to set octavia loadbalancer flavor-id.
```
=> [occm] add octavia loadbalancer flavor option

docs/using-octavia-ingress-controller.md, pkg/ingress/controller/controller.go, pkg/ingress/controller/openstack/octavia.go
When a client sends HTTP/HTTPS request to an Ingress, sometimes the client could add port number to Host HTTP header (see [1]), e.g. when the host in the Ingress is "foo.bar.com", the Host header could be "foo.bar.com:80". This PR adds support for both "foo.bar.com" and "foo.bar.com:80".
[1]: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
fixes #
```release-note
NONE
```
=> [octavia-ingress-controller] Use REGEX compare type for HOST_NAME l7 rule type

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
This implements the update of the listener if one of the service annotations
* `loadbalancer.openstack.org/timeout-client-data`
* `loadbalancer.openstack.org/timeout-member-connect`
* `loadbalancer.openstack.org/timeout-member-data`
* `loadbalancer.openstack.org/timeout-tcp-inspect`
* `loadbalancer.openstack.org/x-forwarded-for`
changes.
Currently, changing one of the service annotation has no effect.
fixes #1149 
Updating `loadbalancer.openstack.org/proxy-protocol` is currently not handled. See the issue for more details.
```release-note
[openstack-cloud-controller-manager] Update listener if service annotation …
```
=> [occm] update listener on Octavia annotation changes

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go, pkg/util/openstack/loadbalancer.go
I previously created #1160 
There a version check was missing to find out if the used octavia version supports flavors already.
This would cause the controller to throw an error if a user specified a flavor-id on a loadbalancer with an old octavia version (< v2.6).
This pr creates a version check so that the flavor-id option gets ignored if the octavia version is too old
fixes #
Thank you @lingxiankong for pointing out how to create a version check.
```release-note
NONE
```
=> [occm] Add version check for lb flavors support

charts/manila-csi-plugin/Chart.yaml, charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml, charts/manila-csi-plugin/templates/runtimeconfig-cm.yaml, charts/manila-csi-plugin/values.yaml, cmd/manila-csi-plugin/main.go, docs/using-manila-csi-plugin.md, examples/manila-csi-plugin/runtimeconfig-cm.yaml, pkg/csi/manila/runtimeconfig/nfsconfig.go, pkg/csi/manila/runtimeconfig/runtimeconfig.go, pkg/csi/manila/shareadapters/cephfs.go, pkg/csi/manila/shareadapters/nfs.go, pkg/csi/manila/shareadapters/util.go
The main point of this PR is to give users the ability to filter out export location for NFS shares. Here is the use-case: https://github.com/kubernetes/cloud-provider-openstack/issues/1136
This is achieved by having a runtime JSON config file (represented as a ConfigMap in k8s) where users may enter a single IP address in CIDR format. This address is then used to choose an export location that matches this address. No match results in `NodePublishVolume` returning error with code `INVALID_ARGUMENT`.
fixes https://github.com/kubernetes/cloud-provider-openstack/issues/1136
```release-note
manila-csi-plugin: added runtime configuration file, …
```
=> [manila-csi-plugin] Added runtime config with export location filter for NFS

pkg/csi/cinder/driver.go, pkg/csi/cinder/driver_test.go
Bump cinder csi driver version to 1.2.1
fixes #
```release-note
[cinder-csi-plugin] Bump Cinder CSI Driver version to 1.2.1
```
=> [cinder-csi-plugin] Bump driver version to 1.2.1

charts/cinder-csi-plugin/values.yaml
fixes #1173
```release-note
NONE
```
=> [cinder-csi-plugin] Update helm chart to latest and bump other images

manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml, pkg/util/mount/mount.go
pods-cloud-data volume is no longer used, so removing the mount
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Remove the pods-cloud-data volume

OWNERS
I have been involved in this project for long time and did
a lot of contributions, aslo, very active in reviewing PRs and
provide comments
fixes #
```release-note
NONE
```
=> propose to add jichenjc as approver

charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
per doc for chart and our previous manifest, cacert is located
at /etc/cacert
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin]update chart cacert location to /etc/caert

cluster/images/cinder-csi-plugin/Dockerfile, cluster/images/cinder-csi-plugin/Dockerfile.build
Update debian base image to v2.1.3 to address CVEs.
```release-note
NONE
```
=> [cinder-csi-plugin]  Update debian base image to v2.1.3

docs/using-cinder-csi-plugin.md, examples/cinder-csi-plugin/snapshot/example.yaml, examples/cinder-csi-plugin/snapshot/snapshotcreate.yaml, manifests/cinder-csi-plugin/cinder-csi-controllerplugin-rbac.yaml, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
update snapshot side car container to v2.1.1
upgrade snapshot to v2.1.1
https://github.com/kubernetes-csi/external-snapshotter/releases
has a broken update when upgrade to 2.0.0
so the upgrade of the side car container including:
1) upgrade the version
2) honor the split of snapshot controller and snapshotter
3) update rbac
4) update example according to the v1beta1 definition
xref #951 
```release-note
[cinder-csi-plugin] updated external-snapshotter to v2.1.1
```
=> [cinder-csi-plugin] upgrade snapshot to v2.1.1 

pkg/cloudprovider/providers/openstack/openstack.go
Without this fix, authentication using application credential fails
since the validator checks for presence of os-password and os-trustID.
fixes #
```release-note
NONE
```
=> [occm] Allow auth-url to partially depend on applicationCredentialSecret

docs/using-cinder-csi-plugin.md, pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/controllerserver_test.go, pkg/csi/cinder/openstack/openstack_volumes.go
When the type of the volume is of "multiattach", it can be attached to multiple instances.
Currently type of the volume can be specified as part of parameters['type'] of storageclass , https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/controllerserver.go#L63
This PR enables the same for multiattach type as well .
fixes #729 
Specify the 'type' as 'multiattach' in storageclass as specified in example doc.
type should exist in backend.
```release-note
[cinder-csi-plugin] Support to attach a volume to multiple instances if ‘multiattach’ flag is enabled in Cinder volume type.
```
=> [cinder-csi-plugin] support "multiattach" volume type 

docs/using-manila-csi-plugin.md, docs/using-openstack-cloud-controller-manager.md, pkg/cloudprovider/providers/openstack/openstack.go
Adds a support for TLS client auth.
fixes #1119
```release-note
Added support for TLS client authentication against OpenStack for all components.
```
=> Auth: add TLS client auth support

README.md, index.html
GH action fails when there is an empty index.yaml file.  It is better to
have none at all so that it can create a valid index.yaml file for us.
fixes #
```release-note
NONE
```
=> Remove index.yaml and add README.md

.github/workflows/release.yaml, charts/cinder-csi-plugin/Chart.yaml, charts/manila-csi-plugin/Chart.yaml
fixes #1193
```release-note
NONE
```
=> Bump up chart version to trigger chart release

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
range copies the value as a local variable in the loop.
Getting the pointer from it makes all the elements in the map point to
the last value that the range variable copied.
This means that only the last port in the array will ever be updated.
Change to get value with an index from the array directly.
fixes #
Testing:
Create a service/ingress with multiple ports and check if failures regarding creating listeners will show up.
```release-note
NONE
```
=> [occm] Fix bug where pointer from local loop variable instead of array variable is used

.github/workflows/release.yaml, charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/values.yaml, charts/manila-csi-plugin/Chart.yaml, charts/manila-csi-plugin/values.yaml
- Also remove dysfunctional Github chart install action.
- Only release charts from release branches.
fixes #
```release-note
NONE
```
=> Bump up chart version to trigger chart release (release-1.19)

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/values.yaml
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Update snapshotter to 2.1.1 in release-1.19 branch

examples/webhook/keystone-deployment.yaml, manifests/barbican-kms/pod.yaml, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml, manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml, manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml, manifests/magnum-auto-healer/magnum-auto-healer.yaml, manifests/manila-csi-plugin/csi-controllerplugin.yaml, manifests/manila-csi-plugin/csi-nodeplugin.yaml
Update docker image tag in the manifest files for release v1.19.0
fixes #
```release-note
NONE
```
=> [All] Update docker image tag to v1.19.0

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go, pkg/util/openstack/loadbalancer.go
**What this PR does / why we need it**: Newest 1.19 ccm uses timeout parameters that are not supported in octavia 2.0 API, we need check is these supported
fixes #1196
```release-note
[openstack-cloud-controller-manager] Added Octavia service version check to the timeout parameters when creating listeners.
```
=> [occm] Check is timeout parameters for Octavia listener supported

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go, pkg/util/openstack/loadbalancer.go
Cherry Picked from #1228
fixes #1196
```release-note
[openstack-cloud-controller-manager] Added Octavia service version check when creating listeners with timeout parameters.
```
=> [occm] Check octavia version for timeout params when creating listener

.github/workflows/pr.yaml
For the chart install to work, the Kubernetes cluster needs to be able
to talk to an OpenStack cloud which cannot be done in the Github Actions CI. Therefore,
only perform the lint test and disable install.
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin][manila-csi-plugin] Disable chart install job on Github actions workflow

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/controllerplugin-rbac.yaml, charts/cinder-csi-plugin/values.yaml
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Update snapshotter to v2.1.1 in charts

docs/using-cinder-csi-plugin.md
indicate `VolumeAttributes ` for ephemeral disk is optional and default to 1G
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] [doc] update doc about VolumeAttributes is optional

pkg/ingress/controller/controller.go
At the moment the OIC connects to the Barbican API on every delete event since the if-statement checking if Barbican client is not `nil` will always be true.
This PR adds another condition to that if-statement, in this case to see if the `TLS` field of the `Ingress` spec is not `nil`. 
With that said there's two other ways to approach this when it comes to the if-statement:
1. As in the `ensureIngress` method check the `len()` of `ing.spec.TLS`.
2. Remove the current if-statement in the `deleteIngress` method and replace it with either a `len()` check or `!= nil` check as i've proposed in this PR.
I've tested this locally and it seems to work as i would expect but i need some more eyes on this.
Proposed …
=> [octavia-ingress-controller] Check if TLS field in Ingress spec is set

pkg/cloudprovider/providers/openstack/openstack_instances.go
nit: when debug a problem ,found this log and seems it's useless ...
fixes #
```release-note
NONE
```
=> [occm][nit] remove unnecessary log 

docs/using-cinder-csi-plugin.md, pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/nodeserver_test.go
fixes #
Fix a TODO 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/nodeserver.go#L145
```release-note
[cinder-csi-plugin] Support volume type for ephemeral volume.
```
=> [cinder-csi-plugin] Add ephemeral disk type support

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml, charts/cinder-csi-plugin/templates/secret.yaml, charts/cinder-csi-plugin/values.yaml, charts/manila-csi-plugin/Chart.yaml, charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml, charts/manila-csi-plugin/values.yaml
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin][manila-csi-plugin] Make cloud-config/cacert volume/volumeMounts configurable

.github/workflows/config/ct.yaml, .github/workflows/pr.yaml, charts/cinder-csi-plugin/templates/controllerplugin-rbac.yaml
For the chart install to work, the Kubernetes cluster needs to be able
to talk to an OpenStack cloud which cannot be done in the CI. Therefore,
only perform the lint test and disable install.
(cherry picked from commit 534bf325c1412c62e753a8ac2e93d166066376e3)
fixes #
```release-note
NONE
```
=> Only perform chart lint, remove install step (#1227)

pkg/cloudprovider/providers/openstack/openstack_instances.go
related to #1208 
```release-note
NONE
```
=> [occm] Add log for NodeAddressesByProviderID

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/controllerplugin-rbac.yaml
related #1215 
```release-note
NONE
```
=> [cinder-csi-plugin] Add explict namespace definition into chart

pkg/cloudprovider/providers/openstack/openstack_instances.go
This calls the API for a flavor name, if only the id is used to lookup the flavor. This provides a more meaningful return value.
fixes #
```release-note
[openstack-cloud-controller-manager] Always use flavor name for the Node label `node.kubernetes.io/instance-type`.
```
<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
=> [occm] lookup flavor name if only id is provided

.github/workflows/release.yaml
The chart-releaser-action assumes that master branch is used for release. I believe this is a bug because the chart-releaser incorrectly tags the HEAD of `master` branch rather than `release-1.19` branch (See https://github.com/kubernetes/cloud-provider-openstack/tags and notice that the openstack-* tags do not correspond to the correct commits but rather the current tip of the master branch). This does not work with our model as we want our charts to be based on `release-*` branches and explicitly not master which uses the `latest` images. This PR copies script from chart-releaser-action repo and make the necessary modification to facilitate chart publishing from release branches. Once the chart-releaser-action fixes this issue, we can revert this …
=> [cinder-csi-plugin][manila-csi-plugin] Add chart releaser script

docs/expose-applications-using-loadbalancer-type-service.md, docs/using-openstack-cloud-controller-manager.md, go.mod, go.sum, pkg/cloudprovider/providers/openstack/openstack.go, pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go, pkg/util/openstack/loadbalancer.go
The Ussuri release of Octavia now supports the availability zone feature where operators can specify some useful capabilities such as the compute availability zone for the amphora instances. 
A POST request to create LB:
https://github.com/openstack/octavia/blob/master/octavia/api/v2/types/load_balancer.py#L109-L126
Added in the 2.14 Octavia version:
https://github.com/openstack/octavia/blob/master/octavia/api/root_controller.py#L109
Such support in gophercloud: https://github.com/gophercloud/gophercloud/pull/2026
fixes #1223
The code to check the availability of the Octavia feature will inform operators through the warning if Octavia doesn't support AZ yet, but the …
=> [occm] Added Octavia Availability Zones support for LoadBalancers

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml, charts/cinder-csi-plugin/templates/secret.yaml, charts/cinder-csi-plugin/values.yaml, charts/manila-csi-plugin/Chart.yaml, charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml, charts/manila-csi-plugin/values.yaml
see https://github.com/kubernetes/cloud-provider-openstack/pull/1218
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin][manila-csi-plugin] Make cloud-config/cacert volume/volumeMounts configurable (release-1.19)

pkg/csi/cinder/openstack/fixtures/clouds.yaml, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_test.go
Now use-cloud option is ignored in the driver's config.
This commit fixes this issue and allows the driver to read credentials from the given clouds.yaml file.
fixes #1260
```release-note
NONE
```
=> [cinder-csi-plugin] Do not ignore use-cloud config option

Makefile
Now we always use docker, but sometimes it's required to use alternative container engines like `podman`.
This patch allows users to specify the desired container engine via CONTAINER_ENGINE env variable.
By default container engine is set to "docker" for backward compatibility.
```release-note
NONE
```
=> Allow to specify container engine in the makefile

manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml, manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
This commit updates the CLI flags used to launch the controller manager.
The usage of address is deprecated. Hence, this commit updates the
flags to bind-address #1258.
fixes #1258 
```release-note
NONE
```
=> [occm] update cloud-controller-manager flags

Makefile
fixes #1253
```release-note
NONE
```
=> [all] Fix build-cross target in Makefile

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/cinder-csi-plugin/values.yaml, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
Default CSI resizer timeout is [10 seconds](https://github.com/kubernetes-csi/external-resizer/blob/ae8826a2ac345af7a9bf4a6c5103441ec9940476/cmd/csi-resizer/main.go#L49), usually this is not enough. This PR explicitly sets 3m timeout in a CSI manifest sidecar containers.
fixes #1265
```release-note
NONE
```
cc @rfranzke
=> [cinder-csi-plugin] explicitly set cinder CSI sidecar timeouts to 3m

docs/cinder-csi-plugin/csc-tool.md, docs/cinder-csi-plugin/examples.md, docs/cinder-csi-plugin/features.md, docs/cinder-csi-plugin/using-cinder-csi-plugin.md
This splits the docs to diff files for better readability
fixes #1268
```release-note
NONE
```
=> [cinder-csi-plugin] Improve docs [Part2]

pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/controllerserver_test.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_mock.go, pkg/csi/cinder/openstack/openstack_volumes.go, tests/sanity/cinder/fakecloud.go
Allows cinder csi plugi to handle a volume, which was already resized.
fixes #1265
```release-note
[cinder-csi-plugin] Added the size check for volume expansion.
```
=> [cinder-csi-plugin] handle a case when a volume was already resized

.zuul.yaml, docs/cinder-csi-plugin/using-cinder-csi-plugin.md
fixes #
```release-note
NONE
```
=> Fix format error

docs/metrics.md, docs/using-openstack-cloud-controller-manager.md
This PR documents the metrics of the openstack-cloud-controller-manager especially for the OpenStack API calls and loadbalancer reconciliation introduced within #1178.
n/a
n/a
```release-note
NONE
```
<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
=> [occm] Documentation for occm metrics

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml, manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
fixes #1237 
```release-note
NONE
```
=> [Cinder-csi-plugin]Add toleration to CSI daemonset

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go, tests/e2e/cloudprovider/test-lb-service.sh
1. Fixed updating listener for service update.
2. Added a test case for service update.
fixes #1242
```release-note
NONE
```
=> [occm] Fix updating listeners

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go, tests/e2e/cloudprovider/test-lb-service.sh
Cherry picked from https://github.com/kubernetes/cloud-provider-openstack/pull/1249
fixes #1242
```release-note
NONE
```
=> [occm] Fix updating listeners (release-1.19)

charts/manila-csi-plugin/Chart.yaml, charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml
Chart removes whitespace too aggressively in 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml#L138-L149
and 
https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml#L128-L139
I saw this when trying to set `.Values.controllerplugin.nodeSelector` or `.Values.nodeplugin.nodeSelector`
fixes #1284
Impossible to set `.Values.controllerplugin.nodeSelector` or `.Values.nodeplugin.nodeSelector`
```
Fix possibility to set `.Values.controllerplugin.nodeSelector` or `.Values.nodeplugin.nodeSelector`
```
=> [manila-csi-plugin] Fix whitespaces and invalid dot

docs/using-manila-csi-plugin.md, pkg/csi/manila/options/shareoptions.go, pkg/csi/manila/volumesource.go
This PR adds the ability to set user-defined metadata on newly created shares.
fixes https://github.com/kubernetes/cloud-provider-openstack/issues/1280
```release-note
[manila-csi-plugin] Added appendShareMetadata volume parameter
```
=> [manila-csi-plugin] Added appendShareMetadata volume parameter

docs/cinder-csi-plugin/features.md
https://github.com/kubernetes-csi/external-provisioner/blob/v1.6.0/pkg/features/features.go#L38 , Topology feature doesnt seem to be enabled by default. So updating the docs.
xref: #1293
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] update topology feature docs

docs/cinder-csi-plugin/using-cinder-csi-plugin.md
fixes #
```release-note
NONE
```
=> [DOC] Fix a doc deadlink

manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml, manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml
Use the latest image tag v1.19.2 for openstack-cloud-controller-manager.
fixes #
```release-note
NONE
```
=> [occm] Update openstack-cloud-controller-manager image tag in manifest

pkg/csi/cinder/controllerserver.go
current implementation checks existing volumes before creating.
but if somehow list request is failed (due to temporal API fails or something), next mechanism is not handle correctly.
we should just return error when list operation is failed 
no-issue
```release-note
NONE
```
=> [cinder-csi-plugin] Add error handling for list fucntions before creating

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md, pkg/cloudprovider/providers/openstack/openstack.go
fixes #1306 
```release-note
NONE
```
=> [Doc] Add description for os-TLSInsecure

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
fixes #
```release-note
NONE
```
=> Fix broken doc link

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/values.yaml, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
bump CSI side car containers to latest one
NOTE: originally the PR plan to bump version to node-driver-registrar to latest (2.0.1)
but due to CI issue, this PR only update it to 1.3.0 along with other update of container 
versions for CSI and a follow up PR will handle node-driver-registrar to 2.0.1
fixes #
```release-note
NONE
```
=> [cinder-csi-driver] bump container version

docs/cinder-csi-plugin/using-cinder-csi-plugin.md, pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/openstack/openstack.go
fixes #1300 
```release-note
[cinder-csi-plugin] support `ignore-volume-az` config parameter.
```
=> [cinder-csi-plugin] support ignore-volume-az

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml
the pull policy already defined in previous sections of the template, define again will overwrite previous settings
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin][chart] Remove duplicate pull policy definition

pkg/ingress/controller/openstack/octavia.go
This small PR adds the Kubernetes node name to the pool member (during batch update). I've tested this with a patched version of OIC based on `v1.18.2`.
fixes #1324 
N/A
```release-note
NONE
```
=> [octavia-ingress-controller] Add node name to pool member during creation

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml, charts/cinder-csi-plugin/values.yaml, docs/cinder-csi-plugin/features.md, docs/cinder-csi-plugin/using-cinder-csi-plugin.md, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
fixes #678
```release-note
NONE
```
=> [cinder-csi-plugin]Add liveness probe

pkg/autohealing/cloudprovider/openstack/provider.go
Cherry picked from https://github.com/kubernetes/cloud-provider-openstack/pull/1334
Before referencing the cluster status, it'd better to check if cluster
get action returns without error.
fixes #1333
```release-note
[magnum-auto-healer] Fixed a nil pointer bug due to getting cluster failure.
```
=> [magnum-auto-healer] Fix autohealer nil pointer bug

manifests/magnum-auto-healer/magnum-auto-healer.yaml
The new container image includes:
- https://github.com/kubernetes/cloud-provider-openstack/pull/1336
The magnum-auto-healer image tags:
https://hub.docker.com/repository/docker/k8scloudprovider/magnum-auto-healer/tags?page=1&ordering=last_updated
fixes #
```release-note
NONE
```
=> [magnum-auto-healer] Bump container image tag to v1.19.3

pkg/csi/cinder/driver.go, pkg/csi/cinder/driver_test.go
This PR bumps the driver version to  1.2.2 for 1.20 release 
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Bump driver version to 1.2.2

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/values.yaml, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
Ref https://github.com/kubernetes-csi/csi-release-tools/issues/86
```release-note
[cinder-csi-plugin] Use GCR images for CSI sidecar containers.
```
=> [cinder-csi-plugin] Switch CSI sidecar image repository to gcr

charts/manila-csi-plugin/Chart.yaml, charts/manila-csi-plugin/values.yaml, manifests/manila-csi-plugin/csi-controllerplugin.yaml, manifests/manila-csi-plugin/csi-nodeplugin.yaml
Ref kubernetes-csi/csi-release-tools#86
Along the way the `csi-node-driver-registrar` was updated from v1.1.0 to v1.3.0 (as the v1.1.0 tag is not available in gcr).
```release-note
[manila-csi-plugin] use GCR images of the CSI sidecar containers.
```
=> [manila-csi-plugin] Switch CSI sidecar image repository to gcr

docs/cinder-csi-plugin/examples.md, docs/cinder-csi-plugin/features.md, docs/cinder-csi-plugin/using-cinder-csi-plugin.md, docs/keystone-auth/using-client-keystone-auth.md, docs/openstack-cloud-controller-manager/migrate-to-ccm-with-csimigration.md, docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin][doc] update doc to link to internal doc instead of external links

tests/e2e/cloudprovider/test-lb-service.sh
Fix the error in the test case test_update_port:
```
2020-12-11 11:02:23.710091 | ubuntu-bionic | >>>>>>> Removing port2 and update NodePort of port1.
2020-12-11 11:02:24.750672 | ubuntu-bionic | Error from server (NotFound): services "test-update-port" not found
```
fixes #
```release-note
NONE
```
=> [occm] Fix the test case test_update_port

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
it is different with the name in EnsureLoadBalancer
fixes #
```release-note
NONE
```
=> [occm] remove underbar of member name while updating loadbalancer

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
It is to fix cording miss.
I realzed this error.
```
Error creating load balancer (will retry): failed to ensure load balancer for service default/wordpress: failed to add tag xxxxxx to port xxxxx: <nil>
```
but, error detail is `nil` because rever variable is deffrent and I fix it.
```release-note
NONE
```
=> [occm] Refer to the correct error variable

pkg/cloudprovider/providers/openstack/openstack.go
Currently, when provided with a unsupported lb-provider,
occm will accept providers that we can't support at this stage.
Rather than accept it, we will parse the provided value, compare
with our new supportedLBProvider map and fail for unsupported
providers.
This change introduces supportedLBProvider map, and a small section
during ReadConfig() to ensure the provided value can be supported.
[occm] Check for supported LBProvider type
All the currently maintained binaries are:
* openstack-cloud-controller-manager (occm)
This PR will add a map of supported LoadBalancer providers, and fail if the user specifies an unsupported Provider.
fixes #1332 1332 …
=> [occm] Add handling for supported LBProvider

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/values.yaml, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
Ref https://groups.google.com/g/kubernetes-dev/c/_2a2BVACg3s/m/4PrS1G4sAgAJ
```release-note
NONE
```
=> [cinder-csi-plugin] Update external-snapshotter to v2.1.3

charts/manila-csi-plugin/Chart.yaml, charts/manila-csi-plugin/values.yaml, manifests/manila-csi-plugin/csi-controllerplugin.yaml
Ref https://groups.google.com/g/kubernetes-dev/c/_2a2BVACg3s/m/4PrS1G4sAgAJ
```release-note
NONE
```
=> [manila-csi-plugin] Update external-snapshotter to v2.1.3

docs/cinder-csi-plugin/features.md, docs/cinder-csi-plugin/using-cinder-csi-plugin.md, docs/keystone-auth/using-client-keystone-auth.md, pkg/csi/cinder/identityserver.go
This fixes a few instances where OpenStack was not correctly cased.
There are other instances in code, but that would be more disruptive to
change.
```release-note
NONE
```
=> trivial: Correct casing of OpenStack

pkg/identity/keystone/authorizer.go, pkg/identity/keystone/authorizer_test.go, pkg/identity/keystone/authorizer_test_policy_version2.json
Signed-off-by: bevisy <binbin36520@gmail.com>
1. Add user authorization information existence judgment
2. Repair request authorization error without namespace
fixes #1308 
```release-note
[k8s-keystone-auth] Fix authorization error
```
=> [k8s-keystone-auth] Fix authorization error

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml, charts/cinder-csi-plugin/templates/secret.yaml, charts/cinder-csi-plugin/values.yaml, docs/cinder-csi-plugin/using-cinder-csi-plugin.md
This PR offers better secret handling for `cloud-config` : 
* use an existing secret : 
```yaml
secret:
use: true
name: cinder-csi-cloud-config
```
* create a new secret for `cloud-config` :
```yaml
secret:
use: true
name: cinder-csi-cloud-config
data:
cloud-config: |-
...
```
=> [cinder-csi-plugin] chart: better optional cloud-config secret handling

charts/cinder-csi-plugin/Chart.yaml, charts/manila-csi-plugin/Chart.yaml, examples/webhook/keystone-deployment.yaml, manifests/barbican-kms/pod.yaml, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml, manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml, manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml, manifests/magnum-auto-healer/magnum-auto-healer.yaml, manifests/manila-csi-plugin/csi-controllerplugin.yaml, manifests/manila-csi-plugin/csi-nodeplugin.yaml
Update the container image tag in the manifest files for release v1.20.0
fixes #
```release-note
NONE
```
=> [All] Update container image tag to v1.20.0

charts/manila-csi-plugin/Chart.yaml, charts/manila-csi-plugin/templates/csidriver.yaml, manifests/manila-csi-plugin/csidriver.yaml
CSIDriver storage.k8s.io/v1beta1 is deprecated. Update to v1.
fixes #
```release-note
[manila-csi-plugin] Updated CSIDriver object to v1
```
=> [manila-csi-plugin] Updated CSIDriver object to v1

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md, pkg/cloudprovider/providers/openstack/openstack.go
Emit's a warning instead of initialisation failure if an unsupported octavia provider plugin is used.
fixes #1356
```release-note
[openstack-cloud-controller-manager] Allow load balancer providers other than 'amphora' and 'octavia'.
```
=> [occm] don't error on unsupported octavia provider

.zuul.yaml
This PR updates e2e conformance jobs to run on latest release branch
fixes #
Depends on: https://github.com/theopenlab/openlab-zuul-jobs/pull/1078
```release-note
NONE
```
=> Update e2e-conformance jobs to latest releases

charts/cinder-csi-plugin/Chart.yaml, charts/manila-csi-plugin/Chart.yaml
Bump charts version for both plugins.
The version should be bumped after release-1.20 branch was cut. Hopefully could fix the Lint Charts job issue in https://github.com/kubernetes/cloud-provider-openstack/pull/1363
fixes #
```release-note
NONE
```
=> [csi-plugin] Bump charts version

.github/workflows/release.yaml
This fixes a bug which was fixed in release-1.19 branch but not
replicated to release-1.20 branch.
fixes #
```release-note
NONE
```
=> [all] Bump up chart-releaser-action version

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/cinder-csi-plugin/values.yaml, docs/cinder-csi-plugin/sidecarcompatibility.md, docs/cinder-csi-plugin/using-cinder-csi-plugin.md, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml
fixes #1362 
```release-note
NONE
```
=>  bump csi-provisioner to 2.1.0

charts/cinder-csi-plugin/Chart.yaml, charts/manila-csi-plugin/Chart.yaml
fixes #
```release-note
NONE
```
=> [all] Bump chart version to trigger release action

cluster/images/openstack-cloud-controller-manager/Dockerfile.build
fixes #1360 
```release-note
NONE
```
=> Add executable flag to openstack-cloud-controller-manager Dockerfile of user/group/other

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml, charts/cinder-csi-plugin/values.yaml
This PR makes the CSI plugin livenessprobe configurable via values in the Helm chart that deploys it, making it easier to work with 
fixes #1387 
```release-note
NONE
```
=> [cinder-csi-plugin] Use values to configure livenessprobe in Helm chart

pkg/csi/cinder/openstack/openstack_snapshots.go, pkg/csi/cinder/openstack/openstack_volumes.go
The #969 PR introduced the pagination support, however the pagination didn't make sense, since the `AllPages()` method was used, which automatically fetches all pages.
This PR uses a proper pagination and requests only one page, when the `MaxItems` limit is provided.
fixes #1383
```release-note
NONE
```
=> [cinder-csi-plugin] Fix pagination support for ListVolumes/ListSnapshots

manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, pkg/csi/cinder/identityserver.go
livenessprobe floods logs with probe logs. This commit removes probe
log and only prints if error occurs.
And also, this commit increases timeout to 10s and peridicity to 60s
of liveness probe
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Remove probe logging

pkg/cloudprovider/providers/openstack/openstack_instances.go
The node.kubernetes.io/instance-type label accepts alphanumeric
characters, '-', '_', and '.' only. If the flavor name contains
invalid characters, the flavor id is used instead.
fixes #
This addresses the issue mentioned in https://github.com/kubernetes/cloud-provider-openstack/pull/1213#issuecomment-757008618.
```
error syncing 'blue-master-1': Node "blue-master-1" is invalid: metadata.labels: Invalid value: "Small HD 4GB": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is …
```
=> [occm] validate flavor name, fallback on flavor id

pkg/cloudprovider/providers/openstack/openstack_instances.go
Cherry picked from #1364 
```release-note
NONE
```
<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
=> [occm] validate flavor name, fallback on flavor id (release-1.20)

pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go, pkg/util/openstack/loadbalancer.go
Add missing metrics observations to OpenStack API calls.
Fix unhandled errors from mc.ObserveRequest(err).
Add log lines for loadbalancer reconciliation.
Log the loadbalancer ID where available.
fixes #
```release-note
NONE
```
<sub>Sean Schneeweiss <sean.schneeweiss@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
=> [occm] loadbalancer: add missing metric observations, improve logs

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml, charts/cinder-csi-plugin/values.yaml, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, pkg/csi/cinder/identityserver.go
This PR backports fixes #1399 and #1395 to release-1.20
fixes #
```release-note
NONE
```
=> Backport #1399 and #1395 to release 1.20

.zuul.yaml
We run
* cloud-provider-openstack-e2e-test-csi-cinder
* cloud-provider-openstack-multinode-csi-migration-test
in the same cases, we don't get any benefit out of
cloud-provider-openstack-acceptance-test-csi-cinder, but we must compile
the binaries multiple times, as well as creating another kubernetes for
only a single testcase. This exact testcase is covered by the mentioned
ones.
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Removed CI Job cloud-provider-openstack-acceptance-test-csi-cinder

docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
fixes #1379
```release-note
NONE
```
=> DOC: Add note about not contain blank in AZ

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
The loadbalancer.openstack.org/proxy-protocol actually controls the loadbalancer pool's protocol, and not the listener protocol.
See also the octavia documentation, there is no PROXY listener protocol: https://docs.openstack.org/api-ref/load-balancer/v2/#protocol-combinations-listener-pool
Correct the documentation of one of the openstack annotations
No github issue opened for minor fix
```release-note
NONE
```
=> [occm] Fix loadbalancer.openstack.org/proxy-protocol docs

pkg/ingress/controller/controller.go, pkg/ingress/controller/openstack/octavia.go, pkg/util/openstack/loadbalancer.go
* Refactored how the ingress controller reconciles resources in Octavia. Changed the way that all the pools and l7 policies were removed before creating new resources, which brings downtime of the Ingress service.
* Improved log.
* Moved octavia related utility functions to `pkg/util/openstack/loadbalancer.go`
fixes #1417
```release-note
[octavia-ingress-controller] Fixed the issue that pools and l7 policies are removed no matter how the Ingress is changed.
```
=> [octavia-ingress-controller] Improve Ingress reconciliation

pkg/ingress/cmd/root.go
Improve the log format for octavia-ingress-controller, with this formatter in place, the logs is like below:
```
$ ksys logs -f octavia-ingress-controller-0
W0305 02:18:01.332625       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
INFO   [2021-03-05T02:18:01Z] Using config file                             file=/etc/config/octavia-ingress-controller-config.yaml
DEBUG  [2021-03-05T02:18:01Z] creating kubernetes API client
DEBUG  [2021-03-05T02:18:01Z] kubernetes API client created                 version=v1.20
WARNING[2021-03-05T02:18:01Z] Barbican not suppported.
DEBUG  [2021-03-05T02:18:01Z] openstack client initialized
DEBUG  [2021-03-05T02:18:01Z] starting Ingress …
```
=> [octavia-ingress-controller] Set log formatter

tests/e2e/csi/cinder/cinder-testdriver.go, tests/e2e/csi/cinder/csi-volumes.go
This commit enables snapshot e2e tests.
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Enable Snapshot e2e tests

pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/nodeserver_test.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_mock.go, pkg/csi/cinder/openstack/openstack_volumes.go, tests/sanity/cinder/fakecloud.go
fixes #1403 
```release-note
[cinder-csi-plugin] Fixed the issue that the ephemeral inline volume is yet available when attaching to the node.
```
=> [cinder-csi-plugin] Ephemeral volumes: wait for volume status to be available

docs/cinder-csi-plugin/development.md
fixes #1420
```release-note
NONE
```
=> [cinder-csi-plugin] write dev guide for CSI version and spec version

pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/nodeserver_test.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_mock.go, pkg/csi/cinder/openstack/openstack_volumes.go, tests/sanity/cinder/fakecloud.go
cherry-pick from commit 87d08ef3abbc7b818a02cc6310623888d9b39b75, PR https://github.com/kubernetes/cloud-provider-openstack/pull/1429
fixes #1403
```release-note
[cinder-csi-plugin] Fixed the issue that the ephemeral inline volume is yet available when attaching to the node.
```
=> [cinder-csi-plugin] Ephemeral volumes: wait for volume to be available

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md, docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md, go.mod, go.sum, pkg/openstack/loadbalancer.go, pkg/openstack/openstack.go, pkg/openstack/openstack_loadbalancer_subnet_match_test.go
fixes #1328
A floating IP for a loadbalancer is created on a subnet of a floating pool (specified by a network id of the provider network).
Such a subnet has a dedicated IP range (CIDR). Therefore it might happen, that the subnet runs out of IP addresses. To not disrupt the existing FIP users in such a case a new subnet can be added to the provider network. This one will potentially automatically be selected for new FIP creation if the creator does not explicitly specify the subnet id.
But this automated subnet selection makes only sense if all subnets configured for a provider network provide the same kind
of routing. In Openstack it is possible to configure subnets for the same provider network that …
=> [occm] pattern based subnet detection for loadbalancers

pkg/csi/cinder/nodeserver.go
Now we use "findmnt" command to find the device path. Unfortunately, this command may return multiple entries of the same mount, but in fact we need just the first one.  To prevent this issue we add "--first-only" flag to the command.
Fixes #1436 
```release-note
[cinder-csi-plugin] Fixed the issue where the file system size stays the same when expanding the volume.
```
=> [cinder-csi-plugin] Fix filesystem resize

tests/e2e/csi/cinder/cinder-testdriver.go
This PR adds CapPVCDataSource capability which enables volume cloning
tests to run.
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Enable volume cloning e2e tests 

.zuul.yaml, pkg/openstack/loadbalancer.go
Define pool name when creating fully populated loadbalancer for service.
fixes #1441
```release-note
NONE
```
=> [occm] Fix creating fully populated loadbalancer

docs/cinder-csi-plugin/using-cinder-csi-plugin.md, go.mod, go.sum, pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/driver.go, pkg/csi/cinder/driver_test.go, pkg/csi/manila/controllerserver.go
bump CSI to sepc 1.3 
fixes #
```release-note
NONE
```
=> [csi-plugin] Bump CSI spec to 1.3

pkg/csi/cinder/nodeserver.go
Now we use "findmnt" command to find the device path. Unfortunately,
this command may return multiple entries of the same mount, but in
fact we need just the first one.
To prevent this issue we add "--first-only" flag to the command.
cherry-pick: aa5e9fe41c38291cad2c888b81b9c5c524b1c209
fixes #1436 
```release-note
NONE
```
=> [cinder-csi-plugin] Fix filesystem resize (#1434)

pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/nodeserver_test.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_mock.go, pkg/csi/cinder/openstack/openstack_volumes.go, tests/sanity/cinder/fakecloud.go
This PR refactors waitForVolumeStatusAvailable to be more generic.
Could be reused in other places as well.
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Refactor waitForVolumeStatus to be generic

pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_snapshots.go
update all error related Infof to Errorf
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin]update CSI logs Log.Infof to Log.Errorf in error case

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/cinder-csi-plugin/values.yaml, docs/cinder-csi-plugin/features.md, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, tests/e2e/csi/cinder/cinder-testdriver.go, tests/e2e/csi/cinder/csi-volumes.go
* Enabled Topology by default
* Updated external-provisioner for Topology support of CSIMigration
* Added more testsuites to e2e of cinder csi
fixes #1407
Topology is GA from perspective of external-provisioner. https://github.com/kubernetes-csi/external-provisioner/issues/569
```release-note
[cinder-csi-plugin] : Enabled Topology by default
```
=> [cinder-csi-plugin] Enabled Topology Support by default

.zuul.yaml, docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md, docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md, pkg/openstack/loadbalancer.go, pkg/openstack/openstack.go, tests/e2e/cloudprovider/test-lb-service.sh
Related issues in other repos:
- https://github.com/kubernetes/kubernetes/issues/66607
- https://github.com/kubernetes/ingress-nginx/issues/3996
In PROXY mode, set Hostname field using IP address and a suffix `.nip.io` to expose the Service of LoadBalancer type.
A new config option `enable-ingress-hostname` is introduced but may be removed in the future, please see the document change.
fixes #1287
```release-note
[openstack-cloud-controller-manager] Fixed the broken header issue when accessing the load balancer service with PROXY protocol enabled from within the cluster.
```
=> [OCCM] Set Hostname in load balancer status when using PROXY protocol

pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/controllerserver_test.go
related-issue: #1437
```release-note
NONE
```
=> [cinder-csi-plugin] Check volume status after volume expand action

cmd/manila-csi-plugin/main.go, docs/manila-csi-plugin/using-manila-csi-plugin.md, pkg/csi/manila/controllerserver.go, pkg/csi/manila/controllerserver_test.go, pkg/csi/manila/driver.go, pkg/csi/manila/volumesource.go
This commit add a new optional string parameter "cluster-id" to manila csi plugin binary. If this parameter value is provided, then the plugin will add "manila.csi.openstack.org/cluster: <clusterID>" to metadata of created shares. It simplifies finding shares created for specific clusters.
Similar solution exists for Cinder: https://github.com/kubernetes/cloud-provider-openstack/blob/master/cmd/cinder-csi-plugin/main.go#L86
https://github.com/kubernetes/cloud-provider-openstack/pull/451
```release-note
[manila-csi-plugin] support `--cluster-id` argument to get the the CO's identifier.
```
=> [manila-csi-plugin] Add --cluster-id option 

charts/manila-csi-plugin/Chart.yaml, charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml, charts/manila-csi-plugin/values.yaml
This PR introduces the ability to configure `priorityClassName`  for the manila-csi-plugin DaemonSet
fixes : #1460
None
```release-note
NONE
```
=> [Helm manila-csi-plugin] Added priorityClassName to DaemonSet

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/_helpers.tpl, charts/cinder-csi-plugin/templates/snapshot-controller-rbac.yaml, charts/cinder-csi-plugin/templates/snapshot-controller-statefulset.yaml, charts/cinder-csi-plugin/values.yaml
Extends the current Helm Chart for Cinder CSI Plugin with a deployment of a Snapshot Controller
none
none
```release-note
[cinder-csi-plugin] Support Snapshot Controller deployment in Helm Chart.
```
=> [cinder-csi-plugin] add snapshot controller to Helm Chart

pkg/autohealing/cloudprovider/openstack/provider.go, pkg/autohealing/cloudprovider/register/register.go
cherry-picked from https://github.com/kubernetes/cloud-provider-openstack/pull/1447
fixes #1446
```release-note
[magnum-auto-healer] Fixed an issue that k8s master node repair failed when the node is boot from volume.
```
=> [magnum-auto-healer] Fix k8s master node repair if it's volume-based

pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/nodeserver.go, pkg/csi/cinder/utils.go, pkg/csi/cinder/utils_test.go
This PR uses the common lib to strip credentials in the logs.
fixes #1469
```release-note
[cinder-csi-plugin] Sanitize secrets in the request, and therefore credentials are not shown in the logs anymore.
```
=> [cinder-csi-plugin] Sanitize secrets in the requests

pkg/csi/manila/driver.go, pkg/csi/manila/identityserver.go, pkg/csi/manila/nodeserver.go, tests/sanity/manila/fakecsiclient.go
This PR closes opened gRPC connections made to the partner node plugins.
Please see the table below for memory consumption comparison without and with this patch:
Without this fix, the memory consumption gradually increases. This PR fixes this and keeps the consumption more or less constant.
fixes #1472
```release-note
NONE
```
=> [manila-csi-plugin] close GRPC connections

pkg/csi/manila/driver.go, pkg/csi/manila/identityserver.go, pkg/csi/manila/nodeserver.go, tests/sanity/manila/fakecsiclient.go
This is a backport of https://github.com/kubernetes/cloud-provider-openstack/pull/1473 into the release-1.20 branch.
Cherry-picked from b20ce967f4b9f259c4148cf809c5111245a53f12.
```release-note
[manila-csi-plugin] Fixed a leak causing high memory consumption
```
=> [manila-csi-plugin] close GRPC connections (release-1.20)

tests/e2e/csi/cinder/cinder-testdriver.go
Disabling cloning tests temporarily to unlock gate.
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] disable cloning tests

pkg/csi/cinder/nodeserver.go
Fixes some trivial typos
```release-note
NONE
```
=> [cinder-csi-plugin] Fix typos on the word ephemeral

pkg/csi/cinder/openstack/openstack_volumes.go
fixes #
```release-note
NONE
```
=> nit: Remove unused global variables

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md, docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md, pkg/client/service.go, pkg/openstack/loadbalancer.go, pkg/openstack/openstack.go
This PR brings support for creating TLS Terminated loadbalancers. User can specify tls container ref either in cloud-config file using `default-tls-container-ref` option or pass tls container ref in service spec using annotation `loadbalancer.openstack.org/default-tls-container-ref`. Cloud provider will create a listener with protocol **TERMINATED_HTTPS** and a pool with protocol **HTTP**.
This feature is supported only for Octavia.
This PR also fixes #1294 
To test this feature you have to create an openstack secret container of type certificate:
```
$ openstack secret container get https://X.X.X.X:9311/v1/containers/3898c759-ef67-4096-8ccf-3719cef674a3
+----------------+---------------------------------------------- …
```
=> [OCCM] add support for TLS terminated loadbalancers

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/custom_storageclass.yaml, charts/cinder-csi-plugin/values.yaml
The pre-defined StorageClasses won't fit for every use case. Give the user the possibility to define their own StorageClasses or VolumeSnapShotClass
none
none
```release-note
[cinder-csi-plugin] Support custom StorageClass in Helm Chart.
```
=> [cinder-csi-plugin] custom StorageClass in Helm Chart

pkg/csi/cinder/openstack/openstack_volumes.go
The [CSI spec](https://github.com/container-storage-interface/spec/blob/master/spec.md#controllerunpublishvolume) lists that the `ControllerUnpublishVolume` function should be idempotent. If the volume corresponding to the `volume_id` is not attached to the node corresponding to the `node_id`, the Plugin MUST reply `0 OK`.
This is not the case for the cinder-csi-plugin. If the disk is not attached to the compute, the `DetachVolume` function returns an [error](https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/openstack/openstack_volumes.go#L285). This in turn causes the `ControllerUnpublishVolume` function to return an [error](https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/controllerse …
=> [cinder-csi-plugin] made ControllerUnpublishVolume call idempotent

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/controllerserver_test.go, pkg/csi/cinder/fake.go
The external CSI provisioner optionally injects metadata in the CreateVolume that we can pass onto the volume as additional tags.
See https://github.com/kubernetes-csi/external-provisioner/pull/399
** Release notes **
```release-note
Tag volumes with additional metadata about pv and pvc if provided
```
=> [cinder-csi-plugin] Tag volume with optional pvc/pv metadata

pkg/csi/cinder/driver.go, pkg/csi/cinder/driver_test.go
This PR bumps driver version ahead of 1.21 release.
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Bump driver version

charts/cinder-csi-plugin/Chart.yaml, charts/manila-csi-plugin/Chart.yaml, charts/openstack-cloud-controller-manager/Chart.yaml
As release-1.21 branch was cut, bump minor version for all the Charts for master branch.
fixes #
```release-note
NONE
```
=> Bump helm charts minor version

examples/webhook/keystone-deployment.yaml, manifests/barbican-kms/pod.yaml, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml, manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml, manifests/controller-manager/openstack-cloud-controller-manager-pod.yaml, manifests/magnum-auto-healer/magnum-auto-healer.yaml, manifests/manila-csi-plugin/csi-controllerplugin.yaml, manifests/manila-csi-plugin/csi-nodeplugin.yaml
Update docker image tag in the manifest files for release v1.21.0
fixes #
```release-note
NONE
```
=> [All] Update docker image tag to v1.21.0

.zuul.yaml
There are issues when v1.21 openstack-cloud-controller-manager is talking to v1.19 k8s cluster. Disable the job for now to not block upstream contribution. More information here: https://kubernetes.io/docs/setup/release/version-skew-policy/#kube-controller-manager-kube-scheduler-and-cloud-controller-manager
We have to manually test the PR when doing review.
fixes #
```release-note
NONE
```
=> [occm] Disable openstack-cloud-controller-manager CI job

pkg/csi/cinder/controllerserver.go
add logs so it's easier to track what we do on create/delete actions
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Add log for POST and DELETE actions

cluster/addons/rbac/cloud-controller-manager-roles.yaml
fixes #1514
```release-note
NONE
```
=> [occm] Add role for serviceaccounts/token

charts/manila-csi-plugin/Chart.yaml, charts/manila-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/manila-csi-plugin/templates/nodeplugin-daemonset.yaml, charts/manila-csi-plugin/values.yaml
https://github.com/kubernetes/cloud-provider-openstack/pull/1459 added `--cluster-id` cmd arg. This PR makes it possible to set it via the Helm chart.
```release-note
[manila-csi-plugin] Helm: Added optional clusterID value
```
=> [manila-csi-plugin] helm: added clusterID value

charts/openstack-cloud-controller-manager/Chart.yaml, charts/openstack-cloud-controller-manager/templates/clusterrole.yaml
New clientbuilder needs permission to create serviceaccount token
fixes #1514 
none
```release-note
NONE
```
=> [occm] add missing RBAC for serviceaccount token

pkg/csi/cinder/nodeserver.go, pkg/util/metadata/metadata.go
Now GetDevicePath from metadata doesn't return an error if something bad happens. This makes it difficult to debug Cinder CSI driver.
This commit modifies the function to return an error value, and also adds additional logging that should help with debugging.
```release-note
NONE
```
=> [cinder-csi-plugin] Cleanup: handle errors from GetDevicePath

CONTRIBUTING.md, README.md, docs/developers-guide.md, docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
Add some guide for reviewers and contributors.
fixes #
```release-note
NONE
```
=> [Doc] Refactor dev guide

charts/cinder-csi-plugin/Chart.yaml, charts/manila-csi-plugin/Chart.yaml, charts/openstack-cloud-controller-manager/Chart.yaml
This PR pins `appVersion` of all currently available CPO Helm charts in `release-1.21` branch to `v1.21.0`.
fixes #1525
```release-note
NONE
```
=> [all/helm] Pin appVersion to v1.21.0

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md, docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md
fix a typo floating-subnet-tag => floating-subnet-tags
fixes #
```release-note
NONE
```
=> [doc][occm]: update doc to fix a typo

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml, charts/cinder-csi-plugin/templates/snapshot-controller-statefulset.yaml, charts/cinder-csi-plugin/values.yaml
Currently there is no way in cinder-csi's Helm chart to convince the scheduler to e.g. schedule the Controller plugin only on master nodes, or set resource constraints. This PR exposes `affinity`, `nodeSelector`, `tolerations` and `resources` PodSpec attributes in the values file, making it possible to influence scheduling the driver in Helm deployments.
```release-note
NONE
```
=> [cinder-csi-plugin] helm: Expose scheduler constraints in values.yaml

pkg/autohealing/cloudprovider/openstack/provider.go, pkg/autohealing/config/config.go, pkg/autohealing/controller/controller.go, pkg/autohealing/healthcheck/healthcheck.go
This is kind of a regression issue. After introducing the feature that restarts the broken node if it's found the first time, then the stack update action is quick because there is no real action involved. But the controller is still polling the status periodically, so another round check coming and will trigger the repair again.
fixes #1529 
```release-note
[magnum-auto-healer] Fix duplicated auto-healing actions and the default health check period is changed from 30s to 60s.
```
=> [magnum-auto-healer] Fix duplicated repair action

pkg/openstack/loadbalancer.go
Previously adding the proxy-protocol annotation after the pool got
created did not change anything. With this fix changing the annotation
also recreates the load balancer pool because the protocol of a pool
can't get changed via an update call.
fixes #1167 
```release-note
[openstack-cloud-controller-manager] Recreate load balancer pool if the protocol changed based on the service definition.
```
---
<sup>
Christian Schlotter <christian.schlotter@daimler.com>, Daimler TSS GmbH,
<a href="https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md">Imprint</a>
</sup>
=> [occm] recreate load balancer pool on protocol mismatch

.zuul.yaml, tests/e2e/cloudprovider/test-lb-service.sh
fixes #
```release-note
NONE
```
=> [occm] Enable cloud-provider-openstack-test-occm job

go.mod, go.sum, pkg/csi/manila/csiclient/builder.go
fixes #1527
This is very simple to reproduce on OpenShift by setting a cluster-wide proxy. See #1527 for reproducer steps.
```release-note
NONE
```
**NOTE**
A better fix would be to update gRPC to at least v1.34.0 which contains https://github.com/grpc/grpc-go/pull/3890. This supports the unix protocol explicitly and never proxies it. However, due to our transitive dep on etcd clientv3 and https://github.com/etcd-io/etcd/issues/11563 we are pinned to gRPC <= v1.30.0. The etcd 3.5 branch has finally bumped the gRPC version, but that is not released yet. None of the etcd stable branch tags contain a gRPC bump.
/cc @Fedosin
=> [manila-csi-plugin] Fix error connecting to nfs plugin when using cluster proxy

pkg/autohealing/cloudprovider/openstack/provider.go, pkg/autohealing/config/config.go, pkg/autohealing/controller/controller.go, pkg/autohealing/healthcheck/healthcheck.go
There are several changes in this commit:
1) Fix the duplicated repair actions
2) Change default health check period from 30s to 60s
(cherry picked from commit db60e005ce04ecccf84bcaa9140182dbf7ab8fb7)
fixes #1529
```release-note
[magnum-auto-healer] Fix duplicated auto-healing actions and the default health check period is changed from 30s to 60s.
```
=> [ magnum-auto-healer] Fix duplicated repair action (#1530)

.zuul.yaml, tests/e2e/cloudprovider/test-lb-service.sh
The job cloud-provider-openstack-acceptance-test-lb-octavia is not used anymore.
fixes #
```release-note
NONE
```
=> [occm] Use CI job cloud-provider-openstack-test-occm

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml, charts/cinder-csi-plugin/templates/snapshot-controller-statefulset.yaml, charts/cinder-csi-plugin/values.yaml
Allow cluster operators in production deployments to avoid scheduling problems by setting appropriate levels of priorityClass for important addons like Cinder CSI.
fixes #1560 
Just like https://github.com/kubernetes/cloud-provider-openstack/pull/1452
```release-note
NONE
```
=> [cinder-csi-plugin] add optional priorityClassName for CSI components

docs/keystone-auth/using-keystone-webhook-authenticator-and-authorizer.md
1) fix link issue
2) remove older version (long time ago) info 
fixes #
```release-note
NONE
```
=> [doc] update keystone auth

Makefile
fixes #https://github.com/kubernetes/cloud-provider-openstack/issues/1554
```release-note
NONE
```
=> [k8s-keystone-auth]Add build for client-keystone-auth

docs/cinder-csi-plugin/using-cinder-csi-plugin.md, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
fixes #1546 
```release-note
NONE
```
=> [doc] [cinder-csi-plugin]update doc to make add cert clearer

.zuul.yaml
Add new job `cloud-provider-openstack-test-occm-e2e-conformance` to replace the existing one. Use k3s instead of kubeadm to make CI job simple, fast and stable.
We will keep this running for some time before totally replacing `cloud-provider-openstack-acceptance-test-e2e-conformance`
fixes #
```release-note
NONE
```
=> [OCCM] Add new job for e2e conformance test

examples/cinder-csi-plugin/snapshot/example.yaml, examples/cinder-csi-plugin/snapshot/snapshotcreate.yaml, examples/manila-csi-plugin/nfs/snapshot/snapshotclass.yaml, examples/manila-csi-plugin/nfs/snapshot/snapshotcreate.yaml
Snapshots v1 API is GA from 1.20, so we can address it in our examples:
https://kubernetes.io/blog/2020/12/10/kubernetes-1.20-volume-snapshot-moves-to-ga/
```release-note
NONE
```
=> Update snapshots examples to start using v1 API

cmd/cinder-csi-plugin/main.go
Signed-off-by: kcx2366425574 <18279911430@163.com>
fixes #
```release-note
NONE
```
=> fix the words to correct ones

docs/cinder-csi-plugin/features.md
fixes #
```release-note
NONE
```
=> [doc][cinder-csi-plugin]update doc to reflect snapshot version

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/templates/controllerplugin-statefulset.yaml, charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml, cmd/cinder-csi-plugin/main.go, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml, pkg/csi/cinder/controllerserver_test.go, pkg/csi/cinder/driver.go, pkg/csi/cinder/driver_test.go, pkg/csi/cinder/identityserver_test.go, pkg/csi/cinder/nodeserver_test.go, tests/sanity/cinder/sanity_test.go
--node-id flag eventhough supported, never used by the driver , the
value is always ignored. To avoid confusion/inconsistency , this commit
deprecates the flag
fixes #1453 
```release-note
[cinder-csi-plugin] Deprecate `--node-id` option . Its value is ignored by the driver.
```
=> [cinder-csi-plugin] Deprecate nodeID flag

cmd/cinder-csi-plugin/main.go, docs/cinder-csi-plugin/using-cinder-csi-plugin.md, pkg/csi/cinder/driver.go, pkg/csi/cinder/driver_test.go, pkg/csi/cinder/openstack/openstack.go, pkg/csi/cinder/openstack/openstack_test.go
This change allows cinder-csi-plugin to be invoked with multiple config
files. These will be parsed sequentially in the order specified. Values
in later config files override values in earlier config files.
This makes 'layered' configurations simpler to manage. For example a
base configuration containing authentication information and a per-node
override configuration which applies only to a single node. Keeping
these in separate files simplifies the task of changing the base
configuration for all nodes.
fixes #1481 
```release-note
[cinder-csi-plugin] The --cloud-config option may now be given multiple times. Multiple configuration files will be merged, …
```
=> [cinder-csi-plugin] Allow multiple config files

docs/cinder-csi-plugin/using-cinder-csi-plugin.md
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] update doc on deprecated params

.zuul.yaml
fixes #
```release-note
NONE
```
=> [occm] Run e2e conformance test for v1.21

pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/controllerserver_test.go
Now cluster id is set by --cluster argument at the driver's start. When it's set, cinder CSI controller appends the cluster id to volumes metadata during creation. Unfortunately it doesn't happen for volume snapshots, which makes it harder to find them after cluster deletion.
This commit adds cluster id to snapshots metadata to unify the behavior with volumes.
```release-note
[cinder-csi-plugin] Append cluster ID (value of `--cluster`) to metadata of snapshots in the cloud when creating VolumeSnapshot.
```
=> [cinder-csi-plugin] add cluster id to snapshot metadata

pkg/csi/cinder/controllerserver.go, pkg/csi/cinder/driver.go
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Add controller get volume function support

.zuul.yaml
The job name is still used in https://github.com/kubernetes/test-infra/blob/master/config/testgrids/kubernetes/sig-cloud-provider/openstack/config.yaml, this PR changes the job name back (but using the new job definition, see [here](https://github.com/theopenlab/openlab-zuul-jobs/blob/master/zuul.d/jobs.yaml#L616)) to avoid test-infra change.
fixes #
```release-note
NONE
```
=> [OCCM] Restore the previous name for e2e-conformance job

docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md, docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md, pkg/openstack/loadbalancer.go, pkg/openstack/openstack.go, pkg/util/openstack/loadbalancer.go
Closes #1350
Signed-off-by: Michał Nasiadka <mnasiadka@gmail.com>
This PR adds support for using OVN Octavia provider driver (in addition to Amphora - the default one)
fixes #1350
```release-note
NONE
```
=> [occm] Add OVN to supported Octavia providers.

charts/cinder-csi-plugin/Chart.yaml, charts/cinder-csi-plugin/values.yaml, manifests/cinder-csi-plugin/cinder-csi-controllerplugin.yaml, manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml
This PR bumps snapshotter to 4.0.0 and also added support --extra-create-metadata tag.
Also updates other sidecars to latest version . 
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Bump snapshotter version to 4.0.0

docs/cinder-csi-plugin/using-cinder-csi-plugin.md, docs/openstack-cloud-controller-manager/migrate-to-ccm-with-csimigration.md
From release1.21 , CSIMigration is ON by default. This PR
is to reflect the same in doc.
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin][doc] Update CSIMigration status

manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml, tests/e2e/csi/cinder/cinder-testdriver.go, tests/e2e/csi/cinder/csi-volumes.go
This PR enables e2e tests for ephemeral volumes.
fixes #
```release-note
NONE
```
=> [cinder-csi-plugin] Enable ephemeral e2e tests 
